### ISSUE TITLE
Reflect and repackage Web Litearcy Basics I

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#100]
We want to test what a distributed curriculum sprint looks like. 

In this heartbeat, we'll scope what's needed in terms of participation and process to i) REFLECT, ii) PACKAGE, and iii) SHIP the remixes and refinements to Web Literacy Basics I module.

**Comment by LauraHilliger** [comment]
Not sure if this is what you were thinking, but I took some time to go through the call notes and Discourse threads to pull out feedback and remixes. Most of the feedback focused on the first section, so we should try to get more folks testing sections 2 and 3. 

Synthesized Feedback is here (hack at will, it's still pretty "notey"): https://teach.etherpad.mozilla.org/club-curriculum-feedback

The process needed (I think):
- [x] REFLECT: synthesized the call notes and discourse threads by topic
- [x] REFLECT: eliminated redundancies
- [x] REFLECT: reviewed feedback and made suggestions for iterations
- [ ] PACKAGE: gather team feedback on those suggestions
- [ ] PACKAGE: determine implementable actions
- [ ] SHIP: implement production on changes + make any new resources

In terms of participation, the REFLECT bit and the actual production tasks could be a community effort using discourse and well defined github issues.

https://teach.etherpad.mozilla.org/club-curriculum-feedback

**Comment by LauraHilliger** [comment]
cc @amirad @ldecoursy - I know you all are thinking about feedback as well!

**Comment by thornet** [comment]
Took first cut of upvoting and adding ticketable items to: https://teach.etherpad.mozilla.org/club-curriculum-feedback

Propose we wrap the feedback etherpad by EOD so we can present it a draft in tomorrow's club call. @LauraHilliger

**Comment by thornet** [comment]
The final repacking of this module will be completed by the next heartbeat. Thanks to @LauraHilliger for filling the tickets and making our punchlist!

**Comment by ldecoursy** [comment]
:dancers:

**Comment by LauraHilliger** [comment]
I’ve implemented (almost) all the tickets we had on the clubs stuff. 2 left, one that is just waiting for Doug + Greg to say “yes, that’s better” #212, and I'm not sure what to do with #215 - the [glossary](https://github.com/mozilla/webmaker-curriculum/wiki/Glossary) is pretty simplistic already.

Recommend finding a time to go through these together and do a final looksie on if we can simplifying things or pretty them up.

**Comment by thornet** [comment]
@LauraHilliger thanks! it's looking amazing. 

made a few edits as well. 

let's leave #215 for now and ship #212 unless @dajbelshaw @jgmac1106 suggest otherwise by Monday Mar 23.

**Comment by jgmac1106** [comment]
I really like it. Stumbled on to it last night when I was working on Hack
the News Tutorials. h/t to all.

**Comment by ldecoursy** [comment]
@LauraHilliger @thornet Are we good to close this and https://github.com/MozillaFoundation/plan/issues/388?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/48"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/48.
Please don't comment on it here.
