### ISSUE TITLE
Implement /activities/maker-party-2015

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1000]
This is the page that will be linked to from /events

This page should follow the same template as /activities/web-lit-basics/ and /activities/protect-your-data/

The content can be found starting on line 21 of this pad, but needs to be finalized: https://teach.etherpad.mozilla.org/teachsite-eventspage

**Comment by hannahkane** [comment]
blocked on copy

**Comment by hannahkane** [comment]
Copy won't be ready this heartbeat, so moving this to the next.

**Comment by chrislarry33** [comment]
Whats the blocker on copy?

**Comment by hannahkane** [comment]
It was that we don't have all of the final Webmaker activities, but just spoke with @amirad about this, and we agreed to move forward with this in the current heartbeat, even if we have to have a "Coming Soon" section.

**Comment by hannahkane** [comment]
Changing this from a design ticket to an implementation ticket, because I'd like to just use the existing template (see https://teach.mozilla.org/activities/web-lit-basics/) for layout and styles.

The final copy starts on line 19 of this pad: https://teach.etherpad.mozilla.org/teachsite-eventspage

**Comment by hannahkane** [comment]
@mmmavis - could you do this without a mock-up, and then @sabrinang can fill in the missing images?

**Comment by hannahkane** [comment]
url should be /activities/maker-party-2015

**Comment by mmmavis** [comment]
@hannahkane 
> This is the page that will be linked to from /events

What should I change on the Events page?

**Comment by hannahkane** [comment]
It will be linked from the pretty banner @sabrinang designed in #843 

![screen shot 2015-06-18 at 11 46 03 am](https://cloud.githubusercontent.com/assets/8389648/8239265/a213cb0a-15af-11e5-8f0e-4a26a37cb6b7.png)

**Comment by mmmavis** [comment]
okie dokie it'll be part of #900 then :smile:

**Comment by mmmavis** [comment]
@hannahkane 
Checking to see if we want to put **subtitle** for each activity (the *italic* line in screencap below)
![screen shot 2015-06-18 at 1 32 32 pm](https://cloud.githubusercontent.com/assets/2896608/8241489/80fc6d46-15be-11e5-851b-6fb6c2c56f31.png)
Also wondering how the "Case Study" section should look like.

@sabrinang could you provide suggestions/assets to use for the 4 activities?

**Comment by hannahkane** [comment]
@mmmavis - just added subtitles to the pad. Thanks for that. Also, I should have specified, but the content for this page stops before the Case Study section of that etherpad. It's just the introduction, learning objectives, and then the six activities. Thanks!

**Comment by mmmavis** [comment]
![maker-party-2015-wip](https://cloud.githubusercontent.com/assets/2896608/8243622/825e614e-15cd-11e5-8017-93dc6f2d3797.png)

@sabrinang what do you think about the 3 images I placed in the 3 activities?
also, missing image for the intro section and for the last activity

**Comment by sabrinang** [comment]
The IP Tracer and Draw Secure Passwords are taken from /protect-your-data so that is great and the x-ray goggles logo works as well for Data Trail since it utilizes the tool.  

For the last activity, we can use the image used in the activity itself: http://mozilla.github.io/webmaker-curriculum/images/hackthenews.png

Cool - I will hunt down a maker party photo for the top intro section that we can use.

**Comment by amirad** [comment]
Some picture options @sabrinang if they help: https://flic.kr/p/pGCs2J or https://flic.kr/p/orWF89
Or any here: https://www.flickr.com/photos/mozilladrumbeat/sets/72157644395497439

**Comment by mmmavis** [comment]
pinnng @sabrinang, help help! Could you pick a photo? :wink: trying to ship this page soon and this is the only thing blocking the PR.

**Comment by hannahkane** [comment]
moving to next heartbeat

**Comment by mmmavis** [comment]
@sabrinang any update on the photo choice?

**Comment by sabrinang** [comment]
I tried editing this photo that @amirad suggested
![makerparty-photo](https://cloud.githubusercontent.com/assets/2492510/8422044/4ae3233c-1e8b-11e5-93bb-17b2d018ff30.png) 
but the quality isn't great...

So lets use this one instead (seen on our social shares):
![makerparty_photo](https://cloud.githubusercontent.com/assets/2492510/8422034/34588404-1e8b-11e5-9184-02926c16fdaf.png)
original: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eVG1BT1JVS0dPZE0/view?usp=sharing
![makerparty_photo 2x](https://cloud.githubusercontent.com/assets/2492510/8422036/346ac740-1e8b-11e5-8b22-86c46399f9e8.png)
retina: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eWXdXbGxhdVVwd1E/view?usp=sharing
