### ISSUE TITLE
Creating reports from site admin UI

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#1003]
As part of the Clubs workflow, when someone submits a club, our goal is to assign them to an RC, who would follow-up with that person and have a short discussion before determining whether to approve/deny a club. Unfortunately the description isn't always enough to go by, and as part of the organizing model, we want to provide a level of personalization to build lasting relationships. 

We currently have 99 clubs in the system, and are trying to determine the best way to divvy up the current list among RCs and Staff Organizers so we can test the workflow/process. 

In the best case scenario, we could export a report that includes:
* Name
* Location
* Email
* Club description

For now, if possible to just have emails added to the admin view, that would be a big help. That information is currently only available when we receive an email that a club has been added (but we won't want all RCs to receive those emails). Since RCs will be doing follow-up, we'll need an easier way to get them that info.

**Comment by hannahkane** [comment]
Is this a one-time request to get the 99 that are in the system already, or is it a request to be able to do this at any point in the future?

**Comment by ldecoursy** [comment]
Both - definitely need to work through the backlog sooner than later, but also working through the process moving forward for how we'll be able to assign RC's, who should have the ability to access email info so they can follow-up with folks before approving/denying Club status.

**Comment by ldecoursy** [comment]
cc @amirad @thornet

**Comment by hannahkane** [comment]
Sorry, I misunderstood the original requirements. I thought we'd be manually updating the spreadsheet after the initial export.

If we need to be doing this regularly, then we'll have to have a UX for it, and a system to prevent the data from getting out of sync (e.g. being able to export a list based on certain search criteria, such as "Created after X date").

Does that make sense to you, @toolness?

**Comment by toolness** [comment]
HMMMmmmmmmm ok. it makes sense but it has be wondering if it'd be easier to just add a "club status" field as I suggested in ...

Anyhow in the meantime, at the very least I have added an email column to the clubs list admin view in https://github.com/mozilla/teach-api/commit/a5b02165dc1e897fea7df330a9e041fa2caefdfd.

This will also help with #923 because now we won't have to give RCs access to the User model at all, since all they really need is username and email.

**Comment by hannahkane** [comment]
Can you remind me what the "club status" field would do? Don't we already have a Club Status field?

**Comment by toolness** [comment]
Doh sorry lol, I submitted that last comment before I had looked up the relevant issue I'd mentioned it in. I also mis-wrote--I meant "staff notes", not "club status", and I mentioned it in https://github.com/mozilla/teach.webmaker.org/issues/911#issuecomment-105879915:

> Given the fact that clubs will be managed by different individuals with different roles at different times, and that the approval flow will likely involve lots of different phases, I'm wondering if we should add a "staff notes" field to the Club model.

> This would be a field that is only visible to staff users of the [admin UI](https://github.com/mozilla/teach.webmaker.org/issues/925#issuecomment-104705395), and they could update it with any information relevant to the current approval flow status of the club that isn't otherwise captured by the system, e.g. "RC alice has set up a 1:1 interview w/ the club lead on june 5". This way more information is stored in the DB for all staff to see, rather than e.g. stuffed in an email thread somewhere that only a few people can see.

There are definite downsides to that approach, though, which we talked a bit about on a stand or something.

**Comment by jgmac1106** [comment]
99 problems and a club ain't one.

(sorry had to)

**Comment by hannahkane** [comment]
I think my flag in the stand-up re: staff notes field was that I'm not sure a single field could be as useful as a spreadsheet, at least not until we run through the process a bunch and work out the kinks.

@ldecoursy - with the email in the admin view, do we have enough for RCs, or do we need the description, too? What if we add the url for the specific club view, so RCs can just go to that URL?

**Comment by ldecoursy** [comment]
That sounds like it would be helpful/handy. And avoids having to add comprehensive descriptions in the admin view. 

@thornet sounds ok with you?

**Comment by toolness** [comment]
OK I GOT THIS

Check it out, this is what the admin clubs list view looks like as of https://github.com/mozilla/teach-api/commit/63b21da58b25d04dbf67d817cf5f260c654c4633:

![2015-06-09_18-23-42](https://cloud.githubusercontent.com/assets/124687/8071078/d50d9464-0ed4-11e5-8e37-74bfecfaf4f2.jpg)

Some things to note about the above screenshot:

* The list is being sorted by the "Created" date in descending order. It can be changed by clicking on the column name you want to sort by, and clicking again to toggle ascending/descending order. Whatever you choose will be how the rows will be listed in the exported CSV.
* The list has all the clubs selected. If you un-check any of the clubs, they won't be included in the CSV.
* The list has no clubs filtered. You can automatically filter out clubs by their status and "is active" properties (we have [docs on the differences between those two properties](https://github.com/mozilla/teach.webmaker.org/wiki/Club-Approval-Flow#aside-the-difference-between-status-and-is-active)). Whatever you filter out won't be in the exported CSV.

Once you choose the "Export CSV" action and click the "Go" button, your browser will be prompted to download a file called `clubs.csv`. Importing that into Google Spreadsheets with its default CSV settings gives you this (I bolded the first row and adjusted some of the column widths, but other than that, this is exactly how it imported):

![2015-06-09_18-38-07](https://cloud.githubusercontent.com/assets/124687/8071311/ce79c0da-0ed6-11e5-9cac-1be24274de0c.jpg)

Is that the kind of thing you were looking for? It's on production now if you want to try it out for yourself.

**Comment by hannahkane** [comment]
Amazing. Does this work for you, @ldecoursy @thornet ?

**Comment by ldecoursy** [comment]
It works for me! Thank you :)

**Comment by toolness** [comment]
Hooray!! I will close this now.
