### ISSUE TITLE
Code cleanup - rearrange list of routes

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1004]
from https://github.com/mozilla/teach.webmaker.org/blob/develop/lib/routes.jsx#L14-L42

```javascript
var routes = (
  <Route handler={Page}>
    <Route name="about" path="/about/"
     handler={require('../pages/about.jsx')}/>
    <Route name="activities" path="/activities/"
     handler={require('../pages/activities.jsx')}/>
    <Route name="protect-your-data" path="/activities/protect-your-data/"
     handler={require('../pages/protect-your-data.jsx')}/>
    <Route name="web-literacy" path="/teach-like-mozilla/web-literacy/"
     handler={require('../pages/web-literacy.jsx')}/>
    <Route name="events" path="/events/"
     handler={require('../pages/events.jsx')}/>
    <Route name="event-resources" path="/events/resources/"
     handler={require('../pages/event-resources.jsx')}/>
    <Route name="mozilla-clubs" path="/clubs/"
     handler={require('../pages/clubs.jsx')}/>
    <Route name="web-lit-basics" path="/activities/web-lit-basics/"
     handler={require('../pages/web-lit-basics.jsx')}/>
    <Redirect from="/clubs/curriculum/" to="/activities/web-lit-basics/" />
    <Route name="clubs-toolkit" path="/clubs/toolkit/"
     handler={require('../pages/clubs-toolkit.jsx')}/>
    <Route name="teach-like-mozilla" path="/teach-like-mozilla/"
     handler={require('../pages/teach-like-mozilla.jsx')}/>
    <Route name="fixme" path="/fixme/"
     handler={require('../pages/fixme.jsx')}/>
    <DefaultRoute name="home"
     handler={require('../pages/home.jsx')}/>
  </Route>
);
```

Could we rearrange these routes so they are in some sort of ordering?  It's getting harder for me to decide where I should plug in new routes :grimacing:  I vote for sorting `path` alphabetically since that can kinda inform sitemap as well.

e.g.,
/about
/activities
/activities/protect-your-data/
/activities/web-lit-basics/
/clubs/
/clubs/toolkit/
...

@toolness , any suggestion?

**Comment by toolness** [comment]
Ah yeah, I like the idea of sorting them alphabetically. Do you think you could issue a separate PR that just alphabetizes them, so we can get it integrated ASAP? (Since it's the re-sort will likely cause merge conflicts w/ any other routes we add/change, it'd be nice to get it over with and cause minimal disruption in other PRs.)

**Comment by toolness** [comment]
Er sorry, I just realized you filed this as a new issue, and not as part of a bigger issue... So you were probably planning on issuing a separate PR anyways hehe. Carry on then! :+1:
