### ISSUE TITLE
[ Pledge Workflow Part 3 ] Form submission and BSD list

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1016]
Depends on [[ Pledge Workflow Part 2 ] Build modals](https://github.com/mozilla/teach.webmaker.org/issues/1015)

Once https://github.com/mozilla/teach.webmaker.org/pull/1028 is landed on staging, verify the following
 - [x] Upon submission, the user's email address should go into a BSD list
 - [x] Should trigger transactional email (see copy in https://github.com/mozilla/teach.webmaker.org/issues/1016#issuecomment-111628846 and https://github.com/mozilla/teach.webmaker.org/issues/1016#issuecomment-113293385)

---

If all looks good,
- [x] push to PROD
- [x] Edit the existing [Mentor Signup Form](https://sendto.mozilla.org/page/s/mentor-signup) on BSD so that it sends proper transactional email and its redirect URL goes to https://teach.mozilla.org/?pledge=thanks

---

meta bug for Pledge Workflow: https://github.com/mozilla/teach.webmaker.org/issues/978

**Comment by mmmavis** [comment]
The following are the required fields we need for the transaction email sent by BSD.

![screen shot 2015-06-12 at 2 52 17 pm](https://cloud.githubusercontent.com/assets/2896608/8140714/f7e49682-1112-11e5-9d65-535ce52d8863.png)


From https://teach.etherpad.mozilla.org/clubtransactionalemails

**Subject line**
```
Thanks for pledging to Teach the Web!
```

**Email body**
```
Welcome! We're thrilled that you've made a commitment to the open Web and to sharing your knowledge with others. Thanks for taking the first step to keep the Web an open public resource for all. 

Now, we'd love to learn a little more about you so we can help you teach the Web! 

Please fill out this short survey: http://bit.ly/1F4jomG

Mozilla Learning Networks offers:
- Free and open source activities and lesson plans for teaching web literacy skills
- Opportunities to develop your own leadership and mentoring skills
- A forum to connect with others around the globe who care about teaching digital skills
- Best practices for leading hands-on, production-centered events and programs

Tell us more about yourself so we can share the most relevant opportunities and resources: http://bit.ly/1F4jomG. Of course, we do respect your privacy* and honor the information you're sharing with us.

If you have questions, we’re here to help. Follow us @Mozteach and use the #teachtheweb hashtag to find us. 

Michelle Thorne
on behalf of the Mozilla Learning team
```
:question: :question: :question: Question: should I put Michelle as the name of the sender and her MoFo email address as the sender's email?

**Comment by mmmavis** [comment]
@hannahkane see above

**Comment by hannahkane** [comment]
@amirad @thornet  - How do we normally do this? Do we say, "Michelle Thorne, Mozilla Foundation"? 
Michelle - are you okay with having your email address on the pledge email?

**Comment by amirad** [comment]
Things to consider:
•In the past we have only listed generic email addresses for response like makerparty@mozilla.org, help@webmaker.org or teachtheweb@mozillafoundation.org - we've never listed a personal email address and it probably makes sense to continue that. 
•If we list a name, that person should be prepared to respond to emails. So that's a question for Michelle? In the past I have received anywhere from 15-100+ emails a week which you have to filter through for spam and respond to many others. An alternative is putting just "the learning networks" on the signature and allowing anyone to answer emails (though it's most only me responding right now).

**Comment by hannahkane** [comment]
@thornet - can you make a decision on how you want to handle the pledge email? Thanks!

**Comment by hannahkane** [comment]
ping @thornet. we need to know who to make this email from before we can move forward with this ticket. thanks!

**Comment by amirad** [comment]
I think @thornet is having trouble getting github notifications right now so I just skype nudged her :)

**Comment by hannahkane** [comment]
Thanks, @amirad!

**Comment by thornet** [comment]
Hey all, 

Sorry for the connection trouble. I'd prefer to use a general, shared email for this rather than my personal one. Fine if we say it's from me if we think it'll get better results having a name there. 

I suggest: teachtheweb@mozillafoundation.org

**Comment by amirad** [comment]
+1 to using a shared email. 

What I was wondering is if we put your name, will you be able to respond to the emails that come to teachtheweb@mozillafoundation.org? I'm okay responding to less of our on-going emails as they come to teachtheweb@mozillafoundation.org and focusing on other support channels as I think it's important if a name is attached to that email you get to sometimes talk to that person. I have heard this voiced from our community in the past.

**Comment by hannahkane** [comment]
Unblocking this since we've decided to use teachtheweb@mozillafoundation.org as the from/replyto address, but keep Michelle's name in the signature.

We can figure out how we reply to emails that come into that account separately.

**Comment by mmmavis** [comment]
blocked on https://github.com/mozilla/teach.webmaker.org/issues/1016

**Comment by mmmavis** [comment]
@hannahkane 

I just tested this on staging site and everything worked out fine.  Now we have to push a new release to PROD before I can change the **existing** BSD form and redirect URL for Thank You message.

I will do ^ tomorrow morning instead - when @hannahkane is back from PTO (and @toolness is online in case things go wrong)  :bowtie: 

/cc @toolness

**Comment by hannahkane** [comment]
Looks great on staging. :)

**Comment by mmmavis** [comment]
DONEEEEEEEEEEEEE! :tada: :dancers: https://teach.mozilla.org/

**Comment by toolness** [comment]
HOORAY!

I just pledged to teach!

I guess that means I have to keep my promise...

**Comment by amirad** [comment]
Haha @toolness! 

It looks great! Awesome job gang.
