### ISSUE TITLE
More than one person should know how to create and deploy a new release

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#1017]
To increase our project's [:bus: bus factor :bus:](http://en.wikipedia.org/wiki/Bus_factor), I think someone other than just me should know how to issue and deploy a new release of the site!

@mmmavis would you be interested in taking this on for the next release? I tried to document the process in [`RELEASE.md`](https://github.com/mozilla/teach.webmaker.org/blob/develop/RELEASE.md) and also made a script that will automatically generate customized instructions for your GitHub username and the release number you want to issue. (For the release number I recommend just incrementing the [PATCH version](http://semver.org/)).

**Comment by mmmavis** [comment]
Yea that's for sure!  I definitely wanna learn that too. It would be fantastic if you could be around when I do my first Teach site deployment in case... *bad things* happen...  :see_no_evil:

**Comment by toolness** [comment]
Cool! One of the nice things about the release process is that nothing really bad can happen until you get to step 8, when you merge the PR into master. So feel free to start the process if you like, and then wait at the end of step 7 for me to give a :+1: on the PR if you want.

**Comment by toolness** [comment]
Hey @mmmavis, @hannahkane and I were talking today and we think it's ok to make a new release with the Tools page orphaned (i.e., not linked-to from the sidebar). It's particularly important to push a new release soon because we really want that maker party promo on the front page to be visible.

Do you think you can get to this today? If not I can take care of it and you can take care of the next one... in fact perhaps it might be better for both of us to push a release in-person at Whistler. Up to you!

**Comment by mmmavis** [comment]
@toolness sorry just saw your comment now.  I can try making a new release today - probably in 30mins or so.  Gonna :fork_and_knife: and read through RELEASE.md again first :bowtie:

**Comment by mmmavis** [comment]
Yayyyyy v0.0.10 is out on https://teach.mozilla.org/ :tada: :tada: :tada: 
Thanks team!  @toolness your [RELEASE.md](https://github.com/mozilla/teach.webmaker.org/blob/develop/RELEASE.md) makes this process super easy! Thanks! :clap: :clap: :clap:

**Comment by hannahkane** [comment]
Nice job on the release, @mmmavis!!!

**Comment by toolness** [comment]
Woot nice work @mmmavis !!! :boom:
