### ISSUE TITLE
development bug - npm start failing 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1019]
When running `npm start` from the `develop` branch the following error occurred.

```shell
Fatal error while compiling index-static.bundle.js { [Error: EMFILE, open '/Users/mavisou/Development/teach-test/build/index-static/1.index-static.bundle.js']
  errno: 20,
  code: 'EMFILE',
  path: '/Users/mavisou/Development/teach-test/build/index-static/1.index-static.bundle.js' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: building index-static.bundle.js failed
    at failure (/Users/mavisou/Development/teach-test/lib/index-static-watcher.js:102:10)
    at IndexStaticWatcher.onBuild (/Users/mavisou/Development/teach-test/lib/index-static-watcher.js:59:14)
    at Tapable.<anonymous> (/Users/mavisou/Development/teach-test/node_modules/webpack/lib/Compiler.js:184:21)
    at Tapable.<anonymous> (/Users/mavisou/Development/teach-test/node_modules/webpack/lib/Compiler.js:263:19)
    at done (/Users/mavisou/Development/teach-test/node_modules/webpack/node_modules/async/lib/async.js:126:15)
    at /Users/mavisou/Development/teach-test/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at fs.js:944:21
    at Object.oncomplete (fs.js:107:15)
```

I *think* this is [the commit](https://github.com/mozilla/teach.webmaker.org/commit/8dca64c5e81e0627a5acce83143d4b916107718b) that introduced this issue.  Gonna see if I can fix this before @toolness is back from PTO :eyes:

**Comment by mmmavis** [comment]
Seems like it's ```gulp.watch('img/**', ['copy-images']);``` in [gulpfile.js](https://github.com/mozilla/teach.webmaker.org/blob/develop/gulpfile.js#L222) that's causing problem.  I tried removing some files from that `img` dir and the error was gone.  I'm guessing it's something to do with the number of files we are watching?

**Comment by mmmavis** [comment]
Ummm I also tried changing 

```javascript
gulp.watch('img/**', ['copy-images']);
```

 to 

```javascript
gulp.watch([
    'img/**/*.png',
    'img/**/*.jpg',
    'img/**/*.svg'
  ], ['copy-images']);
```
and encountered NO errors.  :open_mouth:

**Comment by toolness** [comment]
Hmm, I'm not experiencing this bug on my end, but I like your solution for watching specifically PNG, JPG, and SVG files... If we copy only those files too, this might help with getting the `imagemin` plug-in working properly, which I was having trouble with in https://github.com/mozilla/teach.webmaker.org/issues/946#issuecomment-110430743.

**Comment by mmmavis** [comment]
I'm not sure if this is related to my `ulimit -n`.  It was at 256 initially but changing it to 1024 didn't fix the error either... ummmmm......

I can replace `gulp.watch('img/**', ['copy-images']);` with

```javascript
gulp.watch([
  'img/**/*.png',
  'img/**/*.jpg',
  'img/**/*.svg'
], ['copy-images']);
```

I guess if we happen to add files of another type (e.g., GIF) in the future we'll just have to update the array of glob strings.
