### ISSUE TITLE
Verify hero unit background images look fair on mobile

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1022]
To fix the ["mobile view just shows the back of a head" issue](https://github.com/mozilla/teach.webmaker.org/issues/958), we have set `background-position: center top;` to the `.hero-unit` class.  This ensures on smaller devices the middle section of the background image is visible (instead of the upper right section, which is what we had before).

This change applies to *ALL* hero unit background images.  As @toolness' [suggestion](https://github.com/mozilla/teach.webmaker.org/issues/958#issuecomment-110328707) we should also manually verify how each page looks on the staging site.  If universal CSS rule doesn't work, we can tweak the background position in a per-page fashion.

@sabrinang @hannahkane please help QA :wink: https://teach.mofostaging.net/

**Comment by hannahkane** [comment]
All looks good on Safari in iPhone 5. The center of the homepage is a blurry part of the image, but it's less distracting than the back of the head. Other pages look good.

**Comment by mmmavis** [comment]
Cool, once we get a OK from @sabrinang we can close this ticket :dancer:

**Comment by mmmavis** [comment]
@sabrinang got a chance to QA this?  :information_desk_person:

**Comment by sabrinang** [comment]
Looking good. The centered images for all hero banners improved to focus on the main points visual interests on the photographs! I much prefer the homepage to focus on the person/laptop that is out of focus then the previous back-of-the-head area (on landscape, you can see the side of her face/glasses and is fine) and does not interfere with the title text.

(I tested this on my Nexus 4 on Firefox for android and Chrome)
