### ISSUE TITLE
Create illustrations for "Tools" and "Community"

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1029]
We're adding these two items to the main navigation, and they'll need illustrations to match the other items.

**Comment by sabrinang** [comment]
for issue https://github.com/mozilla/teach.webmaker.org/issues/991

**Comment by hannahkane** [comment]
Moving to next heartbeat

**Comment by sabrinang** [comment]
Adapted existing icon visuals to make tools and community icons 
![screen shot 2015-07-02 at 11 54 49 am](https://cloud.githubusercontent.com/assets/2492510/8485273/5ced5124-20b1-11e5-9c54-901a928efc7d.png)

Exported as white .svgs following [suggested settings] (https://camo.githubusercontent.com/69c348570a2ef5be91c9b265336940328de10479/687474703a2f2f64656d6f737468656e65732e696e666f2f6173736574732f696d616765732f696c6c7573747261746f722d7376672d616476616e6365642d6f7074696f6e732e706e672e7061676573706565642e63652e4a7a53383546665272412e706e67) from previous .svg isssue https://github.com/mozilla/teach.webmaker.org/pull/1052

tools icon: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eX2tsQVNBNWlmY0k/view?usp=sharing
community icon: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ecEptcHNaNUZWMUk/view?usp=sharing

**Comment by mmmavis** [comment]
Thanks! @sabrinang if this is done could you close the ticket :+1:

**Comment by sabrinang** [comment]
Yup! (if it needs to be exported in other ways just comment)
