### ISSUE TITLE
Locally host Open Sans, at least for local development

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#1037]
Because [devs shouldn't let devs use Arial](https://github.com/mozilla/teach.webmaker.org/pull/1036/files#r32576552).

**Comment by mmmavis** [comment]
Closing this ticket - 

We assumed that Open Sans is commonly installed on a dev's local machine and we thought referencing to it [as a local system font as a fallback](https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,700,600italic,700italic,800,800italic) should probably be enough.
