### ISSUE TITLE
Design "Clubs Curriculum" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#106]
### RACI
* Phase: Design
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: @vazquez  
* Dev Lead: NA
* Quality: @davidascher 

As per recent conversation with @cassiemc, this is the *new* page we need to design. 

Let's explicitly present the Web Literacy Basics curriculum as a sequence of activities designed to be done as a unit, in the context of Clubs. 

The most up-to-date Clubs Curriculum can be found here: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/index.html

Some important context can be found here: https://etherpad.mozilla.org/teachsitequestions

**Comment by hannahkane** [comment]
@cassiemc - let me know if you need anything from me on this one. In my mind, this one is more ready to go than the Teaching Activities page content which will be finalized by EOD Friday.

**Comment by mcdermott415** [comment]
@hannahkane hi

**Comment by cassiemc** [comment]
I didn't get to this last week, but think I'd better pass of to @vazquez so I can move on to Login designs. The Teaching Activities page is in issue #36

**Comment by hannahkane** [comment]
@vazquez - lemmeknow if you want to talk through this!

**Comment by vazquez** [comment]
@hannahkane I would love that :) I'll message you on IRC

**Comment by vazquez** [comment]
Design with copy placeholders: http://invis.io/242EBB23A

**Comment by hannahkane** [comment]
@vazquez - thanks for the speedy work! We'll start commenting on the design, but don't worry about actually making design updates until I synthesize our feedback tomorrow.

@thornet @chrislarry33 @ldecoursy - Let's aim to compile our feedback by EOD tomorrow on this one as well.

Some things:
 * Let Ricardo know if you don't have access to the Invision project. Invision is the new tool we're testing out this heartbeat.
 * Copy will happen here: #183 
 * Would welcome feedback about the page design itself, including the sidebar nav, since this is the first time we're addressing a child page (the Clubs Curriculum page will be linked to *from* the Clubs page).

**Comment by vazquez** [comment]
I have added @thornet @chrislarry33 and @ldecoursy to InVision, you all have invite links in your inbox.

**Comment by chrislarry33** [comment]
@hannahkane @ldecoursy Lets talk about this tomorrow during our huddle, get something for @thornet to review

**Comment by vazquez** [comment]
I'm blocked on copy review @ldecoursy @thornet @chrislarry33  

cc @hannahkane

**Comment by hannahkane** [comment]
Copy is happening in #183. I do not expect major changes to the design as a result. (Did I just jinx us? :))

**Comment by thornet** [comment]
Design looks great to me.

**Comment by vazquez** [comment]
Design :white_check_mark:  
Copy :white_check_mark: 

We are good to begin building this page :boom:

**Comment by hannahkane** [comment]
w00t!
