### ISSUE TITLE
link to clubs fact sheet from clubs page

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#1061]
probably already part of the redesign but the fact sheet is only linked to from the add your club modal which requires sign in.

**Comment by kleberveridiano** [comment]
VERY NICE!

**Comment by kleberveridiano** [comment]
VERY NICE PRÁ XUXU


KLEBER

**Comment by kleberveridiano** [comment]
iT´S VERY NICE!

**Comment by hannahkane** [comment]
part of the Clubs re-design, so closing this
