### ISSUE TITLE
Few staffing updates on HiveLearningNetworks.org

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#1063]
Hoping @mmmavis can help with a few small changes on the Locations page of the Hive Global site.

* Hive Toronto - contact should just be Simona (can copy the info under Hive Bay Area)
* Hive Chattanooga - remove Geoff :(
* Hive Kansas City - replace Kari with Lindsey (copy info under Chattanooga)

Thanks!
Lainie

**Comment by mmmavis** [comment]
yup will work on this today

**Comment by mmmavis** [comment]
yay done! :smile:
