### ISSUE TITLE
Stray asterisk in "Thanks for pledging to Teach the Web" email

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#1065]
I signed up to pledge on teach.mozilla.org and the email sent to me includes the following paragraph:

> Tell us more about yourself so we can share the most relevant opportunities and resources: http://bit.ly/1F4jomG. Of course, we do respect your privacy* and honor the information you're sharing with us.

I thought the `*` after "privacy" was indicating some kind of footnote, but there was no footnote at the bottom of the email... is it a typo or something?

**Comment by hannahkane** [comment]
I believe there was meant to be a link to our privacy policy at the bottom (https://www.mozilla.org/en-US/privacy/websites/)

**Comment by mmmavis** [comment]
nice catch!  apparently I forgot to copy the very last sentence
```
* Privacy policy: https://www.mozilla.org/en-US/privacy/websites/
```

**Comment by mmmavis** [comment]
![screen shot 2015-06-30 at 4 23 40 pm](https://cloud.githubusercontent.com/assets/2896608/8444336/6ad41afc-1f44-11e5-998b-1de33aa28214.png)

---
Ok, this is now fixed :+1: thanks @toolness for spotting it

**Comment by toolness** [comment]
Awesome, thanks mavis!
