### ISSUE TITLE
Web-based Version of Mozilla Clubs Wordmark

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.webmaker.org#1066]
Request to have a Thimble make that could use CSS to make a Mozilla Club Wordmark so Club Captains can just change the text of City Name and take screenshots to use - reference https://github.com/mozilla/teach.webmaker.org/issues/933#issuecomment-118085195

**Comment by sabrinang** [comment]
Work in progress using [Fira Sans] (https://www.google.com/fonts/specimen/Fira+Sans) and [Codepen] (http://codepen.io/sabotage/pen/XbZYLz) first and will get to a thimble make
![screen shot 2015-07-02 at 2 26 21 pm](https://cloud.githubusercontent.com/assets/2492510/8488309/aa7e1daa-20c6-11e5-89a6-967cfb1995b3.png)

**Comment by sabrinang** [comment]
https://sabby.makes.org/thimble/LTE3ODg0MTEzOTI=/mozilla-clubs-wordmark
![screen shot 2015-07-02 at 3 44 00 pm](https://cloud.githubusercontent.com/assets/2492510/8490088/3fda1140-20d8-11e5-8d5a-e98c3caf248e.png)

**Comment by jgmac1106** [comment]
You are awesome. Thanks folks.

**Comment by sabrinang** [comment]
cc @mmmavis

**Comment by sabrinang** [comment]
Updated make with some guidelines: https://sabby.makes.org/thimble/NzYxNzkwOTc2/mozilla-clubs-wordmark
![screen shot 2015-07-03 at 4 20 04 pm](https://cloud.githubusercontent.com/assets/2492510/8505579/6c1e03b6-219f-11e5-99d6-bdf8ba0c4cc5.png)

@mmmavis R?

**Comment by mmmavis** [comment]
Awesome @sabrinang !  Nice to see that you are having fun with HTML and CSS :+1: 

Few suggestions:

- Although this may seem obvious, I think it would be great if we specially tell people to "remix" this Make to generate their own wordmark.  This [Make](https://sabby.makes.org/thimble/NzYxNzkwOTc2/mozilla-clubs-wordmark) shows rendered result without source code on the side.  "Select the word" could sound a little vague - is it the text I'm selecting? or the source code? 
- Your `background-color` and `color` of `html, body` are set to the same colour(dark grey).  Taking a glance at the Make you can see the majority of the body text is in `white`.  This suggest you should apply `color: #FFF` to `body` instead.  If any child element wants another colour for its text, you can simply override that rule. e.g.,
```css
#mozilla-clubs-wordmark {
  ...
  ...
  ...
  color: #4E4F53;
}
```
- the `h1 {}` and `h2 {}` block means that the rules within them will apply to ALL `<h1>` `<h2>` in the entire DOM, which is probably not what you want.  If you want those rules to apply just within the workmark section, a more specific CSS selector is suggested, i.e., `#mozilla-clubs-wordmark h1`
- You would need to arrange your [headings](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to make them more semantically correct.  It's a good practice to ask yourself if the text really acts like a heading.  Also think about the ordering of heading elements you are using.
- Some rules could be extracted and moved to their shared / ancestor block instead.

You are making great progress @sabrinang ! Let me if you need further explanation :dancers:

**Comment by thornet** [comment]
<3! Adding it to our resources page for clubs (which will port over eventually to the website). 

http://mozilla.github.io/learning-networks/clubs/

**Comment by ldecoursy** [comment]
Awesome! One small copy edit: In the second bullet, instead of "if your Mozilla Learning network has limited resources." it should say "if your Mozilla Club has limited resources."

Thanks!

**Comment by hannahkane** [comment]
Can I close this?

**Comment by sabrinang** [comment]
I updated the copy edit from @ldecoursy and updated suggestions from @mmmavis
Updated make is here: https://sabby.makes.org/thimble/LTExODQxMDM5MzY=/mozilla-clubs-wordmark
@thornet - I couldn't edit my previous make I had to remix it to change it so you will have to update the previous link
