### ISSUE TITLE
Deploy to a staging S3 site whenever 'master' is pushed to

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#107]
The original version of the site was hosted on gh-pages, because we were able to have an `index.html` file that dynamically loaded all the assets for a full site without needing a build step. However, splitting the JS codebase up into modules necessitated that we migrate to a system requiring a build step.

Currently, I'm manually syncing the codebase every so often to http://mozilla-learning-html.s3-website-us-east-1.amazonaws.com/. But it would be cool if, say, Travis did this when tests pass, or if we just had some kind of git post-commit hook that does it for us.

**Comment by toolness** [comment]
Hmm, while we are at it, we should probably deploy to an easier-to-remember URL, lol.

![screen shot 2015-03-04 at 6 12 08 pm](https://cloud.githubusercontent.com/assets/124687/6495655/12347646-c29a-11e4-9f21-c5c9c53f596d.png)

**Comment by mmmavis** [comment]
+1 :grimacing:

**Comment by toolness** [comment]
Ok, I set up a better stage name today! We're now at http://teach.mofostaging.net/ :)

**Comment by toolness** [comment]
If we use Travis to do this, we'll have to use its support for [secure environment variables](http://docs.travis-ci.com/user/environment-variables/#Secure-Variables).

**Comment by toolness** [comment]
[Hooray it works!](https://travis-ci.org/mozilla/teach.webmaker.org/builds/53397737)

I have a feeling that PRs are likely to fail because Travis will try to push to S3 and won't have the AWS credentials handy for security reasons, but we can cross that bridge when we burn it by having `gulp s3` check whether [`TRAVIS` is `true`](http://docs.travis-ci.com/user/ci-environment/#Environment-variables) and then checking whether `TRAVIS_SECURE_ENV_VARS` is `false` and aborting with a zero exit code if so.

**Comment by toolness** [comment]
Update: in dc3c6783c2275c6220c3cb79e649a95ec07901e4 I made Travis only push to S3 if the job isn't a PR, and if it's on the `develop` branch.
