### ISSUE TITLE
Update or remove Webmaker logo

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/teach.webmaker.org#1073]
Login on this site includes an old Webmaker logo. We should update ... or consider removing the logo. With shift in platforms, it doesn't really belong here anymore. 

cc @cassiemc @hannahkane 

<img width="915" alt="screenshot 2015-07-06 11 21 14" src="https://cloud.githubusercontent.com/assets/53411/8525913/749acaae-23d1-11e5-940a-6c3fea3d5d86.png">

**Comment by hannahkane** [comment]
I think we still need the logo, since the original rationale still stands—when people join the MLN site, they are required to create a Webmaker account.

Will update logo.

**Comment by xmatthewx** [comment]
@hannahkane - makes sense. I don't think we have a flat, one-color version of the logo yet. @lovegushwa @vazquez.

**Comment by cassiemc** [comment]
Would be great if you could tackle a one-color logo this week, @lovegushwa!

**Comment by mmmavis** [comment]
It would be great if we can have this ready before Maker Party starts (July 15).  @lovegushwa would it be possible for you to have the pass the one-color logo to me early next week?

Also, I realized the Webmaker logo on the [Tools page](https://teach.mozilla.org/tools/) needs to be updated as well.  (please attach file here :smile:)

**Comment by xmatthewx** [comment]
@mmmavis - you can probably find what you need here: https://drive.google.com/drive/folders/0B2qu3ExKWIlvMjY0U3I3YUNva0k

**Comment by mmmavis** [comment]
awesome thanks @xmatthewx ! we still need a one-color version though :+1: :smiley:

**Comment by hannahkane** [comment]
@lovegushwa - any chance we could get the one-color version today? We're planning a release, and it would be good to include this.

**Comment by lovegushwa** [comment]
@hannahkane @cassiemc @mmmavis @xmatthewx  R?
Sorry I missed this everyone. I think this should work. 


![webmaker-white](https://cloud.githubusercontent.com/assets/12228435/8681642/9775ede0-2a1d-11e5-9ec1-1a5aecd6c6c4.jpg)

**Comment by cassiemc** [comment]
Niiiice! Love it! R+ from me. Can you add the final svg to Drive @lovegushwa and link it here?

**Comment by hannahkane** [comment]
Pretty!

**Comment by lovegushwa** [comment]
@cassiemc @mmmavis 
For now it's a png (I'm not sure if I can create a transparent svg but I will look into it.)
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvVV90bk5uVXJzQmc/view?usp=sharing

**Comment by cassiemc** [comment]
Sweet, thanks @lovegushwa

**Comment by mmmavis** [comment]
@lovegushwa lovely :smile: !!! One thing I wanna mention is that the sidebar colour changes based on which page you are currently viewing, so it's *not* always blue.  Not sure if the blue for one-colour logo was chosen because of that though... just thought I should flag this :grin:

**Comment by lovegushwa** [comment]
@mmmavis let me see if I can create a version that works with just transparency (rather than color.)

**Comment by lovegushwa** [comment]
@mmmavis try this version on a color background and send me a screenshot.
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvbndtd1RVd1dYTk0/view?usp=sharing

**Comment by mmmavis** [comment]
@lovegushwa working beautifully! :dancer: thanks!

some screencaps
![screen shot 2015-07-14 at 3 13 29 pm](https://cloud.githubusercontent.com/assets/2896608/8686412/fbe8deb4-2a3a-11e5-8b79-7999ca634d6d.png)
![screen shot 2015-07-14 at 3 13 23 pm](https://cloud.githubusercontent.com/assets/2896608/8686413/fbec3a6e-2a3a-11e5-9d38-bd43668ddbd3.png)
![screen shot 2015-07-14 at 3 13 16 pm](https://cloud.githubusercontent.com/assets/2896608/8686415/fbf215f6-2a3a-11e5-80bf-6b37019cca58.png)
![screen shot 2015-07-14 at 3 13 11 pm](https://cloud.githubusercontent.com/assets/2896608/8686414/fbef7864-2a3a-11e5-9d07-8b561134a15c.png)

**Comment by mmmavis** [comment]
@lovegushwa let me know if you are able to create a svg version of this.  Otherwise I can just plug in with the .png you provided :)

**Comment by lovegushwa** [comment]
@mmmavis lets go with the .png for now. It's going to take be a bit of research to figure the transparency out in .svg ... Looks great, nice to see them in so many colors!

**Comment by mmmavis** [comment]
:dancers: :dancers: okie dokie

**Comment by lovegushwa** [comment]
yay!
