### ISSUE TITLE
Design slide template for Mozilla Learning Networks

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#1077]
Need simple slide design template for Mozilla Learning Networks - ideally something that matches teach.mozilla.org and can be used with Google Slides. 

Would love in time for next Program Review on 7/21 if possible! (which means by next Thurs July 16 ideally)

**Comment by hannahkane** [comment]
@sabrinang - is this something you think could fit into the current heartbeat? What additional information would you need?

**Comment by sabrinang** [comment]
Sure. I'll make it in Google slides and I'll use slide size: widescreen 16:9.

**Comment by hannahkane** [comment]
Sweet. Thanks!

**Comment by sabrinang** [comment]
https://docs.google.com/a/mozilla.com/presentation/d/1cDzhTWTsiogmhaRk7uzW_1oKYHJgkF-MD7WpMGGPJoU/edit?usp=sharing

You can use this as a template if you go:
File > Make a copy...

You can find the various slide options in:
Slide > Apply layout

Let me know if there is anything else to add!

**Comment by ldecoursy** [comment]
Thanks!
