### ISSUE TITLE
Use of all-caps to emphasize text is weird

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#1084]
On the Events page, the mini case study for the "Make and Remake Hackathon" says:

> At the Make and Remake Hackathon Day attendees spent the first half of the day using Webmaker tools to MAKE something awesome. In the second half of the Hackathon individuals then turned their completed makes over to a friend so they could then REMAKE their make to create something new.

The use of all-caps for MAKE and REMAKE reads really weird to me, perhaps because we don't use such a typographic convention anywhere else on the site. I think it'd look more consistent (and probably be more accessible) if these words were italicized via `<em>` instead, but it's up to you... Feel free to just close this issue if you disagree.

**Comment by mmmavis** [comment]
+1 on using `<em>`

**Comment by mmmavis** [comment]
- existing, "MAKE" and "REMAKE" in all caps

<img width="1009" alt="screen shot 2015-07-13 at 12 15 48 pm" src="https://cloud.githubusercontent.com/assets/2896608/8658554/65da6e06-2959-11e5-9df2-451c4d0f4e69.png">

- updated, italicized "make" and "remake"
<img width="1031" alt="screen shot 2015-07-13 at 12 19 09 pm" src="https://cloud.githubusercontent.com/assets/2896608/8658556/67138d20-2959-11e5-81a1-9d57d0326409.png">

@hannahkane do you think we can go ahead and make the changes?

**Comment by hannahkane** [comment]
+1. Easier to read this way, for sure.
