### ISSUE TITLE
Modify copy on "Add a club" button and form

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#1085]
We've reached capacity for accepting new clubs. While #859 is underway, there's a few quick edits that would help a lot, especially before all the Maker Party site visitors come to the site: 

https://teach.mozilla.org/clubs/

I.  
* Current: Button "ADD YOUR CLUB" 
* Proposed: Button "APPLY" 

II. 
* Current: Form Header "Add Your Club To The Map" 
* Proposed: Form Header "Apply for the next round of Mozilla Clubs." 

III.
* Current: N/A
* Proposed: Form, add a text line before first question: "We're full! Let us know if you'd like to be consider for the next round."

IV. 
* Current: Form Button "Add Your Club To The Map" 
* Proposed: Form Button "Apply"

**Comment by mmmavis** [comment]
I'll try to get this shipped today :smiley:

**Comment by mmmavis** [comment]
![screen shot 2015-07-09 at 12 27 13 pm](https://cloud.githubusercontent.com/assets/2896608/8604854/fe1de3ea-2635-11e5-9854-8cb4ff4138a9.png)

Hey @sabrinang I've applied all copy changes(see screencap). I'm wondering if there's any styling treatment you would like to add, especially something to make "We're full! Let us know if you'd like to be consider for the next round." more standout? 

If you have time I think this is also a good time to decide what we want to do with https://github.com/mozilla/teach.webmaker.org/issues/1045 .

**Comment by hannahkane** [comment]
Just noticed a typo. Should read, "Let us know if you'd like to be considered for the next round." ("considered" rather than "consider")

**Comment by mmmavis** [comment]
nice catch @hannahkane

**Comment by sabrinang** [comment]
The type treatment is fine. I'm curious about the experience after you hit apply button. Is there copy explaining how long the consideration for the next round will be afterwards? (i.e. - we will inform you within the next weeks or months?)

**Comment by mmmavis** [comment]
@thornet ^ :smile:

**Comment by hannahkane** [comment]
How about a success message that reads, "Thanks for your interest! We'll be in touch when we start the next round."

^ @thornet

**Comment by thornet** [comment]
Looks great! Thanks, all. 

PS. Is there also still an automated email that comes after sign-up? Will file a bug to update that, too, but checking first.

**Comment by hannahkane** [comment]
I don't believe there's an auto-email (as detailed on https://github.com/mozilla/teach.webmaker.org/wiki/Club-Approval-Flow), but maybe @mmmavis can confirm?

**Comment by mmmavis** [comment]
heh I would need to defer this to @toolness  :wink:

**Comment by hannahkane** [comment]
I was wrong! @toolness clarified that we do send an email to the user. Text can be found here: https://github.com/mozilla/teach-api/blob/master/clubs/email.py

**Comment by mmmavis** [comment]
<img width="528" alt="screen shot 2015-07-14 at 1 18 07 pm" src="https://cloud.githubusercontent.com/assets/2896608/8683991/cf840f98-2a2a-11e5-8897-70b02238e94a.png">

@hannahkane above is what the current confirmation modal looks like. Should I just 
- replace `Thanks for your submission!` with `Thanks for your interest!`
- and replace `We‘ll review it and be in touch shortly` with `We'll be in touch when we start the next round.`? (see screencap below)

<img width="522" alt="screen shot 2015-07-14 at 1 22 01 pm" src="https://cloud.githubusercontent.com/assets/2896608/8684096/57ef4410-2a2b-11e5-9c3a-eed64c2e1704.png">

**Comment by mmmavis** [comment]
Oh and do we want to capitalize "club"?

**Comment by hannahkane** [comment]
+1 to your suggestion, and I'd say, yes, let's start capitalizing Club.
