### ISSUE TITLE
Write copy for Clubs landing page changes

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#1086]
Per https://etherpad.mozilla.org/clubssitemeeting and related to #859:

teach.mozilla.org/clubs next version should include: 

- [x] What is a Mozilla Club. Updated from http://mozilla.github.io/learning-networks/clubs/. 
- [x] Map of Active & Approved Clubs.
- [x] Waitlist section / application flow update. "Add" > "apply to the wait list" see also #1085 
- [x] Replace toolkit with fact sheet

Responsible: @thornet 
Consulted: @hannahkane @ldecoursy @sabrinang @amirad

**Comment by hannahkane** [comment]
Hey @thornet - wondering if you can clarify what the deliverables are for this ticket. I *think* it's probably final copy for the page, including section headings and things like that, but just want to confirm, as well as offer help.

**Comment by thornet** [comment]
+1 to delivering the final copy. Modifying the ticket.

**Comment by thornet** [comment]
Content outline stated here: https://etherpad.mozilla.org/clubssitemeeting

**Comment by hannahkane** [comment]
Did a draft of full copy based on @thornet's outline: https://etherpad.mozilla.org/clubssitemeeting

feedback? @thornet @amirad @chrislarry33 @ldecoursy @sabrinang

**Comment by hannahkane** [comment]
Anyone have time to take a look at the copy outlined here? https://etherpad.mozilla.org/clubssitemeeting

cc @thornet @ldecoursy

**Comment by ldecoursy** [comment]
I added some comments/edits last week. @thornet can you give final approval?

**Comment by thornet** [comment]
Updated in the etherpad. Final read-through for any stray bits? 

@hannahkane @ldecoursy @HPaulJohnson merci!

**Comment by hannahkane** [comment]
Just made some grammar edits to the "Why start a Mozilla Club?" bullet points, but needs to be edited for word choice now :)

**Comment by thornet** [comment]
thanks, @hannahkane! Did a pass there as well.

The other unresolved part is the subheader at the top of the page. Threw in a more descriptive alternative. Curious what folks think.

**Comment by hannahkane** [comment]
Closing this to start design work (#858)
