### ISSUE TITLE
Update Maker Party activities with Webmaker teaching kits

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#1090]
Here are the updated activities to be added to the activities page: https://teach.mozilla.org/activities/maker-party-2015/ They are still being updated but the links should stay the same (right @secretrobotron?) 

http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/create-webmaker-project.html

Offline activity: http://secretrobotron.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html 

cc: @hannahkane

**Comment by secretrobotron** [comment]
No, they'll change once they're merged (after you've approved them :smile:). Finals should be at
* http://mozilla.github.io/webmaker-curriculum/MobileWeb/create-webmaker-project.html and
* http://mozilla.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html

**Comment by hannahkane** [comment]
Sweet. Will follow this ticket and will file a ticket to update the MP activities page when these are good to go.

**Comment by secretrobotron** [comment]
cc @HPaulJohnson @alamanda @deryanEM

**Comment by secretrobotron** [comment]
cc @panaggio

**Comment by amirad** [comment]
@hannahkane since we will be sending them out on Wednesday can we update the page with those final links Bobby shared so we can be super ready?
@secretrobotron just provided some feedback, let's push live what we have tomorrow by the latest so at least something is up there.

**Comment by hannahkane** [comment]
sorry, didn't realize what repo I was in. :) yes, we can do this, but we'll need copy that follows this format, for both of the activities:


@mmmavis or @toolness - can either of you make this a priority?

**Comment by hannahkane** [comment]
Here's my suggestion for copy for the /activities/maker-party-2015/ page. Look okay, @amirad @secretrobotron ?

Create a Webmaker Project
Understanding remixing, designing, and composing
Create original Web content using the Webmaker app for Android. Create a scavenger hunt, a scrapbook, a birthday card, or anything else you can imagine!

No Wifi at Your Event? Design a Story for the Web
Understanding remixing, designing, and composing
Ideate, sketch and structure a story to create with Webmaker. By brainstorming offline, learners will start thinking about the different ways to create for the Web and get more comfortable with the idea of creating their own content.

**Comment by secretrobotron** [comment]
* Let's make "the Webmaker app for Android" just "Webmaker for Android.
* IMO "brainstorm" is much clearer than "Ideate".

Otherwise, :+1:. :shipit:

**Comment by amirad** [comment]
I don't think the second activity is specific to Webmaker App so made the text neutral to not scare away those that don't have an Android system. Otherwise great!

No Wifi at Your Event? Design a Story for the Web
Understanding remixing, designing, and composing
Brainstorm, sketch and structure a story to create on your mobile smartphone. By brainstorming offline, learners will start thinking about the different ways to create for the Web and get more comfortable with the idea of creating their own content.

**Comment by secretrobotron** [comment]
I think it makes sense to keep Webmaker in there though. There are cues in the activity that point to it, and it's the platform on which we're encouraging people to make stories. The format of the activity really suggests Webmaker anyway.

**Comment by hannahkane** [comment]
OK, soo final changes to add to "Writing the Web" section of /activities/maker-party-2015/:

Create a Webmaker Project
Understanding remixing, designing, and composing
Create original Web content using the Webmaker for Android. Create a scavenger hunt, a scrapbook, a birthday card, or anything else you can imagine!
Link: http://mozilla.github.io/webmaker-curriculum/MobileWeb/create-webmaker-project.html
    
No Wifi at Your Event? Design a Story for the Web
Understanding remixing, designing, and composing
Brainstorm, sketch and structure a story to create with Webmaker. By brainstorming offline, learners will start thinking about the different ways to create for the Web and get more comfortable with the idea of creating their own content.
Link: http://mozilla.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html

We're going to need images for each. @amirad @secretrobotron - any suggestions?

**Comment by hannahkane** [comment]
@sabrinang - can you help by finding images for this?

**Comment by mmmavis** [comment]
Hey @sabrinang let me know if you need help finding photos. We need to push MP related stuff out today so we should unblock this soon.

**Comment by hannahkane** [comment]
@secretrobotron - do you have a screenshot of Webmaker in action? That could make a good thumbnail.

**Comment by secretrobotron** [comment]
There's a pretty good one on beta.webmaker.org and one in the activity. Happy to grab those if needed.

**Comment by sabrinang** [comment]
![img-webmaker-project](https://cloud.githubusercontent.com/assets/2492510/8686882/2d582532-2a3f-11e5-816d-63341db46c5b.png)

Webmaker: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eQTFIZjlQdk1DVzA/view?usp=sharing
Webmaker (retina): https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eNWdkektIWkJMMjQ/view?usp=sharing

![img-nowifi-webmaker-project](https://cloud.githubusercontent.com/assets/2492510/8686883/30f71a9a-2a3f-11e5-8dd6-5fc93f9145f7.png)

No Wifi Webmaker Project: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eOG05NVV2bFRXZVU/view?usp=sharing
No Wifi Webmaker Project (retina): https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eTnBpSGo3ZXpMVjQ/view?usp=sharing

**Comment by mmmavis** [comment]
<img width="777" alt="screen shot 2015-07-14 at 3 53 33 pm" src="https://cloud.githubusercontent.com/assets/2896608/8687023/bcfd9b62-2a40-11e5-8e8f-5de523ffa204.png">

Thanks all!
