### ISSUE TITLE
ASAP: Change link to TOS

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1091]
On July 27th, and not before, we should change the "LEGAL" link in the sidebar footer to https://beta.webmaker.org/#/legal

**Comment by hannahkane** [comment]
@toolness @mmmavis - is there a way we can schedule this in advance to happen on July 27th?

**Comment by mmmavis** [comment]
I don't know any way other than manually hitting the button on July 27.  Hopefully @toolness can give us some insights :grin:

**Comment by hannahkane** [comment]
This has been delayed, so removing from the milestone.

**Comment by hannahkane** [comment]
Re-opening because now we're ready to do this. Changing timeline to ASAP.
