### ISSUE TITLE
Few updates to Hive locations for hivelearningnetworks.org

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#1094]
Hi @mmmavis, we have a few updates to the list of Hive cities for the landing and /locations page on hivelearningnetworks.org.

If possible, would love to have this updated by Monday in time for our Program Review next Tuesday am - let me know if that's doable. 

We'll be adding four cities to the list under Hive Learning Communities:
* Manchester
* Waterloo
* Portland
* Vizag

@simonaramkisson will add details in comments below for each city including:
* logo
* mission statement
* links (blog, social media, etc.)
* team leaders (incl headshots and contact info)

Also, we have an update to the cities listed as "Hive Coming Soon." Here is the updated list (these are not linked, just a list of city names):
* Barcelona
* Los Angeles
* Pilani
* Providence

Thanks!

**Comment by simonaramkisson** [comment]
![steveflower](https://cloud.githubusercontent.com/assets/8181590/8701929/a1d8d020-2ae2-11e5-87ed-5e5f0e34f457.jpg)
![damienpayton](https://cloud.githubusercontent.com/assets/8181590/8701932/a4c67e72-2ae2-11e5-8a3e-abed5bccb5fc.JPG

Logo: needs to be created

Mission Statement: Hive Manchester is a learning community inspired by the Hive Learning Network Community. Essentially, a Hive Learning Community is a cluster of organisations and individuals coming together, who have a keen interest in engaging the youth of Manchester, and the Hive’s core principles for connected learning experiences. Together, we put on events, which are outside of the traditional classroom and inside creative spaces across the city, that generate fantastic and exciting learning opportunities for the diverse youth population of Manchester!

links (blog, social media, etc.)
Website: hivemanchester.net

Contact Information:
Steven Flower, co-founder: stevieflow@gmail.com 
Damian Payton, co-founder: damianjpayton@gmail.com

**Comment by simonaramkisson** [comment]
Hive Cascadia (Portland):

Logo: needs to be created

Mission Statement: Hive Cascadia fosters and promotes creative cross-institutional, cross-disciplinary partnerships that support youth participatory learning and leadership.

Social Media:
Twitter: https://twitter.com/hivecascadia

Contact Information:

Jeffrey Sens
Co-Executive Director, Pixel Arts Game Education
jsens@gameeducationpdx.com

Sara Ryan
Teen Services Specialist, Multnomah County Library
sryan@multcolib.org  

Kristin Bayans
Interpretive Media Specialist, Portland Art Museum
kristin.bayans@pam.org

![sararyan](https://cloud.githubusercontent.com/assets/8181590/8702294/039e878a-2ae5-11e5-8a29-456418cf1d97.jpg)
![kristinbayans](https://cloud.githubusercontent.com/assets/8181590/8702293/039da23e-2ae5-11e5-8818-48efc534dd71.jpg)
![jeffrey sens](https://cloud.githubusercontent.com/assets/8181590/8702292/039c6694-2ae5-11e5-80ef-1b1c9997700a.jpg)

**Comment by simonaramkisson** [comment]
Hive Waterloo:

Logo: needs to be created

Mission Statement:  Hive Waterloo is  leading the work to increase access to technological learning, and to shine a spotlight on tech learning opportunities, organisations, and facilities in the region of Waterloo-Kitchener. 

Social Media: http://www.yocwr.ca/about/

Team Leaders:

Stephanie Rozek
Co-Founder
stephanie@yocwr.ca 

Sean Yo
Co-Founder
me@seanyo.ca

![seanyo](https://cloud.githubusercontent.com/assets/8181590/8703918/d9428258-2aed-11e5-8202-2c3c5a383a2f.jpg)
![srozek](https://cloud.githubusercontent.com/assets/8181590/8703919/dc94bc3c-2aed-11e5-85f6-8136cb6934fe.jpg)

**Comment by sabrinang** [comment]
@mmmavis logos you mentioned that are needed can be found here: 
https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efnBpVWxiVkV4bU1OUWp5U3Q0VU5TZjY0RDRfZ0NUWW0zVFpxLWkwYjN2Ym8&usp=sharing

![hive_community_logo_manchester](https://cloud.githubusercontent.com/assets/2492510/8706132/e37eea32-2ae2-11e5-9474-8ce06429715a.png)
![hive_community_logo_portland](https://cloud.githubusercontent.com/assets/2492510/8706133/e399faf2-2ae2-11e5-84c5-6f26ade00cf7.png)
![hive_community_logo_vizag](https://cloud.githubusercontent.com/assets/2492510/8706134/e39c9186-2ae2-11e5-9b0b-201429aa2b2b.png)
![hive_community_logo_waterloo](https://cloud.githubusercontent.com/assets/2492510/8706135/e39ddfa0-2ae2-11e5-82eb-d085def80ccb.png)

**Comment by mmmavis** [comment]
@simonaramkisson (I love your GitHub profile pic :wink: ) Do you have info for Hive Vizag or we are still waiting?

**Comment by mmmavis** [comment]
@simonaramkisson any updates on Hive Vizag info? :grin:

**Comment by hannahkane** [comment]
blocked on final location info

/cc @simonaramkisson

**Comment by hannahkane** [comment]
@ldecoursy - is the Monday deadline still accurate?

**Comment by ldecoursy** [comment]
Given no program review, not imperative this happens today. If @simonaramkisson can provide ETA on Vizag info, we can decide whether to hold for that, or go live with the other changes.

**Comment by simonaramkisson** [comment]
Hi All,

Sorry it took so long, they just submitted information!

Mission Statement: 

Mozilla's Hive Vizag Learning Network is a city-wide knowledge lab dedicated to helping youth find and explore their interests. Make! Hack! Learn!

Social Media: 
Facebook : https://www.facebook.com/HLCvizag 

Team Leaders:
Vikas Burri
Program Director
vikas.burri@gmail.com

![vikasburri](https://cloud.githubusercontent.com/assets/8181590/8809289/c07cf34e-2fb5-11e5-8eda-3da488744c60.jpeg)

**Comment by mmmavis** [comment]
blocked on https://github.com/MozillaFoundation/mofo-devops/issues/123 (I can't access to the server atm)

**Comment by mmmavis** [comment]
@ldecoursy @simonaramkisson Do we want Hive Cascadia (Portland) to show as **Hive Cascadia** or **Hive Portland**?

@sabrinang can you help create Hive Cascadia logo?

**Comment by simonaramkisson** [comment]
Hi All,
Thanks for your patience, I have a call with the team tomorrow morning after their event today. Will provide updates after that call.

Thanks again for all your amazing awesomeness.

**Comment by sabrinang** [comment]
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eOGVlQWhYLW4xTGc/view?usp=sharing
![hive_community_logo_cascadia](https://cloud.githubusercontent.com/assets/2492510/8883462/1e2cdb62-3204-11e5-9e54-08aa5e397952.png)

**Comment by mmmavis** [comment]
@simonaramkisson no worries just let me know :wink:

**Comment by mmmavis** [comment]
This is what currently looks like on my machine. Can make edits if needed :)

![fireshot capture 15 - local hive learning networks locations - http___localhost_8888_locations_](https://cloud.githubusercontent.com/assets/2896608/8884357/040da07a-320b-11e5-9001-b681540ec7ed.png)

**Comment by simonaramkisson** [comment]
Hi All, spoke to team in Portland. They are going to move forward with Hive Cascadia. :)

**Comment by mmmavis** [comment]
DONE! https://hivelearningnetworks.org/locations/ :tada:

**Comment by ldecoursy** [comment]
Looks great! Can we also reflect this updated list of cities on the landing page of hivelearningnetworks.org?

**Comment by mmmavis** [comment]
Oh yea sorry I missed it. Will update the landing page today!

**Comment by mmmavis** [comment]
Done!
