### ISSUE TITLE
Updated visual for MLN 

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#1095]
@sabrinang Wondering if you can help create a visual from this post-it from Whistler: ﻿﻿﻿
![screen shot 2015-07-14 at 4 26 37 pm](https://cloud.githubusercontent.com/assets/4885898/8684212/23eb441a-2a45-11e5-8a15-1fd2874a057f.png) Here is another link: https://flic.kr/p/uWJ1D3

It's an evolved representation of our team's networked ecosystem. Headline "Mozilla Learning Networks," showing three main nodes in service of "universal web literacy" in the center. The three nodes are "networks," as represented by Hives, "groups" as represented by Clubs and "convenings" as represented by MozFest. 

Hoping to add this to our Program Review next Tuesday, so would be included on one of the slides from the beautiful template you made us last week :)

**Comment by hannahkane** [comment]
@ldecoursy - do you want any of the other text to appear in the graphic? If so, could you include it in a comment? It's kind of hard to read!

And just to clarify, you don't want Maker Party to appear on the graphic?

@sabrinang - assigning to you for this heartbeat. Let's talk during stand-up tomorrow if that changes anything else.

**Comment by ldecoursy** [comment]
Think we just want the simple version on the white post-it for now. And let's keep Maker Party off for the time being.

**Comment by davidascher** [comment]
Might be good to check that the visual is effective first.  I have to say I
didn't understand it at all at Whistler. Could be just me!

**Comment by ldecoursy** [comment]
Think it will be helpful to have something other than picture of a post-it to check that moving forward. We should probably specify "Mozilla Learning Networks - Programs" at the top.

**Comment by chrislarry33** [comment]
I agree doesn't have to mimic the visual on post it, just communicate the content. We are very open to different visual communication techniques

**Comment by sabrinang** [comment]
I referenced the [narrative outline doc](https://docs.google.com/document/d/1teATL93SzPNCUNa-fcYmama6gs1iFiHXjKm9V2TzaiM/edit) and [wiki](https://wiki.mozilla.org/Learning/2015) and attempted to visualize the MLN ecosystem and opinions/ideas/feedback here would be great or [redpen](https://redpen.io/bn6afc54720917401d) if you prefer and I'll continue to iterate on a visual.
![mozilla-learning-network-visualization-ideation-small](https://cloud.githubusercontent.com/assets/2492510/8735437/898fd6c4-2bc5-11e5-8172-c864041f1452.png)

**Comment by ldecoursy** [comment]
Thanks @sabrinang! This seems like a good start. Some of the items currently in white text seem compartmentalized when there may be a better way to show interactions across the three main circles. Our program review was rescheduled, so would like to get more of the team's input, which likely won't happen by tomorrow. @hannahkane should we move to next heartbeat?

**Comment by hannahkane** [comment]
blocked on getting further input from team

/cc @ldecoursy

**Comment by hannahkane** [comment]
@ldecoursy - is this still needed? if so, is there a new timeline?

**Comment by ldecoursy** [comment]
Maybe we close it for now. Otherwise might move to end of August.

**Comment by hannahkane** [comment]
K. Closing, but feel free to re-open or re-file as needed.
