### ISSUE TITLE
Design MozFest promo banner for MLN site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1099]
This will take the place of the Maker Party banner after July 31st.

**Comment by hannahkane** [comment]
Suggested copy: MozFest is Mozilla's annual, hands-on festival dedicated to forging the future of the open Web. We are now accepting session proposals. 

Button copy: Submit Your Proposal [link to https://2015.mozillafestival.org/proposals]

[Note: The copy and CTA will likely change after August, so, ideally, the design works regardless of the messaging.]

/cc @thornet @Saallen for edits to suggested copy

**Comment by sabrinang** [comment]
Current promotional space (featuring Maker Party):
<img width="1440" alt="screen shot 2015-07-28 at 5 05 14 pm" src="https://cloud.githubusercontent.com/assets/2492510/8947023/dcfdf51e-354a-11e5-90bf-e8a91f280a04.png">

Mozilla Festival promotional space ideas:

![mozilla-learning-network_promo-banner_mozfest-ideation](https://cloud.githubusercontent.com/assets/2492510/8947060/3c9ecd4a-354b-11e5-85cf-4e4af9aa350b.png)
Redpen here: https://redpen.io/p/yz38ce64d1affe1558

I am leaning towards the light blue option (very similar to maker party) or navy blue options as red clashes quite a bit with our UI.

Any feedback?

**Comment by mmmavis** [comment]
I actually prefer navy > red > light blue as light blue makes that section too integrated and therefore not eye-catching enough as a promo banner.

**Comment by Saallen** [comment]
I definitely think we should change the banner colour as the event and CTA is different. That would be my only preference here- that its a different colour from the  Maker Party Banner. Copy looks good to me- clear action :eyes:

**Comment by hannahkane** [comment]
I'd also vote for navy, for the same reasons @mmmavis and @Saallen mentioned.

**Comment by sabrinang** [comment]
We can use the Mozfest Navy (#093D60) for this proposal CTA and we can also switch to Red (#E12526) for another CTA after August later on if that's preferred too.

Logo and pattern here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efkEyaHhTMTh5TDlaNDhaNEljUnhPM25Ta2VWQy1aQVlkVWFKT19tWWtaNWM&usp=sharing

**Comment by hannahkane** [comment]
As just discussed at stand-up: let's go with red for the Call for Proposals, and we can make use of the other colors for later CTAs.

Will open a separate implementation ticket now.
