### ISSUE TITLE
Update link on Maker Party activities page

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#1101]
Hi - 

The link for the first activity under "Participating on the Web" is going to the wrong activity. I believe it should link to this one instead: https://stephguthrie.makes.org/thimble/ODU3ODAxMjE2/hacking-my-media-with-x-ray-goggles

Thanks!
Lainie

**Comment by hannahkane** [comment]
@mmmavis - could you do this one today?

**Comment by ldecoursy** [comment]
Hold on this please - confirming.

**Comment by ldecoursy** [comment]
Nevermind - let's change please. Thanks!

**Comment by hannahkane** [comment]
assigning to @toolness for east coast speediness

**Comment by mmmavis** [comment]
oops missed the flag sorry :stuck_out_tongue_winking_eye:
