### ISSUE TITLE
Add Google Analytics Tracking for 3 x Homepage CTA Buttons

### ISSUE THREAD

**Issue by adamlofting** [mozilla/teach.webmaker.org#1109]
We'd like to record a Google Analytics event when the Pledge Modal is displayed.

Here's an example of existing GA event tracking: https://github.com/mozilla/teach.webmaker.org/blob/1444a78be36362a1633b91bffdef6b1d239096d7/lib/teach-api.js#L147

Let's use these titles:

```js
ga.event({ category: 'Modal', action: 'Pledge to Teach' });
```

Just let me know if you need any further info to be able to implement this.

**Comment by hannahkane** [comment]
Can we do this on all three homepage modals? Would be useful to have data on all of them. :)

**Comment by adamlofting** [comment]
:+1:

**Comment by mmmavis** [comment]
@hannahkane what are the 3 modals mentioned here?

**Comment by hannahkane** [comment]
Was referring to the Pledge to Teach, Teach an Activity, and Start a Club buttons

**Comment by mmmavis** [comment]
<img width="1088" alt="screen shot 2015-07-20 at 3 39 19 pm" src="https://cloud.githubusercontent.com/assets/2896608/8789226/8aec530c-2ef5-11e5-9647-9ac57a7bfe3e.png">

@adamlofting out of the 3 buttons we want to track, only the first one ("PLEDGE TO TEACH") triggers a modal, the other two link to another page on the Teach site.  Is there a conventional way to track button/anchor clicks?

**Comment by adamlofting** [comment]
We could also record GA events when users click on those buttons by firing equivalent JS code. e.g.

```JS
ga.event({ category: 'Clicked Home CTA', action: 'Teach an Activity' });
```

**Comment by mmmavis** [comment]
@adamlofting this is up on https://teach.mofostaging.net/. Feel free to test it and reopen this ticket if things are not working as expected! :wink:

**Comment by adamlofting** [comment]
This is working great! Thanks. :sunny: :+1:
