### ISSUE TITLE
Add Google Analytics event tracking to outbound links on Activities Page

### ISSUE THREAD

**Issue by adamlofting** [mozilla/teach.webmaker.org#1110]
We'd like to know how many people are clicking on each of the [activities listed here](https://teach.mozilla.org/activities/), but links to external URLs don't get recorded in GA automatically.

In order to do this we need to record the click manually, and then re-direct the user to the target URL.

Our GA tracking is using our `react-ga` library, where I have written the [basic logic for recording an outbound link](https://github.com/adamlofting/react-ga/#gaoutboundlinkargs-hitcallback) with minimal delay in the UX.

But, @toolness [suggested we make this a React Component](https://github.com/adamlofting/react-ga/issues/14) which will then be much easier to implement when there are lots of links to track, as there are on this page. This is an excellent idea, and I think it's the best way to move forward with this bug.

I don't have time to write that component myself, but am happy to review any PRs against the library or to give more people edit writes on `react-ga`. (I need to move it into the `mozilla` github org soon too).

-- 

As always, let me know if I can help with anything.

**Comment by mmmavis** [comment]
@adamlofting I have a PR to react-ga for you: https://github.com/adamlofting/react-ga/pull/19 :smile:

**Comment by mmmavis** [comment]
![screen shot 2015-07-31 at 12 54 55 pm](https://cloud.githubusercontent.com/assets/2896608/9016157/9abe0d52-3783-11e5-8566-14222e77d993.png)

**Comment by mmmavis** [comment]
Accidentally closed this ticket earlier.  This will be close once the PR I just submitted get merged.
