### ISSUE TITLE
Add Google Analytics event tracking to outbound links on navigation

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1112]
The "Community" link currently goes to an external site (Discourse). I'd like to know how many ppl are clicking on it.

See #1110 for relevant pre-requisite.

**Comment by hannahkane** [comment]
@mmmavis - do you have an update on this one?

**Comment by mmmavis** [comment]
Spent my time yesterday fighting with BSD.  Will submit PRs for the two GA tickets and favicon today :+1:
