### ISSUE TITLE
npm error with phantomjs version

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1113]
Travis build on https://github.com/mozilla/teach.webmaker.org/pull/1106 failed due the following error

```bash
npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!

npm ERR! peerinvalid Peer mocha-phantomjs@3.5.4 wants phantomjs@1.9.1 - 1.9.7-15
```
Reason:
[phantomjs](https://www.npmjs.com/package/phantomjs) is now at 1.9.17 which meets [our specification in package.json](https://github.com/mozilla/teach.webmaker.org/blob/v0.0.15/package.json#L55) but phantomjs@1.9.17 doesn't fall within [the range of version mocha-phantomjs takes](https://github.com/nathanboktae/mocha-phantomjs/blob/v3.6.0/package.json#L39).

Fix:
We should probably just match our semvar string fo phantomjs with mocha-phantomjs's for now.  I've created [this ticket](https://github.com/mozilla/teach.webmaker.org/issues/1115) to remind us to update the string once mocha-phantomjs update theirs.

/cc @simonwex

**Comment by simonwex** [comment]
By the way, @mmmavis, nice commit message :cat: :joy_cat: :bomb: :boom:
