### ISSUE TITLE
Host 3 Made With Code pages on teach.mozilla.org

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1119]
When the new Webmaker goes live, lots of pages will 404. Three such pages are:
https://webmaker.org/en-US/madewithcode-meme
https://webmaker.org/en-US/madewithcode-poster
https://webmaker.org/en-US/madewithcode-firstwebpage

Those pages are popular referrals for the site, so we don't want to lose them.

We need to host them on teach.mozilla.org with the following changes:
 * obviously, the header will become the Teach header, rather than the old Webmaker
 * ~~is it possible to remove the rest of the Teach page wrapper (nav and footer)?~~
 * each activity includes this in it's final step: Log in to Webmaker and hit "Save." Please change that to: Log in and hit "Publish."
 * change "Or Webmaker has lots of other free activities too." at bottom of each page to "The Mozilla Learning Network has lots of other free activities as well." and link to /activities

Once they're on Teach, we should update https://github.com/mozilla/webmaker.org/issues/1423 with the urls, so we can re-direct.

Speaking of urls, I'm thinking these pages should live under /activities. 
So /activities/madewithcode-meme, etc.

**Comment by hannahkane** [comment]
@mmmavis - can you take a look at this ticket and let me know if it a) makes sense and b) how much time you think it will take?

**Comment by hannahkane** [comment]
Was being a dork and forgot that Teach doesn't have a header. @ldecoursy - do you have an opinion about whether we could put the MadeWithCode content on a page with the Teach site page wrapper (navigation and footer and Tabzilla)? 

Would that be weird or jarring, or is that okay? Another option is to have NO page wrapper, but I think that's even weirder. No way for people to to rest of Teach site ('cept for editing the url).

**Comment by ldecoursy** [comment]
I think it's fine to have the MLN wrapper. Thanks!

**Comment by mmmavis** [comment]
@hannahkane @ldecoursy 
Do you think if we can take out the "favourite/like" functionality (the green heart in screencap below) to keep things simple? 

![screen shot 2015-07-22 at 3 25 46 pm](https://cloud.githubusercontent.com/assets/2896608/8838976/fb936c26-3085-11e5-9b3f-d4f403c734b9.png)

**Comment by ldecoursy** [comment]
WFM

**Comment by mmmavis** [comment]
Got the "madewithcode-firstwebpage" page built.  See screencaps below (ignore the "DEV VERSION" ribbon at top plz :smile: )

@hannahkane @sabrinang @ldecoursy anything I should tweak? I think we should probably add a header before "Congratulations on your new...".

![fireshot capture 13 - made with code _ - http___localhost_8008_activities_madewithcode-firstwebpage_desktop](https://cloud.githubusercontent.com/assets/2896608/8840830/638fb93c-309b-11e5-97a2-57196fc5fca9.png)

![fireshot capture 14 - made with code _ - http___localhost_8008_activities_madewithcode-firstwebpage_small](https://cloud.githubusercontent.com/assets/2896608/8840832/661a2796-309b-11e5-9731-ad17606b5f68.png)

**Comment by hannahkane** [comment]
I think we can probably just remove those first two sentences, and have the page start with the header "Make your first web page."

**Comment by hannahkane** [comment]
Otherwise, +1 from me! :)

**Comment by ldecoursy** [comment]
+1 thanks @mmmavis

**Comment by mmmavis** [comment]
٩(｡・ω・｡)﻿و
