### ISSUE TITLE
Implement Automated Testing

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.webmaker.org#112]
* [x] Implement testing framework ( #143)
* [X] Pick two open bugs
  *  Bug: #138 (tests added in 54b8ce0da26b1d8b281004988ae7e9e61d1a9750)
  *  Bug: #166 (tests added in #167)
* [x] implement tests that validate fixes for two open bugs
* [x] Document how to add a new test
* [x] Set up project on TravisCI
* [x] Add Travis status Image to README
* [x] Add mofo-style linter (#142)
* [x] Ensure all tests are passing

https://github.com/MozillaFoundation/plan/issues/351

**Comment by toolness** [comment]
So one big advantage of having a static site generator is that the build phase kind of doubles as a testing phase.

I've just added some functionality for #117 that raises errors during `npm test` if any React warnings are raised. This includes:

* warnings that come with React core, such as forgetting to put a `key` attribute on components in an array;
* warnings raised by [prop validation](http://facebook.github.io/react/docs/reusable-components.html#prop-validation);
* anything logged in our own code via `console.warn()` during component initialization or rendering, like f28ef4624c1df17b946f0d941cb7352a2a8a2d24.

So I highly recommend we use these sorts of features to make sure our code is up-to-snuff at build/test time!

**Comment by toolness** [comment]
That said, dynamic functionality, such as event handlers, isn't exercised at all during the build step, so writing tests for those would be super useful. <code>[Reacts.addons.TestUtils](http://facebook.github.io/react/docs/test-utils.html)</code> could come in handy here, and this blog post might too:

http://www.jackcallister.com/2014/12/01/building-a-test-suite-in-react-js.html

Currently our code doesn't actually include much dynamic event-handling yet. Two things that would be great to test are the collapsible hamburger code and the `pushState` support.

If we can't effectively test these things in an automated way, it might be worth writing up instructions for manually testing them.

**Comment by toolness** [comment]
It seems like there exist modules like `react-a11y` (see #126) that we can add to our build-time testing, which effectively serve as "linters" for our React code. Cool!

**Comment by toolness** [comment]
Woot, this is done!
