### ISSUE TITLE
Update Teach Like Mozilla page with new content

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1120]
Content list is here and is a WIP: https://teach.etherpad.mozilla.org/tlmcontent

/cc @chrislarry33 @ldecoursy @thornet @acabunoc @kaythaney

**Comment by thornet** [comment]
Thanks, @hannahkane! Added some edits in the etherpad, in case this ticket is still live.

**Comment by hannahkane** [comment]
Thanks, @thornet.

The design team did some wireframing work on this. I'm going to close this ticket because it feels premature now. Will open a ticket for finalizing the design and we can continue the discussion there.
