### ISSUE TITLE
Figure out where Maker Party content lives after MP is over

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1121]
Update based on July 27 meeting between @amirad @ldecoursy and @hannahkane
 - [ ] Remove MP banners on teach.mozilla.org and webmaker.org on August 4 (https://github.com/MozillaFoundation/plan/issues/509)
 - [ ] Updates to /events (https://github.com/mozilla/teach.webmaker.org/issues/1135)
  - Remove "Join the global celebration" text and sign-up form in hero image
  - Change order of content on the page: 1) intro paragraph and logo, 2) "Get the 2015 activities" banner, 3) "What does a MP look like" paragraph 4) Flickr feed and link to all photos 5) case studies 6) video
 - [ ] Will not remove MP from navigation at this point

**Comment by hannahkane** [comment]
We don't actually need to have this all figured out by the end of this milestone, but we do need to confirm what needs to happen on or about August 1, if anything.

/cc @amirad @chrislarry33 @ldecoursy @thornet

**Comment by amirad** [comment]
•Date to remove MP banners on teach.mozilla.org and webmaker.org (August 1?) --> August 1st is a Saturday, the 3rd is a holiday in Canada so let's set a date for August 4th?

•Whether we need a "post-MP" state for /events that celebrates the success of this year's MP, and if so...
Usually we share our infographic but we have no data to share this year and on the /events page we don't tie anything to the date of MP. We have a lot of community members running their events from aug-oct so I'm inclined to just leave it as is. 

•Whether/when to remove Maker Party link from navigation
Let's keep it! As mentioned the community is still running MP events throughout the year so we don't want it to just disappear on them. 

•Whether/when to retire content on /events, or re-package in some way
Do we have resources/people to give this page a refresh? I don't think it's super critical, other than changing the sub-heading up top that reads "Join the global celebration from July 15-31"

•From where to link to /events/resources. Could be from /teach-like-mozilla.
Why can't we keep it under the Maker Party/events section still?

**Comment by amirad** [comment]
@hannahkane sorry answers up top!

**Comment by ldecoursy** [comment]
My thoughts in bullets below. Thinking it might be worthwhile to set up a call to - I'll send an invite. 

•Date to remove MP banners on teach.mozilla.org and webmaker.org (August 1?) --> August 1st is a Saturday, the 3rd is a holiday in Canada so let's set a date for August 4th?
* This seems fine to me, but then should we change the copy on the MP page (just remove the dates) from July 31-Aug 4 so it doesn't seem old?

•Whether we need a "post-MP" state for /events that celebrates the success of this year's MP, and if so...
Usually we share our infographic but we have no data to share this year and on the /events page we don't tie anything to the date of MP. We have a lot of community members running their events from aug-oct so I'm inclined to just leave it as is.
* While we won't have an infographic, it might still make sense to update the copy and highlight some of this year's events. Maybe we don't have the "Join the Global Movement" section, but rather introduce MP as a way for people to activate people in their community around making and learning more broadly. @amirad do we have a handful of great events we can point to or highlight from this year? Also we should probably remove the specific MP signup link. 

•Whether/when to remove Maker Party link from navigation
Let's keep it! As mentioned the community is still running MP events throughout the year so we don't want it to just disappear on them.
* I think given the amount of traffic it's getting we should leave it, but maybe we move things around so the activities are featured at the top, with highlights from some of this year's events.

•Whether/when to retire content on /events, or re-package in some way
Do we have resources/people to give this page a refresh? I don't think it's super critical, other than changing the sub-heading up top that reads "Join the global celebration from July 15-31"

•From where to link to /events/resources. Could be from /teach-like-mozilla.
Why can't we keep it under the Maker Party/events section still?

**Comment by jgmac1106** [comment]
This may be way left field but could the same code you use for the club map
be used for post-maker party stuff. You could highlight all the events on
the map and then there could be links and descriptions to some of the "big
events"  you want to highlight.

**Comment by hannahkane** [comment]
Will we be continuing to drive traffic to this page post-MP?

**Comment by ldecoursy** [comment]
The final Maker Party email is slated to go out Aug 3, although wonder if we push that to Aug. 4 given CA holiday.

**Comment by amirad** [comment]
+1 to moving it to Aug 4th
I am going to start organizing some top stories, images and links for us to use. Will share out when I've got things in a good place to start using them.

**Comment by amirad** [comment]
MP 2015 stories and pictures! https://teach.etherpad.mozilla.org/MP2015stories

**Comment by hannahkane** [comment]
Updated ticket description to reflect latest decision-making

**Comment by hannahkane** [comment]
Actually, I think we can close this ticket now, since all follow-up tasks are ticketed separately.
