### ISSUE TITLE
Host Private Eye activity on teach.mozilla.org

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1125]
The page is currently here: https://webmaker.org/en-US/private-eye 

It can go in the Teach page wrapper.

Please remove the CTA section at the bottom ("Privacy Matters. Learn more..."), as well as the footer

Not sure if this fits better in /activities or as a fourth link on /tools. @ldecoursy - thoughts on that?

**Comment by mmmavis** [comment]
I vote for putting it under `/activities` since Lightbeam is never a Webmaker branded tool.

**Comment by hannahkane** [comment]
+1
