### ISSUE TITLE
Staff admin additions for teach.mozilla.org

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#1127]
Hi - can you please add @amirad @Saallen and @soapdog as admin? Will be helpful for viewing, exporting, approving, denying Clubs that have been submitted. Thanks!

cc @thornet

**Comment by hannahkane** [comment]
@mmmavis - are you able to do this?

**Comment by mmmavis** [comment]
Nope sorry I don't.  I'm afraid I don't have admin access to Teach API.

/cc @simonwex

**Comment by hannahkane** [comment]
@simonwex - is this something you can give @mmmavis (and me?) access to, so we don't have to ask you every time?

**Comment by thornet** [comment]
+ also @simonaramkisson to be a staff admin. Thanks!

**Comment by hannahkane** [comment]
@simonwex - can you help us out with access to the Teach API? There are a few tickets in this milestone with the "need Teach API access" label that are currently blocked.

**Comment by hannahkane** [comment]
no longer blocked!

**Comment by hannahkane** [comment]
Done.

**Comment by amirad** [comment]
Thanks everyone! I just logged in and I get to a blank screen that says "You don't have permission to edit anything." - that doesn't feel right? @hannahkane

**Comment by mmmavis** [comment]
hey @amirad can you try again and let me know if it works now?

**Comment by amirad** [comment]
Yes! It works now. Thank you @mmmavis :)
