### ISSUE TITLE
Unable to push to staging server

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1129]
We set up Travis so that every time things get merged into `develop` branch it will also trigger a build to [`staging`](https://teach.mofostaging.net/). However, something happened last week and now staging is many commits behind `develop`.

Comparing the [commit history](https://github.com/mozilla/teach.webmaker.org/commits/develop) and [the latest commit](https://github.com/mozilla/teach.webmaker.org/commit/b9b93eb3a02d20660dfaae45c6e2ae490706b239) on staging site (you can find it via the DEV ribbon on the site) looks like things after "Release v0.0.15." have gone to nowhere :sob: .  I checked [Travis build history](https://travis-ci.org/mozilla/teach.webmaker.org/builds) but couldn't find anything suspicious.  @simonwex can you help?

**Comment by simonwex** [comment]
The problem is that the keys stuffed in the .travis.yml file were disabled. 

I created the user: 
deploy-teach.mozilla.org. 

I attached two inline policies:
S3-teach-mozilla-org-s3bucket-1oinic8tfxxim-RW
and
S3-teach.mofostaging.net-RW

It's still getting a 403 when the build task tries to upload. @jbuck I sent you an email, but let's continue the discussion here. Any ideas?

**Comment by simonwex** [comment]
Fixed and deployed to staging.

**Comment by mmmavis** [comment]
lovelyyy! thanks so much @simonwex :tada:

**Comment by hannahkane** [comment]
win!

**Comment by mmmavis** [comment]
@simonwex 
it's been ~2 hours since I pushed to PROD but the changes aren't live yet. any idea why?

**Comment by jbuck** [comment]
@mmmavis prod deploy isn't working: https://travis-ci.org/mozilla/teach.webmaker.org/builds/72888817

**Comment by simonwex** [comment]
Hey @jbuck it's likely also an issue with ACL perms. Mind fixing it up for the prod bucket, too?

**Comment by jbuck** [comment]
So, this is because the changes to .travis.yml didn't land on master... and I don't understand why: https://github.com/mozilla/teach.webmaker.org/compare/v0.0.15...v0.0.16

**Comment by simonwex** [comment]
I also applied the ACL to the prod bucket.
