### ISSUE TITLE
Sidebar menu items need icons

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.webmaker.org#113]
_From @toolness on February 26, 2015 0:18_

_Copied from original issue: toolness/mozilla-learning-html#1_

**Comment by alicoding** [comment]
I don't know what milestone this would be, but assigning this to @cassiemc since I saw that in the demo :)

**Comment by cassiemc** [comment]
Hey @alicoding, I believe Simon means these: 

![teach-nav icons](https://cloud.githubusercontent.com/assets/1186326/6556331/1b8e449a-c643-11e4-8d93-4f7ae42a7a77.png)

SVG icons are here: https://www.dropbox.com/sh/2a26zh8dtx1l54a/AAAvp9DFqvtNNLFvpTO4cDlSa?dl=0 These are in black, if you need them in white, those are here: https://www.dropbox.com/sh/8etd31vn8b6zvmd/AABOIJXBk8Gg51jyYwtBH0fZa?dl=0

One tricky thing might be the different colors the icons will have in the sidebar depending on the page. So maybe you could just make the white ones slightly transparent? Not sure that you can adjust the colour of svg images in css? If you CAN, then for the homepage icons should be #e48598 and for teaching activities, icons should be #6dc1e3

@alicoding I'm going to pass this one back to you. Let me (or @vazquez) know if you need any help!

**Comment by vazquez** [comment]
@alicoding I believe we could change the `fill` attribute of the SVG based on the class of the navigation

**Comment by toolness** [comment]
Hmm, I guess I might recommend just changing the opacity of the SVGs here--an unfortunate thing about including SVGs as `<img>` or `background-url` is that they don't inherit the CSS of their parent document, so changing their fill will be difficult unless we inline them into our HTML...

**Comment by vazquez** [comment]
That's what I'm finding out right as we speak lol. I'll change opacity.

**Comment by toolness** [comment]
Hooray for SVGs!
