### ISSUE TITLE
AUGUST 4: Post-MP updates to /events

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1135]
- [ ] Remove "Join the global celebration" text and sign-up form in hero image (updates: and remove the signup form at bottom of the page)
 - [ ] Change order of content on the page: 1) intro paragraph and logo, 2) "Get the 2015 activities" banner, 3) "What does a MP look like" paragraph 4) Flickr feed and link to all photos (https://www.flickr.com/photos/mozilladrumbeat/sets/72157654235131834) 5) case studies 6) video

**Comment by hannahkane** [comment]
@amirad to provide a new Flickr feed to point to

**Comment by hannahkane** [comment]
Flickr feed is here: https://www.flickr.com/photos/mozilladrumbeat/sets/72157654235131834

**Comment by thornet** [comment]
Just a quick ping on this one: is the a4962c8 fix listed here capturing the /events edits or are there still a few things outstanding? Is there a way we could help get any remainder items through?

**Comment by hannahkane** [comment]
@thornet - might make sense to file a ticket with the specific ask. will let @mmmavis decide the best way to get it into the next release (assuming it's a minor change)

**Comment by mmmavis** [comment]
@thornet we were having deployment problem in the past 2 weeks and we weren't able to push things to production. The problem got fixed this morning and once @hannahkane says okay on https://github.com/mozilla/teach.webmaker.org/pull/1162 we should be able to see changes live.

**Comment by mmmavis** [comment]
updates: some git drama happened. the new release will likely be out tomorrow instead of today.  sorry about that.
