### ISSUE TITLE
Change text of email user receives after applying to add their club

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1136]
Revised text:

%(username)s,
Thanks for your interest in teaching the web!

Get started right away by guiding a group of learners through these featured activities: https://teach.mozilla.org/activities/

We believe in the power of peer learning. That's why we match each Mozilla Club Captain with a volunteer Regional Coordinator who can support you in getting started and making the most of this program.

Please note: Our first cohort of Regional Coordinators is in full swing right now, so you've been added to our waiting list. We'll match you with a Regional Coordinator as soon as we can. Your club will not show up on the map until you've been matched up.

To begin on your own, check out these resources to organize and teach your learners: http://mozilla.github.io/learning-networks/clubs/#resources

Please also say hello in our discussion forum (http://discourse.webmaker.org/category/clubs) or tweet using hashtag #teachtheweb if you need any help.

Let's teach the web!

Michelle Thorne
on behalf of the Mozilla Learning Network

**Comment by hannahkane** [comment]
@mmmavis - are you able to do this one?

**Comment by mmmavis** [comment]
I can make a PR for [ changes to`email.py` on the teach-api repo](https://github.com/mozilla/teach-api/blob/8ed32b2477b24ef918f68eb8374ae5f6416a0d4d/clubs/email.py) but I don't know how the deploy process is like for that service.  @simonwex do you know?

another teach-api related ticket: https://github.com/mozilla/teach.webmaker.org/issues/1127

**Comment by hannahkane** [comment]
No longer blocked. win!

**Comment by thornet** [comment]
Fantastic! Do we know when this new email will go live?

**Comment by hannahkane** [comment]
Sorry, I should have clarified. This is no longer technically blocked. Still don't have staff to assign to it. :(

**Comment by hannahkane** [comment]
@mmmavis - do you know if you'll be able to do this this week?

**Comment by mmmavis** [comment]
sorry for the wait.  i'm hoping to get this out in the next few hours.

**Comment by mmmavis** [comment]
<img width="961" alt="screen shot 2015-08-18 at 12 14 04 pm" src="https://cloud.githubusercontent.com/assets/2896608/9340089/b3bf78e0-45a2-11e5-9982-0ea5d5f8e897.png">

Fix is in! :+1: and I finally made my first push to teach-api yay!
