### ISSUE TITLE
AUGUST 4: Update homepage banner with MozFest banner

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1139]
We'll use Red (#E12526) for the first CTA.

Logo and pattern here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efkEyaHhTMTh5TDlaNDhaNEljUnhPM25Ta2VWQy1aQVlkVWFKT19tWWtaNWM&usp=sharing

**Comment by hannahkane** [comment]
(For reference, design ticket is #1099)

**Comment by thornet** [comment]
Awesome!
