### ISSUE TITLE
Add language selector

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.webmaker.org#114]
_From @toolness on February 26, 2015 0:18_

At the top-right of the hero unit.

_Copied from original issue: toolness/mozilla-learning-html#2_

**Comment by hannahkane** [comment]
Not a requirement for v1. Going to test the site in EN before we start localising.

**Comment by alicoding** [comment]
I'm just going to unassigned myself until we get to localization for teach site.

**Comment by hannahkane** [comment]
Closing this. It's not a requirement yet. Will open new tickets related to l10n when we're ready.
