### ISSUE TITLE
Implement design/copy changes on /Clubs

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1142]
Design work is being finalized in #858

**Comment by mmmavis** [comment]
@hannahkane @sabrinang mind giving me a ping when the design work has been finalized? Thanksssss :+1: :see_no_evil:

**Comment by hannahkane** [comment]
This is ready to go. https://redpen.io/egd04381c2b4f26f22

@sabrinang - can you please add assets to this ticket.

For now, the "If you'd like to get started on your own, check out these resources" sentence near the bottom should link to: http://mozilla.github.io/learning-networks/clubs/

**Comment by mmmavis** [comment]
@hannahkane @sabrinang don't forget to attach the mockup for the "see the full list" page as well :wink:

**Comment by hannahkane** [comment]
Oh, these are the links for the "What does a Mozilla Club..." section:
* Afterschool program: https://docs.google.com/document/d/1rUivWQybJymNlfZZHWkSJqFN5TNDVuPRSH_YCObALeM
 * Community Meet-Up: https://docs.google.com/document/d/1gzbC5Q_XeHeii66v_Z4py6QrqYin5j1ozNhdeKJ-Ssg
 * Neighborhood with low connectivity: https://docs.google.com/a/mozilla.com/document/d/18DwRtmttN_EUlp1PUsQJWrDgUwMpCf5ipKG-TGfN1Rc/
 * Existing program: https://docs.google.com/document/d/1WbEEuomaH3eHd--vn_mBBBdAMuS8s9_WxJ4zm-N-UQI

**Comment by hannahkane** [comment]
@mmmavis @sabrinang - good call, Mavis, on the "See the full list" page. My suggestion for that would be:
 * Same header as /Clubs, including the button
 * Replicate the "Where in the world..." section header from the /clubs page
 * Map
 * Full list (can use same styles as on the current /clubs page)
 * nothing below the list besides the site footer

**Comment by mmmavis** [comment]
I'm having hard time coming up with a url for that new page. `https://teach.mozilla.org//clubs/full-list` ?

**Comment by hannahkane** [comment]
what about just /clubs/list?

**Comment by sabrinang** [comment]
redpen mockup of clubs list: https://redpen.io/qd0672bdaec511d12f

**Comment by hannahkane** [comment]
+1 WFM

**Comment by sabrinang** [comment]
![clubs-page-intro-photo](https://cloud.githubusercontent.com/assets/2492510/9286281/f9523b32-42a4-11e5-893b-cceeb1da3dd8.png)

original: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eMmZ6QV8zQmZyaVk/view?usp=sharing
retina: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eVWEzWEJZNUlPM0E/view?usp=sharing

clubs page .sketch file: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eU3o3UTl0NUNpMjA/view?usp=sharing

**Comment by mmmavis** [comment]
> what about just /clubs/list?

+1 :+1:

**Comment by hannahkane** [comment]
@mmmavis - do you think this will land this heartbeat, or should we roll it into the next?

**Comment by mmmavis** [comment]
Hey @hannahkane,

I'm afraid not - this ticket actual needs a few days to build since it has lots of logic lying behind it. PR will be ready for review once I finish writing unit tests (will happen today).  Then I'll pass it to @Pomax to review. :+1:

**Comment by hannahkane** [comment]
That's fine. Will move to next heartbeat to finish!

**Comment by mmmavis** [comment]
<img width="686" alt="screen shot 2015-08-28 at 10 56 57 am" src="https://cloud.githubusercontent.com/assets/2896608/9553389/8c679ab0-4d73-11e5-8ab8-a1e48a0a7fe1.png">
 
@sabrinang @hannahkane mind providing urls to the above links?

**Comment by hannahkane** [comment]
projects we care about: don't know; I don't think that should be linked
Mozilla Club Captain: doesn't need to link
curriculum: /activities
Web Literacy: /teach-like-mozilla/web-literacy/

**Comment by mmmavis** [comment]
Code was merged into `develop` as part of [PR#1198](https://github.com/mozilla/teach.webmaker.org/pull/1198)
