### ISSUE TITLE
Revise About page copy to better reflect Leadership Development focus

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1146]
The current About page copy is good, but could be reframed to better emphasize our leadership development focus.

We might also want to add a comprehensive list of our programmatic offerings to this page.

Could also set a new page title for all pages on the Teach site. This title could reference leadership dev.

**Comment by hannahkane** [comment]
@ldecoursy - okay if I assign to you? Feel free to remove the milestone if it doesn't feel reasonable to tackle in the next heartbeat.

**Comment by ldecoursy** [comment]
Yes! :)

**Comment by hannahkane** [comment]
Moving this to current heartbeat, so it doesn't get lost.

**Comment by ldecoursy** [comment]
Here's some interim language (draft) for the About page. I'm pulling from an exercise our team did a few weeks ago. I imagine we'll iterate on this more as we hone and align our offerings as part of the Leadership Development working group.

**About the Mozilla Learning Network**
We're cultivating a global network of web literacy leaders who are teaching others the most important skills of our age: the ability to read, write and participate in the digital world. Our programs and resources can help you make an impact in your community, and build your citizenship in an openly networked world. 
* Learn and deepen your own 21st Century digital skills, and get better at teaching them to others
* Contribute to real-world products and projects that are open, participatory and networked
* Access free resources like event planning guides and step-by-step teaching activities, or share your own to receive feedback from peers
* Develop your skills in facilitative leadership, participatory practices and collaboration

Feedback from @chrislarry33 @KevZawacki?

**Comment by KevZawacki** [comment]
Looks great! +1

**Comment by hannahkane** [comment]
@chrislarry33 - what do you think? Wondering if we can close this ticket, and file a separate for implementation.

**Comment by anmechung** [comment]
Recommendations for some tweaks - feel free to ignore!

Is it cultivating a global network of web literacy leaders who are "learning" and teaching ...?
What does "build your citizenship" mean? Do you mean "participate" in an openly reworked world?
First bullet: Could "own" be deleted?
3rd bullet: how about this: access free resources like event planning guides, adapt step-by-step teaching activities, or share your own resources to receive feedback from peers (trying to convey idea that people can iterate in activities)
4th bullet: leadership - is it clear that the leadership is specific to teaching web literacy skills?

**Comment by chrislarry33** [comment]
@hannahkane I tweaked a bit as per @anmechung feedback. The below is good. Yes let's do as you suggest and close this ticket and start one for implementation. 


About the Mozilla Learning Network

We are cultivating a global network of web literacy leaders who are teaching and learning most important skills of our age: the ability to read, write and participate in the digital world. Our programs and resources can help you make an impact in your community, and participate in an openly networked world.

   -  Learn and deepen your 21st Century digital skills, and get better at teaching them to others
    - Contribute to real-world products and projects that are open, participatory and networked
    - Access free resources like event planning guides and step-by-step teaching activities, or share your own resources to receive feedback from peers
    Develop your skills in facilitative leadership, participatory practices and collaboration
