### ISSUE TITLE
Add search box

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.webmaker.org#115]
_From @toolness on February 26, 2015 0:18_

At the top-right of the hero unit.

_Copied from original issue: toolness/mozilla-learning-html#3_

**Comment by alicoding** [comment]
@toolness want to assign this to anyone specifically? or we still want to wait for search page to be finalized first before doing this one?

**Comment by hannahkane** [comment]
This is not a requirement for v1. Search will become more important as we go, but at launch...there's not much to search for. :)

**Comment by hannahkane** [comment]
Closing this. It's not a requirement.
