### ISSUE TITLE
Update to Hive Waterloo on Locations page on hivelearningnetworks.org 

### ISSUE THREAD

**Issue by simonaramkisson** [mozilla/teach.webmaker.org#1157]
Hi @mmmavis,

We need to make a few updates to Hive Waterloo on the locations page on hivelearningnetworks.org, in the :

• In the mission statement, can we remove Waterloo-Kitchener to "Waterloo Region" at the end of the sentence. 
• Replace www.yocwr.ca to www.hivewaterloo.ca
• Include twitter handles for both Stephanie and Sean: @srozek @seanyo and remove their email addresses. They are currently working on getting hivetoronto.com email addresses.

Let me know if this makes sense. 

Thanks so much!

**Comment by mmmavis** [comment]
Done! :smile:

**Comment by simonaramkisson** [comment]
Thanks Mavis, you rock big time!
