### ISSUE TITLE
Design version of homepage with only one CTA in header

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1158]
We want to see if we can increase the conversion rate of pledge-takers to 5% of site visitors.

Experiment #1: Make the pledge the only CTA in the homepage hero

See how it affects Pledge rates, as well as traffic to /activities and /clubs

**Comment by sabrinang** [comment]
redpen idea here: https://redpen.io/oc9b75cf4cbed72a1e
I suggest we keep yellow button for main CTA button and make the promo button more subtle and have some copy to give main CTA some context
![teach_homepage_1cta-edition](https://cloud.githubusercontent.com/assets/2492510/9316004/61cce1d2-44e7-11e5-9763-3989e1ff795b.png)

**Comment by chrislarry33** [comment]
Do we have any documentation of best practice/advice/research/analysis from our two years in small dollar EOY fundraising  they we can apply here?

**Comment by ldecoursy** [comment]
@valianttry Is this something you have/can share?

**Comment by hannahkane** [comment]
Our plan is to see about installing Optimizely so we can run a variation test, which is something we were able to do for EOY elements last year.

**Comment by hannahkane** [comment]
@ldecoursy - can you help come up with 2-4 copy variations that we could test? Should be very pithy. We could also test button color, but that seems very related to whatever is in the banner space below, so I'd rather focus on testing copy.

**Comment by HPaulJohnson** [comment]
My 2 cents is that this is a great first test to run. Single CTA's almost always outperform. 

Also, if you didn't catch it last week (the button color comment reminded me of it), I'd suggest watching Hiten Shah brantina presentation. He is the founder of Crazy Egg and Kissmetrics and an expert in this type of experimentation. https://air.mozilla.org/august-brantina-with-hiten-shah-founder-kissmetrics-crazy-egg/

**Comment by hannahkane** [comment]
To be clear (because I wasn't before), for this initial test, let's just compare the effect of one CTA versus three CTAs. So, no copy variations needed. We just need a single line of copy to accompany the single CTA version illustrated here: https://redpen.io/oc9b75cf4cbed72a1e

@ldecoursy and @KevZawacki - copy suggestions for the part that currently reads "Copy here about joining us to teach the web today"?

**Comment by KevZawacki** [comment]
Is "web literacy" too technical to have there? Some suggestions:

Join with Mozilla and start teaching the Web today
Make a difference — start teaching web literacy
Help us create a more web literate world

**Comment by chrislarry33** [comment]
i like: Help us create a more web literate world

**Comment by hannahkane** [comment]
Thanks, @KevZawacki!

The "help us" one is my preferred choice as well. 

I'd rather we didn't use the word "Join," because taking the pledge is not actually "joining" the site (in that it doesn't create a user account), so that might be misleading.

And I think "start teaching" sounds like a bigger ask than the pledge actually calls for.

**Comment by ldecoursy** [comment]
+1 to above. Thanks @KevZawacki!

**Comment by sabrinang** [comment]
![teach_homepage_1cta-edition2](https://cloud.githubusercontent.com/assets/2492510/9369174/59a1cf54-467c-11e5-8373-7b6175bbb9af.png)
copy updated redpen: https://redpen.io/be444fcbbc2d7fa0f0

**Comment by hannahkane** [comment]
Perfect. I think we can close this.

**Comment by mmmavis** [comment]
@sabrinang any styling changes I should implement for the hover state of the CTA button?

**Comment by sabrinang** [comment]
@mmmavis the hover state for the yellow CTA button should look as if the button depresses a bit like on https://teach.mozilla.org/clubs/

**Comment by mmmavis** [comment]
:+1: gotcha
