### ISSUE TITLE
Add circular "divot" at bottom of case study divider

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.webmaker.org#116]
_From @toolness on February 26, 2015 0:21_

It's subtle, but a nice touch that the original mockups have:

![divot](https://cloud.githubusercontent.com/assets/124687/6383892/78a64f20-bd23-11e4-9f5e-7854151d60b5.jpg)

_Copied from original issue: toolness/mozilla-learning-html#5_

**Comment by toolness** [comment]
It looks like we are removing the case studies that this divider divides in #184, which renders this issue irrelevant, so I am dujging it.
