### ISSUE TITLE
AUGUST 31: Thimble promotion: homepage banner

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1166]
@sabrinang - can you add assets?

**Comment by sabrinang** [comment]
## Thimble Promotion on Homepage
<img width="920" alt="screen shot 2015-08-17 at 3 21 28 pm" src="https://cloud.githubusercontent.com/assets/2492510/9317927/b0c9ae94-44f3-11e5-823c-351f223fce62.png">

<img width="187" alt="screen shot 2015-08-17 at 3 19 23 pm" src="https://cloud.githubusercontent.com/assets/2492510/9317887/62eb01fa-44f3-11e5-905d-0270a677d289.png">
__Logo lockup:__
original: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eNmVESkhJOURURUE/view?usp=sharing
retina: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eQjBxYVlXTkdSRGM/view?usp=sharing
![teach-promo-bg-grey](https://cloud.githubusercontent.com/assets/2492510/9317734/7047db3a-44f2-11e5-9a12-3d9778914ff3.png)
__Background pattern:__ 
original: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eWFp5cDlPMkFiSGM/view?usp=sharing
retina: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_edG5FaEVLTEl3WVU/view?usp=sharing
__Background colour:__ #279761 (dark green)

__Main copy:__ Try Mozilla Thimble, a more powerful way to teach web literacy. It's designed for educators and classrooms everywhere. Start teaching the Web.
__Button copy:__ Start teaching

_the redpen progress here: https://redpen.io/gp21f69cfd2b152c2f_
_the copy etherpad here: https://etherpad.mozilla.org/thimble-marketing-copy)_

**Comment by mmmavis** [comment]
i'm working on this now

**Comment by mmmavis** [comment]
<img width="606" alt="screen shot 2015-08-31 at 3 28 24 pm" src="https://cloud.githubusercontent.com/assets/2896608/9592069/f65424ec-4ff4-11e5-851b-86c5741be9c6.png">

I'm assuming this is the button styling we want to go with and that button links to https://thimble.mozilla.org/

**Comment by hannahkane** [comment]
+1 on the url.

Defer to @sabrinang on styling.

**Comment by sabrinang** [comment]
@mmmavis ah yes that's right! and the hover state is yellow similar to https://github.com/mozilla/teach.webmaker.org/issues/1189#issuecomment-134415427
