### ISSUE TITLE
Finish assets for Thimble email template

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1168]
- [ ] create the images for Paul to drop in

**Comment by sabrinang** [comment]
I have some email assets to choose from:
Green or white background
Start coding or Learn more button 
Circle or rectangle feature section
<img width="874" alt="screen shot 2015-08-18 at 1 40 35 pm" src="https://cloud.githubusercontent.com/assets/2492510/9342100/c5a39b8e-45ae-11e5-9514-61bce0c70a33.png">

![mozilla-thimble_email_main-graphic-white](https://cloud.githubusercontent.com/assets/2492510/9341532/5f08d5cc-45ab-11e5-94d8-9d57159d720a.jpg)
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ea2NkZjlSZzdMYWs/view?usp=sharing

![mozilla-thimble_email_main-graphic-green](https://cloud.githubusercontent.com/assets/2492510/9341534/5fdd5658-45ab-11e5-826b-089da8eae28d.jpg)
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ed1NuY0hNNHd5eU0/view?usp=sharing

![mozilla-thimble_email_features-graphic-circle](https://cloud.githubusercontent.com/assets/2492510/9341536/613ed9b8-45ab-11e5-8e95-24e5a2c27360.jpg)
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eaG1jNFRiUHpWdlU/view?usp=sharing

![mozilla-thimble_email_features-graphic-rectangle](https://cloud.githubusercontent.com/assets/2492510/9341537/62378c98-45ab-11e5-8081-db17d4cb689a.jpg)
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eTGYyckVUcVdpR2s/view?usp=sharing

![mozilla-thimble_email_cta-learn-more](https://cloud.githubusercontent.com/assets/2492510/9341539/6379d084-45ab-11e5-96cc-ff865c230476.jpg)
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ebE8zWng1ZjJGLVU/view?usp=sharing

![mozilla-thimble_email_cta-start-coding](https://cloud.githubusercontent.com/assets/2492510/9341541/6486624e-45ab-11e5-89cb-cfa208fec8a4.jpg)
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eZ21jc2I3eXJNN3c/view?usp=sharing

**Comment by sabrinang** [comment]
@HPaulJohnson feedback?
@cassiemc design review?

**Comment by mmmavis** [comment]
One note - 
since the container comes with preset padding, the green banner(in option #1) won't be able to extend to 100% width. It will have some whitespace on both ends.

**Comment by HPaulJohnson** [comment]
Looks good.

One thing we found when using the new Webmaker template in BSD was that the headline itself was easiest to do as an image also. Otherwise, maintaining formatting became a nightmare. Can you create an image file for that too?

In terms of preference, I like the all-white as the email copy flows a bit better. 

If/when the template is in BSD I can construct the email to see if there's anything else we need but this should be good to go. 

Nice work, thank you.

**Comment by cassiemc** [comment]
Looks good @sabrinang, just a couple issues to really clean it up.

* I like the white as well but would remove the grey horizon line. Possibly just add a more subtle shadow underneath the computer itself, then centre the Thimble logo vertically with the computer graphic.
* The 'Learn more' button text doesn't read as a particularly strong call to action.
* Is the 'keep calm carry on' really the project we want to feature here?

One trend I've noticed recently (and would love your comment on this @HPaulJohnson and @KevZawacki ) is to make software emails a lot friendlier and more personal by removing any kind of headline or highly designed graphics. They literally read as personal letters to me, which tricks me into opening them. I'm not a fan of it but have noticed it done in several places, so something to test.

**Comment by HPaulJohnson** [comment]
@cassiemc The best thing to do is test. every audience is different. The good thing about a simple, letter format is that it's really easy to put together. 

Letter style emails often do perform well though with anything, mixing things up over time is sometimes the best formula as one format/approach fatigues and another emerges. 

For context, I think most of our emails are generally personal. We took a different approach with the Webmaker launch emails - focusing on visuals and design and stripping personalization - and it's performing as well as any email we've sent this year.  

I'm up for trying it in this campaign. We could use the same template and wrapper, just strip out the graphics and do more personalized copy. 

On your other questions, we are also testing the language in the CTA so we will find out if "learn more" is strong enough. 

For the "Keep Calm" graphic, I like it but I thought we had one that was more project specific that said "Keep Calm and Code On" or something Thimble-related?

**Comment by sabrinang** [comment]
I exported the heading two alternative ways if an image is used for it: 

![mozilla-thimble_email-title](https://cloud.githubusercontent.com/assets/2492510/9449302/90aa3f94-4a56-11e5-83b5-e26e89fe2269.jpg)
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eSm02SWc1TzJZQkU/view?usp=sharing
Using this image heading we can have: "A More Powerful Way to Teach the Web" in text beneath it (a similar format to the Webmaker email)

![mozilla-thimble_email-full-title](https://cloud.githubusercontent.com/assets/2492510/9449306/921031c2-4a56-11e5-91a5-26ae623eed1f.jpg)
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_edjlaejlPV2FRelU/view?usp=sharing
This is the entire heading as an image.

For e-mail, I think it may be best to have it in type if possible (left) in case images are disabled it won't appear.
<img width="766" alt="screen shot 2015-08-24 at 11 50 54 am" src="https://cloud.githubusercontent.com/assets/2492510/9449276/6d1eeed0-4a56-11e5-837f-7779725c7471.png">

However, the webmaker e-mail had both image + text heading and those results can inform if this is the approach to take.
<img width="1168" alt="screen shot 2015-08-24 at 11 48 42 am" src="https://cloud.githubusercontent.com/assets/2492510/9449278/6f63c1b6-4a56-11e5-9d2d-f0e1ec3964d2.png">

Horizontal Thimble Image
![mozilla-thimble_email-callout-horizontal](https://cloud.githubusercontent.com/assets/2492510/9449308/93a75920-4a56-11e5-9bb3-a54c956ae96b.jpg)
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eNHYyNlllSzk3V3c/view?usp=sharing

Vertical Thimble Image
![mozilla-thimble_email-callout-vertical](https://cloud.githubusercontent.com/assets/2492510/9449309/96261a92-4a56-11e5-92eb-9200dd2d99df.jpg)
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eeGtVN0RQaU1KMVU/view?usp=sharing

**Comment by chrislarry33** [comment]
I would like to employ the same plan that the successful Webmaker email used. It is very important to better learn and deploy best practices we have as an organization. Can we do what @HPaulJohnson suggests here?

**Comment by HPaulJohnson** [comment]
@sabrinang and I discussed today and we are going to use an image for the header, like we did with the Webmaker launch emails. I'll be setting those up in the next couple of days and running them through emailonacid to ensure everything looks good. we should be good to go for a send next week!

**Comment by chrislarry33** [comment]
Love it, thanks all!

**Comment by hannahkane** [comment]
@sabrinang - can we close this ticket?

**Comment by HPaulJohnson** [comment]
For reference this is the tracking link we'll be using for email: 

http://thimble.mozilla.org?ref=MLN_ThimbleLaunch&utm_campaign=MLN_ThimbleLaunch&utm_source=newsletter-mofo&utm_medium=email

(NOTE: link not working at the moment; we'll test on Monday when new URL is live.)

**Comment by sabrinang** [comment]
As discussed in issue https://github.com/mozilla/teach.webmaker.org/issues/1160, all assets have been exported here (includes original and 2x versions): https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efkRlbG5yS2hFdmFZbnR3UHN0aUZrc1hqc2g2U0YxU1FTOWR4T3l4ZXVjVEE&usp=sharing
and been used in sample test seen here:
![thimble-email_sample-test](https://cloud.githubusercontent.com/assets/2492510/9586614/b8e33d54-4fd2-11e5-8376-9ca373de65f8.png)
