### ISSUE TITLE
Finish social media assets for Thimble promo

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1169]

**Comment by sabrinang** [comment]
Social share - Generic thimble logo in case it is needed:
![mozilla-foundation_social-assets-thimble_horizontal-logo_twitter-1760x800](https://cloud.githubusercontent.com/assets/2492510/9586036/469a4e52-4fcf-11e5-8086-027b9c0f7f3d.png)
![mozilla-foundation_social-assets-thimble_vertical-logo_fb-tw-200x200](https://cloud.githubusercontent.com/assets/2492510/9586037/46f879be-4fcf-11e5-9774-cc96698872f2.png)

Social share to accompany "The new #MozillaThimble makes hands-on digital learning easy. Start coding in your classroom." post:
![mozilla-thimble_social-assets_hands-on-learning_twitter-1760x800](https://cloud.githubusercontent.com/assets/2492510/9586141/d1c97e80-4fcf-11e5-8a4d-7beb3b30c596.png)
![mozilla-thimble_social-assets_hands-on-learning_fb-tw-800x800](https://cloud.githubusercontent.com/assets/2492510/9586144/d3978a7c-4fcf-11e5-9c43-adef6f56bc9a.png)


Social shares will be uploaded here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efjJ4aGFlbW84UTNOQjN2SFRtSlIxMDlNRWN1eDQybVdGS0VKWkhhQmVELWs&usp=sharing

**Comment by HPaulJohnson** [comment]
Looks great. Thx, @sabrinang

**Comment by sabrinang** [comment]
all sizes: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efjJ4aGFlbW84UTNOQjN2SFRtSlIxMDlNRWN1eDQybVdGS0VKWkhhQmVELWs&usp=sharing

Social share to accompany "Coding, decoded. #MozillaThimble makes teaching code simple: mzl.la/thimble (+ graphic) #TeachTheWeb" post: 
![mozilla-thimble_social-assets_coding-decoded_twitter-1760x800](https://cloud.githubusercontent.com/assets/2492510/9592525/b1383eda-4ff8-11e5-9a73-c56c1d27dc46.png)
![mozilla-thimble_social-assets_coding-decoded_fb-tw-800x800](https://cloud.githubusercontent.com/assets/2492510/9592527/b9026e24-4ff8-11e5-8c91-e7b4fd37fd14.png)

**Comment by sabrinang** [comment]
all sizes: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efjJ4aGFlbW84UTNOQjN2SFRtSlIxMDlNRWN1eDQybVdGS0VKWkhhQmVELWs&usp=sharing

Social share to accompany "Teachers, don't go back to school without your handy code editor. Mozilla Thimble makes learning code simple — try it in your classroom: mzl.la/thimble" or "With #MozillaThimble, teaching code has never been so <i>simple</i>. Try it in your classroom: mzl.la/thimble" post: 
![mozilla-thimble_social-assets_try-in-classroom_twitter-1760x800](https://cloud.githubusercontent.com/assets/2492510/9627176/313d73b0-5117-11e5-9f0a-6dc824d2fab3.png)
![mozilla-thimble_social-assets_try-in-classroom_fb-tw-800x800](https://cloud.githubusercontent.com/assets/2492510/9627180/3796e6e2-5117-11e5-80f7-70b76206a995.png)

**Comment by hannahkane** [comment]
Wondering if we should close this ticket? @KevZawacki - do you need more assets?

**Comment by KevZawacki** [comment]
We have plenty -- OK to close. 
Thanks again for the awesome artwork, @sabrinang!
