### ISSUE TITLE
A/B testing on home page CTA buttons

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1172]
Hey @adamlofting (and @ScottDowne I thought you might know too) :grin: 

We would like to run some tests on the home page and we are wondering if it's possible to do it via Optimizely. On the hero banner on https://teach.mozilla.org/

1. three CTA buttons 
2. one CTA button with a line of copy to provide context

Is it achievable? If so, how should the implementation be done? Do I just commit code that contains **both** Option 1 and 2, and we can toggle things off via Optimizely?

**Comment by adamlofting** [comment]
Hey @mmmavis 

The best way to set this up depends on how big the change is, but I'll explain roughly here.

### Setup Optimizely

Step one is to get the Optimizely tag into the head of the template, like this https://github.com/mozilla/donate.mozilla.org/blob/master/pages/index.jsx#L8

Then setup Optimizely conversion tracking on the goal you are optimizing for. [Donate example here](https://github.com/mozilla/donate.mozilla.org/blob/master/public/js/analytics.js#L121) and [Optimizely Docs](https://help.optimizely.com/hc/en-us/articles/200039925-Custom-event-goals). I suspect this is `number of pledges to teach`

### Setup experiment in Optimizely

You can either:

1. Create multiple variations of the page to test big changes `teach.m.o/`, `teach.m.o/home-simple`, `teach.m.o/etc` and use Optimizely to send a % of visitors to each variation
2. Or if it's a smaller content change (say hiding two of the three existing buttons) just use the Optimizely editor interface to edit the content dynamically at load time. [See video example here](https://learn.optimizely.com/hc/en-us/articles/201847996-Product-Video-Setting-Up-a-Basic-Experiment)

The example you've described could be either:

> three CTA buttons
> one CTA button with a line of copy to provide context

But it depends on how much design work is needed to add the line of copy, which depends a little on how easy it is to work with the existing CSS styles.

My hunch in this case is that we can create that variation via Optimizely without having to commit it to the codebase first.

#### Suggested next steps

- [ ] Get Optimizely tags and conversion tracking onto the site
- [ ] Setup a call and I'll walk through setting up this first test with you and @hannahkane

**Comment by mmmavis** [comment]
assigning this ticket to myself for now so the ticket has an owner

**Comment by hannahkane** [comment]
Thanks, @adamlofting - your calendar looks pretty full. Can you suggest a time after 8am PST some day next week?

**Comment by adamlofting** [comment]
I've sent an invite this morning :smile:

**Comment by adamlofting** [comment]
To follow up, here is how I've added the Optimizely tags to the donate pages, which is also built with React: 

https://github.com/mozilla/donate.mozilla.org/pull/325/files

And here is an example from id.webmaker.org which uses Optimizely with react-router:

https://github.com/mozilla/id.webmaker.org/commit/b34dd06dd7ef75ba399af97105fae78759acd4ff

I'm happy to talk this through further and/or review a PR at any time.

**Comment by mmmavis** [comment]
@adamlofting https://github.com/mozilla/teach.webmaker.org/pull/1201 awaits your review :dancer: 

Once it gets merged and pushed live I'll tackle the rest of the steps.

**Comment by mmmavis** [comment]
Hey @adamlofting 

So my https://github.com/mozilla/teach.webmaker.org/pull/1201 was merged and landed. And

- I created an experiment on Optimizely called `Teach Site Number of CTA Buttons`.
- Added a variation
- Added a custom goal (see screencap below) and made sure the custom event name matched [what I put in the code](https://github.com/mozilla/teach.webmaker.org/pull/1201/files#diff-d06502677d45fab6ff321d04b9d0f54fR282) (ie., `pledgeFormSubmitted`)

<img width="585" alt="screen shot 2015-09-03 at 12 57 47 pm" src="https://cloud.githubusercontent.com/assets/2896608/9669411/d2501724-523b-11e5-8153-5dddec88da83.png">

Did I miss any steps? If not, could you help start the experiment as I don't have permission to do that :wink:

**Comment by adamlofting** [comment]
That's perfect.

I've started the experiment now, and also given you permission to start tests yourself too.

**Comment by mmmavis** [comment]
WOOHOOOO! first A/B testings on the MLN site :dancers: :dancers: :dancers: 

thanks @adamlofting :+1:
