### ISSUE TITLE
Convert logos to SVG (or higher-resolution bitmap)

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.webmaker.org#118]
_From @toolness on February 26, 2015 18:56_

It's not a requirement, but it seems like the logos might be better represented as SVGs, or at least as higher-resolution bitmaps than they currently are, for retina displays and such. The Webmaker, Hive, and Maker Party logos in there were just taken from Cassie's original PSDs.

If we decide against this, we can just close this issue, but I wanted to at least document my concern about it.

_Copied from original issue: toolness/mozilla-learning-html#8_

**Comment by simonwex** [comment]
_From @toolness on February 27, 2015 0:8_

Also, somewhat related is the fact that the mozilla wordmark is the old version of the logo--the one in Cassie's PSD was way too low-res for the page so I just did a Google search for the logo, and all I could find was a high-res version of the old wordmark.

**Comment by alicoding** [comment]
@cassiemc or @vazquez do any of you have the SVG?

**Comment by cassiemc** [comment]
@alicoding The "learning" part of the logo is still being finalized afaik (@hannahkane?), and could be created with live text (we don't have an official logo). Here is the webmaker logomark part though: https://www.dropbox.com/sh/7nwgazjrlbh1x1l/AAAK-yKt6-DgCHQ_Yy2BjiSQa?dl=0 I exported as svg but it seemed like the shadow came out a bit wonky, so am also providing a hi-res jpg which should look okay scaled for retina.

**Comment by hannahkane** [comment]
Yes, hoping to lock down the namespace and logo issues this week. Working with @HPaulJohnson on that.

**Comment by hannahkane** [comment]
Will address the logo/wordmark issue in another ticket. @toolness - are we good to close this ticket, based on the original issue?

**Comment by toolness** [comment]
Hmm, so I think we still need **either** the SVGs **or** a go-ahead from design that our existing assets are "good enough" for the following:

https://github.com/mozilla/teach.webmaker.org/blob/develop/img/maker-party-logo.png

https://github.com/mozilla/teach.webmaker.org/blob/develop/img/hive-logo.png

https://github.com/mozilla/teach.webmaker.org/blob/develop/img/mozilla_wordmark.png

Also, @hannahkane can you link to the "Mozilla Learning" logo/wordmark issue once you make it, just so it's referenced in this issue?

**Comment by iamjessklein** [comment]
I can source the hive logo. @vazquez can you source the mozilla wordmark? 
We are talking about removing the Maker Party from the footer so that's most likely unnecessary at this time.

**Comment by vazquez** [comment]
The Mozilla Wordmark SVG asset is here: https://dl.dropboxusercontent.com/u/43783651/Mozilla/mozilla-wordmark.svg

**Comment by iamjessklein** [comment]
The Hive SVG [asset is on dropbox](https://www.dropbox.com/s/yz6ykagfaxr4va4/Hive_Network_logo.svg?dl=0)
