### ISSUE TITLE
Tweak promo banner button styling

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1189]
button should look more subtle, as seen in https://github.com/mozilla/teach.webmaker.org/issues/1158#issuecomment-132786537

![screen shot 2015-08-24 at 4 18 15 pm](https://cloud.githubusercontent.com/assets/2896608/9455000/c99d0e56-4a7b-11e5-8ea1-96112b95148d.png)

**Comment by mmmavis** [comment]
@sabrinang how should the button look on hover state?

**Comment by sabrinang** [comment]
<img width="889" alt="screen shot 2015-08-24 at 4 41 59 pm" src="https://cloud.githubusercontent.com/assets/2492510/9455338/24c19fce-4a7f-11e5-87d4-4ba133c1cd60.png">
