### ISSUE TITLE
Code review HTML/CSS/LESS

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.webmaker.org#119]
_From @toolness on February 26, 2015 19:3_

I don't consider myself an HTML, CSS, or LESS expert, so I'd appreciate some code review (or I can rubber duck w/ someone). In particular:

* I'm using LESS, but I'm not actually building Bootstrap from LESS; just importing its `variables.less` to reuse some of its variables. Not sure if that is cool or not.
* Not sure how well my CSS rules follow best practices. For instance, I'm using `>` in a number of my rules, which could break as HTML changes--might be better to come up with explicit classes for such things.
* Cassie's original mockups used a 16-column grid, while Bootstrap uses a 12-column grid. My code attempts to resolve this by [nesting columns](http://getbootstrap.com/css/#grid-nesting), which I'm not sure is the best approach.
* I'm using CSS flex layout a *lot* but I'm not sure how smart that is; I guess it depends on what our criteria for browser compatibility is, and how bad the site looks on browsers without flex support. According to [caniuse](http://caniuse.com/#search=flex) it appears IE9 doesn't support flex layout at all, while IE10 only partially supports it. Also not sure about the stock Android browser on older versions of Android.
* I suspect I'm not using the most semantically-relevant HTML tags that I could be using, so that could use some review.
* I doubt my HTML works very well on screen-readers, so I should probably check that. And run the HTML through a validator, perhaps.

_Copied from original issue: toolness/mozilla-learning-html#9_

**Comment by vazquez** [comment]
I can partner up with @toolness on this.

**Comment by gesa** [comment]
I'm also so happy to offer some insight on this!

**Comment by toolness** [comment]
Cool, I just talked to @gesa about this on IRC and I believe she'll be issuing some PRs to refactor/fixup the LESS a bit. @vazquez, would you mind reviewing those once she submits them? (I can provide feedback too but I'm no expert)

**Comment by vazquez** [comment]
I'll be happy to! :)

**Comment by toolness** [comment]
Ok, aki will be doing this as part of her work on #226, so I'm closing this ticket now.
