### ISSUE TITLE
Basic Web Lit Module Hack the News activitiy formatting broken in Safari?

### ISSUE THREAD

**Issue by chadsansing** [mozilla/teach.webmaker.org#1199]
![screen shot 2015-08-26 at 7 24 02 am](https://cloud.githubusercontent.com/assets/4128600/9492219/8bdee3de-4bc3-11e5-957e-8043506c84d4.png)

Looked this way on two computers at home yesterday. Sidebar and header crunched left.

**Comment by Pomax** [comment]
this looks like a flexbox rendering issue - Safari needs the `-webkit-` vendor prefix; might be missing?

**Comment by mmmavis** [comment]
Yup that seems to be the issue.  I'll submit a PR to https://github.com/mozilla/webmaker-curriculum today.

**Comment by mmmavis** [comment]
for reference: this is the page @chadsansing was talking about :smile: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session02-hackthenews.html

**Comment by mmmavis** [comment]
should be fixed by now, yay! :dancers:
