### ISSUE TITLE
Create privacy badges landing page at hivetoronto.org/privacybadges

### ISSUE THREAD

**Issue by OpenMatt** [mozilla/teach.webmaker.org#12]
As per Planning Ticket https://github.com/MozillaFoundation/plan/issues/206
* **In addition to the individual badge pages, we'll also want a landing page that shows off all three badges**. That shows all three badges, with a bit of explanation, linking through to the individual badge pages.

* **After talking with Karen, we decided the best and simplest way to do this would to just update the WordPress page at hivetoronto.org/privacybadges**. A simple WordPress page with some copy (that Karen will write), images and links. 

* **The landing page will be created and maintained using the HiveToronto.org WordPress site**. With a bit of copy explaining what the badges are, providing come context, and images of the badge designs that links out to the badges landing pages on webmaker.org

* @smithisgeneric will write copy and own the page. A designer would be helpful to provide a bit of extra HTML expertise in the wordpress page to get it looking how we want. 

* Here's a sketch that maps out the relationship:
![hivebadgeflow](https://cloud.githubusercontent.com/assets/6931814/6132068/31b87cc0-b11e-11e4-9869-cd5e81bdfeb5.jpg)

**Comment by OpenMatt** [comment]
cc @iamjessklein @cassiemc

**Comment by OpenMatt** [comment]
Here's another version of the same diagram Karen sketched above, in case it helps. 
![landing page flow 001](https://cloud.githubusercontent.com/assets/1007376/6148465/b6abb332-b1cf-11e4-9059-cc9245410b15.jpg)

**Comment by OpenMatt** [comment]
@iamjessklein does this make sense?

**Comment by OpenMatt** [comment]
@smithisgeneric I'd encourage you to start working on this page yourself now, instead of blocking on design. You can start staging the copy, etc. and hacking on the WordPress page yourself. Then work w. Jess to improve and polish it once she's available.

**Comment by iamjessklein** [comment]
yes this makes sense. I am also wondering if this page could be a thimble make (vs. a Wordpress page) - it feels simple enough.

**Comment by davidascher** [comment]
Making an HTML page isn't a blocker for anything.  Design the page that should exist. =)

I'm more worried about the claim code workflow bit.  Will show it to k88hudson who'se sitting right beside me.

**Comment by OpenMatt** [comment]
* @iamjessklein: would rather not use Thimble. What Karen wants is a page that can be easily managed using the HiveToronto WordPress CMS. (There are lots of advantages to that.) Karen can get you set with credentials once the work starts. Minimal design work needed there -- mostly just advice and maybe a bit of HTML guidance from you. 
* @davidascher this is the wrong ticket for that. @ScottDowne is working on the build and claim code here: https://github.com/MozillaFoundation/Mozilla-Learning/issues/11(he's already made some progress)
* the meta-ticket for all this work is here: https://github.com/MozillaFoundation/plan/issues/206 It'll become a P1 next week.

**Comment by smithisgeneric** [comment]
I created a draft landing page on Wordpress. I am still open to considering Thimble if you want to discuss @iamjessklein .  

![landingpage](https://cloud.githubusercontent.com/assets/6931814/6222686/6415befa-b626-11e4-83ae-06972d1ae2c9.png)

**Comment by OpenMatt** [comment]
@smithisgeneric fantastic work! 
* If we create and maintain this in WordPress, it will make it extremely simple for Hive Toronto (and others) to copy and duplicate the page in a range of ways -- without any future production help. 
* over to @iamjessklein to help w. design help

**Comment by hannahkane** [comment]
@cassiemc - will you be taking this part on as well, or just the badge design?

**Comment by iamjessklein** [comment]
@smithisgeneric great work! Where can I access the page you created?

@hannahkane - is a design review the next step?

**Comment by cassiemc** [comment]
@hannahkane For context, @iamjessklein and I were just discussing this and think design review would be adequate here, in which case Jess still has the bandwidth to finish it up this week. I will be finishing up the badge design.

**Comment by smithisgeneric** [comment]
I will message @iamjessklein with the login info

**Comment by iamjessklein** [comment]
@smithisgeneric here is my feedback based on reviewing the draft:

* **Language**:  overall I am confused as to who the audience is for this page. Is it a teacher, an end user, a grant reviewer? For example, the first sentence: "As part of a co-design project with teen peer researchers, Hive Toronto designed privacy badges that include production-centered learning opportunities." If this isn't directed towards the end user I would drop it to the footer with the rest of the information about the project context.

* **Style**: The format of everything here is consistent with the current wordpress theme. The orange on gray has some legibility concerns. I would try adding a white padding to the background - something similar to what the [HiveNYC wordpress site](http://hivenyc.org/resources/for-educators/) does. 

* **Calls to Action**: To add more punch to the CTA's I would consider adding buttons. This is, however, inconsistent with the rest of the theme so I am tempted to suggest that you leave it as is for now.

**Comment by smithisgeneric** [comment]
As Jess noted, the copy for the Hive Toronto page was awkward when trying to speak to both educators and learners.   

- **Language:** redrafted  @iamjessklein @OpenMatt can one of you review?  https://docs.google.com/document/d/1bPJl4ch63JOQwmq2K3CjUdjkfzo3ajZKbzIYNqEdFsI/edit#    
- **Style:** none of the Hive Toronto pages have the white padding so I'd like to leave it like the other pages and move your suggestion re: white padding to a global "to do" for the Hive Toronto site @iamjessklein 
- **Calls to action:** agreed, we don't have any other buttons on pages on HiveToronto @iamjessklein

The copy deck also breaks out the 3 Webmaker landing pages for each badge and I'll comment in the right issue.

**Comment by hannahkane** [comment]
Hey, @smithisgeneric, have the most recent change suggestions been implemented? What's left to do on this one?

**Comment by smithisgeneric** [comment]
I am fine to finish this and will close the issue early next week.  I have the page built behind login on Hive Toronto's wordpress and will update it with the links Scott has provided and as many of Jess's design changes as possible.

**Comment by hannahkane** [comment]
Excellent! I'm going to close the parent issue.

**Comment by hannahkane** [comment]
@smithisgeneric - can we close this ticket?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/2"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/2.
Please don't comment on it here.
