### ISSUE TITLE
Un-postprocess hero unit image

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.webmaker.org#120]
_From @toolness on February 27, 2015 0:59_

The [hero unit image](https://raw.githubusercontent.com/toolness/mozilla-learning-html/gh-pages/img/hero-unit.jpg) currently has the pink triangles at the bottom-right baked into it, and it might also be darkened... if we remove those effects and put them in the client-side, this could make adding new photos and/or using different accent colors easier.

_Copied from original issue: toolness/mozilla-learning-html#10_

**Comment by gesa** [comment]
Where is the PSD/Sketch file for this design? (I kind of did a cursory search and came up with nothing)

**Comment by toolness** [comment]
By the way, this isn't a super-high priority--in some ways it's *better* for us to have the post-processed version, as older browsers that don't support the features needed to post-process it on the front-end won't be left out.

So I'm de-prioritizing this and removing it from v1 and the milestone; we might even close the ticket entirely if we decide that it's definitely best to leave the image post-processed.

**Comment by hannahkane** [comment]
I'mma close this for now. Will re-open if the need emerges.
