### ISSUE TITLE
Update /about with new copy

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1200]
Final approved copy:

About the Mozilla Learning Network

We are cultivating a global network of web literacy leaders who are teaching and learning most important skills of our age: the ability to read, write and participate in the digital world. Our programs and resources can help you make an impact in your community, and participate in an openly networked world.

* Learn and deepen your 21st Century digital skills, and get better at teaching them to others
* Contribute to real-world products and projects that are open, participatory and networked
* Access free resources like event planning guides and step-by-step teaching activities, or share your own resources to receive feedback from peers Develop your skills in facilitative leadership, participatory practices and collaboration

**Comment by hannahkane** [comment]
To discuss at kickoff: Do we need design first, or can we just use the existing styles on that page?

**Comment by mmmavis** [comment]
I think we can just keep this simple by following the existing style.  We can remove the "Our Focus" header if that doesn't fit well with the updated copy.

**Comment by hannahkane** [comment]
+1
