### ISSUE TITLE
Sept 7: Close MozFest Call for Proposals

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1202]
Includes:
 - [x] https://github.com/mozilla/2015.mozillafestival.org/issues/172
 - [x] https://github.com/mozilla/2015.mozillafestival.org/issues/175
 - [x] https://github.com/mozilla/2015.mozillafestival.org/issues/184

**Comment by mmmavis** [comment]
@hannahkane are we just going with [Sarah's suggested copy](https://github.com/mozilla/2015.mozillafestival.org/issues/172#issuecomment-136329486). If so I can push the changes today.

**Comment by hannahkane** [comment]
@Saallen actually wants to keep the call for submissions up for one more week, so we don't have to push today. I just suggested revised copy on the ticket. Will wait for her to respond.

**Comment by hannahkane** [comment]
@mmmavis - assigning this to you, if that's alright

**Comment by hannahkane** [comment]
@mmmavis - would it be possible to do https://github.com/mozilla/2015.mozillafestival.org/issues/173 today, rather than on Monday? (Sorry, I missed that this request was for an earlier date.)

**Comment by hannahkane** [comment]
Actually, will pull out into a separate ticket, to be less confusing.

**Comment by mmmavis** [comment]
PRs submitted, pending review

**Comment by mmmavis** [comment]
@hannahkane plz help verify changes on https://mozillafestival-org-2015.herokuapp.com/ (staging) :+1: :smile:

**Comment by hannahkane** [comment]
homepage + /proposals look good. +1

**Comment by mmmavis** [comment]
all done :dancer:

**Comment by hannahkane** [comment]
Thank you, @mmmavis !!!!
