### ISSUE TITLE
Makes used in the "Made with Code" pages are HTTP 500 now

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1206]
We feature a sample Make in each of our Made with Code pages for people to remix.
- https://teach.mozilla.org/activities/madewithcode-firstwebpage/
- https://teach.mozilla.org/activities/madewithcode-meme/
- https://teach.mozilla.org/activities/madewithcode-poster/

The Makes aren't accessible anymore(HTTP 500 Internal Server Error), e.g., https://thimble.webmaker.org/project/60764/remix.  Should we take down these pages? Or migrate the sample Makes to the new Thimble server?

/cc @hannahkane

**Comment by hannahkane** [comment]
Will fix with https://github.com/mozilla/thimble.webmaker.org/issues/997

So, let's keep for now

**Comment by jbuck** [comment]
Fixed
