### ISSUE TITLE
Implement git-flow style branching standard

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.webmaker.org#121]
Reference this issue for discussion:
https://github.com/MozillaFoundation/MoFo-Engineering-Handbook/issues/47

**Comment by alicoding** [comment]
I was commenting on the wrong repo :S derp me

@gesa @simonwex @mmmavis @toolness 

I'm thinking about having a gulp task to take care of these tasks, and would like some input from you guys.

Run: `gulp prod:patch/minor/major` should do the following:

1. tag 0.0.1 / 0.1.0 / 1.0.0 (depend on the tag)
2. push tag to `master`/`stable` branch from the current head of `developer`
3. push everything in `dist/*` to `gh-pages` so that we can enable github `gh-pages`.

**Comment by toolness** [comment]
Ali, regarding your (3) above, I've just made successful travis builds push out to teach.mofostaging.net in #107... not sure if we want it to be different from gh-pages or not. I need to read up on gif-flow.

**Comment by Pomax** [comment]
a gulp task like this feels incredibly dangerous - it should not be the case that running the wrong gulp task suddenly tags a release and pushes it out for deployment. This is one part of the chain that I'd strongly advocate *has* to stay a manual process, even if that process is "load jenkins, tell it to build"

**Comment by alicoding** [comment]
@toolness I guess the only problem here for pushing to S3 would be the credential. Unless we are going to setup one for Travis as you mention so everytime we push to master/stable then after travis passed all the tests it should push to S3?

**Comment by toolness** [comment]
Yep, that's literally what I just implemented earlier today in cd513f1a6d953486ced1b78223c0837d78f144bf :)

**Comment by toolness** [comment]
Ok, this seems cool. I'm not sure exactly what we need to do to mark this issue as "complete" though--should we tag our first v0.1 or something?

RIght now [teach.mofostaging.net](http://teach.mofostaging.net/) is actually a real-time reflection of the `develop` branch. Until we actually get the real teach.mozilla.org domain, do we want our tagged "production" releases to deploy to teach.mofoprod.net or something?

**Comment by hannahkane** [comment]
@toolness, do we need to move this ticket to the current heartbeat?

**Comment by toolness** [comment]
yes please!

**Comment by hannahkane** [comment]
Is there anything more to do on this ticket?

**Comment by simonwex** [comment]
Looks done to me. We should create a CONTRIBUTING.md, but that's a separate task. #447
