### ISSUE TITLE
Create badge wireframes for users

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.webmaker.org#1218]
Wireframes for badges overview landing page, badge detail page, confirmation email, and approval/denied email. 

Achieved badges will also be on the user profile page #1194 

Exact badges and badge criteria is not set - see #1191 and mozilla/learning-networks#236

Will need to discuss cred.ly with dev.

**Comment by anmechung** [comment]
@kristinashu

**Comment by hannahkane** [comment]
Why was this ticket closed?

**Comment by anmechung** [comment]
oops - accident!

**Comment by anmechung** [comment]
was just reading, and my fingers must have gone astray. :)

**Comment by kristinashu** [comment]
@hannahkane here's a rough starting point for the wireframes https://redpen.io/p/em825f743e11fa2874

**Comment by hannahkane** [comment]
@kristinashu - these look awesome.

want to flag @simonwex to take a look as well: https://redpen.io/p/em825f743e11fa2874. Simon, please let us know if any of the functionality implied seems not-doable with cred.ly, including the idea of a seamless authentication experience.

**Comment by kristinashu** [comment]
@simonwex  here are updated wireframes with @hannahkane feedback applied https://redpen.io/p/cf7e3f8ea85544c703

I've also added some annotations in pink.

**Comment by hannahkane** [comment]
I think we can close this. What do you think, @kristinashu?

**Comment by kristinashu** [comment]
Yup I think so.
