### ISSUE TITLE
Setup mailing list in BSD for the group of contributors we have permission to email

### ISSUE THREAD

**Issue by adamlofting** [mozilla/teach.webmaker.org#122]
This task follows on from:

*  See how many of last year's contributors we have permission to contact #64

**Comment by adamlofting** [comment]
I've setup a constituent group in BSD called `2014_contributors_with_email_optin`.

cc: @amirad @chrislarry33 @ldecoursy @thornet

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/49"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/49.
Please don't comment on it here.
