### ISSUE TITLE
Complete testing and repackaging of Web Lit Basics I

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#123]
Meta ticket:

- [ ] Gather top insights and suggestions from club testers @LauraHilliger 
- [ ] Vote on edits @LauraHilliger @chrislarry33 @thornet
- [ ] Repackage activities with new edits @thornet

**Comment by thornet** [comment]
Don't have the right permissions yet in the new repo to add labels, etc.

**Comment by alicoding** [comment]
@thornet now you can! :D

**Comment by thornet** [comment]
thanks @alicoding!

**Comment by thornet** [comment]
Closing in favor of #100

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/50"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/50.
Please don't comment on it here.
