### ISSUE TITLE
Update sample Thimble activity under "Tools" page

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#1231]
The current sample activity under Thimble on this page https://teach.mozilla.org/tools/ links to a project using the old Thimble.

Can we update it with the Keep Calm project? https://thimble.mozilla.org/anonymous/642982a9-9fa7-43d6-a807-ff3456a8770e/72

**Comment by Pomax** [comment]
this should actually be https://thimble.mozilla.org/projects/72/remix
