### ISSUE TITLE
Import all MozFest session proposals into github repo

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1235]
- [x] https://github.com/mozilla/2015.mozillafestival.org/issues/174

**Comment by hannahkane** [comment]
@mmmavis - we can close this now, right?

**Comment by mmmavis** [comment]
Let's wait for that ticket on MozFest repo gets close first :smile:

**Comment by hannahkane** [comment]
Closing because other ticket was closed!
