### ISSUE TITLE
Create a site map

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#124]
Create a site map for the teach site.

**Comment by iamjessklein** [comment]
The most up to date map can be found on invision [here]
![sitemapv2](https://cloud.githubusercontent.com/assets/535012/6483957/fee1f5fa-c244-11e4-906b-d553b4086f4c.png)
 (http://invis.io/MF2CYHTEK)

**Comment by hannahkane** [comment]
Just confirmed that the "Teaching Materials" page will actually be called "Teaching Activities."

**Comment by iamjessklein** [comment]
Great. adjusted:

![sitemapv3](https://cloud.githubusercontent.com/assets/535012/6491491/7aec1eb0-c27b-11e4-91f6-b8343a7032ca.png)

**Comment by alicoding** [comment]
"teach.webmaker.org/": "Home"
"teach.webmaker.org/clubs": "Clubs"
"teach.webmaker.org/events": "Events"
"teach.webmaker.org/templates": "Teaching Activities"
"teach.webmaker.org/teach-like-mozilla": "Teaching Like Mozilla"
"teach.webmaker.org/about": "About"
"teach.webmaker.org/search": "Search"
"teach.webmaker.org/curriculum": "Clubs curriculum"
"teach.webmaker.org/tips": "Tips for Clubs"
"teach.webmaker.org/literacy": "Web Literacy"

@iamjessklein @hannahkane can you edit this list if this is not right? I'm about to create the urls on the repo

**Comment by hannahkane** [comment]
Thanks, @alicoding. Can we make the url for Teaching Activities "/activities"? Otherwise, these look good to me.

Also, just want to make sure we're not painting ourselves into a corner with the domain. I believe we're still waiting for the final word on whether we're using teach.webmaker.org or teach.mozilla.org or something else. I'm assuming we can make a change later if we need to, but you know what they say about assuming... :)

/cc @HPaulJohnson

**Comment by alicoding** [comment]
@hannahkane can you have another look at this updated version? We are just confused with theses:

"teach.webmaker.org/clubs": "Clubs"
"teach.webmaker.org/clubs/curriculum": "Clubs curriculum"
"teach.webmaker.org/clubs/tips": "Tips for Clubs"

should it `tips` be under `clubs` or should just have it be `/tips`?

**Comment by iamjessklein** [comment]
@alicoding - the tips, curriculum, web literacy are child pages - so they might appear like
* "teach.webmaker.org/teachingactivities/web-literacy" 
* "teach.webmaker.org/clubs/tips"
* "teach.webmaker.org/clubs/clubs-curriculum"

**Comment by hannahkane** [comment]
+1 to the nested versions. 

I don't have a strong opinion about things like "activities" vs. "teachingactivities" or "curriculum" vs. "clubs-curriculum," just as long as we're consistent with hyphen usage. 

Do we have a documented convention anywhere for stuff like that?

**Comment by iamjessklein** [comment]
I am closing this issue as the design work is complete -- yet ongoing :)

**Comment by iamjessklein** [comment]
FYI - I updated the map on [invision](http://invis.io/9G2DK7SR2) to reflect the sitemap for the upcoming release. 
![sitemapv3](https://cloud.githubusercontent.com/assets/535012/6780842/ed3169ae-d13e-11e4-9484-1f216440c94e.png)
