### ISSUE TITLE
Wireframes for badge issuer workflows

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1240]
Wireframes for:
 - [ ]  page to access open badge applications: list of open badge applications with minimal info (applicant's name, badge applied for, application date); include filter by badge action
 - [ ] application detail view: applicant name + link to profile; the evidence submitted; badge criteria; actions ("Approve" "Deny")

**Comment by kristinashu** [comment]
Added to the same redpen https://redpen.io/p/cf7e3f8ea85544c703

**Comment by kristinashu** [comment]
@hannahkane I've updated the outstanding applications page with your feedback https://redpen.io/bd0f1e0430ca48257a
I've just added a list of badge requirements and a custom email comment box.

**Comment by kristinashu** [comment]
@hannahkane I guess we don't need to do this anymore?

**Comment by hannahkane** [comment]
Ah, yeah.
