### ISSUE TITLE
New homepage variation: have popup enabled on first page load

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1244]
Let's try a version where the pop-up appears when the user lands on the page. Is dismissable and doesn't do it more than once within the same session.

Let's do this with the single CTA layout, which seems like it would be a less confusing experience for the user.

/cc @adamlofting

**Comment by hannahkane** [comment]
@mmmavis - putting this in the current heartbeat in case you have time, but it's not more important than the other tickets

**Comment by adamlofting** [comment]
Here's some documentation here on how to trigger custom Javascript in an experiment variation:
* https://help.optimizely.com/hc/en-us/articles/200039835-The-Code-Editor-Edit-Code-and-Variation-Code

For this test I was imagining that on pageload, we use js to trigger an event click on the Pledge button to auto display the form.

I had a quick look at setting this up in Optimizely this morning, so there is an experiment called `Teach Site Auto Display Pledge` you can work on. I ran out of time to get this working, but you can see where it's started.

**Comment by mmmavis** [comment]
@adamlofting thanks for setting this up! I didn't wanna spend much time recalling my jQuery knowledge so I decided to use pure JS to trigger the button click :bowtie: That said, I think we are ready to start testing that variation. Just one question - are we gonna start this as a **new** experiment? or this will be added as an additional variation on the existing "Teach Site Number of CTA Buttons" experiment? I assume the answer is the former.  If so, how are the traffic be split between multiple experiments if we are running them concurrently?

**Comment by mmmavis** [comment]
oops, forgot to add a few lines of JS. Will update this ticket again once I've polished up that variation.

**Comment by mmmavis** [comment]
Done! Here's the code I added, in case you would like to skim through it @adamlofting :smile: 

```js
$(document).ready(function(){
  if ( window.location.href.indexOf("pledge=thanks") == -1 && !sessionStorage.getItem("autoOpenPledgeModal") ) {
    var pledgeCTAButton = document.querySelector(".hero-unit .icon-buttons .icon-button").querySelector(".btn");
    pledgeCTAButton.click();
    sessionStorage.setItem("autoOpenPledgeModal", "true");
  }
});
```

**Comment by adamlofting** [comment]
> I didn't wanna spend much time recalling my jQuery knowledge so I decided to use pure JS to trigger the button click

Even better :smile: 

>  If so, how is the traffic split between multiple experiments if we are running them concurrently?

In this case we should just stop the old test, and start the new one. The old variation wasn't generating significantly different results so it's best to close it.

I've made this change in Optimizely now :+1:

**Comment by mmmavis** [comment]
yay thanks @adamlofting :dancers: 

just checked Optimizely - now I see what you meant by "significantly different result" - conversion is 0 vs 6 now in just 5 hours! :+1:

**Comment by mmmavis** [comment]
im closing this ticket now :smile:

**Comment by hannahkane** [comment]
This variation is doing really well. It has a 13.82% conversion rate. Woohoo! Will test another variation before making a decision about what to use moving forward.

/cc @chrislarry33
