### ISSUE TITLE
Design new homepage variation: put Pledge form directly on homepage

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1245]
Let's try another single CTA version that puts the copy and the form directly onto the homepage

/cc @adamlofting

**Comment by hannahkane** [comment]
@kristinashu - put this in the current heartbeat and assigned to you in case you have time; but this isn't more urgent than the badges work

**Comment by kristinashu** [comment]
@hannahkane I've mocked it up but I'm not really sure it's working https://redpen.io/p/cm2c1c9eb67aa9430e
I think there's too much content for the banner area (and I had to cut out some of the existing copy).

@sabrinang any ideas?

**Comment by hannahkane** [comment]
cc @adamlofting who may also have ideas

Wondering if it would work better to have the copy be "Because the Web is a global public resource that's integral to modern life, I pledge to teach the web", rather than the bullet points?

**Comment by kristinashu** [comment]
Thanks @hannahkane - having less copy helps. 

I've added the updated comp to Redpen https://redpen.io/p/cm2c1c9eb67aa9430e

**Comment by hannahkane** [comment]
Thanks, @kristinashu. I think this looks good. Curious is @sabrinang or @adamlofting has other ideas. If not, I'm game to try this!

/cc @mmmavis

**Comment by sabrinang** [comment]
:+1: yes to less copy in this top area!

Yeah I agree there is a lot of content in the banner area. I'm wondering if we can explore the idea of removing the white box and simplifying the background (currently a photo) to something else so the text is legible? 
![dsc02307](https://cloud.githubusercontent.com/assets/2492510/9891484/69e5646c-5bbb-11e5-85db-40f91754e0e5.png)

However, I am unsure if this is too different (not having the same photo) of a homepage variant for testing purposes

**Comment by adamlofting** [comment]
Those look like two great test variations to me :smiley: 

Also, in the spirit of risk-taking to find bigger possible test wins, I'd encouraging design variations that break out of the existing banner area if that enables more space to guide the viewer to our primary ask.

**Comment by kristinashu** [comment]
Thanks for the ideas!

I've added two more comps to redpen https://redpen.io/p/cm2c1c9eb67aa9430e

I like option .03 but it might need to wait for Thimble's banner to retire.

**Comment by sabrinang** [comment]
I also like the option 3 to use the promo space for the pledge but yeah that space would have to be unoccupied and also really nice to see that photo alternative that allows for more text in that area.

**Comment by hannahkane** [comment]
Happy to try both options (we don't have any specific Thimble goals right now, so we can temporarily retire that in order to run this experiment). If either of these wins, we may eventually have to come up with a new solution for temporary promotion of things like Thimble, MozFest, Maker Party, etc.

**Comment by chrislarry33** [comment]
Love the momentum here every one. I am excited about the testing and getting smarter with site. Really like @hannakane's plan above and agree on having quick and time relevant promotion at the ready and/or using it as part of a test.

**Comment by kristinashu** [comment]
I've made the minor edits and updated Redpen (added checkbox and shortened the email field) https://redpen.io/p/cm2c1c9eb67aa9430e

@adamlofting do you think these are ok to test with? Are there too many variables for testing? Ie. colour background vs photo, shorter text than existing version, different icon...

**Comment by hannahkane** [comment]
thanks, @kristinashu!

also, @adamlofting, is the best practice to stop the existing experiment and start a new one with these new variations compared to the current control?

**Comment by adamlofting** [comment]
> also, @adamlofting, is the best practice to stop the existing experiment and start a new one with these new variations compared to the current control? 

The current test has a clear winner (> 1,000% improvement :stuck_out_tongue_closed_eyes:  ).

So I'd recommended committing that winning variation to the repo, pushing it to production, and stopping the current test. Then treat that as your new control to test as many of these further variants as you like / have capacity to build.

CTA01 and CTA02 are quite similar though, so you could test one of them against the current winner. And if it wins, then test the variation as a smaller tweak-style test.

**Comment by jgmac1106** [comment]
If the current test is the take over at what point does UX beat out
conversion? It happened to me two different times. It was really annoying.
Still those numbers are amazing. Tempting and annoying.

**Comment by hannahkane** [comment]
Added implementation ticket: https://github.com/mozilla/teach.webmaker.org/issues/1273

@jgmac1106 - good point, though you shouldn't have seen the pop-up more than once in a session (let us know if you did). If we do go with the version that's winning now, we might need to store a cookie so as not to repeatedly bombard ppl with the pop-up.

**Comment by kristinashu** [comment]
One more idea, a slightly less intrusive pop-up we could try is when it slides up from the bottom of the browser window and doesn't completely cover the page. We could also time it so it comes up a few seconds after the user has been on the page.

**Comment by jgmac1106** [comment]
Two different sessions probably from different IPs

**Comment by hannahkane** [comment]
@kristinashu - I like that idea. Will file a separate ticket.
