### ISSUE TITLE
Build sitemap.xml

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#125]
A  sitemap is being designed in #124. It would be cool if the site build process generated a [sitemap XML](http://www.sitemaps.org/) so search engines could provide extra helpful results.

For example, I believe it's due to mozilla.org's own sitemap that these rich search results are provided by Google:

![2015-03-04_8-33-31](https://cloud.githubusercontent.com/assets/124687/6484379/65404348-c249-11e4-88dd-bf1909ce3b4c.jpg)

Aside from that, the code could potentially help new developers acquaint themselves with the project, maybe.

**Comment by alicoding** [comment]
note to self: 

```
"teach.webmaker.org/": "Home"
"teach.webmaker.org/clubs": "Clubs"
"teach.webmaker.org/clubs/curriculum": "Clubs curriculum"
"teach.webmaker.org/clubs/tips": "Tips for Clubs"
"teach.webmaker.org/events": "Events"
"teach.webmaker.org/activities": "Teaching Activities"
"teach.webmaker.org/teach-like-mozilla": "Teach Like Mozilla"
"teach.webmaker.org/about": "About"
"teach.webmaker.org/search?q=something that I search for": "Search Result"
"teach.webmaker.org/activities/literacy": "Web Literacy"
```

**Comment by toolness** [comment]
By the way, because of the fact that our site is fully static and intended to be easily deployable on most standard web servers, **every webpage on our site needs to end with a /**, so that the web server will find an `index.html` file.

So, for example, the actual HTML file for the Clubs curriculum will be at `/clubs/curriculum/index.html`, which means that the URL for that page will be `/clubs/curriculum/` (note the slash at the end).
