### ISSUE TITLE
Typo in pledge form

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.webmaker.org#1269]
Just noticed a minor typo on the pledge form. It says 'with' twice "Pledge now, and we'll follow up with with details about how you can teach the web!"

<img width="1414" alt="screenshot 2015-09-16 15 20 10" src="https://cloud.githubusercontent.com/assets/1068783/9920194/d76347c2-5c86-11e5-961c-dd07686277ba.png">

@hannahkane not too sure who to assign this to? @sabrinang maybe?

**Comment by sabrinang** [comment]
@mmmavis can make the update

**Comment by kristinashu** [comment]
Oops, meant to tag @mmmavis not you @sabrinang !

**Comment by mmmavis** [comment]
nice catch :eyes: @kristinashu
