### ISSUE TITLE
Create comms/engagement plan for Clubs/Maker Party roll-out 

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#13]
RACI

Driver: @HPaulJohnson 
Decision-Maker: @chrislarry33 ?
Consulted: @ldecoursy @thornet @amirad @hannahkane Kevin

Develop plan and messaging arcs to cover April-August roll-out of new site, Clubs, Maker Party, MozFest

Initial planning notes here: https://etherpad.mozilla.org/teachbrandingcomms

**Comment by KevZawacki** [comment]
+ @kevzawacki

**Comment by amirad** [comment]
Updated plan from @KevZawacki https://docs.google.com/document/d/1-XY8Q8Hr4tEdNbRxBUmEAK4nk2ZTdL_XWVQPTgT5rOg/edit

@HPaulJohnson can we close and open new tickets for each phase of the roll-out?

**Comment by HPaulJohnson** [comment]
Yes, closing now.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/3"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/3.
Please don't comment on it here.
