### ISSUE TITLE
[MIGRATED] Document all mailing lists Learning Networks team has access to

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#130]
RACI
* Owner: @amirad
* Decision Maker: @amirad @chrislarry33
* Consulted: Kelli, @ldecoursy @simonaramkisson @LucyeoH 

We need to compile a list of all the mailing lists we have full access to, and include how many people are on each as a baseline.

Pull from BSD, Hives, anywhere else?
Also to include list of contributors referenced here: https://github.com/mozilla/teach.webmaker.org/issues/122

**Comment by ldecoursy** [comment]
Tracking here: https://teach.etherpad.mozilla.org/retain4k

@Saallen can you add #'s from MozFest lists?

**Comment by Saallen** [comment]
@ldecoursy added! I added 2013 numbers too but not sure we can still access these emails due to data storage guidelines as set out by @adamlofting  on the mana. Can you confirm @adamlofting

**Comment by adamlofting** [comment]
I made a note in the etherpad. Have we stayed in touch with these people since then? If not, a "random" email two years later will have poor response rates which would have a negative impact on our general mailing stats (deliverability rate etc).

**Comment by Saallen** [comment]
Thanks @adamlofting I would not of had emailed 2013 folks since 2013. But I have pinged the 2014 list already since MozFest.

**Comment by adamlofting** [comment]
I'd also expect there's some overlap in these lists :smile:

**Comment by ldecoursy** [comment]
Agree - let's just add 2014 for now. Thanks @Saallen

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/51"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/51.
Please don't comment on it here.
