### ISSUE TITLE
Design "Helpful Tips" icon for Clubs page

### ISSUE THREAD

**Issue by vazquez** [mozilla/teach.webmaker.org#133]
We already have Curriculum and Connect, we are just missing the Tips icon.

![screenshot 2015-03-04 13 59 29](https://cloud.githubusercontent.com/assets/1119821/6490765/b1acce86-c276-11e4-94d4-58000ebfb9cb.png)

Cassie, could you also send the .svg (or .ai) file for all three icons?

**Comment by cassiemc** [comment]
@vazquez / @hannahkane – what do you think? 
![clubs-icons](https://cloud.githubusercontent.com/assets/1186326/6514829/676b7ec0-c353-11e4-9fe8-03a44a36360b.png)
If okay, the svgs are here: https://www.dropbox.com/sh/2a26zh8dtx1l54a/AAAvp9DFqvtNNLFvpTO4cDlSa?dl=0

**Comment by hannahkane** [comment]
+1. Nice!

**Comment by cassiemc** [comment]
Closing now. We can reopen if Ricardo has any qualms.
