### ISSUE TITLE
Design "How do Clubs work?" illustration

### ISSUE THREAD

**Issue by vazquez** [mozilla/teach.webmaker.org#134]
I made an illustration already, but I don't know if you would like to update it, Cassie.

![screenshot 2015-03-04 14 22 32](https://cloud.githubusercontent.com/assets/1119821/6491265/103bb7de-c27a-11e4-8e01-4435223a1c86.png)

**Comment by hannahkane** [comment]
Perhaps unrelated question - is the text part of the illustration? If so, I have some copy revisions that I didn't know where to put. Let me know if I should create a separate ticket for these.

Final, approved copy:

Grow the web literacy of learners
Meet regularly in classrooms, libraries, coffee shops—anywhere!
Teach with open practices
Guide people to learn by making
Connect with local and global networks

**Comment by vazquez** [comment]
@hannahkane The text is not part of the illustration, but I will definitely update the copy. No separate ticket needed.

**Comment by vazquez** [comment]
@hannahkane Done! Copy changed. http://invis.io/VK2CZH0ZC

![screenshot 2015-03-04 15 55 53](https://cloud.githubusercontent.com/assets/1119821/6493176/f76ce644-c286-11e4-81fb-8f77bc1cccc9.png)

**Comment by hannahkane** [comment]
Thank you! :)

**Comment by cassiemc** [comment]
Looking great @vazquez! Can you link me to the vectors? Might make a couple small tweaks as I do the other illustrations.

**Comment by davidascher** [comment]
I think we need more contrast between schoolhouse bricks and background, no?

**Comment by chrislarry33** [comment]
I think the school house sends the wrong message. It reads to overtly juvenile and sends a very formal message. While we love and partner with school, we need to broadcast more broadly and have an edge a activist/punk/subversive vibe.

**Comment by hannahkane** [comment]
I'm +1 on conveying informality and non-traditional settings, though we also shouldn't lose site of the basic definitional "group of people learning web literacy" piece.

It will be challenging to convey the activist vibe, while also strongly connecting to the text. I mean, I can imagine imagery involving mohawks, megaphones, and raised fists, but it might seem quite out of place next to the copy we wrote. 

What about something like the image on this page? https://bilnigma.wordpress.com/2012/08/03/a-case-for-activism-from-the-quran/

I'm not talking about the style, which doesn't fit with the site design, but the concept might be more like what @chrislarry33 is getting at, without seeming totally random.

**Comment by dajbelshaw** [comment]
> I think the school house sends the wrong message.

It's also very US-centric. It looks more 'town hall' to us Europeans, I'd suggest. ;)

**Comment by vazquez** [comment]
It actually was a town hall, good eye @dajbelshaw :)

Here are the vector just in case you need them @cassiemc: https://dl.dropboxusercontent.com/u/43783651/Mozilla/clubs-illustration.svg

**Comment by cassiemc** [comment]
Tried a couple abstract ideas, more around the theme of "how does this work" as opposed to defining a club. @vazquez @hannahkane – does this work?
![how to clubs work-11](https://cloud.githubusercontent.com/assets/1186326/6518296/b6dce682-c372-11e4-9d11-6656bc930d37.png)

**Comment by cassiemc** [comment]
If that looks okay, the svg is here: https://www.dropbox.com/s/sb0188yzsnh4k9u/icon-how-do-clubs-work.svg?dl=0

**Comment by vazquez** [comment]
I love it :100: I would say this is safe to close, but I will let @hannahkane give the last word.

**Comment by hannahkane** [comment]
Thanks, @cassiemc! I think this concept will work.
