### ISSUE TITLE
Disable minification of JS during development

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#135]
Our [current `webpack.config.js`](https://github.com/mozilla/teach.webmaker.org/blob/603f1f378707b060d01f287bb4124ccec27813fb/webpack.config.js#L19-L23) always minifies the JS it outputs.

Obviously this is a particularly unfortunate thing until #102 is fixed, but even once we have source maps, it can still be useful to not minify our development code, simply because minification takes extra time and can really slow down older systems. Also, we may eventually be testing and debugging our code on older browsers that don't have source map support!

@mmmavis, @gesa, @alicoding - Do you have any opinions on this?

**Comment by alicoding** [comment]
I think we should always disable minification of JS when we run `gulp dev` or `npm start`.

**Comment by toolness** [comment]
Good plan! I notice you've done this in #139, but since there are currently issues w/ that PR and ease of development is more important to us than production efficiencies, I've gone ahead and committed only your changes to the `webpack.config.js` file from your PR, so that we never minify at all for now. I've also filed #140 so that we remember to bring back minification for production deploys.
