### ISSUE TITLE
Enable minification for production

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#140]
In e0ad0ec08fa09e043f9a58efac748ef232bc9b91 I changed things so we *never* minify code instead of minifying it all the time. This solution is suboptimal too, just not at this stage of development, when we're more concerned about developer ergonomics than production efficiencies.

Eventually we do need to build minified code for production, though, which is why I'm filing this issue.

**Comment by hannahkane** [comment]
@Gesa - do we need to move this to the current heartbeat? (that is, was it not completed last heartbeat?)

**Comment by gesa** [comment]
@hannahkane  Yeah this needs to be moved.
