### ISSUE TITLE
Design a Template page

### ISSUE THREAD

**Issue by vazquez** [mozilla/teach.webmaker.org#144]
We need a general Template page for the Teach site.

The template should include:

- Use of H1 H2 and H3
- Image treatment
- Unordered list
- Blockquote

A 2 and 4 column approach would be good to have

**Comment by vazquez** [comment]
Here is the design for the Template page :sheep: 

https://projects.invisionapp.com/screens_public_member/66690678/latest/28364835/61351fd9c8160cde9668db0dddeb55c305ba1b0a315229e1f6699a797cf6dcd4/0/img.png  
  

![template page 1x](https://cloud.githubusercontent.com/assets/1119821/6530422/cab1a74c-c3fe-11e4-8e5d-334be3515505.png)

**Comment by hannahkane** [comment]
Like!

**Comment by hannahkane** [comment]
@vazquez - what do we need to do to close this issue?

**Comment by vazquez** [comment]
@hannahkane Nothing needed, we can close this issue :)

On Tuesday, March 10, 2015, hannahkane <notifications@github.com> wrote:

> @vazquez <https://github.com/vazquez> - what do we need to do to close
> this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/teach.webmaker.org/issues/144#issuecomment-78164652>
> .
>


-- 
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo
