### ISSUE TITLE
Design Join userflow

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#154]
A userflow needs to be considered for when a site visitor clicks: "Join" or " Sign up for an Account"

![screen_shot_2015-03-06_at_8_32_40_am](https://cloud.githubusercontent.com/assets/535012/6526095/dbec7942-c3db-11e4-9616-1eb5786c3377.png)

**Comment by iamjessklein** [comment]
cc/ @toolness @vazquez @hannahkane @cassiemc

**Comment by iamjessklein** [comment]
This will most likely be a modal and will be addressed as part of the login work that @cassiemc will be starting next week.

**Comment by cassiemc** [comment]
I think there are still some questions around whether or not we wait for new webmaker login to be complete, or use some other lower-bar option. @hannahkane @simonwex thoughts?

**Comment by hannahkane** [comment]
As far as I'm concerned, that's a 100% implementation question, so I'll defer to @simonwex. Product requirements are documented in #46 (need an opt-in for future mailings, and should trigger a transactional email).

**Comment by iamjessklein** [comment]
@hannahkane - Does this email need to be designed?

**Comment by hannahkane** [comment]
Had not thought of that. Yes, let's do it right. I'll create a separate ticket for that.

**Comment by hannahkane** [comment]
Tabling this, pending #227

**Comment by iamjessklein** [comment]
Assigning myself

**Comment by hannahkane** [comment]
This is now being done via the id.webmaker.org project.
