### ISSUE TITLE
Decide where the "mentor" button goes on Home screen

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#156]
Question 1: Where does the "mentor" button on the home screen link out to? 
Question 2: If the answer to Q1 is "I don't know" or "nowhere" can this be removed from the mockup for this heartbeat?

cc/ @hannahkane 

![screen shot 2015-03-06 at 9 40 00 am](https://cloud.githubusercontent.com/assets/535012/6526941/c9fb4412-c3e4-11e4-97b3-50eea358a5ce.png)

**Comment by hannahkane** [comment]
Was intended to go to sign-up. If that seems weird to do, before we have the concept of a Mentor Profile, I'm fine with removing the button for now.

**Comment by iamjessklein** [comment]
Agreed. I think for the time being let's remove it. 
cc/ @toolness
