### ISSUE TITLE
Design: Revise navigation item from "Teaching Materials" to "Teaching Activities" 

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#157]
The item should be "Teaching Activities" as per the site map #124 
![screen_shot_2015-03-06_at_9_43_17_am](https://cloud.githubusercontent.com/assets/535012/6527054/91c85ef8-c3e5-11e4-969c-1fb920b4307a.png)

**Comment by toolness** [comment]
Oh, this was done in b943f8e60fc4d13aa2f20d658d4ffcbb128bc96e, yay!

**Comment by iamjessklein** [comment]
woot :+1:
