### ISSUE TITLE
Assign leadership roles within our own team

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#16]
We have organizers and Regional Coordinators (RCs) on our team. Let's make it official!

**Comment by thornet** [comment]
@amirad and I will lead the first batch of R.C. onboarding and support. We will likely need to grow this going forward.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/6"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/6.
Please don't comment on it here.
