### ISSUE TITLE
Design Lost Password flow

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#162]

**Comment by hannahkane** [comment]
Made an executive decision to put this in the current heartbeat and assign @iamjessklein, but please call me on my scope-expanding bs if you'd like.

**Comment by toolness** [comment]
Hmm, since we're sharing login with the rest of Webmaker (er, at least I think we are?) my assumption was that we would essentially redirect the user to the universal Webmaker "lost password" flow... but I am not sure where we are with Webmaker login so not sure how viable that is.

**Comment by hannahkane** [comment]
Good call. I hate the idea of duplicating work. Maybe we can get an update during tomorrow's stand-up from @cassiemc or @simonwex about the state of that project.

**Comment by hannahkane** [comment]
Tabling this, pending #227

**Comment by iamjessklein** [comment]
outmoded due to the sign in flow work
