### ISSUE TITLE
Replace homepage quote

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#164]
We have a real quote we can use to replace the fake one on the homepage.

"Web literacy is about more than coding - it's about how you can be a better web citizen."
- Maurya C. New York, United States

Her image is here: https://cloud.githubusercontent.com/assets/4885898/6420808/93e53f06-be97-11e4-90b6-b81600edaf32.jpg

**Comment by hannahkane** [comment]
@iamjessklein or @vazquez, same question on this one - can I assign this to one of you to crop the image and then pass along to the engineers?

**Comment by vazquez** [comment]
Asset available here: (1x) https://dl.dropboxusercontent.com/u/43783651/Mozilla/maurya-nyc%401x.png and (2x) https://dl.dropboxusercontent.com/u/43783651/Mozilla/maurya-nyc%402x.png

This is ready to implement.

**Comment by iamjessklein** [comment]
@vazquez none of these links are working for me.
