### ISSUE TITLE
Replace Clubs page quote

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#165]
We have a real quote to replace the fake quote on the Clubs page.

""The idea of teachers and students learning at the same time is what makes me excited about this work."

- Mikko K, Helsinki, Finland

Image is here: https://cloud.githubusercontent.com/assets/4885898/6493917/1f7b5436-c28c-11e4-8ec7-50756314d9af.jpeg

**Comment by hannahkane** [comment]
@iamjessklein or @vazquez, can I assign this to one of you to crop the image and then pass along to the engineers?

**Comment by vazquez** [comment]
I will put the asset in #44

**Comment by vazquez** [comment]
Done, I have also updated InVision

**Comment by iamjessklein** [comment]
:+1:
