### ISSUE TITLE
Design email template for Teach site emails

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#169]
Initial transactional email copy is here: https://teach.etherpad.mozilla.org/clubtransactionalemails

**Comment by hannahkane** [comment]
Putting this in the current milestone as a P2 in case @iamjessklein or @vazquez has time to work on it; but not more urgent than other tickets.

**Comment by mmmavis** [comment]
Is this going to be a BSD e-mail template? Is so I'd suggest keeping the design simple.  Just a note that email templates in general need to be built in nested `<table>` and `media qurey` isn't well supported across all browsers.  :cold_sweat:

**Comment by davidascher** [comment]
No, transactional emails are not going to be driven by BSD.  But yes, we should find a way to templatize these emails, and have tooling that takes from an easily-editable form and generates the emails within a designed template.

@jbuck, @simonwex and @thisandagain have been looking at the same problem for the webmaker site, i'd like us to use the same solution (after all, the same copywriters will be editing these)

**Comment by toolness** [comment]
> @jbuck, @simonwex and @thisandagain have been looking at the same problem for the webmaker site, i'd like us to use the same solution (after all, the same copywriters will be editing these)

Is there an issue on another repo where this is being discussed?

I'm personally partial to MailChimp/Mandrill, as they have glorious developer APIs and nice UX for letting non-technical people edit slick email templates, but I've heard in the past that there may be privacy issues with them or something too.

**Comment by HPaulJohnson** [comment]
Started a similar discussion back in Jan for Webmaker emails. See details in issue: https://github.com/MozillaFoundation/plan/issues/242.

It was pushed back for NN campaign but looks like it popped back up as a P2 in last week's prioritization. Might be able to tackle all our transactional emails with this one project.

**Comment by hannahkane** [comment]
@toolness @simonwex @davidascher - wondering if this will be a blocker for site launch. Is the email templating work likely to be completed before the end of the next heartbeat? If not (seems unlikely), can we brainstorm other solutions?

**Comment by hannahkane** [comment]
Since we're unlikely to have a new tool in place by April 1, let's move forward with what we currently have (sawmill?) for the initial release.

**Comment by toolness** [comment]
Hmm, if we're only implementing something temporary, I'd recommend going with something that easily integrates with our existing backend, which is in Django. I've got experience using [Mandrill](http://mandrill.com/) for this kind of thing from working on the Hive Directory. Alternatively, if we're not expecting to send out a ton of emails, we could even use good ol' SMTP.

**Comment by hannahkane** [comment]
Just to clarify: there will be three transactional emails for v1 of the Teach site. 1) the email a user receives after signing up for the site, 2) the email they receive after adding their Club to the map, and 3) the email they receive after completing the "find out more" workflow from the Clubs page.

I believe 1) will be covered by the login work that's happening elsewhere (https://github.com/MozillaFoundation/plan/issues/53). 

Should 2) and 3) be handled via the same system, or does it make sense to build something else? Thoughts @toolness @simonwex @jbuck ?

**Comment by iamjessklein** [comment]
I am wondering if we might be able to build of the template that @sabrinang made in the past. @sabrinang - can you direct us to the file for this?

**Comment by simonwex** [comment]
@hannahkane these will all be handled by "sawmill" -- the current system. The work on the login project will, indeed cover numero uno.

**Comment by hannahkane** [comment]
ping @toolness re: simon's comment above. Are you good with sawmill? 

also, as mentioned at today's stand-up, plain text email is probably ok for v1.

**Comment by toolness** [comment]
Hmm, if sawmill is just a temporary solution anyways, I'd prefer to just have Django send them out--it's very easy to integrate Django's email w/ existing out-of-the-box services (SMTP, Mandrill, etc) but integrating with a custom solution like sawmill would likely take more work. Which is fine, if we were sticking with sawmill, but I was under the impression that we will be migrating to something else soon?

**Comment by simonwex** [comment]
Just to close the loop here: @toolness, you're going to use our SES SMTP provider directly, correct?

**Comment by toolness** [comment]
Correctamundo!

**Comment by hannahkane** [comment]
This ticket is messy. Going to close for now. Will re-open as new mail solution shakes out.
