### ISSUE TITLE
Recruit 5+ Regional Coordinators for Q2

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#172]
We'd like to identify and recruit at least 5 Regional Coordinators for Q2. 

- [x] Publish #33 
- [x] Finalize application & selection process 
- [x] Practice making the ask to RCs w/ @amirad @simonaramkisson & Natalie
- [x] Shortlist of Regional Coordinator candidates we want to ensure apply
- [x] 1:1 interviews with applicants
- [x] Finalize first RC cohort
- [ ] Publicize

**Comment by thornet** [comment]
Reviewing shortlist today with @amirad @soapdog @simonaramkisson @ldecoursy

**Comment by thornet** [comment]
Current update: 7 confirmed RCs. 1:1 interviews continuing through next week. Kickoff call with RCs scheduled for May 5.

**Comment by thornet** [comment]
Update: 13 confirmed RCs. Invitation to May 5 kickoff call being sent today.

**Comment by chrislarry33** [comment]
Worth closing this ticket and starting one(s) on next steps with our pioneer cohort?

**Comment by thornet** [comment]
Yes, good call. Closing now.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/53"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/53.
Please don't comment on it here.
