### ISSUE TITLE
[MIGRATED] Outline and Map Peaks for Mobilizing Clubs

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#174]
These questions stood out to me @ldecoursy when I was thinking over the processes needed for building out the roadmap headers for Mobilizing section within [Clubs Roadmap] (https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1FZk_0-zAcjF0nc7fa3EK7QfVVDgRAhMoOuCoxsVR4Ts/edit#gid=0)
What counts as a peak in the yearly arc of the Clubs for Mobilization?
Are we creating these peaks or are they naturally within the calendar of community events ?
What tools kits are needed for RC for yielding peaks outcomes?

Are they relevant or points already decided upon?

**Comment by ldecoursy** [comment]
I think our campaigns and key events mark the peaks here. Plus anything from your events calendar that we think make sense.

**Comment by Saallen** [comment]
I will add events into the roadmap steming from our events calendar which we can then review on Wed :smile:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/54"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/54.
Please don't comment on it here.
