### ISSUE TITLE
Finalize the domain name

### ISSUE THREAD

**Issue by adamlofting** [mozilla/teach.webmaker.org#175]
I think this is still an open issue. :hatching_chick:

This will be a blocker to setting up a GA account for this property.

**Comment by hannahkane** [comment]
Re-assigning to @HPaulJohnson who is the decision-maker on this, I believe.

**Comment by ldecoursy** [comment]
Based on a conversation earlier today, consensus is to move forward with teach.mozilla.org. Notes from meeting are here: https://etherpad.mozilla.org/teachbrandingcomms

@HPaulJohnson to confirm it's ok to use mozilla.org

cc @chrislarry33

**Comment by cassiemc** [comment]
w00t! :+1: team.

**Comment by HPaulJohnson** [comment]
Confirmed with Jennifer Bertsch that we can create a new subdomain on mozilla for teach.mozilla.org. 

Will be filing a separate bugzilla issue to have that created.

**Comment by hannahkane** [comment]
Thinking we can close this ticket then, yes? Will file separate tickets for changing the logo in the corner of the site, and moving everything to the new domain once it's created.

**Comment by HPaulJohnson** [comment]
Bug for the new subdomain on mozilla.org: https://bugzilla.mozilla.org/show_bug.cgi?id=1143719
