### ISSUE TITLE
Scope club tester debriefs

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#177]
Decide if and how we want to do debriefs with our Q1 club testers. This would include feedback on the testing process and an ask to continue with us into Q2, as well as recommendations for new testers. 

Proposal: 
* [ ] Scope the debrief ask
* [ ] Schedule 1:1s with testers 
* [ ] Report back and synthesize

**Comment by thornet** [comment]
Have drafted a debrief email to testers and a series of blog posts. 

The debrief ask should be: 
* grab a time slot with @amirad @ldecoursy or @thornet (we'll use similar breakdown as the initial interviews)
* run through a quick script of questions and reflections
* discuss interest in Q2 (mentoring, R.C, curriculum, recruitment, other.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/55"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/55.
Please don't comment on it here.
