### ISSUE TITLE
[MIGRATED] Provide expectations and resources for RCs during Maker Party

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#18]
### RACI
* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: NA 
* Dev Lead: NA
* Quality: 

### Deliverables
- [ ] List of expectations for our RCs during and post-Maker Party 
- [ ] Resources to support RCs during and post Maker Party (e.g. "How to see potential in MP event hosts as CC's," "How to use the Self, Us, Now model to invigorate new recruits," and "How to expand clubs within regions")

**Comment by hannahkane** [comment]
Can we clarify this one further? What are the deliverables? 

/cc @Saallen @thornet

**Comment by Saallen** [comment]
Within this issue we should be mapping out what we expect our RC to achieve during and post Maker Party with a potential new community of Club Captains.
How to see potential in MP event hosts as CC's
How to use the Self, Us, Now model to invigorate new recruits
How to expand clubs within regions

**Comment by thornet** [comment]
Proposing @amirad takes this one as part of her Maker Party planning

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/8"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/8.
Please don't comment on it here.
