### ISSUE TITLE
[example] Add a better photo to the Web Chef activity

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#181]
*This is an example ticket for the club curriculum.* 

We need a better photo in the Web Chef activity. Here are the steps required: 

- [ ] Search for a photo
- [ ] Make edits to the activity page
- [ ] Close this ticket when complete

**Comment by thornet** [comment]
Closing this since it was an example.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/56"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/56.
Please don't comment on it here.
