### ISSUE TITLE
Final copy for "Clubs Curriculum" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#183]
### RACI
* Owner: @hannahkane 
* Copywriter: @thornet 
* Contributor: @ldecoursy 
* Approver: @chrislarry33 

We need final copy for v1 of the Clubs Curriculum page. This includes an intro paragraph to the entire page, a brief intro to the Web Literacy Basics module, and a brief description of each of the six activities in the module.

@thornet - can you provide by EOD tomorrow, by any chance? @vazquez is working on the design in #106 in the meantime, but I'd like to draft this out in case it makes us rethink anything.

**Comment by thornet** [comment]
Drafting here: https://teach.etherpad.mozilla.org/club-curriculum-landing

**Comment by thornet** [comment]
cc @ldecoursy for QA

**Comment by vazquez** [comment]
I have updated the copy to match what is in the Etherpad. I recommend embellishing the Intro section. We currently have too little copy for the section. 

http://invis.io/242EBB23A

**Comment by ldecoursy** [comment]
I think generally we don't want too much copy - might recommend moving the image flush with the Web Literacy Basics, or do we need the image at all since the page also has visuals for the individual activities?

**Comment by vazquez** [comment]
Okay sounds good. Let me know when copy is finalized so I can close the design issue.

**Comment by ldecoursy** [comment]
I just made a few small edits on the copy - looks good to me!

**Comment by vazquez** [comment]
Awesome. Changes made to the design. Closing issue. Thanks!
