### ISSUE TITLE
Begin forging the static HTML/CSS for the Clubs page

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#186]
Ricardo finished designing the Clubs page in #44 and prepared some static assets for us.

Ali is working on implementing the dynamic, [Mapbox](https://www.mapbox.com/)-based functionality for this page in #185. However, it'd be useful for us to start building a static version of this page in JSX and LESS so that he can easily just drop his component into the page once he's done.

@mmmavis would you be interested in taking this on? It would basically involve writing JSX as though it's static HTML, much like `lib/homepage.jsx`, so could be a nice way to ease yourself into writing JSX code.

**Comment by mmmavis** [comment]
cooool, a good way for me to start using React! :grin:

**Comment by mmmavis** [comment]
@toolness @alicoding @gesa 
For modal dialogs do we write our own or use existing libraries?

**Comment by toolness** [comment]
Ugh good question. I've been writing my own modals for previous projects, because I'm slightly annoyed by the "boil the ocean" approach of [react-bootstrap](http://react-bootstrap.github.io/), but it might ultimately be more prudent to just go with the latter... Ugh. For now, if you can try reusing the [`modal.jsx`](https://github.com/mozilla/webmaker-addons/blob/gh-pages/src/modal.jsx) I wrote for the webmaker addon, that would be preferable since its implementation is so simple--then we could migrate to something else if we decide it's too limiting.
