### ISSUE TITLE
Map the communications model for RCs

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#19]
Develop the call structure for RC's with organisers and other RCs.

## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier: 

## Deliverables

 - [ ] TBD

**Comment by thornet** [comment]
Duplicate of #20, closing

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/9"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/9.
Please don't comment on it here.
