### ISSUE TITLE
Give milestones more exciting names

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#192]
Hey @hannahkane, didn't you make up awesome names for our milestones somewhere? You should totally change the names of our GitHub milestones to reflect that :smile: 

Obviously totally optional, you can just close this issue if you're too busy!

**Comment by hannahkane** [comment]
I <3 this idea and will definitely do it once @simonwex is able to sort out the repo business, so as not to confuse the Learning Networks team in the meantime.

Be warned, though, that all badges-related milestones will likely be called Honey Badger.

**Comment by toolness** [comment]
Haha awesome :+1:

**Comment by iamjessklein** [comment]
I volunteer to help! :hand:

**Comment by thornet** [comment]
Favorite ticket. ^^

**Comment by iamjessklein** [comment]
This might be fun to bring to the Wednesday team meeting and make into the "mad libs". Thoughts @chrislarry33 @hannahkane ?

**Comment by hannahkane** [comment]
Love the idea of crowdsourcing, but right now we don't have many milestones spec'ed out. 

In fact, I'm going to close this ticket for now. I promise that once we spec out the next milestone, I will remember to give it an awesome name. Please note: most of my pop culture references are from the 80s so get ready for some Back to the Future and Moonlighting jokes.
