### ISSUE TITLE
Design: Teach Podcast page

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#198]
As the site is linking out a few times to the Teach the Web Talks podcast, we should allocate some time to do a few design tweaks. 

The initial ticket might just be cosmetic, however we could probably dedicate a heartbeat just to this. 

Things to keep in mind:

* consistency with the brand
* frequency of updates
* searchability 
* bonus content 

![screen shot 2015-03-06 at 2 20 24 pm](https://cloud.githubusercontent.com/assets/535012/6578961/a5fe3b64-c71d-11e4-9f1c-9985f9ecb734.png)

![screen shot 2015-03-06 at 2 20 38 pm](https://cloud.githubusercontent.com/assets/535012/6579018/f8356f42-c71d-11e4-9fa8-6eea6c54d0e8.png)

cc/ @hannahkane @LucyeoH @secretrobotron

**Comment by hannahkane** [comment]
@Saallen - are we continuing with the podcast?

**Comment by toolness** [comment]
We better be continuing with the podcast, it's awesome!!!

**Comment by Saallen** [comment]
We are! I have allocated some time in July to get the next 3 episodes produced as interviews have been recorded. :radio:

**Comment by hannahkane** [comment]
Oh, cool. Glad to hear it! :)

**Comment by iamjessklein** [comment]
w00t! I :heart:  the podcast. Let me know if there's anything I can contribute to.

**Comment by hannahkane** [comment]
Closing this in light of conversations happening about community calls, etc. Can reopen if needed.
