### ISSUE TITLE
[ACTIVITY] Write suggested target audience

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#199]
Possibly we could add target audience on overview pages, but people have identified that there might be different ages per section. Per Meredith "reading = 8+ but participating = 11"

**Comment by LauraHilliger** [comment]
commit 8ae35d215d8bc0550383d31d9a9e893b18ba10a9

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/57"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/57.
Please don't comment on it here.
