### ISSUE TITLE
[MIGRATED] Define communication and work processes for RC's

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#20]
### RACI

* Phase: Scoping
* Owner: @amirad
* Decision Maker: @thornet
* Quality: @chrislarry33 

### Deliverables

- [ ] Publish "what's expected as a Regional Coordinator" from #33 
- [ ] Propose communication model for RCs and staff organizers
- [ ] Review communication model with RCs

**Comment by hannahkane** [comment]
@Saallen, can you say more about this one? I'm not sure I understand what the deliverables are.

**Comment by Saallen** [comment]
Within this issue we should be considering and building a communciation and how to work open model for RC's to follow. This must to a clear consistant work flow so that each RC can work and support regions with a similar and collaborative approach

**Comment by davidascher** [comment]
What's an RC?

**Comment by thornet** [comment]
Regional Coordinator

**Comment by davidascher** [comment]
Thanks!

**Comment by thornet** [comment]
Develop from: https://docs.google.com/a/mozillafoundation.org/document/d/1e4Thi0RVq2VA8z9MBax0fAQKg1wfzvpslWxRU_r_YQQ/edit

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/10"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/10.
Please don't comment on it here.
