### ISSUE TITLE
[LANDING] Add "Where to get help" section

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#200]

**Comment by LauraHilliger** [comment]
https://github.com/mozilla/webmaker-curriculum/pull/159

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/58"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/58.
Please don't comment on it here.
