### ISSUE TITLE
[MIGRATED] Create and link to "How to adapt this to your learners" resource

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#201]

**Comment by LauraHilliger** [comment]
@jvallera if you have ideas here after your April 1st meetup, definitely throw some in!!

**Comment by jvallera** [comment]
Will do. Thanks.

**Comment by LauraHilliger** [comment]
holy! Just found @smithisgeneric's resource on adding Appmaking. This is good to pull from/think about for this ticket: https://karenlouisesmith.makes.org/thimble/LTk0ODk1ODcy/align-with-appmaking

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/59"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/59.
Please don't comment on it here.
