### ISSUE TITLE
[ACTIVITY] Give time ranges instead of set times

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#202]
We've had lots of feedback that people need an idea of timing, but the 45 mins have proven unrealistic. A suggestion was made to give a range for each activity (thanks to @iamjessklein)

**Comment by iamjessklein** [comment]
:+1:  :watch:

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/0bc1fa619cc76a1c9121f3fc99ff08b7e0d354d5

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/60"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/60.
Please don't comment on it here.
