### ISSUE TITLE
[ACTIVITY] Link to Discourse for each activity to surface further remixes

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#203]

**Comment by LauraHilliger** [comment]
Comment from Clubs call:  Should there be localized links because there will be non-english speaking clubs, right? Good q. Maybe we pilot this with Portuguese? +1 +1

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/0215a727a76f9f235fd571fb0680035b54f5e67b

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/61"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/61.
Please don't comment on it here.
