### ISSUE TITLE
[ACTIVITY] Curate or take photos/videos for each activity. 

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#204]
Stories of how an activity was used in a real location and utilize the Clubs Cohorts as "models" :camera:

**Comment by LauraHilliger** [comment]
solved in other issues.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/62"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/62.
Please don't comment on it here.
