### ISSUE TITLE
[ACTIVITY] Curate or make examples of a completed task for each activity

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#205]

**Comment by jgmac1106** [comment]
I have scans of krakenthecode handout available on discourse but I am sure MOUSE has a ton as well. I thinkntbey used slides or thimble.

**Comment by LauraHilliger** [comment]
added examples, left out Story of Us – want a *real* story! https://github.com/LauraHilliger/webmaker-curriculum/commit/487d13426476c8573e66eff923698e006f39b257

**Comment by jgmac1106** [comment]
We are doing story of us as part of #walkmyworld. Will have endless stories
using the curriculum by Sunday.

**Comment by LauraHilliger** [comment]
@jgmac1106 AWESOME! You rule! Can't wait to see what you all came up with (and build it in). Reopened the issue and am on pins and needles :dancer:

**Comment by jgmac1106** [comment]
Blog Post: http://misslanningskindergartenkorner.blogspot.com/2015/03/the-story-of-us-week-nine-walkmyworld.html

Storify: https://storify.com/cpastor24/story-of-us#publiciz

ThingLink Poster: http://www.thinglink.com/scene/636310532860674048 reflective post: http://walkmyworld.weebly.com/blog/event-9-the-story-of-us

Animation: http://www.powtoon.com/show/g8raHg3p9Uz/

YouTube: https://www.youtube.com/watch?v=mYT5CwUCWeg

Poetry: https://notegraphy.com/dogtrax/note/1614920

Animation: http://www.powtoon.com/show/d7woyIDEQwg

Script to text movie: https://plotagon.com/42510

Multimodal Critical Response: http://jgregorymcverry.com/computers-versus-printing-press/

Sketchnote: https://twitter.com/mkurashige/status/579183861726216193/photo/1

**Comment by jgmac1106** [comment]
Here are some chef pieces:

https://sites.google.com/site/textsandtools/techtutorials/animoto

https://sites.google.com/site/textsandtools/techtutorials/thinglink

http://jgregorymcverry.com/writing-mini-lessons-with-sock-puppets-creating-a-lead/

**Comment by LauraHilliger** [comment]
rad. Built in MOAR examples with https://github.com/LauraHilliger/webmaker-curriculum/commit/f59075d4f750a6999730229cdc1cb00486da4bdd Thanks Greg!!

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/63"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/63.
Please don't comment on it here.
