### ISSUE TITLE
[ACTIVITY] Embed pre & post activity questionnaires

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#206]
so that they are more easily completed

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/227bfd951f0682bc590a2594b16d07d45bdb3b6d

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/64"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/64.
Please don't comment on it here.
