### ISSUE TITLE
[LANDING] Add an intro activity to set up your club's thread in Discourse

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#207]

**Comment by LauraHilliger** [comment]
blocked by #208

**Comment by LauraHilliger** [comment]
commit bd671bf

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/65"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/65.
Please don't comment on it here.
