### ISSUE TITLE
[KRAKEN] Prompt to complete only 2 sources

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#209]

**Comment by LauraHilliger** [comment]
commit 
dea9102

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/67"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/67.
Please don't comment on it here.
