### ISSUE TITLE
[MIGRATED] Design quarterly report template for RC's

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#21]
## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier: 

## Deliverables

 - [ ] Standard reporting template that we request of RCs each quarter

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/11"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/11.
Please don't comment on it here.
