### ISSUE TITLE
[KRAKEN] Rewrite learning objectives

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#210]
Many did not feel that learners would gain enough based on this activity to credential for credibility  competency

**Comment by dajbelshaw** [comment]
Will need a bit more detail to action this. Are we changing the activity or just the learning objectives?

**Comment by jgmac1106** [comment]
I was one of those who said it during club call, but I am biased as I work in this space. 

One 45 min activity IMO would not create artifacts that I could justidy credentialing. I don't think a rewrite of objectives would change ny opinion. 

When you look at all the skills under credibility Kraken does not result in an artifact suggesting competency of that skill. 

Maybe we don't credential after the basics module for some competencies.

**Comment by dajbelshaw** [comment]
So the badge is issued as a result of activities undertaken by learners. If we don't feel like the activities lead to the badge, then we need to change the activities. 

I'm happy to rewrite the learning objectives, but if we're not changing the activities it seems a little... pointless?

**Comment by jgmac1106** [comment]
Yes. You can't change objectives and not alter learning activities.

Why must every activity result in badging? If some credentialing requires a
greater preponderance of evidence could that come after multiple
activities?

Learners need to do Kraken it introduces the skills but I don't think I
would be comfortable as an issuer saying someone who completed Kraken
mastered the skills under the competency.

If I recall the skill level badges were deprecated and we went with just
the competencies. Therefore higher bar.

**Comment by LauraHilliger** [comment]
The artifact is the tip sheet. I guess would agree with @jgmac1106 that *out of context* that tip sheet isn't enough to badge with. But it's not out of context if the educator is reviewing the badge application, right?

The credibility badge asks for 1 of the following:

1) researching the authorship and ownership of websites and their content
in Kraken, Groups start by spending 20 minutes researching. The [tip sheet](https://docs.google.com/a/zythepsary.com/file/d/0B1vyNnSVEMIDbDVLX1E4ZXRmclE/edit) asks for authorship, though not ownership (I would argue "ownership" of a website is mostly irrelevant. Ask me why in a web lit call ;)
2) comparing information from a number of sources to judge their trustworthiness
in Kraken, we're doing EXACTLY that
3) discriminating between 'original' and derivative web content
in Kraken, we're asking "Where does this sites info come from" which IMHO is at least turning in the direction of discriminating b/w content
4) making judgments based on technical and design characteristics to assess the credibility of information
Is the Kraken real = judgement

For this issue, should we add LOs on the credibility skills? I think the activity does lead to the badge, just not in a context free environment. Thoughts?

**Comment by jgmac1106** [comment]
Oh didn't catch the language that you oy need one of the skills in the
competency to meet badge requirements.

If that is case then activity is fine.

**Comment by jgmac1106** [comment]
Though I could (but won't) argue that the badge requirements need to be
revised. Doing "one of the following" seems strange when we. Have
identified specific skills under competency.

**Comment by LauraHilliger** [comment]
i added two LOs reworded from the credibility badges.

https://github.com/LauraHilliger/webmaker-curriculum/commit/9ceba80cd2ebc25bb01156f1fe7be47ea7b5d7fe

@jgmac1106 the "one of the following" language is on lots of the Web Lit badges. I think the idea was to have a variety of badges (e.g. "maker: credibility" vs "mentor: credibility"), but I'm not sure where we are on the badge front in general ;)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/68"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/68.
Please don't comment on it here.
