### ISSUE TITLE
[PINGKONG] Lengthen suggested duration (1hr+)

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#211]

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/0bc1fa619cc76a1c9121f3fc99ff08b7e0d354d5

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/69"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/69.
Please don't comment on it here.
