### ISSUE TITLE
[PINGKONG] Rewrite learning objectives

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#212]

**Comment by dajbelshaw** [comment]
Need more detail to action this.

**Comment by jgmac1106** [comment]
The general feedback was many concepts were too advanced and required a good bit of pre teaching. Does that sum it up @laurahillinger?

**Comment by dajbelshaw** [comment]
OK, so are we changing the activity as well as the learning objectives? Was there a mis-match between the two?

**Comment by LauraHilliger** [comment]
yes, @jgmac1106 summed it up perfectly. I added quite a bit of contextual information to this activity. I also revised the learning objectives based on comments in the feedback etherpad. Maybe you all want to take a look and see if the iterations have solved this issue? It's still an involved activity, but if you feel like the LOs and activity match, please close!

live page:  http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-pingkong.html

PR: https://github.com/mozilla/webmaker-curriculum/pull/165

**Comment by jgmac1106** [comment]
This is better. Hopefully embedding the form will also increase the number of people completing the assessment survey.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/70"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/70.
Please don't comment on it here.
