### ISSUE TITLE
[PINGKONG] Add videos that introduce the concepts

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#213]
There and Back Again: A Packet's Tale - How does the Internet work? https://www.youtube.com/watch?v=WwyJGzZmBe8

How does the Internet work? https://www.youtube.com/watch?v=oj7A2YDgIWE

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/56adea9366fc42a15fdd8e4436dd126e21c38185

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/71"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/71.
Please don't comment on it here.
