### ISSUE TITLE
[PINGKONG] Add improv skits

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#214]
@chadsansing suggested improv with this activity. Chad, do you happen to have a link or a write up? Video!?

**Comment by chadsansing** [comment]
I'd like to develop this a bit more - include some improv tips, too, but maybe it'll do for now?

https://chadsansing.makes.org/thimble/LTE4Mjg3MTYwMzI=/perform-the-net

**Comment by LauraHilliger** [comment]
Thanks Chad! I added to the pingkong activity with 

https://github.com/LauraHilliger/webmaker-curriculum/commit/84f6355bb8f4e0b57b60afc9a361c6b02cd52557

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/72"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/72.
Please don't comment on it here.
