### ISSUE TITLE
[PINGKONG]  Simplify language explaining terms

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#215]

**Comment by thornet** [comment]
Do we still need this one, @LauraHilliger?

**Comment by LauraHilliger** [comment]
closing because despite going through the notes again, I cannot find context for this issue (and the wiki descriptors don't seem too complicated to me). Will reopen if this feedback surfaces again.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/73"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/73.
Please don't comment on it here.
