### ISSUE TITLE
[PINGKONG] Add distinction between Internet and web.

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#216]

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/ea48c0befc86a717529e006a946de59a11e88d18

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/74"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/74.
Please don't comment on it here.
