### ISSUE TITLE
[PINGKONG] include the government spy idea

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#217]

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/a1873782a030dcb5fe83221ccc527ce1f147ba2c

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/75"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/75.
Please don't comment on it here.
