### ISSUE TITLE
[HACKTHENEWS] Find and link to a tutorial on "How to easily get a photo of yourself from Facebook/Instagram"

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#218]

**Comment by LauraHilliger** [comment]
No tutorial for right clicking, just added a note.

https://github.com/LauraHilliger/webmaker-curriculum/commit/5abcc3567714d9adc21d7e27fa046e0036e5433b

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/76"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/76.
Please don't comment on it here.
