### ISSUE TITLE
[HACKTHENEWS]     Add section to help educators talk about the word "hack"

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#219]
remix https://wiki.mozilla.org/Hackasaurus/FAQ

**Comment by LauraHilliger** [comment]
wikied it here: https://wiki.mozilla.org/Webmaker/Teach/Terminology#Hack and 

https://github.com/LauraHilliger/webmaker-curriculum/commit/913500e0fec911fa770a7a40511cadb9e656d1aa

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/77"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/77.
Please don't comment on it here.
