### ISSUE TITLE
[MIGRATED] Conduct Train the Trainer in Whistler for RC's

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#22]
We'll invite RCs to Whistler, and will use the time to train them in the Teach Like Mozilla module so they can then go forth and train Club Leaders.

## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier: 

## Deliverables

 - [ ] Invite RCs to Whistler
 - [ ] Plan TTT
 - [ ] Prepare supplementary materials
 - [ ] Run the training!

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/12"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/12.
Please don't comment on it here.
