### ISSUE TITLE
[HACKTHENEWS] Add tip to use web pages that have HTML to play with and not a lot of Javascript. 

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#220]
Need worldwide examples (e.g. BBC.co.uk vs .com)

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/ba7046d2d17b2b35f0aeba518d42e624717f4b3a

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/78"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/78.
Please don't comment on it here.
