### ISSUE TITLE
[HACKTHENEWS]  Add tip to create a shared Webmaker account

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#221]

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/94dfa59095a401a8ac2a413025430da4b9d01efd

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/79"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/79.
Please don't comment on it here.
