### ISSUE TITLE
[HACKTHENEWS]  Suggestion to go further: share your hack with the news station 

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#222]
and hear their reaction

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/b4c984c1059951b7e8e6a6d622b66c311008306e

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/80"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/80.
Please don't comment on it here.
