### ISSUE TITLE
[HTMLPUZZLE] Add tip: write on pieces of paper or post-its instead of making boxes

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#223]

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/8e7cabf83d5468e48379781080e31fb7077db24e

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/81"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/81.
Please don't comment on it here.
