### ISSUE TITLE
[STORYOFUS] Add tip to start storyboarding with pen & paper

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#224]
maybe useful, the storycamp storyboarding resource: https://mozteach.makes.org/thimble/schematics-and-storyboards

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/daab93e0a77332f2b229479a5638460378472329

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/82"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/82.
Please don't comment on it here.
