### ISSUE TITLE
[STORYOFUS] Add example of a story as an animated gif 

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#225]
using Meredith's links: https://katermouse.makes.org/thimble/LTIwNjQwNTYzMjA=/creative-commons-gif-exchange-activity

**Comment by jgmac1106** [comment]
@LauraHillinger if you want any help or want to bounce ideas around let me know. Will be a fun make.

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/92a4338cc5898e87606342aa18beb2f361fd88ef

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/83"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/83.
Please don't comment on it here.
