### ISSUE TITLE
Modularize LESS code

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#226]
Right now we've just got a big massive `styles.less` file that contains a ton of rules. Ali mentioned on today's stand that we might want to consider breaking it up into multiple files, where each file addresses the styling needs of a particular page or component.

I've already "modularized" the rules in `styles.less` to some extent by prefixing rules under the class of the part of the page they're in, e.g.:

```less
.sidebar {
  // All sidebar-related CSS rules go here...
}
```

However, I believe [Nicole Sullivan disagrees](http://www.stubbornella.org/content/2011/04/28/our-best-practices-are-killing-us/) with such things.

I'm not super experienced with refactoring CSS so would appreciate any feedback from @mmmavis, @gesa, @alicoding or anyone else who has dealt with large CSS codebases before!

**Comment by gesa** [comment]
I totally saw that Nicole Sullivan talk! ^_^

I'd love to take this on if you're looking for someone to assign to.

**Comment by alicoding** [comment]
@gesa you are welcome to work on this, but I would love to chat with everybody on our 3PM (EST) meeting to finalized what approach we are going to take exactly here.
