### ISSUE TITLE
Figure out login for Q1 deliverable

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#227]
So, for Q1 we'd like to have login, so that users can register a webmaker club on the map.

However, one challenge right now is that integrating login is currently non-trivial for a variety of reasons; even more importantly is that **a complete revamp of login will begin in the next heartbeat**. So I have concerns about the cost/benefit of integrating login now and then migrating, versus simply holding off on integrating login until the new infrastructure is finished.

That said, though, there *are* a few lightweight things we could do to address user needs without necessarily adding login. For example, it might not be hard to allow new webmaker club map pins to be submitted **anonymously**, and for learning team members to have access to an admin console where they could either approve submissions (the whitelist approach) or delete submissions flagged for abuse (the blacklist approach). There's some issues to migrating this data when we add real login, but it's possible.

Anyways, we should definitely talk about this soon! Any ideas for next steps, @hannahkane?

**Comment by hannahkane** [comment]
Would love an estimate from @simonwex about how long the login revamp might take. May be preferable to delay release of the site, but only if we're confident it will be completed soon.

@toolness  - the anonymous approach wouldn't allow for users to edit or remove their Club, right? That seems like a significant blocker. People be typo'in'.

Does anyone have add'l ideas about how to create a login experience with low effort - one that we could easily replace later? Might even consider third-party login tools, if that's a possibility.

/cc @davidascher @OpenMatt

**Comment by toolness** [comment]
Well, a [persona](https://persona.org/)-based login experience would be pretty easy to implement, actually... there's just the issue then of requiring users to use persona. If the vast majority of people posting their webmaker clubs on there are already our core community, though, it's likely that they already have Persona accounts.

**Comment by hannahkane** [comment]
I think Persona would likely be fine for v1. @chrislarry33 @thornet @ldecoursy @amirad - do you have concerns about requiring Persona until we have a new login experience completed?

**Comment by ldecoursy** [comment]
Agree, seems ok to plan for Persona for v1. Once we have a better sense of timing for new login, we can figure where it fits best into the roadmap.

**Comment by chrislarry33** [comment]
I actually am struggling with this a bit b/c we have seen how persona/login have a chilling effect on participation. But I am going top defer to @hannahkane and @ldecoursy here and vote for having it be updated when its ready

**Comment by hannahkane** [comment]
Going to give this until tomorrow to see if anyone has any other comments. Otherwise, will file a ticket for implementing Persona.

**Comment by toolness** [comment]
FWIW, I'm struggling with this too because I'm also familiar with the chilling effect of persona on participation. So I will aggressively push for migrating away from persona as soon as it's technically feasible.

That said, particular advantages of going with Persona for the time being are:

* It's *really* easy to implement from a developer perspective; this allows us to spend more time on crucial site features, and less on a login mechanism that will only be in-place for a (hopefully) very short period of time.
* It will be easy to migrate *from* persona because we'll have the verified email addresses of users, which we can associate with Webmaker accounts when we migrate. This is in contrast to other low-effort, temporary mechanisms such as anonymous cookie-based submission, where we don't have a verified email address.

**Comment by toolness** [comment]
That said, I am currently talking to jbuck about other possibilities, so please don't make the executive decision just yet @hannahkane!

**Comment by hannahkane** [comment]
Closing this because we've decided to go with Persona, until the new login is completed.
