### ISSUE TITLE
Consider re-naming repository to teach.mozilla.org

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#231]
Today @mmmavis mentioned that we might want to rename this repository to teach.mozilla.org, since that's apparently going to be its new name.

Another option might be to rename the repository to just `teach`, so that it doesn't need to be renamed in the future if it's decided that the domain name be something different.

@simonwex, any thoughts on this?

**Comment by ldecoursy** [comment]
This repo is really supposed to be Mozilla-Learning, and there should be a separate one for teach.mozilla.org (to track site-specific work). Think @simonwex is working with Github on this?

**Comment by hannahkane** [comment]
@toolness - assigning this to you, since I believe you're working on it anyway.

**Comment by hannahkane** [comment]
Closing this because it's a bit confusing. Will open a ticket with the plan @ldecoursy outlined in her comment.
