### ISSUE TITLE
Define <main> element

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#234]
Currently we have `<footer>` on our pages, I wonder if we should define `<main>` as well?  Looks like https://github.com/mozilla/teach.webmaker.org/blob/develop/lib/page.jsx#L16 is the place to change if we decide to have `<main>`.

/cc @toolness @alicoding @gesa

**Comment by gesa** [comment]
I am a big supporter of using as many semantic HTML5 elements as possible :+1:

**Comment by toolness** [comment]
Sure sounds good to me!

This message was typed with haste on a tiny keyboard with no tactile feedback.

**Comment by mmmavis** [comment]
Cool, I'll include this in my PR for /clubs page.

**Comment by mmmavis** [comment]
we can close this ticket one https://github.com/mozilla/teach.webmaker.org/pull/193 is landed
