### ISSUE TITLE
Detect regular/retina display and render proper images

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#236]
As we chatted on PR https://github.com/mozilla/teach.webmaker.org/pull/193 we need to come up with a way to detect and render images for regular/retina display automatically.

@toolness 
> So, this is a weird question, but ... are we actually using the non-@2x images yet? Do web browsers somehow handle this when they see the @2x, or do we need to file a bug to add some JS logic or CSS rules for that? I'm completely unfamiliar with how to adjust to this post-retina world we live in.

@gesa 
> I wrote a [teensy-tiny script](https://github.com/mozilla/webmaker-landing-pages/blob/master/site/resources/js/core.js#L10-L30) for this. Best practice, images should [include a noscript](https://github.com/mozilla/webmaker-landing-pages/blob/5d37adef6ce8272839226e8e99c45036189cc9cf/site/src/from/net-neutrality.html#L39-L42)

**Comment by gesa** [comment]
call me biased, but i'd love to see my solution react-ified and implemented as a component.
