### ISSUE TITLE
[LANDING] Add acknowledgements section thanking testers

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#239]
Let's get the names of the people who helped tested and add an acknowledgements section.

**Comment by LauraHilliger** [comment]
commit dd4b655

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/84"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/84.
Please don't comment on it here.
