### ISSUE TITLE
[MIGRATED] Check in with RCs at end of Q2 to plan for Q3

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#24]
## RACI

* Phase: Review
* Owner: @thornet
* Quality Verifier: @chrislarry33 

## Deliverables

- [ ] 1:1s with R.C. to review organizing model
- [ ] Document needs and iterations on model for Q3

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/14"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/14.
Please don't comment on it here.
