### ISSUE TITLE
[ACTIVITY] Add CC-licensing info

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#240]
We should have proper CC licensing on our activities. Suggest: CC BY.

**Comment by LauraHilliger** [comment]
#85bc67f413c5fc24642c71a15b535c0a4faaa705

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/85"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/85.
Please don't comment on it here.
