### ISSUE TITLE
Mozilla Learning logo should be Mozilla Teach

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#243]
We need to do a design treatment for the wordmark/logo considering that the site is now branded as teach.mozilla.org (not under the parent brand of Webmaker - but the parent brand of Mozilla) 

![screen shot 2015-03-11 at 1 40 37 pm](https://cloud.githubusercontent.com/assets/535012/6602784/39589536-c7f4-11e4-9a4f-947642ce58ba.png)

**Comment by iamjessklein** [comment]
@vazquez - I am wondering if we should keep the mark and just change the text. There are larger branding implications for this, however. We are then saying that there is a direct association between teach and webmaker. 

@cassiemc @HPaulJohnson - would also love your thoughts on this.

**Comment by cassiemc** [comment]
I don't think we should use the webmaker logo at all. Options for placeholders:
* mozilla logo + Learning (my fave)
* just the text: Mozilla Learning (or whatever text)
* just the mozilla logo

Thoughts @hannahkane @HPaulJohnson ?

**Comment by iamjessklein** [comment]
also wondering if there is a distinction being made between "Learning" and "Teaching" 

cc/ @chrislarry33 @ldecoursy

**Comment by hannahkane** [comment]
Just confirmed with @chrislarry33 - we should use "Mozilla Teach", not Mozilla Learn or Learning. 

I think we're probably good to use the Mozilla logo + "Teach" or just the text "Mozilla Teach".

**Comment by hannahkane** [comment]
Wait! Stop the presses!

This point seems to be contentious, so let's just have the mozilla logo and NO word at all (no "Teach", no "Learning").

**Comment by iamjessklein** [comment]
I love this feed.

So just to clarify. We are talking about this:

![screen shot 2015-03-23 at 1 55 13 pm](https://cloud.githubusercontent.com/assets/535012/6786691/45271fb2-d164-11e4-865b-66ceb8f8c45c.png)

**Comment by hannahkane** [comment]
yes, exactly. :)

**Comment by davidascher** [comment]
Actually, the evolving wordmark has some tweaks:

![screenshot 2015-03-23 11 12 53](https://cloud.githubusercontent.com/assets/51278/6787086/9b931444-d14d-11e4-8e9a-853c89a6b6c5.png)

**Comment by iamjessklein** [comment]
I was under the impression that the new wordmark wasn't being used yet. It's not on the mozilla.org site yet as far as I can tell. Do you know otherwise @davidascher ?

**Comment by davidascher** [comment]
No, I don't, but we're using it internally, I expect we will be using it
externally, and just wanted to make sure that y'all were looped in.

**Comment by chrislarry33** [comment]
+1 to @hannahkane

**Comment by iamjessklein** [comment]
cool. thanks @davidascher 

@vazquez - since this will be on the white section above the left navigation I assume we should shoot for the new logo in mozilla gray.

**Comment by HPaulJohnson** [comment]
re: use of new wordmark: when @cassiemc and talked to Sean Martell a few weeks ago he said they would be phasing in the new version over time not in one big reset. It's already started showing up in other public places, most notably MWC. 

@cassiemc do you want to check with Sean - or do you know from previous converstaions - what version we can/should use now?

**Comment by cassiemc** [comment]
Have just followed up with mart3ll by email.

**Comment by jgmac1106** [comment]
“But Taborlin the Great knew the names of all things, so all things were
his to command."

Can you ask that guy?

**Comment by cassiemc** [comment]
From Sean: "We're actually holding it back going forward until an official launch, which will most likely be in Whistler. We used it at MWC, but going to hold off elsewhere for now."
