### ISSUE TITLE
Build modal dialogs

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#244]
According to the [mockup](https://redpen.io/wc356809d269ed0827) of the /clubs page we need modal dialogs to display some forms.  I'm opening this ticket separately so @alicoding doesn't have to wait longer for my [big Clubs page PR](https://github.com/mozilla/teach.webmaker.org/pull/193) to land.

@toolness 
> Ugh good question. I've been writing my own modals for previous projects, because I'm slightly annoyed by the "boil the ocean" approach of [react-bootstrap](http://react-bootstrap.github.io/), but it might ultimately be more prudent to just go with the latter... Ugh. For now, if you can try reusing the [`modal.jsx`](https://github.com/mozilla/webmaker-addons/blob/gh-pages/src/modal.jsx) I wrote for the webmaker addon, that would be preferable since its implementation is so simple--then we could migrate to something else if we decide it's too limiting.

Is what you said on https://github.com/mozilla/teach.webmaker.org/issues/186#issuecomment-78112843 still the approach we are going to take?

**Comment by hannahkane** [comment]
@mmmavis - you are my labeling hero! :)

**Comment by toolness** [comment]
Ah yup, I think it's a fine approach for now. Here is an example of the `modal.jsx` component in use, if it helps:

https://github.com/mozilla/webmaker-addons/blob/gh-pages/src/export-modal.jsx#L145-L151

It basically just uses Bootstrap's CSS to render a modal, albeit without any cool slide/fade effects. As long as the `<Modal>` is in your React component heirarchy, it will be displayed... as soon as its `onClose` handler is called, you'll want to set some internal state that prevents the `<Modal>` from being rendered--[here's an example](https://github.com/mozilla/webmaker-addons/blob/gh-pages/src/app.jsx#L281-L287).

**Comment by vazquez** [comment]
The Sketch file: ﻿https://www.dropbox.com/s/f8xvapyuy7i2wrp/Clubs%20Page.sketch?dl=0
The Globe asset: https://www.dropbox.com/s/qjl3hp4uxx1b84i/orange-globe.svg?dl=0
The Envelope asset: https://www.dropbox.com/s/1agylnxsqy8xlvm/orange-mail-icon.svg?dl=0
