### ISSUE TITLE
Determine an accessible solution for the webmaker clubs map

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#245]
As @adamlofting mentioned in https://github.com/mozilla/teach.webmaker.org/issues/151#issuecomment-78243236:

> As a fallback, you can always search and see a list of local clubs without needing to see a map. The data is essential, the map presentation is the progressive enhancement.

So we need to actually implement that!

This will require some **design**, since we don't currently have any mock-ups that show what such a list of clubs might look like.

Then it will require **implementation**. It's likely that for v1 we can constrain the implementation in some ways. For instance, it's likely that there won't be a ton of webmaker clubs at first, so we probably don't need pagination, and even search might not be needed (though ordering the list in a reasonable way, such as grouping the clubs by country or geographic region, might be necessary).

Aside from that, there's also the question of *when* we progressively enhance to the map. Currently, we only really know what the map will look like on desktops, since that's all we have mockups for; we'll likely need mockups for how things should look on mobile, and how interactions should work. If we don't have time to design/implement that for v1 then we may have to fallback to the list on mobile.

**Comment by hannahkane** [comment]
@toolness - do you want this to start out as a design ticket? Wondering how we push this forward.

**Comment by iamjessklein** [comment]
Can this be pushed to the March 27 heartbeat?

**Comment by toolness** [comment]
@hannahkane - Yeah, i think it makes sense to start out as a design ticket... and @iamjessklein I think it's cool to push it out of this heartbeat!

**Comment by iamjessklein** [comment]
I'm thinking that we can give it a similar treatment to the [Contacts, Spaces and Offices map on mozilla.org](https://www.mozilla.org/en-US/contact/spaces/)
This is what it looks like in desktop:
![screen shot 2015-03-23 at 8 44 32 am](https://cloud.githubusercontent.com/assets/535012/6780163/12627e44-d139-11e4-9b5f-f6141929e7d0.png)

These are mobile views:

![screen shot 2015-03-23 at 8 43 56 am](https://cloud.githubusercontent.com/assets/535012/6780165/1beb4dec-d139-11e4-9f98-58d113833b41.png)

![screen shot 2015-03-23 at 8 44 12 am](https://cloud.githubusercontent.com/assets/535012/6780166/1d4a60a6-d139-11e4-8e1c-537b3fc278ce.png)

cc/ @toolness @amirad @chrislarry33

**Comment by hannahkane** [comment]
Let's be sure to imagine a future with 200 Clubs, or 500 Clubs, and consider how ppl will find the Clubs near them. Should we group by region, for example?

**Comment by iamjessklein** [comment]
good point. 

For starters, the page could ask if we could use geolocation, which would simplify the range of data being displayed. 

Otherwise, I suspect  we have by country, by region, by neighborhood - will research a bit.

**Comment by iamjessklein** [comment]
@amirad also pointed me to the Coder Dojo map that simply collapses from the map -> "find a club near you" which seems pretty logical. 

![screen shot 2015-03-23 at 11 45 16 am](https://cloud.githubusercontent.com/assets/535012/6783789/208b1882-d152-11e4-91ba-3714d1262f83.png)

![screen shot 2015-03-23 at 11 45 27 am](https://cloud.githubusercontent.com/assets/535012/6783790/23b4de12-d152-11e4-9984-4020705f1060.png)

**Comment by toolness** [comment]
Hmm, I'm now realizing that if we group by country or region, it will involve changing the data model... Right now we literally just store a location string and a lat/long, but if we group by country/region we'll also have to store that information.

**Comment by hannahkane** [comment]
Seems like regional groupings will become important very quickly. Perhaps we can use an ISO standard to define regions, like this one: http://unstats.un.org/unsd/methods/m49/m49regin.htm

**Comment by iamjessklein** [comment]
For this release we are going to display the map as a list.

**Comment by iamjessklein** [comment]
@vazquez @hannahkane take a look at [invision](http://invis.io/H32JRAF2K) 

![mobile-map](https://cloud.githubusercontent.com/assets/535012/6854882/5c0b9ce0-d3ca-11e4-865c-1f5a7f7ce0be.png)

**Comment by hannahkane** [comment]
Looks good, @iamjessklein. I'm worried that people won't get to the key CTAs at the bottom of the page - the curriculum, the toolkit, and discourse. Any thoughts on that?

**Comment by iamjessklein** [comment]
@hannahkane are those the key CTA's or is the key CTA to add a club to the map?

**Comment by hannahkane** [comment]
The primary CTA is to add their Club. But am I correct that those lower secondary CTAs are *only* accessible by scrolling down the page? I think we need to make sure that people can get to the Curriculum and the Toolkit some other way as well. What do you think?

**Comment by iamjessklein** [comment]
I have an idea to collapse the content. I'm going to mock it up.

**Comment by iamjessklein** [comment]
Updated the mockup - now it's a dropdown arrow. 

cc/ @vazquez 


![mobile-map]
(https://cloud.githubusercontent.com/assets/535012/6858255/668dea6a-d3e3-11e4-8a3c-3c774bd9d337.png)

**Comment by hannahkane** [comment]
<3

**Comment by davidascher** [comment]
Drive-by: Contrast on edges of that school/church/town hall building is
still not strong enough.

**Comment by iamjessklein** [comment]
hey @vazquez can you take a look at that color? As @davidascher mentioned - It does feel a touch light.

**Comment by vazquez** [comment]
That is an old image. We are using this now.

![screenshot 2015-03-27 09 39 17](https://cloud.githubusercontent.com/assets/1119821/6868827/27073702-d465-11e4-9759-0ce25e24a57b.png)

**Comment by hannahkane** [comment]
@iamjessklein - do you feel like we can close this? I opened a new ticket for implementation.

**Comment by iamjessklein** [comment]
:+1:  we're good.

**Comment by toolness** [comment]
Hey, what is this accessible sol'n supposed to look like on desktop?

I know this may seem like a silly question since the map will be available on desktop but hear me out!

You will notice that many sites which offer maps also offer a **list view** of their markers too. While maps are very slick and make it possible to see *where* clubs are at a glance, they don't make it easy to see *who* is leading them, or what their names are--doing that requires zooming into the map and clicking on every pin, which is actually quite cumbersome. Perhaps this isn't a use case we want to address, but I thought I'd throw it out there--after all, some of our users may be more interested e.g. in the people behind the clubs rather than where the clubs are located.

**Comment by hannahkane** [comment]
+1 to having a desktop view as well. @iamjessklein - is that something you can do?

**Comment by iamjessklein** [comment]
:+1: will upload today.
