### ISSUE TITLE
Design "Tips for Running Your Club" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#254]
### RACI

Driver: @hannahkane
Design Lead: ?
Quality: @cassiemc 

The content for this page is here: https://docs.google.com/document/d/1syswSeON-0o1svFz8F457uCncg8Kvx5IW8-2Xi3RBpw/edit#

Note, there is *a lot* of content, so this calls for a new design solution—something we haven't yet built for the Teach site so far. Perhaps the individual sections are collapsed by default, or something like that.

This page is linked *from* the Clubs page.

**Comment by chrislarry33** [comment]
Could consider putting content on a wiki as inbetween step if this is a blocker for April 1. Maybe pull out high level points for page and then link to wiki.

**Comment by jgmac1106** [comment]
I love the tips doc but it reads more like a handbook. One idea might be to
publish like the white papers. I love the crispness of that design and
layout.

In terms of the "tips"  page how about having a brief version on the
"handbook" . Some of those nifty icons, for all level 1 and 2 headings with
a few words. They could possibly link to each section of the "handbook."

**Comment by iamjessklein** [comment]
After looking at the exhaustive amount of content - and taking into account that links might need to be constantly updated, I propose that we look into incorporating a wiki into this page. Either this page should link out to a wiki or if it is technically feasible, it would be most ideal to turn the page into a wiki while maintaining it's presence within the site. 

:bulb: :bulb: Thoughts? :bulb: :bulb:   @toolness @jbuck @hannahkane @vazquez

**Comment by vazquez** [comment]
I agree. The content that exists on the Events Resources page would most likely be the max amount of content we could handle; and the Tips content is about 2.5x the size of Events Resources.

**Comment by hannahkane** [comment]
I'm not sure I understand how a wiki is any better. I mean, it's easier to edit, but it's not easier to read. If we have a problem with presenting too much information, maybe we need to address that directly. (Perhaps by drastically cutting down the content. @amirad, thoughts on that?)

I doubt we can add wiki technology in a week, and I'd prefer to keep users on site as much as possible, so for v1 I'd vote for applying the design conventions established on the Events Resources page.  (Is it really 2.5x the size? I just did a word count, and it looks like it's only about 400 words more.)

@iamjessklein, what makes you think think the links will need to be updated frequently?

**Comment by amirad** [comment]
Can we break it up like @vazquez did for the events page? 
I know it's a lot more information but my experience says the community wants and needs that info. The only things that might change are URL/titles around the move from Webmaker titled properties. In Q2 we wanted to test this info with out club leaders so I can imagine just one update to it at the end of the quarter.

**Comment by toolness** [comment]
Ah, so I suspect that **this** is the kind of thing jbuck and I were meant to be prototyping editing experiences for in that [other heartbeat](https://github.com/mozilla/teach.webmaker.org/issues/75)!

I think there's definitely some good stopgap solutions we can bust out here to make editing easier for the teach folks, e.g. so they don't need to know JSX and stuff just to make some edits to the pages.

I think we can probably store these pages in Markdown in the github repository and stuff them into the content of pages on the teach site when the static site is generated. Github offers pretty decent preview-based editing of markdown files in repositories--for instance, [here's an example of editing `README.md`](https://github.com/mozilla/teach.webmaker.org/edit/develop/README.md)--so teach team folks can make edits through GitHub. If we want something slicker, we can try [prose.io](http://prose.io/), which is conceptually similar to editing Markdown on GitHub but with a friendlier UI.

The major disadvantage of this approach is that it will be a lot harder to do things that are more complicated than basic text content changes, e.g. adding images won't be terribly easy, and doing some of the really complex layouts that our other pages have will also be hard.

There are more options we can explore in the future but for now this is all I can think of.

**Comment by hannahkane** [comment]
I'd strongly advocate for holding off on adding editing functionality until that need actually emerges.

**Comment by jgmac1106** [comment]
Is their a hybrid approach? I agree with @amira that the clubs want and
need this information but we also know that too much copy and the the
content gets ignored.

What @amira and her team wrote is great but it comes off not as tips but as
a handbook or guide.

This probably doesn't work with the current design and I am once again
sticking my head where it doesn't belong....but.....

I really think you should make the page just the level 1 and 2 headers from
the tips Google Doc. Have 150-200 characters for each level AND make a
handbook available as a wiki (or the github pages you use for white papers).

On another page I think @iamjessklein called it a deep read. Maybe the
handbook is the deep read.

**Comment by hannahkane** [comment]
Thanks, @jgmac1106. I agree with you that this is more like a handbook.

For the initial release (which is coming up soon!), we're going to go with breaking up the content using the same design elements as the Events Resources page.

What I'd like to do in a future iteration is conduct a bit of research into *how* this information is used in the real world. At what points does a Club leader need this information? (I suspect the answer might be different for different sections.) If we can really understand when this information is useful to people, we can figure out the best mechanism for delivering it at the right time.

**Comment by amirad** [comment]
YES! Testing this page and how people gather/use it is part of the plan with our awesome Q2 club testers like @jgmac1106 ;)

**Comment by jgmac1106** [comment]
I am late with design and style (just got a Member's Only jacket and
started wearing Drakkar) and it seems the Web is moving into all the
content in an endless scroll and now appearing through animation or
something as you scroll.

If it wasn't for you folks I would still be styling webpages using html
tables.

**Comment by hannahkane** [comment]
My new life mission: figure out how to reference Drakkar in as many tickets
as possible. :)

**Comment by jgmac1106** [comment]
You get half the credit. It was a callback to your eighties request. I
think we found the new name for milestones.

**Comment by hannahkane** [comment]
Every milestone will be named after a prestige men's fragrance from the 80s? I accept the challenge.

**Comment by iamjessklein** [comment]
UX review: http://invis.io/SQ2HTH5CG
Note: the idea here is that it's a checklist like page with different steps that can be looked at individually. It will super clean in mobile view as well.

**Comment by hannahkane** [comment]
<3 this.

@amirad and @chrislarry33 - what do you think?

**Comment by iamjessklein** [comment]
I incorporated the feedback into the wireframes on [invision](http://invis.io/SQ2HTH5CG)

Any additional comments before we move into UI design?
cc/ @amirad @chrislarry33 @hannahkane @vazquez

**Comment by amirad** [comment]
Beauty. Looks great broken up.

**Comment by hannahkane** [comment]
+1, looks great!

**Comment by iamjessklein** [comment]
assigning to @vazquez for UI treatment

**Comment by vazquez** [comment]
UI Review @cassiemc http://invis.io/HR2IW8U98

I tried other more complex layouts, but the simpler approach ended up being better in terms of type organization and content clarity.

**Comment by cassiemc** [comment]
@vazquez Just one comment about the orange bar.

**Comment by vazquez** [comment]
Thanks @cassiemc, I addressed feedback. Design is finalized. @hannahkane, this page is ready to code up. :boom:

**Comment by hannahkane** [comment]
woohoo!
