### ISSUE TITLE
Build "Tips for Running Your Clubs" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#255]
Design is here: http://invis.io/HR2IW8U98

@vazquez - any assets to add?

**Comment by vazquez** [comment]
No assets to hand over (the line we have already).

The copy is available here: https://docs.google.com/document/d/1syswSeON-0o1svFz8F457uCncg8Kvx5IW8-2Xi3RBpw/edit?usp=sharing

**Comment by hannahkane** [comment]
@ScottDowne - can I assign this one to you?

**Comment by ScottDowne** [comment]
@vazquez What colour orange do we want for this? (I kinda like using off colours of the main pages for child pages)

**Comment by ScottDowne** [comment]
@vazquez I also need some colours on the expander bit.

**Comment by toolness** [comment]
By the way, we want to make sure the path for this page is at `/clubs-toolkit/`... or if it's not, we want to change our [email](https://github.com/mozilla/teach-api/blob/master/clubs/email.py) copy to mention the new URL, because it's the URL @iamjessklein specified in https://github.com/mozilla/teach-api/pull/8.

**Comment by iamjessklein** [comment]
@toolness I just checked the [sitemap](http://invis.io/9G2DK7SR2) and it's actually at /toolkit/ 
I will go ahead and make that adjustment.

**Comment by iamjessklein** [comment]
@toolness or @ScottDowne can you R? this PR https://github.com/mozilla/teach-api/pull/9

**Comment by ScottDowne** [comment]
I thought (and currently have) the url at "teach.mozilla.orb/clubs/toolkit"

**Comment by iamjessklein** [comment]
@scottdowne that's right - I originally had the wrong url in there.

**Comment by vazquez** [comment]
Colors! 

![screenshot 2015-03-27 09 33 38](https://cloud.githubusercontent.com/assets/1119821/6868751/8cce0dc8-d464-11e4-801b-fb1bb282622d.png)

**Comment by iamjessklein** [comment]
:rainbow:

**Comment by ScottDowne** [comment]
Merged, closing.
