### ISSUE TITLE
Design the footer for teach.mozilla.org

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#256]
A few things to consider here:

* Now that this is on mozilla.org - should we incorporate the mozilla.org footer?
* The current footer has Maker Party in it which needs to be removed
* The new footer should include Webmaker.org

**Comment by hannahkane** [comment]
Can we also change the copy in the Hive section? Should read, "Learn more about Hive Learning Networks"

Also, that font is a little hard to read. Different color? Slightly heavier?

**Comment by iamjessklein** [comment]
+1 - I am also going to design this mobile first.

**Comment by hannahkane** [comment]
Also - can we remove the Partners link from the footer? We will not have a partners page initially.

**Comment by OpenMatt** [comment]
https://dl.dropboxusercontent.com/spa/6c38yp3crbxni5b/3l9td6eb.png
* +1 to removing Maker Party. We do need to do that. 
* Also: feels like the logos should be less prominent. Right now, it feels like we're prominently pushing people other places. Instead of converting them on teach.
* If we use tabzilla (which we should, to make it feel like a true Mozilla web property), then we don't need the Mozilla logo / link in the footer
* That just leaves Hive. I'm a little unclear on why we're trying to cram a link to every Hive city into the footer -- feels complex.

**Comment by iamjessklein** [comment]
You guys were writing all of this while I was designing a bunch of these changes - and some I haven't designed. Take a look at my revised footer concept. If we do pull out any additional content, let me know. It feels like we could remove the Webmaker content that I added in. I also adjusted the background color to make the Hive logo stand out a bit more.

The concepts are in invision for [mobile](http://invis.io/RV2FVXNFP) and [desktop](http://invis.io/7X2FVXRN9):

![mobile portrait-footer](https://cloud.githubusercontent.com/assets/535012/6645565/f2306228-c993-11e4-947e-d5fdd0457bd2.png)


![desktop-footer](https://cloud.githubusercontent.com/assets/535012/6645566/f44150f4-c993-11e4-8cb7-e81e88605587.png)

**Comment by iamjessklein** [comment]
Update:

![desktop-footer](https://cloud.githubusercontent.com/assets/535012/6646031/823af092-c997-11e4-9797-89f4120740f2.png)
![mobile portrait-footer](https://cloud.githubusercontent.com/assets/535012/6646032/83e5d218-c997-11e4-8830-67252ded8baa.png)

**Comment by hannahkane** [comment]
I'm +1 on the later iteration. We do need to remove the Facebook and Partners links in the, uh, sidebar footer.

**Comment by iamjessklein** [comment]
@hannahkane what should *remain* in the sidebar footer?

**Comment by hannahkane** [comment]
These seem right to me: Webmaker, Donate, Legal, Privacy, Facebook, About

**Comment by iamjessklein** [comment]
I thought we were removing Facebook, no?

**Comment by hannahkane** [comment]
Dammit, I meant Twitter. 

So: Webmaker, Donate, Legal, Privacy, Twitter, About

**Comment by iamjessklein** [comment]
Updated:
![mobile portrait](https://cloud.githubusercontent.com/assets/535012/6671040/f10914c0-cbd8-11e4-8e69-02cd76dac45b.png)
![tablet 9 landscape](https://cloud.githubusercontent.com/assets/535012/6671041/f2490b42-cbd8-11e4-88f0-eebc36317580.png)

**Comment by hannahkane** [comment]
+1
