### ISSUE TITLE
Scope Web Lit Basics II module 

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#26]
## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier: 

## Deliverables

 - [ ] List of six (?) modules to write and test
 - [ ] Tickets for next steps

**Comment by LauraHilliger** [comment]
FWIW we have [this issue in the curriculum repo](https://github.com/mozilla/webmaker-curriculum/issues/97) that relates to this and has a good start on the conversation. I'm not sure if the conversation moved forward in a different forum while I was away, but maybe one of you can update the issue if so!

cc/ @dajbelshaw @thornet @ldecoursy

**Comment by dajbelshaw** [comment]
I think this is a tracking issue @LauraHilliger, but definitely worth pointing to the work done so far! :)

**Comment by dajbelshaw** [comment]
Just updating this to point to issue in this repo: https://github.com/MozillaFoundation/Mozilla-Learning/issues/91

This etherpad may be useful: https://teach.etherpad.mozilla.org/weblitbasics

**Comment by thornet** [comment]
The privacy module made by @smithisgeneric is the next best web literacy module for us to package and ship into clubs offer.  

* https://hivetoronto.makes.org/thimble/MTkxMTYxOTg0MA==/privacy-coach-activity-kit
* https://hivetoronto.makes.org/thimble/MTkyODM5NzA1Ng==/ip-address-tracer-activity-kit
* https://hivetoronto.makes.org/thimble/MTg3ODA2NTQwOA==/data-trail-timeline-activity-kit

Added to: 

http://mozilla.github.io/webmaker-curriculum/

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/16"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/16.
Please don't comment on it here.
