### ISSUE TITLE
Draft movement story template

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#260]
To be used when on-boarding R.C.s. Initial draft by Natalie: 

https://teach.etherpad.mozilla.org/clubs-story

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/86"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/86.
Please don't comment on it here.
