### ISSUE TITLE
QA on mobile

### ISSUE THREAD

**Issue by alicoding** [mozilla/teach.webmaker.org#261]
Recently I've tested the site on mobile and find that the site is not very responsive as it suppose to be.

It feels like it's being scale down to fit on mobile phone but all the text are too small including the icons and images.

CC @toolness @iamjessklein @vazquez @gesa 

just want to CC some people to help QA as well.

**Comment by alicoding** [comment]
![mozilla learning](https://cloud.githubusercontent.com/assets/4368149/6625721/2e8547a6-c8c8-11e4-859a-1f12ca5900ef.png)

**Comment by iamjessklein** [comment]
:+1:  I'm in. :hand:

**Comment by toolness** [comment]
Yeah, it's weird b/c when I first made the HTML for the page, I was using Firefox's mobile view (ctrl-shift-M on windows), which it looked nice and responsive on... But yeah, when using it on certain phones, it seems like Bootstrap's responsive classes aren't being triggered or something, which is odd.

**Comment by toolness** [comment]
For instance, on a desktop browser's "mobile development view" which sets the viewport width to about 320px:

![2015-03-17_17-49-22](https://cloud.githubusercontent.com/assets/124687/6698333/1e70c796-ccce-11e4-95bd-7f89bffe4a76.jpg)

**Comment by toolness** [comment]
Oh wait! I'm looking at the `index-static.jsx` and realizing that we don't have a [viewport meta tag](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag). I'll bust a PR with that in it, which should help things out a lot.

**Comment by iamjessklein** [comment]
is this qa on-going? should I do it today?

**Comment by gesa** [comment]
@iamjessklein I think this particular issue can be closed, because it was looking for a specific solution. A more general QA still needs to happen, but ideally once the devs stop mucking about in the codebase.

I'm guessing @hannahkane will schedule that maybe?

**Comment by iamjessklein** [comment]
:+1: thanks for clarification @gesa

**Comment by hannahkane** [comment]
will schedule! Thanks!
