### ISSUE TITLE
Port webmaker's ToS and PP

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#267]
Let's bring over the Terms of Service and Privacy Policy content from webmaker.org to the new site.

There are linked to from the bottom of the sidebar navigation (under "Legal" and "Privacy," respectively)

**Comment by hannahkane** [comment]
@iamjessklein @vazquez @toolness - do we need to design these pages first, or can we go straight to building them using the template page?

**Comment by iamjessklein** [comment]
I suspect that we use the template for the sake of the heartbeat. I would like to eventually design these pages in a more humane way - since this is a great teaching/learning touchpoint.

**Comment by hannahkane** [comment]
Thanks, @iamjessklein. Does this still need to go through design first, to apply the template styles?

**Comment by vazquez** [comment]
I can do the design for this.

**Comment by hannahkane** [comment]
Thanks for being the best, @vazquez. :)

**Comment by vazquez** [comment]
@hannahkane :relaxed:

TOS Design is ready: http://invis.io/X62FVGQDS

The copy is exactly the same. The only difference is the title. Should we still name it "Webmaker Terms" or can we name it "Mozilla Teach terms"

Starting on the Privacy Policy page.

**Comment by hannahkane** [comment]
Good call on changing the name! +1

**Comment by vazquez** [comment]
Privacy Design is ready: http://invis.io/H72FVORWN

**Comment by hannahkane** [comment]
+1

**Comment by iamjessklein** [comment]
:+1:  looking good @vazquez

**Comment by vazquez** [comment]
The design is finished, the build can begin.

cc @hannahkane

**Comment by hannahkane** [comment]
We're linking to Mozilla ToS and PP, so I'm closing this for now.
