### ISSUE TITLE
[MIGRATED] Gather and collate resources for Teach Like Mozilla module 

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#27]
## RACI

* Phase: Scoping
* Owner: @LauraHilliger 
* Decision Maker: @chrislarry33 
* Quality Verifier: @thornet

[edited by Laura]
##Collections
- [x] @jvallera collection
- [ ] @leahatplay
- [x] @smithisgeneric
- [ ] @kkeefe4
- [x] @amirad
- [ ] @Saallen 
- [ ] @LucyeoH 
- [ ] @omnignorant 
- [ ] @gmillener 
- [ ] @LindseyFrost 
- [ ] @SimonaRamkisson
- [x] @iamjessklein 
- [ ] @mcdermott415
- [ ] @Elsamozilla
- [ ] @thornet 
- [x] @kathrynmeisner (though, on your last day maybe this one doesn't happen!)
- [ ] @ldecoursy
[end edit]

## Deliverables

- [ ] Research and collation of resources for Teach like Mozilla. (curated, annotated folder): @LauraHilliger 
- [ ] Cluster into six modules to write and test: @LauraHilliger @thornet @chrislarry33 
- [ ] Tickets for next steps

**Comment by LauraHilliger** [comment]
Several possible modules and approaches:
1) revisions for content currently on Training. At the moment projects and activities are mostly contingent on the old Webmaker tools. 
2) how to be open (partner with SOO)
3) how to be a Mozillian (define the cultural differences b/w Mozilla & open. Collaborate with Emma and reps teams)
4) confidence in  teaching (I would think about general personal and professional development here, with the "teaching" bit as a lens and avenue for practicing newly developed perspective skills)

**Comment by dajbelshaw** [comment]
I'd also add that there's at least three different audiences:

* Those that already teach in **formal** settings and want to try out different pedagogies/styles
* Those that already teach in **informal** settings and want to up their game
* Those that have **no experience** of teaching at all

**Comment by thornet** [comment]
Possible later topic as well: 
"how to organize and mobilze learners start to learn to take action in their community"

**Comment by LauraHilliger** [comment]
Julia & Mouse just did Innovative Partner Professional Development: http://hivenyc.org/2015/02/18/ippd-training-doe-educators/

just storing a note I received from @thornet

**Comment by LauraHilliger** [comment]
@chrislarry33 - I started a google doc here:
https://docs.google.com/a/mozillafoundation.org/document/d/1quD8jfETB3_vuRc6IqWlbKAcn9bMcLGQOnpBiuH66Mw/edit

It is reflective of the conversation we had last week and begins to pull together resources for remixing content. Most is from Webmaker Training, but as I think about building out each module, I'll be looking through Hive archives ;)

**Comment by LauraHilliger** [comment]
tons of PD example agendas collected by @jvallera in https://github.com/MozillaHive/HiveCreate/issues/1

https://hive.etherpad.mozilla.org/JuliaGH

**Comment by LauraHilliger** [comment]
added this to my doc, but double adding here cause it's awesome @billmills http://mozillascience.github.io/instructorTraining/

**Comment by chrislarry33** [comment]
Thanks @LauraHilliger great start. I still think there is tons more to collect. Would like to map to heartbeat structure to do a similar capture to what we did with @jvallera I want it all in one place" agendas, blog posts, curriculum, best practices etc. Lets design an intake process and use a heartbeat to drive all team members to get us their stuff.

**Comment by jvallera** [comment]
Yes, love the training by Bill! and like the idea of gathering even more from across team. I am also interested in substantial ways to share out. I've am hoping to work @billmills training into a community call or future PD of some kind. Would love to do the same once we have curated more from across team. Other ideas for sharing with community aside from discourse/minigroup and other channels:
* Bi-monthly "Learn new curriculum with Hive NYC" hangout 
* 20 minutes of every community call designated to sharing/testing new content
* Curriculum Jam - twice a year for anyone, but directed toward classroom teachers

**Comment by LauraHilliger** [comment]
@chrislarry33 for intake, can we just repeat the process @jvallera guinea pigged? See:

https://teach.etherpad.mozilla.org/Collection

Then we could either file an issue & assign individual team members or you could email MozTeach w/ a deadline?

**Comment by chrislarry33** [comment]
Love the momentum here, makes me very happy.

WFM. I'd move Julia's example at top with the ask (and still leave at first completed version later). 

- Lets do a combo of a mozteach email and assigning tickets for the discreet work ala what we did with @jvallera 

- @LauraHilliger can draft email copy to send to team and share with me. Still debating better to come from me or you. I am leaning towards you, with a followup email from me to say this is important.

- Want to make sure its mapped to upcoming heartbeat and advertised as such to 1) better condition us to do direct ask task in a project managed and time boxed way 2) build accountability 3) Have better tracking and  publicity in the TPS process.

sound good?

**Comment by chrislarry33** [comment]
Also next step is a Discourse conversation aligned with this research, discovery and reflection. Put plan together for up coming heart beat, launch conversation in second for a start to finish date range of a month.

**Comment by LauraHilliger** [comment]
@chrislarry33  Draft copy: https://teach.etherpad.mozilla.org/CollectionDraft
Discourse thread: http://discourse.webmaker.org/t/what-have-you-made-for-teaching-in-the-last-3-years/1299

Please hack at will, happy to edit the discourse thread as well if you have suggestions.

**Comment by chrislarry33** [comment]
Looks good @LauraHilliger I made a few minor tweaks and edits in the email pad. Go ahead and send on Monday!

**Comment by thornet** [comment]
＼（＾▽＾）／ 
@LauraHilliger this is brilliant. great stuff!

**Comment by LauraHilliger** [comment]
@chrislarry33 - sending email, edited the description of this issue to include a checklist of folks on Mozteach team, probably easier than filing separate issues.

**Comment by iamjessklein** [comment]
Added my [etherpad](https://etherpad.mozilla.org/collections-jess) -it's  not exhaustive, but I have indicated to the best of my memory what I am not providing content on.

**Comment by BillMills** [comment]
>  I've am hoping to work @billmills training into a community call or future PD of some kind.

@jvallera cool! Let me know if I can help out there or answer any questions.

**Comment by jvallera** [comment]
@BillMills thanks! I really loved your kit and was wondering if you would introduce it/give background about it on an upcoming Hive NYC community call. Thinking June-ish. I will connect via email.

**Comment by BillMills** [comment]
@jvallera happy to - reach me at bill@mozillafoundation.org. I'm happy to find excuses to visit NY too, if a live meeting us useful; let me know.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/17"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/17.
Please don't comment on it here.
