### ISSUE TITLE
Add tabzilla to navigation

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#276]
Since this is a mozilla property it should probably have tabzilla incorporated. 

![screen_shot_2015-03-13_at_11_33_02_am](https://cloud.githubusercontent.com/assets/535012/6641564/e735b8ba-c974-11e4-8e84-cbea56a19e4b.png)

cc/ @vazquez @hannahkane @cassiemc @HPaulJohnson

**Comment by iamjessklein** [comment]
ping @toolness

**Comment by hannahkane** [comment]
Don't worry about mobile for v1

**Comment by gesa** [comment]
Okay ready to open a PR, but should note that we have two mozilla wordmarks at the top now:
![](http://snaps.akibraun.com/tyc32.png)

Also when we are ready to bring add this to mobile, this is a collision we are going to have:
![](http://snaps.akibraun.com/3kx6w.png)

**Comment by iamjessklein** [comment]
this relates to the convo going on over in #401
