### ISSUE TITLE
Add clubs-line-divider.svg to repo

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#279]
@vazquez :wink:

**Comment by vazquez** [comment]
Already done @mmmavis! :) I did it in #275

**Comment by mmmavis** [comment]
ahhh is it called `img/line-divider.svg` now?  I must have rebased something wrong heh :grimacing:

**Comment by vazquez** [comment]
It's called `line-divider.svg` yes! But now that you mention it, you are right: it should be called `clubs-line-divider.svg`
