### ISSUE TITLE
Scope MDN intermediate Module 

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#28]
## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier: 

## Deliverables
- [ ] clear scope for module
- [ ] assign person to support the development of the module

**Comment by thornet** [comment]
Meeting with MDN on March 27 to develop this.

**Comment by LauraHilliger** [comment]
MDN is leading this project. We're merely consulting so I'm going to ahead and close this. @thornet and I are #onit, and will reissue tickets when there are team specific tasks. 

Project wiki: https://wiki.mozilla.org/MDN/Projects/Content/MDN_Content_Kits

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/18"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/18.
Please don't comment on it here.
