### ISSUE TITLE
Develop and approve plan for Maker Party 2015

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#280]
Write a plan on outline for MP 2015 and what shape it will take.

**Comment by amirad** [comment]
Update to plan here: https://docs.google.com/a/mozilla.com/document/d/15VRGwqzBYqi-11It3SqEzyqmYHSNeXDR-CI6My4DELI/edit?usp=sharing

@HPaulJohnson to add additional marketing and sales information be EOD

**Comment by chrislarry33** [comment]
Looking great team! This makes a lot of sense. I think the frame and plan is ready to share and feels doalble/aligned. I do think the doc needs a few more passes to make sure its as tight as we need to tell the story of the plan. I added some comments. And many of Paul's comments need to be added/addressed. I say this in the doc, but cane we get @edrushka to take a stab at the "Sample Community Messaging" section? That basically tells the story of the plan in a compelling way and we need a level of polish there that would be close to what we'd want as web/email copy.

Awesome work, i like this a lot, way to thread a needle.

**Comment by ldecoursy** [comment]
@amirad Can we close this ticket since plan is approved? 

Re: https://github.com/MozillaFoundation/plan/issues/347

**Comment by amirad** [comment]
Yup, that we can do.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/87"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/87.
Please don't comment on it here.
