### ISSUE TITLE
Don't load google analytics script if the browser has DNT enabled

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#282]
It should be [pretty easy](https://github.com/toolness/lotl-site-prototype/blob/master/static/analytics.js#L1-L2) and it is neat for privacy.

What do you think, @adamlofting?

**Comment by adamlofting** [comment]
That's an interesting question, but I don't think it's something we need to do.

My understanding is that DNT is about tracking 3rd party cookies for things like advertising networks. Ie sharing data between/across disparate sites.

We don't put any PII into GA (as per GA T&Cs) and we don't allow our GA account data to be shared with any other orgs or 3rd parties.

My view is likely biased though, as I use that data to do my job. :wink: 

For those who dislike GA specifically, there is https://tools.google.com/dlpage/gaoptout

I vote 'not-needed', but am happy to hear more views on this.

**Comment by toolness** [comment]
Oh, ok, no worries, that makes sense! I will close the issue but if someone disagrees, they can re-open it.
