### ISSUE TITLE
404 on /img/clubs-line-divider.svg

### ISSUE THREAD

**Issue by alicoding** [mozilla/teach.webmaker.org#283]
@mmmavis or @vazquez I think you might have forgotten to include this on /clubs page

**Comment by vazquez** [comment]
I just pulled the latest code and it's 200

![screenshot 2015-03-16 10 58 47](https://cloud.githubusercontent.com/assets/1119821/6668786/85f2a92e-cbcb-11e4-991b-48b867125962.png)

**Comment by alicoding** [comment]
probably cache... thanks for verifying @vazquez !
