### ISSUE TITLE
Debrief with Q1 club testers

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#284]
- [ ] Implement #177 with @amirad @ldecoursy

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/88"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/88.
Please don't comment on it here.
