### ISSUE TITLE
[MIGRATED] 15 RCs are onboarded

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#286]
- [ ] Kick off call -- scheduled for May 5
- [ ] Regular comms (#19)
- [ ] Assigned clubs to support

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/90"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/90.
Please don't comment on it here.
