### ISSUE TITLE
[MIGRATED] Recruit Q2 testers

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#288]
Goal: 200 cities 

Path includes: 

- [ ] leverage partners
- [ ] recruit from Q1 testers
- [ ] RCs reach out
- [ ] staff leads
- [ ] marketing
- [ ] emerging Hives (@simona)

**Comment by thornet** [comment]
Next steps: 

* Prepare pipeline of partners & eager clubbers with @amirad @ldecoursy @simonaramkisson 
* Customize Q2 asks depending on recipient

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/91"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/91.
Please don't comment on it here.
