### ISSUE TITLE
Build "About" page for site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#289]
Design is in #99

**Comment by alicoding** [comment]
Referencing the design URL here: https://projects.invisionapp.com/share/3T2FDPIUV#/screens

The asset, once it's done can you paste it here for whomever going to work on this @vazquez ?

Just want to avoid the confusion of clicking and finding the assets and design and going through all the discussion :P

**Comment by vazquez** [comment]
Assets available here: https://dl.dropboxusercontent.com/u/43783651/Mozilla/About%20Assets.zip

**Comment by hannahkane** [comment]
@alicoding - thanks for adding the design URL. I'll try to do that in the future. :)

**Comment by vazquez** [comment]
Missing asset has been created. No more assets missing :)

https://dl.dropboxusercontent.com/u/43783651/Mozilla/About%20Assets.zip

**Comment by gesa** [comment]
For the record, it appears to me that the about page isn't linked to from anywhere on the site?

**Comment by alicoding** [comment]
Yeah I don't see it either... I don't even know if we have those links on the footer sidebar in the design at all?

**Comment by hannahkane** [comment]
See this ticket: https://github.com/mozilla/teach.webmaker.org/issues/296
