### ISSUE TITLE
[MIGRATED] Prepare analysis of Web Lit Basics I learner outcomes

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#29]
## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/19"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/19.
Please don't comment on it here.
