### ISSUE TITLE
Change instances of "Clubs" to "Mozilla Web Clubs" and "Web Clubs"

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#290]
Here are the instances I can find where the word "Clubs" appear, and my recommendations for what to change to:
 * Navigation: change "Clubs" to "Mozilla Web Clubs"
 * Clubs page header (text over the photo): "Mozilla Web Clubs"; keep button as is ("Add Your Club")
 * Clubs page "How do Clubs work?" section: "How do Web Clubs work?")
 * All other instances on Clubs page (i.e. "Connect with other Club leaders," "Tips for running your Club", "Add your Club to the map"): leave as is

**Comment by ldecoursy** [comment]
I think if you're already on the Mozilla Web Clubs page, it's probably fine to just refer to Clubs. That said, I think in some ways we want to be branding "Web Clubs" so the initiative doesn't seem too generic. "Web" is a modifier in that sense.

**Comment by hannahkane** [comment]
Per Lainie's comment: Changed my recommendation to make the "How do Clubs work?" section "How do Web Clubs work?". Still leaning towards the other instances being overkill, but willing to be persuaded. :)

**Comment by thornet** [comment]
+1 to the recommendations as currently written. Think it's good to use full name when introducing the concept and then moving to Web Club or Clubs in supporting text.

**Comment by hannahkane** [comment]
@chrislarry33 - are you good with this?

**Comment by chrislarry33** [comment]
ship it

**Comment by hannahkane** [comment]
@vazquez @toolness - are these small copy changes something a designer should do, or a developer?

**Comment by vazquez** [comment]
I can tackle those @hannahkane

**Comment by hannahkane** [comment]
Thanks, @vazquez!
