### ISSUE TITLE
Upgrade to React v0.13

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#294]
It was just released [a few days ago](https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html). I'm not concerned about the new features so much as ensuring that we continue to avoid deprecated APIs, ensuring that it's easy to keep up with React's bugfixes and such as it continues to mature.

It's probably best that I take this one on, as resolving this issue may involve modifying any part of the codebase.

**Comment by toolness** [comment]
Actually, I'd argue that this isn't crucial to `v1`-it's probably a good thing to do *after* we finish the milestone, since React v0.13 doesn't have any crucial features that we absolutely need for the milestone.

**Comment by hannahkane** [comment]
Grooming notes:
 * p1 
 * Effort: large (b/c involves upgrade of all react components)

**Comment by toolness** [comment]
Hey, good news! Effort here is actually **extra small (XS)** and raised way fewer issues than I thought it would. Still need to do some manual testing to make sure everything is actually OK, but after a bit of fixing in #692, was able to get all tests to pass without any warnings.
