### ISSUE TITLE
[Blog Post] The Web Journey

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#298]
Mashing up the Web Lit Map + https://github.com/MozillaFoundation/research/issues/2

Notes: 

* Open reflection
* Changes over time as technology, access and reality changes
* Never finished because behavior changes

w/ @LauraReynal 

Reading assignments:

* India report: https://webmaker-dist.s3.amazonaws.com/reports/india.pdf
* Learning pathways whitepaper: https://docs.google.com/a/mozillafoundation.org/document/d/1xqPW8phSQ_kaKXrMVKf8y1Ol2mc1OORasEp8YgJt5h4/edit

**Comment by thornet** [comment]
Moving this a heartbeat. 

Draft here: https://docs.google.com/a/mozillafoundation.org/document/d/1qzjUAsML3BmN5KvHDLFLwrzJX0n6GNDowz0E7a2ljqM/edit

Will send shortly to @iamjessklein @chrislarry33 @thisandagain for review.

**Comment by iamjessklein** [comment]
:heart_eyes: thanks @thornet

**Comment by thornet** [comment]
Adding @LauraHilliger since her Open Fluency doc is a great piece for the later parts of the journey: http://www.zythepsary.com/techie/open-fluency/

**Comment by jgmac1106** [comment]
Just went back and read the original ticket. The web journey flow chart is
really cool and agree @lauraHillinger leadership work fits well at the end.

**Comment by LauraHilliger** [comment]
added some comments, happy to think further / explain more on that "master" level if need be.

**Comment by thornet** [comment]
The post is ready to go. @LauraReynal is publishing it on blog.webmaker.org and we'll cross-post on our personal blogs. 

We should also queue up some posting continuing to discuss this idea.

**Comment by jgmac1106** [comment]
One thing to think about with cross posting is planet webmaker. You often
end up with the same post three times in the feed. Not sure how many people
use the RSS feed. I do.

**Comment by KevZawacki** [comment]
This looks awesome! Looking forward to seeing it published. & always happy to help with future blogs.

**Comment by LauraReynal** [comment]
Live here https://blog.webmaker.org/understanding-web-literacy-within-the-web-journey feel free to edit formatting or typos !

**Comment by thornet** [comment]
Yay!

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/92"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/92.
Please don't comment on it here.
