### ISSUE TITLE
[MIGRATED] Develop tool-related activity for Maker Party

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#30]
This is a placeholder ticket for now, as it's dependent on the Learning Product. The idea is to provide a piece of teaching content for Maker Party that makes good use of the new tool.

## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier: 

Deliverables:
- [ ] TBD

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/20"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/20.
Please don't comment on it here.
