### ISSUE TITLE
Modal Dialog - Ensure that modals have proper accessibility markup

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#301]
(Per discussion on https://github.com/mozilla/teach.webmaker.org/pull/269#issuecomment-81800754)

**Comment by toolness** [comment]
Helpful documentation on this: http://accessibility.oit.ncsu.edu/training/aria/modal-window/

Oy, maybe we should just use [react-bootstrap](http://react-bootstrap.github.io/) after all.
