### ISSUE TITLE
Design "Events Resources" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#305]
### Content

See https://docs.google.com/document/d/1yORrrsU4lN7itEC7BLTLHSR8JqRevppVPABxlmJqxXg/edit

Note: this is distinct from #35 which is about designing the Events landing page.

Will need to determine how a user arrives at the Events Resources page - e.g. from a link on the Events landing page? From an email they receive after adding their event to the database?

**Comment by vazquez** [comment]
The design can be found here: http://invis.io/AC2H7GAKJ

There are a couple of points to take note of:  
1. If you go to the Expanded state of of Event Details (http://invis.io/KY2H8L5UX), the copy on "Before Your Event" inundates the user. Are there points we can take out? At minimum, we should be breaking up this section into two sections for improved comprehension. It is much too long as it is.    
2. For the Logos & Assets section, is everything necessary to display? As an example, do we have metrics or other data to show that people use the Table Cloth asset? If not, we can remove it and make the page more lightweight.  
3. I will add an Index at the top of the page (similar to a Wiki) to give the user anchor links as well as a brief overview of what the page contains.  
4. I am favouring the tab bar treatment of Event Details, we just need the size of copy to go down in order for this approach to be possible: http://invis.io/KT2H8NKMF

**Comment by hannahkane** [comment]
Thanks for this, @vazquez. Great job presenting a huge amount of content!

1. Agree that this section is too long. One suggestion for breaking up the content into two pages: a) The Basics (venue, equipment, materials, gear, wifi) b) Before Your Event (map, recruit, promote, signup, schedule, press). @amirad - does that work for you?

2. Agree that cutting down the number of assets would be ideal. Do we need all three wallpapers? I defer to @amirad on this, though.

3. Index - w00t!

4. I also favor the tab bar treatment.

**Comment by amirad** [comment]
+1 to using an index and tab bar. 
Very open to breaking up the content into sections as I know the text is too long. We did something similar on the makerparty site. 
I'll comment in the design which assets we can kill.

**Comment by vazquez** [comment]
Design is ready for review @cassiemc http://invis.io/ZU2HJU6JR You can click and hover around.

**Comment by vazquez** [comment]
Ping @cassiemc for Review http://invis.io/ZU2HJU6JR

**Comment by cassiemc** [comment]
Left a review, look forward to seeing the next iteration @vazquez :)

**Comment by vazquez** [comment]
2nd round of UI Review @cassiemc http://invis.io/ZU2HJU6JR

**Comment by vazquez** [comment]
3rd round of UI Review @cassiemc http://invis.io/ZU2HJU6JR

**Comment by cassiemc** [comment]
@vazquez I left some more comments on a previous version that I think you haven't looked at yet?

**Comment by vazquez** [comment]
Got them! Thanks. 3rd round (again) of UI Review @cassiemc http://invis.io/ZU2HJU6JR

**Comment by cassiemc** [comment]
Ok, not far now @vazquez, just a couple things.

**Comment by vazquez** [comment]
Final review @cassiemc http://invis.io/ZU2HJU6JR

**Comment by cassiemc** [comment]
Still not totally convinced about the 'quick links' area but I don't want that to block this. So, we can iterate on that in the build if needed. R+

**Comment by vazquez** [comment]
Sounds good. @hannahkane, design is finalized. This page will take longer to build due to the added components that haven't built in other parts of the site yet.

**Comment by hannahkane** [comment]
Awesome. Thanks!
