### ISSUE TITLE
[MIGRATED] Rio: Prepare invite list & agenda for LAN house kick-off meeting

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#306]
We should do an in-person kickoff with all the participating LAN house owners.

Include Graci in agenda development and meeting.

**Comment by soapdog** [comment]
Agreed! :D Will talk to ITS and Mario so that we can set a date.

**Comment by soapdog** [comment]
Our initial desired LAN House set is:

* #1 - Marios LAN House - Abolição
* #4 - Jacsandi LAN House - Realengo
* #6 - Naigel LAN House - Santa Cruz
* #7 - Alessandro LAN House - Engenho Novo
* #9 - Marco LAN House - Colegio
* #10 - Otacilio & Loiane LAN House - Sepetiba

I've sent an email to Mario and Constance and we're starting to organize this meeting. It will require some back and forth until we find a date where everyone can meet. We must remember that these LAN Houses are very far away from each other and getting around in Rio is difficult. I will update this task as we move along.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/93"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/93.
Please don't comment on it here.
