### ISSUE TITLE
Clean up SVGs

### ISSUE THREAD

**Issue by gesa** [mozilla/teach.webmaker.org#310]
Whether manually or in some automated fashion, I noticed the SVGs in #309 could use some cleanup. This wasn't a blocker on that PR, but something we should think about in future iterations.

**Comment by hannahkane** [comment]
Is this still needed? @mmmavis @toolness ?

**Comment by mmmavis** [comment]
I believe similar issue got fixed in https://github.com/mozilla/teach.webmaker.org/pull/919.  Closingggggggg it now :dancers:

**Comment by toolness** [comment]
Somewhat related: as mentioned in https://github.com/mozilla/teach.webmaker.org/issues/946#issuecomment-110056894, we could use `gulp-imagemin` or a similar minifier to remove all the comments and extraneous stuff in the SVGs. Not sure if that is what Aki (gesa) meant by the SVGs needing cleanup or not.

**Comment by mmmavis** [comment]
> Not sure if that is what Aki (gesa) meant by the SVGs needing cleanup or not.

I assume it was related to [her comment](https://github.com/mozilla/teach.webmaker.org/pull/309#issuecomment-82631349) (though I could be wrong)
