### ISSUE TITLE
.glyphicon-menu-right obscures sidebar text on narrow sidebars

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#311]
I've noticed that when the sidebar is narrow, the `.glyphicon-menu-right` starts crowding into the sidebar text and overlapping it a bit:

![2015-03-18_9-17-39](https://cloud.githubusercontent.com/assets/124687/6709462/e3275b3c-cd4f-11e4-8c7c-82a02c4ca681.jpg)

What's particularly unfortunate is that this is actually how things look by default on an iPad in landscape orientation, as that viewport is just *barely* wide enough to trigger the sidebar CSS instead of collapsing the sidebar into a hamburger menu.

@vazquez, @gesa - any ideas on a quick fix for this one?

**Comment by gesa** [comment]
My solution is make 'em smaller, but maybe the designer should have a more nuanced look at it :smile_cat:

Assigning this to you, @vazquez, just to make sure you see it.

**Comment by toolness** [comment]
Hmm, I'm noticing now that the text also wraps below the icon too... not sure if it's a regression or just a very edgy edge case that always existed:

![2015-03-25_8-32-23](https://cloud.githubusercontent.com/assets/124687/6824540/82d93870-d2c9-11e4-92bc-2517c6f77e22.jpg)

**Comment by gesa** [comment]
I fixded it in #381!
![](http://snaps.akibraun.com/tvfhy.png)
