### ISSUE TITLE
[MIGRATED] Add Media release form to clubs tip page

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#313]
we need to have a quick blurb + link on media release forms for clubs aimed at youth. Meredith from Mouse suggested this form from the NYCDOE:

http://schools.nyc.gov/NR/rdonlyres/2E974D18-2CA2-445D-8A0F-8AAE9B4EF238/88120/consent_form_revised35.pdf

@amirad is it too late to add that to the Clubs tips content?

**Comment by amirad** [comment]
Hm not sure! @hannahkane thoughts?

**Comment by chrislarry33** [comment]
This would be great to have. Might not be ready for launch, shouldn't be a blocker. Basically has to involve Angela and legal. Can someone start an Ops bug on this? If/when we have it I agree it will be a key asset.

**Comment by hannahkane** [comment]
We can add it whenever it's ready.

**Comment by LauraHilliger** [comment]
Heya – found this from Hive Toronto: https://docs.google.com/a/zythepsary.com/document/d/1aO0rEdV5QpMGoRDFJupf3xRtEWO7ByM4x0h9615xXAk/edit

sounds like it was written by legal, so we might just do a slight remix. Closing https://github.com/MozillaFoundation/plan/issues/398 (please reopen if you think we need a new one for Clubs)

**Comment by ldecoursy** [comment]
Also @Saallen may have one from MozFest?

**Comment by Saallen** [comment]
This is the form I use for MozFest -https://drive.google.com/a/mozilla.com/file/d/0B_B9-Ny1xBaRYU4tYUZEUlNKUFU/view?usp=sharing

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/94"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/94.
Please don't comment on it here.
