### ISSUE TITLE
Update Learning Networks stories spreadsheet 

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#315]
Update the existing spreadsheet to capture stories for the learning networks team. 
Must include:
-Date
-Community Member
-Team member added the story
-Store/info
-Quotes
-Social info
-Pictures, video or links
****Potentially also include what makes a good story
****Potentially also include just a data dump of quotes, links and pictures

**Comment by amirad** [comment]
Created https://blog.webmaker.org/how-were-collecting-great-community-stories

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/95"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/95.
Please don't comment on it here.
