### ISSUE TITLE
[MIGRATED] What's happening in the Mozilla Learning team communities shareout

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#318]
Turn community stories pilot into blog post and email by April 15th.

**Comment by thornet** [comment]
Moving to a heatbeat milestone.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/97"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/97.
Please don't comment on it here.
