### ISSUE TITLE
[MIGRATED] Update Learning Networks calendar with Hive calls/events/meetups

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#319]
@Saallen can you share the calendar for Elsa/Simona to update. Also, we should identify other best places to put and share this calendar for people to see. Do we post a link somewhere? Tweet it out regularly?

**Comment by Saallen** [comment]
Hey, I have shared the calendar with @Elsamozilla and @simonaramkisson  and they now should be able to add their calls to the calendar. Happy to do a skype call and share screen to run through how to do this if there are issues. Can this calendar go on teach.mozilla.org @hannahkane ? As we will be adding more and more community events as we hear about them. 
In the meantime we can tweet about it.

**Comment by hannahkane** [comment]
Yes, we can link to the calendar from the site. What's the link?

We're currently linking to https://wiki.mozilla.org/MozillaWiki:Teach_the_Web_Talks on the "Teach Like Mozilla" page of the site. Should we instead link to this calendar?

**Comment by Saallen** [comment]
Is there space for both? 
If not, then I would think that TTW talks speak more to Teach like Mozilla.

**Comment by Saallen** [comment]
Hannah, I sent you the link via email. Here is the link to embed the calender on a website

<iframe src="https://www.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=zythepsary.com_q6ugl9iepetabcp9eg9ltmruic%40group.calendar.google.com&amp;color=%23853104&amp;ctz=Europe%2FLondon" style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe>

**Comment by hannahkane** [comment]
Sorry, I might be misunderstanding the purpose of the calendar. I thought the TTW talks would be on the calendar, and therefore there would be no reason to link to the TTW talks separately.

But if the calendar and the TTW wiki page are serving different purposes, we can certainly figure out the right place to link to each. To help me understand, can someone write a sentence-long description of the calendar - the type of thing we would put on the site to explain it to users?

**Comment by Saallen** [comment]
Just checking with @amirad on what is the best description around the calendar.

**Comment by amirad** [comment]
We can add the TTW talks to the calendar but I think the way TTW talks is currently featured is better.
 
The calendar is showing "where the community is and what they are up to" so is a nice add but doesn't need prominence on the site. Maybe just a link if it makes sense? Otherwise we can save it for social and other places.

**Comment by hannahkane** [comment]
Agree that TTW talks probably makes more sense as the event-related item to feature on the site. The full calendar feels a little insider-y, so might be a bit confusing or overwhelming to the broader audience we're hoping to appeal to with the website. I'd vote for using social media as the main channel for promoting the calendar.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/98"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/98.
Please don't comment on it here.
