### ISSUE TITLE
Clarify what it means to be "in" a city 

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#323]
* Driver @ldecoursy
* Decision Maker @chrislarry33 
* Consulted @hannahkane @amirad @thornet 

We broke our previous definition! Need to finalize this so we can better track and measure towards our goals. 

Here's a most recent take: 

Mozilla Learning Networks aims to provide value and impact to cities and communities around the globe. Our goal in 2015 is for sustained engagement in 500 cities. 
***What does it mean to be "active in a city?"***

* Web Clubs - facilitating clubs/programs that teach web and digital skills
* Hive - networked activity driving towards innovation, collaboration and the adoption of connected learning practices/principles
* Events - regular meet-ups/workshops/convenings, Maker Party, Hive Pop-Up 
* Groups - affinity groups aligned by location or interest area

Let me know thoughts on the above, or feel free to tweak here: https://teach.etherpad.mozilla.org/metrics

**Comment by OpenMatt** [comment]
cc @adamlofting : as I believe he was planning to help work on this following Program Review

**Comment by adamlofting** [comment]
Yes, this will join up with the other ticket filed here: https://github.com/MozillaFoundation/plan/issues/395

**Comment by ldecoursy** [comment]
Closing this ticket - now tracking at https://github.com/MozillaFoundation/plan/issues/395

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/99"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/99.
Please don't comment on it here.
