### ISSUE TITLE
Update icon links in both the club page and teach like mozilla page

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/teach.webmaker.org#324]
Both the pages, club and teach like mozilla have icons and the bottom that are links. Right now that links are "fixme"

I'm not sure where we want these to go yet, but they are as follows:

- teach like mozilla
  - listen
  - attend
  - say hello
- clubs
  - curriculum
  - connect
  - helpful tips

**Comment by hannahkane** [comment]
ah, good questions. :)

- teach like mozilla
 - listen: http://mzl.la/TTWpodcasts
 - attend: https://wiki.mozilla.org/MozillaWiki:Teach_the_Web_Talks
 - say hello: http://discourse.webmaker.org/category/meet
- Clubs
 - curriculum: the Clubs Curriculum page that @gesa is making in #42
 - connect: http://discourse.webmaker.org/category/meet
 - helpful tips: the Tips page that's currently in the design queue (#254)

**Comment by gesa** [comment]
Thanks @hannahkane!

qq: which email address does this link to? ![](http://snaps.akibraun.com/rs9ki.png)

**Comment by hannahkane** [comment]
Help@webmaker.org

**Comment by ScottDowne** [comment]
Because some of these pages don't exist yet, we should just leave this open and do it all then.

**Comment by ScottDowne** [comment]
Looks like the events page is also missing links in the bottom three link icons. @hannahkane

**Comment by hannahkane** [comment]
Good catch.
 * Event Resources should go to the page being built in #388. Assuming the url will be /events/resources
 * Join the Conversation should go to http://discourse.webmaker.org/category/maker-party
 * Add Your Event should go to https://events.webmaker.org/

**Comment by ScottDowne** [comment]
@hannahkane Looks like I need that links for bottom of the web lit page too (I may have missed it somewhere). Updating events page now.

**Comment by hannahkane** [comment]
Web Lit page links:
 * Contribute: https://wiki.mozilla.org/Webmaker/WebLiteracyMap
 * Learn More: https://mozilla.github.io/webmaker-whitepaper/
 * Get Reading: https://www.mozilla.org/en-US/about/manifesto/

[Please note: there's an error in the Get Reading copy. That should say "Web Literacy is core to the Mozilla mission and values", rather than "Webmaker is core..."]

**Comment by ScottDowne** [comment]
Should be live now, closing.
