### ISSUE TITLE
Do a (short-term) analysis of badges/assessment of work

### ISSUE THREAD

**Issue by k88hudson** [mozilla/teach.webmaker.org#326]
Tickets here:
https://github.com/mozilla/teach.webmaker.org/issues?q=is%3Aopen+is%3Aissue+label%3Abadges

My initial overview/assessment of short term work and constraints:
https://drive.google.com/a/mozilla.com/file/d/0B9Spnx3qAl7pclBXWXBoQUppV0E/view?usp=sharing

Action items
*  [ ] There are a few technical holes that need looking into described in the report, e.g. connecting applications and badge instances
* [ ] Most of the challenges here are front end and design. @simonwex to organize a meeting to discuss specific requirements with @ScottDowne, others?
* [ ] @hannahkane to add requirements about IA/integrating teach.webmaker.org and webmaker.org. What should/must be ported to the teach.webmaker.org? What can stay on webmaker.org?

**Comment by hannahkane** [comment]
Thanks, @k88hudson. This is the best.

Some questions:
 * What is the difference between the earner and the consumer of the badge?
 * Is the application data currently not stored at all, once the badge instance is issued? 
 
Some comments:
 * I think the location requirement might be bogus. It's related to our "500 active cities" KPI. But I don't believe we're planning to use "badges issued in a city" as a proxy for active cities. Will confirm.
 * the new site is actually going to be hosted at teach.MOZILLA.org. Ideally, all of these features will live there, though they might also live on webmaker.org if the learning product wants to use them. Is that crazypants?

Some comments/questions about credly, which I think we should explore as an option, that I'm hoping you can help answer:
 * Would we be able to fully integrate the entire end user workflow - from the application to the earned badge appearing on our user profiles? In other words, can we create an experience that doesn't require the user to leave our site? 
 * Is the applicant required to have a credly account?
 * Is credly l10n-able? Mobile-friendly? Do you happen to know if it meets our privacy standards?

**Comment by k88hudson** [comment]
> What is the difference between the earner and the consumer of the badge?

I *think* the consumer is the person viewing the badge (i.e. public), the earner is the person who earns the badge. So if you earned a Carrot badge, and I was looking at your Carrot badge, I would be the consumer and you would be the earner.

> Is the application data currently not stored at all, once the badge instance is issued?

It is stored, but marked "archived".

> the new site is actually going to be hosted at teach.MOZILLA.org. Ideally, all of these features will live there, though they might also live on webmaker.org if the learning product wants to use them. Is that crazypants?

I'm not sure it makes sense to rewrite the admin interface already on webmaker.org for issuing badges and approving them. Implementing a badges homepage, the individual display of badges, the application form, claim code form (i.e. things for end users) on teach.moz.org would be reasonable.

Credly-

> Would we be able to fully integrate the entire end user workflow - from the application to the earned badge appearing on our user profiles? In other words, can we create an experience that doesn't require the user to leave our site?

Short answer is yes; there is a [full featured API](https://developers.credly.com/api/credit) that support evidence, claim codes, etc.

> Is the applicant required to have a credly account?

Yes, but it looks like we could create them on behalf of users via an API through our own login system/UI.

> Is credly l10n-able?

> Mobile-friendly?

There is an iPhone app, although web/android options for mobile don't look too great. The display of badges (on our site, etc.) would be mobile as long as we implement it that way. I don't think localization is built into it. (badgekit-api does not support localization either)

> Do you happen to know if it meets our privacy standards?

I don't – I'm sure we could find out.

**Comment by hannahkane** [comment]
Feels acceptable to have admin UI on webmaker.org and some end user-facing UI on teach.mozilla.org.

@k88hudson - given what you know of the requirements, our tech, and credly, which do you think is less effort - rewriting some of our stuff, or moving to credly?

**Comment by k88hudson** [comment]
@hannahkane Mostly because of the reduced design requirements, my impression is that moving to credly is less effort, provided we look into it a little more thoroughly.

**Comment by hannahkane** [comment]
Thanks, @k88hudson. Wondering if anyone has a compelling non-technical reason *not* to use credly? 

/cc @simonwex @thisandagain @davidascher @chrislarry33

**Comment by thisandagain** [comment]
This is great progress. No blockers to using credly from my POV.

**Comment by davidascher** [comment]
re: credly:

- [ ] need to confirm that credly badges are OBI complaint, and (in
particular) that timing of their support for the 1.1 extension
- [ ] need to understand what user data would live on credly servers

**Comment by chrislarry33** [comment]
I am open to Credly, but also I think we need a proposal that goes to Ops here on why and how. There is some thought that needs to go into Mozilla using Credly over its own software given our role in the badge conversation over the last five years. This would also need to be considered as part of some storytelling about badges/Mozilla that is in the works. These aren't strictly engineering decisions. That said if that is also considered as part of this and we decide on Credly, that is fine with me and I see then upsides for sure.

**Comment by hannahkane** [comment]
According to their FAQ (https://credly.com/faq), they are OBI compliant. @simonwex - when you talk with them today, can you find out about the timing of their support for the 1.1 extension?

@k88hudson - perhaps you know the answer to the question about what user data would live on their servers?

I can get started on a proposal for Ops, but will likely need help on both the technical and storytelling parts.

**Comment by simonwex** [comment]
Just to confirm, I've got the 1.1 extension question as well as these topics to discuss with them:

* User privacy & security
* Bulk credential portability (avoiding lock-in)
* l10n plans
* pricing
* details on white-labeling
* authentication integration (using our login system)
* performance SLAs
* details for a vendor review/security audit

 Jonathan was unable to talk today. I've suggested some new times and will update when scheduled.

**Comment by chrislarry33** [comment]
thanks @hannahkane and @simonwex for the research and investigation here. Really appreciate it and think this could be a smart way forward.

**Comment by hannahkane** [comment]
Closing this. Next step: present the Credly option to Ops for discussion.
