### ISSUE TITLE
"Learn more" link on clubs page has wonky hover state

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#328]
The "learn more" link has weird interactivity:

<a href="https://toolness-media.herokuapp.com/v/learn-more-css-weirdness/play/loop"><img src="https://toolness-media.herokuapp.com/v/learn-more-css-weirdness.poster.play.jpg" alt="Play 'learn-more-css-weirdness' video"></a>

The cursor style isn't a pointer, even though it's a proper `<a>`, and it's weird that the underline goes away when hovered-over too.

@gesa can you take a look at this one?

**Comment by gesa** [comment]
I was having a conversation while opening the PR for this and I accidentally merged it without review. (I reverted, will open a new PR.)
