### ISSUE TITLE
Sort images directory

### ISSUE THREAD

**Issue by gesa** [mozilla/teach.webmaker.org#329]
It's freakin anarchy in there rn.

**Comment by ScottDowne** [comment]
Ideas?

I dunno why, but I put all the teach like mozilla images in it's own sub dir.

I thought it was a good idea at the time, maybe we could do it for other page assets to clean it up a bit more?

**Comment by gesa** [comment]
I created [this directory](https://github.com/mozilla/teach.webmaker.org/tree/develop/img/shared-iconography) while i was making the about page, putting any SVGs i thought would be shared in there. Then a directory for each page makes a ton of sense to me. Maybe adding a `photos` directory as well?
***
Thinking about those SVGs, they have a different color on every page. I would be happy to go in and add a class to control that with CSS, but does that work if the SVG is included as an `<img>` source?

**Comment by ScottDowne** [comment]
Yeah, I like that.

**Comment by hannahkane** [comment]
hey @mmmavis - will this be covered by #720 ?

**Comment by mmmavis** [comment]
I believe so and PR https://github.com/mozilla/teach.webmaker.org/pull/852 has been merged :bowtie:
