### ISSUE TITLE
Finalize Job Descriptions for RC's

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#33]
https://teach.etherpad.mozilla.org/clubroles

**Comment by Saallen** [comment]
https://teach.etherpad.mozilla.org/clubroles

**Comment by thornet** [comment]
@amirad would this be something you could lead?

**Comment by amirad** [comment]
Updated job descriptions here: https://teach.etherpad.mozilla.org/clubroles

**Comment by thornet** [comment]
Awesome! Closing this ticket.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/23"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/23.
Please don't comment on it here.
