### ISSUE TITLE
CSS fixes

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#337]
Reserving time for some clean-up!

- [x] Navigation Bar
- [x] Clubs Curriculum page
- [x] About page
- [ ] Footer
- [x] Web Literacy
- [ ] Map Popups

**Comment by hannahkane** [comment]
@vazquez - wondering if we can close this ticket, or is there more to do that's not covered in other tickets?

**Comment by vazquez** [comment]
We can close :)

**Comment by iamjessklein** [comment]
woot :+1: :postal_horn:
