### ISSUE TITLE
Build workflow for "learn more about clubs" flow

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#338]
The user submits their name, email address, and location via the modal form, and the system should fire off an email to Claw, Michelle, and Hannah with the user's information.

Design work was done here:
Form: http://invis.io/ZC2DQ2TPU
Form filled out: http://invis.io/Y22HK5WD9
Confirmation: http://invis.io/762HK6CZA

@vazquez to provide any necessary assets

**Comment by vazquez** [comment]
Envelope and Globe assets available here: https://www.dropbox.com/s/7h6s0v8sharvhwz/Assets.zip?dl=0

**Comment by toolness** [comment]
As mentioned in https://github.com/mozilla/teach.webmaker.org/issues/339#issuecomment-85321494, the email to claw/michelle/hannah should look like this:

```
Subject line: Someone is interested in Clubs!
Body: [First name] from [location] has expressed an interest in learning more about Clubs. You should email them at [email address]!
```

@hannahkane, if this is the wrong issue, let me know!

**Comment by hannahkane** [comment]
This is the right issue. Thanks!

**Comment by toolness** [comment]
Hey, I'm a bit confused about the status of this issue, b/c @iamjessklein told me that she removed the "Learn more" link from the mockups... Does it still need to be implemented?

FWIW it will take a decent amount of work to implement, as it requires changes to both the server and client. If it's functionally the equivalent of a `mailto:` link, I recommend just using that instead for v1--it's more accessible, too!

**Comment by iamjessklein** [comment]
:+1:  @toolness this convo is outdated in terms of thinking. If you take a look at issue #378 you can see that I removed that link and adjusted the layout so that the information is upleveled in the page hierarchy.

**Comment by toolness** [comment]
Hmm should we close this issue then?

**Comment by hannahkane** [comment]
I'm confused. @iamjessklein - do we no longer have the "learn more" workflow? I think it's still important.

**Comment by iamjessklein** [comment]
As per our conversation on IRC, I added [a new ticket issue](https://github.com/mozilla/teach.webmaker.org/issues/428) to work on the learn more about clubs call to action.
