### ISSUE TITLE
"Add Your Club" should trigger an email 

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#339]
Approved copy:

Subject line: Thanks for joining the global movement to teach the web!

[First Name], 
 
You did it! You put your city on the map and showed your dedication to increasing web literacy around the world. This is a big first step, so thank you for all that you are doing to teach the web. 
 
Whether you are a new club leader or an expert at running clubs, we recommend you get started by meeting others in our community. Join the conversation on our discussion forum [http://discourse.webmaker.org/category/clubs], or tell us what you’re teaching on Twitter using hashtag #teachtheweb. 

A member of our team will send you an email soon to see how you’re doing and make sure your club is on the road to success!
 
Michelle Thorne
on behalf of the Mozilla Learning team

p.s. Be sure to check out our tips for running clubs [link to page that will be built in #255]. They'll help you get support, find training opportunities, increase the impact of your club, and much more.

**Comment by toolness** [comment]
I've just added most of this functionality in https://github.com/mozilla/teach-api/commit/99f1c38a941364eceb8148b54a29c020508a511c. The one thing remaining to do is have it email Michelle/Claw/etc.  There's a few ways to do this.

One way is to actually integrate it into the admin backend UI, which will make it easy for the learning team folks to change the list of people who get sent the emails without having to block on us.

Another way is to just use an environment variable in the app config, which basically means that devs are the only people who can change the list.

**Comment by toolness** [comment]
Oh, also, we're only addressing the user by their Webmaker username at the moment, because that's all we have on them. Once we fully integrate with the new login system we should have their first name, assuming we collect that from them when they create an account.

**Comment by hannahkane** [comment]
@toolness - want to make sure I understand the choices. Are you talking about building in functionality so that we can easily change the list of ppl who receive the email? I hope we won't need to do that so often that it requires add'l functionality. Feels like unnecessary work at this point.

**Comment by toolness** [comment]
Ah ok, that makes sense. So I added support for this in https://github.com/mozilla/teach-api/commit/908334c2eccd203d8b5860bc93280ff85b97a29e.

2 things left though:
* Currently, the thing is set up to put the creator of the club *and* the teach staff (aka michelle/claw/etc) in the "To:" field of the email, which means that the creator of the club will be able to see the teach staff's email addresses and vice versa. I'm assuming this shouldn't be the case, but I wanted to make sure before changing the behavior.
* Should the teach staff actually get a verbatim copy of the email sent to the creator of the club, or should they receive some sort of email saying "Hey, user <username> created a club called "foo", you can see it in the admin UI at https://blahblahblah"? Obviously the former is easier but I can do the latter too.

**Comment by hannahkane** [comment]
Yeah, I don't think Michelle and Claw should be addressees in the email to the user. Would be good if they email they got said:

Subject line: A new Club has been added to the map
Body: [user name] has added their Club to the map.
[name of club]
[location]
[url]
[description]

You may want to email them to say hello! [user email address]

---
Is there a separate ticket for triggering a similar email to Michelle/Claw from the "I don't have a Club yet, but I'm interested" workflow?  That one should be like this:

Subject line: Someone is interested in Clubs!
Body: [First name] from [location] has expressed an interest in learning more about Clubs. You should email them at [email address]!

**Comment by toolness** [comment]
Ok, done in https://github.com/mozilla/teach-api/commit/d5b636744a4b844bfb6c68ad5ab61d40c136c255! I think that means we can close this ticket now...

**Comment by hannahkane** [comment]
winning!
