### ISSUE TITLE
Build "remove your club" workflow

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#341]
Design was done here:

Authenticated user with Club (sidebar): http://invis.io/YC2HKEHQD
Remove club: http://invis.io/6W2HKGLMV
Remove confirmation: http://invis.io/F92HKGSK5

Acceptance test:
 - Club should no longer be accessible in db

**Comment by toolness** [comment]
It should be noted that removing clubs is *functionally* working now, it's just done via a janky [`window.confirm()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) call rather than the slick modal that ricardo mocked up.
