### ISSUE TITLE
Consider writing test (or component?) generator

### ISSUE THREAD

**Issue by k88hudson** [mozilla/teach.webmaker.org#349]
@gvn suggested writing a yeoman generator, we could also consider just a plain node script depending on what's needed

**Comment by gvn** [comment]
Yeah I could probably just add an npm command really...

**Comment by gvn** [comment]
@k88hudson @toolness : Is this still needed? My PR just kinda sat there, so let's close if not...

**Comment by gvn** [comment]
Assuming this is good to close...re-open if not...
