### ISSUE TITLE
Design Events landing page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#35]
### RACI
* Phase: Design
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: 
* Dev Lead: NA
* Quality: @davidascher 

### Content

https://docs.google.com/document/d/1yORrrsU4lN7itEC7BLTLHSR8JqRevppVPABxlmJqxXg/edit

This ticket is for the landing page, as described in the doc above.

**Comment by vazquez** [comment]
This is where I got to today: http://invis.io/TY2GT8GBX

**Comment by hannahkane** [comment]
Thanks, @vazquez. Will leave comments shortly. 

/cc @amirad @thornet @ldecoursy @chrislarry33 for feedback by earlyish tomorrow, if possible. (Note: this is the Events landing page, there will be a separate /Events/Resources page with the rest of the content.)

**Comment by amirad** [comment]
Added a few comments. Is there a link to the resources page too? Or is that still being built?

**Comment by vazquez** [comment]
The events resources page is being treated as a separate issue, #305. It is in the process of being designed.

**Comment by amirad** [comment]
Ahh thanks @vazquez

**Comment by hannahkane** [comment]
@vazquez - what would you think about adding three CTAs to the bottom of this page, similar to the Clubs page and Teach Like Mozilla page - where there's a linked illustration and a brief bit of text for each, in three columns? 

The three CTAs could be the "sign up to learn more" that's already there + the link to the Resources page + "Add your event" (link to events.webmaker.org).

**Comment by vazquez** [comment]
No problem :) good because it's more consistent with other pages.

**Comment by vazquez** [comment]
I updated the design: http://invis.io/TY2GT8GBX

**Comment by amirad** [comment]
I like your picture choice @vazquez ;)

**Comment by hannahkane** [comment]
Looking good. I added one comment, but otherwise +1.

@chrislarry33 - can you give final approval?

**Comment by chrislarry33** [comment]
Love it, ship it
