### ISSUE TITLE
[Landing] Fix width of curriculum queue

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#355]
The formatting of this page is off: 

http://mozilla.github.io/webmaker-curriculum/

Would be great to tweak the width so the body doesn't expand so far to the page's edge.

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/32f48f368239cefe7f0c0ad661532db07aa13f56

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/100"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/100.
Please don't comment on it here.
