### ISSUE TITLE
Build "Teaching Activities" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#356]
* Design is here: https://redpen.io/jue07a72a4a77906e0
* Grid is here: https://cloud.githubusercontent.com/assets/1186326/6582335/08fc746e-c733-11e4-9708-1e582f1396a0.jpg
* Final assets are here, including all relevant svgs and image thumbnails, reg & 2x + the psd: https://www.dropbox.com/sh/q8gfn31yw3qjyfv/AABEIIbYU5E7m3D01_-YJpF_a?dl=0
* All of the links referenced on the page are here: https://teach.etherpad.mozilla.org/teachingactivitiespagecopy

**Comment by ScottDowne** [comment]
Merged, closing this.

**Comment by ScottDowne** [comment]
Merged
