### ISSUE TITLE
Design "Teaching Activities" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#36]
### RACI
* Phase: Design
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: @cassiemc 
* Dev Lead: NA
* Quality: @davidascher 

### Primary content - activities!
* The activities are being finalized in #81.

### Secondary content - web literacy
* Suggested headline copy: "What is Web Literacy?" 
* Suggested body copy:  "Mozilla defines web literacy as the skills and competencies needed for reading, writing and participating on the web. Learn more" [link to Web Literacy page (to be created)]

### Tertiary content - upsell Clubs
* Suggested headline copy: "Join the global web literacy movement" 
* Suggested body copy: "We invite you to adapt the Web Literacy curriculum to meet the needs of your group of learners. Add your local group to our global network, share any remixes you create, and help grow this movement." [link to Clubs]

**Comment by thornet** [comment]
FWIW, I quickly made this overview page of the curriculum we're producing, its audience, and its status: 

http://mozilla.github.io/webmaker-curriculum/

We can use this for internal purposes, including with our small group of club testers. Although might be informative as we think about how these resources show up on teach.wm.org

The page is hosted in this repo: https://github.com/mozilla/webmaker-curriculum

**Comment by hannahkane** [comment]
Thanks, @thornet. Is Web Literacy Basics II a thing, or did I just make that up? Maybe I meant the intermediate curriculum that we'll work on with MDN?

I think it could be useful to show some of the planned work on the Teaching Materials page, though I'd want to focus on the stuff that's ready to go, with just a small nod to what's coming up. Good discussion topic for this heartbeat's kickoff.

**Comment by cassiemc** [comment]
First iteration here: https://redpen.io/zrbe8092072240b490 Feedback @hannahkane @thornet?

**Comment by hannahkane** [comment]
Based on comments on this pad: https://etherpad.mozilla.org/teachsitequestions, I have the following suggestions:
 * Let's explicitly present the Web Literacy Basics curriculum as a sequence of activities designed to be done as a unit, in the context of Clubs. That might mean renaming the page (e.g. "Clubs Curriculum"), numbering the activities, removing the tags (which imply that the user should pick and choose, when really we want them to do each of the activities), and linking to this page *from* the Clubs page, as opposed to the other way around.
 * Let's create a different workflow for people who are just testing the waters and don't necessarily have an intention to start a Club. This "grab and go"-style page should have a small number of really easy-to-grok activities, as well as the high-quality content we have that falls outside of the Clubs curriculum (eg. Lo-fi, no-fi; Net Neutrality).

**Comment by hannahkane** [comment]
Note: I changed the title of this ticket to reflect the plan I outlined in the comment above.

**Comment by hannahkane** [comment]
Note: before we begin the build, we can populate the mock-up with six actual activities. Can be found here: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/index.html

**Comment by hannahkane** [comment]
As per conversation with @cassiemc, the page that's been designed works well for the "new" Teaching Materials page. We just need to replace the activities (currently Ping Kong and Kraken the Code) with the finalized activities from #81.

**Comment by cassiemc** [comment]
@hannahkane A few questions to finalize this design – 
* The links to the Hives portfolios. Should that be treated as a 'partners / endorsed' kind of area? Will that have content from people other than Hives? Or if Hive only, perhaps a little intro to describe where they are being directed? I think the flow could be a little confusing without that.
* There was suggestion in #81 that we link to Tools we like. Thoughts? Should that be reflected in this design?
* Sounds like we'd be launching with 11-15 finalized activities. I could see this growing enormously over time and addressing Laura's comment about how to involve community in the curation of this content. Maybe this means, for the moment, highlighting some kind of feature to get people to +1 or :heart: activity kits.
* Should this page have a filter?

Lastly, can you help update the title / description of this issue? Want to make sure I'm still addressing the right needs with this page!

**Comment by hannahkane** [comment]
Just spoke with @ldecoursy. We're aiming to finalize the content for this page by EOD Thursday. Content will include: final list of activities, a brief description of each, and an intro paragraph for the top of the page.

In the meantime, to answer your questions, @cassiemc:
 * I'll defer to @ldecoursy on this one - do you want to have a separate section linking to Hive portfolios? If so, can you write copy for an intro to that section?
 * Skipping the Tools section for v1, though I will bring it up again for a later iteration
 * Love the way you're thinking about community curation. The first iteration after we launch v1 will focus specifically on curriculum/activity features. I've scheduled a brainstorming meeting about that for next week. Will bring the +1 <3 idea to that meeting. I don't think we need it for v1, though, given we'll have no more than 15 activities to start.
 * Same thing with filtering. That will become important as we grow this page, but doesn't feel necessary for v1.

Will update the ticket title to reflect approved page name, which is "Teaching Activities." I think the description is still accurate, pending the possible addition of the Hive Portfolios section.

**Comment by hannahkane** [comment]
Final copy is here: https://teach.etherpad.mozilla.org/teachingactivitiespagecopy (as per #81)

**Comment by cassiemc** [comment]
Just a quick update here. I'm working on it this morning.

**Comment by cassiemc** [comment]
Here's the latest on redpen. Left a few questions for you there @hannahkane: https://redpen.io/jue07a72a4a77906e0

**Comment by hannahkane** [comment]
Awesome. Thanks, @cassiemc. Giving @chrislarry33 @ldecoursy @thornet today and tomorrow for feedback on redpen. I'll synthesize all decisions for you tomorrow, @cassiemc, so don't feel you need to iterate on comments in the meantime.

**Comment by cassiemc** [comment]
Also, design R? from @vazquez please!

**Comment by vazquez** [comment]
Left feedback!

**Comment by cassiemc** [comment]
Thanks @vazquez! Updated the design with the other content amends from claw, lainey, etc. Latest design here: https://redpen.io/jue07a72a4a77906e0 @hannahkane is this ready to close or do we need another round of content review?

**Comment by cassiemc** [comment]
Working on saving out assets now.

**Comment by hannahkane** [comment]
I think we're good to close. Nice work!

**Comment by cassiemc** [comment]
Great, final assets are here, including all relevant svgs and image thumbnails, reg & 2x + the psd: https://www.dropbox.com/sh/q8gfn31yw3qjyfv/AABEIIbYU5E7m3D01_-YJpF_a?dl=0

Here's the final design + 1 with a grid. Have uploaded a 'closed for comment' still on redpen.

![teaching-activites-v4-approved](https://cloud.githubusercontent.com/assets/1186326/6582331/0652edce-c733-11e4-9c12-fdde51ffcfa0.jpg)
![teaching-activites-v4-grid](https://cloud.githubusercontent.com/assets/1186326/6582335/08fc746e-c733-11e4-9708-1e582f1396a0.jpg)
