### ISSUE TITLE
Only one club in a given location is visible

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#360]
As mentioned in https://github.com/mozilla/teach.webmaker.org/pull/354#issuecomment-84063644:

> I'm now realizing that if people *only* enter the city/country of their club, we're potentially going to have lots of pins stacked on top of each other--for example, if there are two webmaker clubs in brooklyn, then their pins will both likely be located in the center of brooklyn, directly on top of each other. Which means we need to either have a single marker for multiple webmaker clubs (showing all clubs in the location in the marker's popup), or "fake" things by artifically spreading the clubs a few hundred feet away from each other, or something else.

I tried adding two clubs with the same location name, "Mumbai", in the site and this is indeed the case. The clustering plugin does "cluster" them for as long as it can, which at least shows people that there are 2 clubs there, but once the user is maximally zoomed-in to the map, it only shows one of the markers.

**Comment by hannahkane** [comment]
d'oh! this feels like a bit of a dealbreaker. Is the artificially distancing the clubs from one another idea a real possibility? other sites must have encountered this problem before, right? I wonder how others have solved it.

**Comment by rossbruniges** [comment]
So to me there are a few problems to solve with this ticket.

The first one is what the map is there to show? Is it accuracy (viewing the
map shows where things are accurately happening) or volume (there are x
number of things happening in city y).

If it's the later then clustering (and restricting zoom levels to stop at a
point where it starts getting inaccurate) is an option. If not then you
need to require more information up front so you're able to plot it to a
more specific point.

Im sue both these things have been considered but when we tackled the
problem for webmaker v1.0 we went with the more details upfront option
(with the lat/lngs obtained through Google APIs) and it works pretty well...

**Comment by hannahkane** [comment]
I think the map is there to a) show volume, but we also need to b) help ppl find activity near them. What if we use the map for a, and whatever design solution we come up with in #245 for b?

**Comment by alicoding** [comment]
I've thought about this as well and was wondering maybe we should use Google location autocomplete for pinning markers on the map to prevent this kind of problem. It is actually a one input field for that which doesn't add any addition steps to add the club, and I think the UX is really obvious for adding the location here. The advantage for this will also help us get the exact coordinate for each markers for each clubs we have.

**Comment by toolness** [comment]
> The advantage for this will also help us get the exact coordinate for each markers for each clubs we have.

Are you implying that people enter the exact street address for their club, rather than just the city? My guess is that even with the autocomplete (#353), two Webmaker clubs in Brooklyn will still likely both submit "Brooklyn, NY, United States" rather than anything more specific, as these clubs probably won't have a dedicated street address or anything.

**Comment by alicoding** [comment]
Given Google Map Autocomplete allow user to enter full address I guess it will solve problem for users who would like to have their pin display at the exact location assuming they want people to be able to locate the club. For those who didn't put the full address and if we have more than one from the same city then yeah I don't know if we can do anything much except manually move them ourselrves to make it all visible.

**Comment by toolness** [comment]
O hi @rossbruniges!
