### ISSUE TITLE
Additional Analytics Instrumentation

### ISSUE THREAD

**Issue by adamlofting** [mozilla/teach.webmaker.org#362]
Now that the site build has progressed, there are further user interactions we want to count / measure in Google Analytics. This ticket is to review the site, list those interactions, and add the additional GA tracking code we require.

**Comment by toolness** [comment]
Oh!

So currently, modals don't actually trigger a change in URL (which I actually have issues with, but it'll have to wait until v2 to be addressed). We could have some tracking occur when users activate any of those modals, which currently includes:

* When a user adds, deletes, or changes a club.
* When a user clicks the "learn more" link on the clubs page and fills out the form. (and we should track if they submit it too I guess?)

There are also a variety of things we could track about how the user uses the map widget itself, though I'm not sure what the best ones to track would be.

**Comment by adamlofting** [comment]
- [ ] Start Log-in
- [ ] Complete Log-in
- [ ] Log-out
- [ ] Start Create an account (this might not be wired up yet)
- Clubs
  - [ ] Add
  - [ ] Delete
  - [ ] Edit
- [ ] Complete adding a club
- [ ] Validation errors on clubs modal
- [ ] 'Learn more' form interactions

**Comment by adamlofting** [comment]
Thanks @toolness - I'll have a look at the code now but I think we will be able to fire the GA events in JS without the need for new pageviews 

Also. I hadn't realised that that 'Learn more' link was a sign-up/register CTA. I just thought it was a link to another content page. I'll file a bug for @hannahkane and others to talk about that, if it's something we want people to do.

**Comment by toolness** [comment]
Heh, same here re: the "learn more" link :)

Regarding hooking the code up to this, I'm thinking that a lot of this can be done by attaching event listeners to our `TeachAPI` instance, which emits a bunch of different kinds of events when stuff changes... I guess I'd like to help figure out a solution that doesn't break our unit tests, though I suppose such a thing could be accomplished by just stubbing out the entire `lib/googleanalytics.js` during test runs.

**Comment by toolness** [comment]
Hmm, so one thing I've been thinking about lately is that it'd be great to be able to track, at the very least, the rate at which JavaScript errors are occurring on the page, if not more detailed feedback like stack traces and such.

I believe that New Relic does this, but my understanding from @jdotpz is that MoFo is no longer paying for that... In lieu of that, @adamlofting do you think that some very basic error metrics could be recorded via GA, or should we use something else for that?

**Comment by adamlofting** [comment]
Let me know if that PR works for you. It covers all the interactions I was hoping to track right now, but I'm very happy if you prefer it coded another way. 

`npm test` ran successfully against that, but let me know what else we could do to make this work better with the test suite.

And... JS errors is an interesting one. Where we catch an error and handle it in code, we can push that to GA [like this example](https://github.com/mozilla/teach.webmaker.org/pull/373/files#diff-d367edcb1a8dfe23b8cd1155e8eda445R62) in this current PR.

But to track all JS errors isn't such a natural fit for GA.
