### ISSUE TITLE
'Add your club link' somewhere next to the map?

### ISSUE THREAD

**Issue by adamlofting** [mozilla/teach.webmaker.org#363]
An idea: When looking at the map, it would be nice to have a small link or button to 'Add your club' right above or below it, mainly to indicate that it's possible for users to contribute. 

![screen shot 2015-03-23 at 11 02 46](https://cloud.githubusercontent.com/assets/1901816/6778643/51c24b9c-d14c-11e4-8228-6d5302a69ba8.png)

**Comment by hannahkane** [comment]
Thanks for the idea! I have a feeling you're right that it will be needed for usability purposes. Given the # of tickets to get through to launch our v1, I'm going to call this a p2 for now, though. It may become urgent if the "add your club to the map" task fails in usability testing right after launch.

**Comment by hannahkane** [comment]
Closing, as this will be covered in an upcoming re-design of the Clubs page.
