### ISSUE TITLE
Promotion of 'Learn More' Call to Action

### ISSUE THREAD

**Issue by adamlofting** [mozilla/teach.webmaker.org#365]
Sorry if this is already being designed/discussed elsewhere, I just wanted to file while it was front of mind.

We have a 'Learn More' workflow, where a user can fill out a simple form to get in touch with us. This feels to me like an important high value action. But I only found the form on the site by accident.

I thought this 'find out more about us' was going to link to a content page on the site.

![screen shot 2015-03-23 at 11 30 26](https://cloud.githubusercontent.com/assets/1901816/6779084/4817cd84-d150-11e4-86b0-52acd28354cc.png)

I think we could use some more explicit language here (not !%$!$% :wink: ) but something like: get in touch / tell me more / register your interest / talk to us / etc - something that implies engagement rather than reading content.

And, I think this CTA should appear much more prominently throughout the experience if it is valuable to us.

**Comment by hannahkane** [comment]
You're right that the copy is misleading. I'm thinking language like "Not ready to start a Club just yet? Talk to us!" could be better. And if that's the case, we probably need to remove it from the header image. Maybe it goes down at the bottom of the page where the second "Add your Club" CTA currently is, and we move that CTA up to right under the map? (also addressing #363).

@vazquez, @iamjessklein  - thoughts?

Thinking I will add this workflow to the usability test plan as well.

**Comment by iamjessklein** [comment]
Good catch. It feels like the secondary CTA in the header should be dropped.

**Comment by hannahkane** [comment]
Closing this, in lieu of #428.
