### ISSUE TITLE
Revise ordering of items in Navigation

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#369]
The navigation should read (from top to bottom) as: 
* Clubs
* Teach Like Mozilla
* Teaching Activities
* Events

cc/ @hannahkane @toolness @ldecoursy @vazquez

**Comment by hannahkane** [comment]
Did we agree on this? I thought this was still under discussion. I have a slight preference for going in order or increasing intensity of involvement (Teaching Activities, Events, Teach Like Mozilla, Clubs).

**Comment by iamjessklein** [comment]
Ah based on the email thread I thought that it was agreed upon. If not, lets resolve it in this issue.

**Comment by hannahkane** [comment]
OK, as per email thread (sorry!), let's keep it as is for now. I imagine the nav items will evolve as we add more content, get real users on the site, etc.
