### ISSUE TITLE
Design "Teach Like Mozilla" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#37]
### RACI
* Phase: Design
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: 
* Dev Lead: NA
* Quality: @davidascher 

Refining the content and copy here: http://mzl.la/18QNAn8 

Note: in Q2 we'll develop the "Teach Like Mozilla" curriculum modules. Once those are ready, those will be the primary content on this page.

**Comment by hannahkane** [comment]
cc @thornet @LucyeoH @amirad @Saallen @ldecoursy @chrislarry33 to confirm that this is the correct content/hierarchy for April 1, and to provide the most relevant Discourse threads to embed.

**Comment by chrislarry33** [comment]
Is there a ticket or documentation on the seamless integration of Discourse?

**Comment by chrislarry33** [comment]
How about links/copy about our various community calls?

**Comment by hannahkane** [comment]
Good thought. Added community calls to the description. Feel free to edit the description directly - not sure the hierarchy is right. 

Re: Discourse—wasn't imagining seamless integration would happen for April 1st, though that's on the roadmap for later. For now, was just wanting to embed some threads, if possible. And, if not, just link to Discourse.

**Comment by chrislarry33** [comment]
I think we need this somewhere:

    Why we teach: We are dedicated to empowering others with web literacy so that they have agency on the web as creators, citizens and future leaders. 

    How we teach: Teaching and learning is how we achieve our mission. They are political as well as self-actualizing acts. We teach and learn by making projects together and openly reflecting on the process in an inclusive and locally relevant environment. Learning is social, production-centered, and open-ended. It is done best when facilitated in small groups meeting in-person.

    Who we teach: We teach our peers, so that we can reflect and improve together. We teach our local community, so we can give back and make a different locally. 

    What we teach: We teach web literacy, which encompasses the mechanics, culture and citizenship of the web. Our learners are more self-actualized as creators when they can use the web as a platform for creativity. They are better citizens when they can make more informed choices on the web. And they are economically more empowered with skills and practical knowledge of this public resources. 

    Where we teach: We teach locally, wherever we have our learners, be that in formal classrooms, to libraries and coffee shops and kitchen tables. We learn globally, as we connect with peers who inspire and mentor us to make local change that has a global impact.

**Comment by hannahkane** [comment]
That strikes me as the kind of content that would go on an About page. We could build one and link to it from the footer. Does that sound right, or do you want it to be on the "TLM" page?

**Comment by thornet** [comment]
We might want to include a condensed version in "Teach Like Mozilla", since it's our value proposition. Why teach like us if we don't say what that means? etc. 

@hannahkane how much space do you think would be available and make sense for an appropriate summary from that longer content?

**Comment by hannahkane** [comment]
Good point that the TLM page needs an easy-to-grok definition of what it means to teach like us. The Why/How/Who/What/Where feels pretty long for web copy, though. Wondering if we can come up with  headline length copy for the TLM page itself (something like "We teach and learn by making projects together and openly reflecting on the process"), and link to a separate page for people who want to know more. Similar to what we're doing with the Web Lit page (linked to from the Curriculum page).

**Comment by dajbelshaw** [comment]
There's some stuff we could repurpose / riff off from the [Why Mozilla cares about Web Literacy](https://mozilla.github.io/webmaker-whitepaper/) whitepaper - for example:

> Mozilla’s work is underpinned by a philosophy that we learn best through doing and making. While our thinking is influenced and informed by the works of academics in related fields, we’re interested in practical action. We're focused on helping people become more sophisticated in writing the web, participating in communities that explore web literacy and become advocates for the value and need for an open web.

...and:

> We understand ‘webmakers’ to be those participating in the culture of building the social and technical elements required for an open web. At the same time, we use ‘Webmaker’ to refer to the Mozilla website as well as the community that has mobilized in alignment with it. We recognize that there are also an array of webmaker practices which occur with and without Mozilla. Therefore, webmakers may complete various activities, including building content for the web through remix or coding, participating in discussions online, or teaching web literacy skills in their local communities.

**Comment by hannahkane** [comment]
Updated the ticket description with headline-style copy to get us started. Will file a separate ticket for an About page that can be more verbose.

**Comment by thornet** [comment]
Love it! 

Slight edit suggestion for the headline: "We learn best by making and reflecting -- together."

**Comment by hannahkane** [comment]
Thanks for the edit, @thornet. Updated!

**Comment by cassiemc** [comment]
@iamjessklein can you start this ticket off with some (can be loose) high level wireframes?

**Comment by iamjessklein** [comment]
yes will do :+1:

**Comment by iamjessklein** [comment]
@hannahkane @thornet  - can you clarify where I should find the most up to date content for the first iteration of this page?

**Comment by iamjessklein** [comment]
Also, on first look at this comment, it feels like a missed opportunity to have the primary call to action direct the site visitor off this page.

**Comment by hannahkane** [comment]
Hey @iamjessklein, the first comment is updated with the latest thinking on content. 

Good point that it's weird to direct the visitor off the page. :) Discourse is the primary tool we have right now for people to learn how to "Teach Like Mozilla." Ideally, we'd do a full Discourse integration that doesn't require the user to leave the site, but I'm not clear on whether that's possible within the time constraints, so I didn't make it a blocker to launch.

We're planning to have the Teach Like Mozilla curriculum shipped in mid to late April, so there will be an update to this page after that.

**Comment by iamjessklein** [comment]
I guess if that's not possible with this heartbeat, I would also de-prioritize this page (possibly ship without it?) It seems strange to have a page that just redirects to another page. Unless we were to prioritize the secondary content.  

Where can I find this content:
*  TTW talks- Titles, descriptions, and links to recorded TTW talks - Date/time/link to upcoming TTW talks
* Community Calls -  For each: Topic, day/time, etherpad

cc/ @toolness @hannahkane

**Comment by hannahkane** [comment]
cc @LucyeoH to provide TTW / Community calls content

@iamjessklein, I think the links to Discourse, the TTW talks, and the community calls are valuable, so I think it's worth having them at launch. (Also, keep in mind that the "launch" is not a particularly broad launch; we'll likely just be promoting this to the Club leaders and other highly-engaged folks.)

**Comment by iamjessklein** [comment]
Oh, sorry, it LINKS to discourse (vs. embeds) - yes, that's doable.

**Comment by hannahkane** [comment]
Just discussed with @LucyeoH and @iamjessklein: started a doc (http://mzl.la/18QNAn8) to collaborate on page content and copy. Agreed to include philosophical POV content from Claw's comment above, though we may cut it down or figure out a way to present it visually, so as not to overwhelm with a wall of text.

Lucy to finalize the CTAs in that doc.

**Comment by iamjessklein** [comment]
I am going to move forward with the design now - and will have something to review soon.

**Comment by iamjessklein** [comment]
I took a first stab which you can [find and comment on invision](https://projects.invisionapp.com/d/main#/console/2977378/66501215/preview), as you can see - the mockup is copy heavy.

![mockup](https://cloud.githubusercontent.com/assets/535012/6510780/290bb18a-c336-11e4-8f75-386997b79beb.png)

**Comment by hannahkane** [comment]
cc @chrislarry33 @thornet @ldecoursy @LucyeoH @Saallen - let's aim to finalize all of our feedback for @iamjessklein by EOD today.

**Comment by iamjessklein** [comment]
Note: you might need to set up an account to leave feedback in invision (we are testing this vs. redpen for this heartbeat) [Here is the link to the invision mockup] (http://invis.io/2J2DHDBYE)

**Comment by thornet** [comment]
Looks great to me!

**Comment by iamjessklein** [comment]
Update: Take a look @hannahkane @thornet @ldecoursy I revised the mockup to reflect the copy changes per the most recent ticket. Take a look at [the invision mockup](http://invis.io/2J2DHDBYE)

![mockup](https://cloud.githubusercontent.com/assets/535012/6577272/fd7cfaac-c712-11e4-98cb-615fdc311a4c.png)

**Comment by vazquez** [comment]
UI Design here: https://projects.invisionapp.com/d/main#/console/2977378/67226158/preview

cc @hannahkane @chrislarry33 @thornet @ldecoursy

**Comment by hannahkane** [comment]
Looking good, @vazquez. Left a couple questions in invision.

**Comment by vazquez** [comment]
Questions answered in InVision @hannahkane :shipit:

**Comment by iamjessklein** [comment]
all that's left to do is change out the image.

**Comment by vazquez** [comment]
Image has been changed. Looking for a final review by @hannahkane to close issue.

http://invis.io/YB2EPJQUF

**Comment by iamjessklein** [comment]
Has anyone on the teach team seen this image? cc/ @ldecoursy @chrislarry33 @thornet 
My only concern with this image is that there is text that's not localizable - ie: english words appear.

**Comment by ldecoursy** [comment]
It works for me - or I've seen other images where many people seem engaged with post-it action.

Maybe here: https://www.flickr.com/photos/newyouthcity/sets/72157643074122585/ or here: https://www.flickr.com/photos/newyouthcity/sets/72157648900371526/

Also Sprout Fund has good pics from Open Badge Summit last year -would need permission  https://www.flickr.com/photos/sproutfund/sets/72157641857133854/

**Comment by hannahkane** [comment]
@chrislarry33 and I just chatted - we're good with the Gunner photo. The post-it notes convey that there are a multitude of ideas going on, which is good in any language!

I'm calling this ready for implementation. Thanks, all!
