### ISSUE TITLE
Adjust the placement and copy for Login/ Join buttons

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#371]
* The login/ join should be integrated into the navigation more.
* The Join button currently say "Join Webmaker" but it should be revised to "Join Mozilla Teach" 

On the second item, as @hannahkane pointed out " Join Mozilla Teach" doesn't sound quite right - could use some copy suggestion here. 
cc/ @ldecoursy @vazquez 

![screen shot 2015-03-23 at 10 23 29 am](https://cloud.githubusercontent.com/assets/535012/6781799/add6508c-d146-11e4-96f5-6bbeb577f7ba.png)

**Comment by ldecoursy** [comment]
We're not locked on "Mozilla Teach." Perhaps "Join Mozilla Learning Networks"

@chrislarry33 @HPaulJohnson

**Comment by iamjessklein** [comment]
This relates to #243

**Comment by hannahkane** [comment]
Can we just say "Join"?

And "Sign in" probably needs to say "Sign in with your Webmaker account" to prevent surprises.

**Comment by hannahkane** [comment]
once we get this mocked up, can we add it to https://github.com/mozilla/id.webmaker.org/issues/68?

**Comment by iamjessklein** [comment]
@cassiemc mocked this up. You can see the design in her [redpen](https://redpen.io/vy733a8b80210605bd)

![screen shot 2015-03-26 at 9 40 12 pm](https://cloud.githubusercontent.com/assets/535012/6860627/d468a18e-d400-11e4-891b-a23aa676405d.png)
