### ISSUE TITLE
Finalize Clubs Partner Pipeline 

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#372]
Develop the next stage of the partner pipeline (include responsible and consulted). Fill in next steps for each partner and have an idea of partner standing. 
https://docs.google.com/a/mozilla.com/spreadsheets/d/1nl3N52qff2o4rrOv2HSAcRvGCrlhqub0yz1DtzA3T9Y/edit?usp=sharing

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/101"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/101.
Please don't comment on it here.
