### ISSUE TITLE
Scroll focus moves from page to map as user scrolls down page

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#375]
On desktop/laptop systems, my mousewheel scrolling starts out scrolling the page, but as soon as the cursor is above the map, my mousewheel starts zooming-out the map instead of scrolling the page down.

Here it is in action:

<a href="https://toolness-media.herokuapp.com/v/teach-site-map-scroll-focus/play/loop"><img src="https://toolness-media.herokuapp.com/v/teach-site-map-scroll-focus.poster.play.jpg" alt="Play 'teach-site-map-scroll-focus' video"></a>

There are some UX solutions we can try out to make this less frustrating, but I wanted to document it here.

**Comment by hannahkane** [comment]
The more I use this page, the more of a blocker this seems, so I'm labeling this v1 and putting it into the current milestone. 

Per @iamjessklein, one possible solution is to make the map zooming require a click first.

**Comment by iamjessklein** [comment]
+1 it's presently challenging - although not impossible - to get to the core content.

**Comment by iamjessklein** [comment]
This issue is now being worked on in #387 and we should comment on the fix there.
