### ISSUE TITLE
Add a few lines of context to the top of the Teach page

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#378]
It doesn't feel clear to me what clubs are when you land on the Teach page  because the content is buried a bit deep. If you are new to the site you need to learn what Mozilla clubs are and if you familiar with our work you need to learn how Clubs differ from Hives. 

@ldecoursy @amirad could you provide some copy here? 2-3 sentences tops.

![screen_shot_2015-03-23_at_5_42_33_pm](https://cloud.githubusercontent.com/assets/535012/6791305/656fb458-d184-11e4-9fe4-ad2fc0f57a37.png)

**Comment by ldecoursy** [comment]
I'd just suggest flipping the map with How to Web Clubs Work? Also I found it hard to scroll the page with the map right there (ended up zooming in/out of the map).

**Comment by hannahkane** [comment]
1) I think we tried flipping the map and the "How Do Web Clubs Work?" list in an earlier iteration, and decided it looked weird. 

I think I understand the issue you're raising, Jess, but I'm not sure the solution is more blocks of text. I worry people won't read them. :( 

I think the map is actually one of the best ways to convey what a Club is - it shows that they are local entities, which seems like the key piece of information for people to grok. The other definitional point I might want to convey is that they are sustained (to distinguish from one-time Events), but I think the word "Clubs" strongly suggests that already.

In terms of telegraphing the difference between Hives and Clubs, I'm not sure this page needs to do that work. The people who know about Hives are a relatively defined set of people, a group that we can directly message offsite.  

2) Map zooming issue - yes! Atul opened a separate ticket for that. (#375)

**Comment by iamjessklein** [comment]
I am not suggesting blocks of text - but a sentence or two - or even a meaningful tagline here. Is a club something I make or join? Is the club about support for teachers or is it youth facing? These are the kind of things that need to be communicated to a visitor upon a glance of the page. I don't see this being communicated in the map. 

Another option could be to move that quote that is on the bottom of the page up. It really sums up the concept quite nicely.

**Comment by hannahkane** [comment]
That makes lots of sense. I like the idea of moving up the quote. Can we see what that looks like? Wondering if the globe illustration will be too close to the three CTAs.

**Comment by iamjessklein** [comment]
Here are 3 iterations. I spoke with @vazquez and both of us are leaning towards v1 (with the what is a club section on top). Note: that is not Mikko's photo. 

V1: 
![v1](https://cloud.githubusercontent.com/assets/535012/6805704/c67b7b74-d21a-11e4-8aa4-9c7e077026e6.png)

V2:
![v2](https://cloud.githubusercontent.com/assets/535012/6805710/cc922b16-d21a-11e4-913e-d3f91b72c10d.png)

V3:
![revision](https://cloud.githubusercontent.com/assets/535012/6805715/d322fa46-d21a-11e4-8db3-44c115b9028b.png)

cc/ @hannahkane @ldecoursy

**Comment by ldecoursy** [comment]
+1 to v1

**Comment by hannahkane** [comment]
Another +1 to v1

**Comment by amirad** [comment]
V1! V1! V1!

**Comment by chrislarry33** [comment]
V1

**Comment by iamjessklein** [comment]
re-labeling as an engineering ticket.
cc/ @ScottDowne

**Comment by ScottDowne** [comment]
I can take for now. Likely get to it today.

**Comment by ScottDowne** [comment]
Merged

**Comment by iamjessklein** [comment]
:+1:

**Comment by hannahkane** [comment]
I'm not seeing this one on staging yet. Should I be?

**Comment by ScottDowne** [comment]
If I understand the problem, yes, you should see it on staging.

I implemented the v1 from above, which moved the "how do clubs work" list to be above the map itself.

**Comment by hannahkane** [comment]
Oh, I see it. Sorry about that. Thanks!
