### ISSUE TITLE
import react-a11y in browser

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#379]
at the very least we should import it for unit tests, but doing it for dev builds too would be good. otherwise the react that only gets rendered client-side does not show us accessibility warnings.

**Comment by hannahkane** [comment]
@toolness - is this needed for v1?

**Comment by toolness** [comment]
@hannahkane I wouldn't say so--it's more of a nice-to-have; the `react-a11y` library is experimental anyways and I am running into some technical issues in #398 anyhow, so I'd say we should leave it off v1.

**Comment by toolness** [comment]
Since we're not using `react-a11y` anymore, I'm closing this issue.
