### ISSUE TITLE
Finalize copy for "About" page of site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#38]
### RACI
* Phase: Design
* Owner: @hannahkane 
* Decision Maker: @chrislarry33 
* Copywriter: @ldecoursy 

### Content
https://teach.etherpad.mozilla.org/aboutpagecopy

**Comment by hannahkane** [comment]
Whoops. There is no "About" page.

**Comment by hannahkane** [comment]
Adding an About page (will need to be added to the nav panel footer) to capture the POV content.

@thornet @chrislarry33 - can you confirm the copy here? Might be good to add more introductory/context-setting copy. Or perhaps a bit of history?

**Comment by hannahkane** [comment]
Could be a good place to reference some of the differentiators from @thornet's email thread: "peer learning, production-centered, open practices, in-person facilitated, culturally localized, with low-fi/no-fi options, and don't push a single product"

**Comment by chrislarry33** [comment]
Is there a deadline on this? I think we need @ldecoursy on this one as well.

**Comment by hannahkane** [comment]
Hoping to get this one written and designed in the next heartbeat.

**Comment by ldecoursy** [comment]
Just assigned myself - should we change the title of this ticket to Finalize copy for "About" page and have a separate one for design?

**Comment by hannahkane** [comment]
@ldecoursy - let me know if I can help with this one. Would be good to finalize content by EOD Friday, so we can design this page next week.

**Comment by vazquez** [comment]
@ldecoursy @hannahkane - Has there been progress on the copy? Am I okay to take the existing copy and start designing?

**Comment by ldecoursy** [comment]
Planning to have a draft to share by EOD today.

**Comment by hannahkane** [comment]
So... @iamjessklein liked the idea of adding the "Who/What/How..." content to the Teach Like Mozilla page (see #37), which means that we don't necessarily need to add that to an About page.

Wondering if we need an About page at this point. @ldecoursy - can you imagine content other than the "Who/What/How" language?

(Note: We need to find somewhere to put Contact information, but I don't think that necessarily needs to be here.)

**Comment by ldecoursy** [comment]
Hi - here's my stab at draft copy for the About page https://teach.etherpad.mozilla.org/aboutpagecopy

One thing I was considering was adding bullets for the key initiatives - Clubs, Maker Party, Hive, MozFest... Let me know what you think.

**Comment by hannahkane** [comment]
Thanks, @ldecoursy. I think this looks great. 

I think we should call out Hive and link to it, but I think we can do that from within the connected cities bullet point. 

I also think we should add a bullet point and link for MozFest when the 2015 site is ready.

I don't feel like we need Clubs or Maker Party links, but will defer to @chrislarry33 on that point.

**Comment by chrislarry33** [comment]
+1 Hannah

**Comment by chrislarry33** [comment]
I made a few tweaks/comments in etherpad

**Comment by iamjessklein** [comment]
considering this copy, I am beginning to think that the top section (why, what how, etc.) on the Teach Like Mozilla page (issue #37) is redundant. 

I propose we keep this, and summarize the top section into a sentence or two (mission-like) and then focus the visitor's attention on the 3 calls to action. 

Reference: [the invision mockup for the Teach Like Mozilla page](http://invis.io/2J2DHDBYE)

cc/ @ldecoursy @hannahkane @chrislarry33

**Comment by hannahkane** [comment]
@iamjessklein - that's fine with me and sounds similar to what the ticket originally called for.

**Comment by ldecoursy** [comment]
Updated the About page copy based on comments in the etherpad https://teach.etherpad.mozilla.org/aboutpagecopy - marking this ticket closed!

**Comment by iamjessklein** [comment]
:+1:
