### ISSUE TITLE
Copy changes on New Club/Learn More modals

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#380]
Noticed a couple things on the modals.

New Club modal:
Prompt text in description field reads: "Give us a brief description about what your Club is about." That's a little awkward. Please make it, "Please provide a brief description of your Club."

Learn more modal:
Title reads: "Learn More About Hive Learning Clubs". Should read: "Learn More About Mozilla Clubs"

Field label on location field reads: "Where does it take place?" which doesn't make sense in this context. It should read, "Where are you located?"

**Comment by toolness** [comment]
Hey @iamjessklein, do you want to take this one? The relevant file is `pages/clubs.jsx` if you want to give it a try, otherwise I can take it.

**Comment by iamjessklein** [comment]
I accept the mission.
