### ISSUE TITLE
Build Events Resources page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#388]
This is a child page of /Events

Design is here: http://invis.io/ZU2HJU6JR

@vazquez to provide any needed assets.

**Comment by vazquez** [comment]
Before you take on this ticket, let's talk about the different interactions that exist on this page.

**Comment by toolness** [comment]
Rad!

Hmm it looks like this will require figuring out #232.

**Comment by iamjessklein** [comment]
Hey - I haven't had a chance to review the ux here - mind if I take a stab at that today?

**Comment by toolness** [comment]
Hmm, I'm curious what the tab bar should work like on browsers that don't have JS... 

![2015-03-25_10-40-52](https://cloud.githubusercontent.com/assets/124687/6827013/76e68a06-d2db-11e4-97cb-cf5e1463a6b9.jpg)

We could potentially have different routes for each tab, e.g. `/events/resources/before-event/` for the "before events" tab, or we could just require users have JS enabled to see the other tabs.

Alternatively, we could design the CSS in such a way that the tabs actually just look like a big long expanded list when JS isn't enabled. This has the added benefit of being useful as a `@media print` stylesheet, if users want to print out the page as a handy reference.

That said, making this accessible looks like it might actually involve a lot of work for a Friday deadline, so if there's any way for us to do *only* the accessible version (i.e. the version w/o any tab bar interactivity) for v1, that would be rad.

**Comment by vazquez** [comment]
@iamjessklein Yes, if you find issues I think it's best to file them as separate tickets so that this can go through.

**Comment by iamjessklein** [comment]
thanks, @vazquez will do.

**Comment by vazquez** [comment]
Interesting points @toolness!

I am deferring to @hannahkane for that decision. Hannah, we are talking of the tab bar looking like below. The thing with this is that the page would become super super long again. With that being said though, I think it is an excellent approach for users that do not have JS enabled.

![screenshot 2015-03-25 10 57 49](https://cloud.githubusercontent.com/assets/1119821/6827443/ce165c96-d2dd-11e4-8b8c-1fa0cf712ac5.png)

**Comment by hannahkane** [comment]
I'm +1 on the non-JS approach. Happy to have it implemented first. And excited to implement the JS version very soon after (though it doesn't have to be a blocker for the first release).

**Comment by toolness** [comment]
Yaaaaaaay! Thanks for the extremely quick mockup ricardo and thanks for the decision hannah!

**Comment by vazquez** [comment]
No problem @toolness  :)

I put the page up on Invision for easy retrieval. This is the Events Resources with no JS: http://invis.io/742J711GK

**Comment by hannahkane** [comment]
@ScottDowne - since @toolness is out today, this would be a good candidate for you, if you haven't been assigned to another project. This is the last page that needs to be built to launch the site.

cc @simonwex in case Scott is more needed elsewhere. :)

**Comment by simonwex** [comment]
@ScottDowne can help until the end of the week.

**Comment by hannahkane** [comment]
@ScottDowne - did you have a chance to start on this today?

**Comment by ScottDowne** [comment]
Yeah, I have a huge chunk of it and the components mapped out.

I just need to do the css and interactive bit. The interactive bit is similar to the same stuff in web lit and toolkit, but actually simplier. I'm hoping it's in review some time tomorrow.

**Comment by ScottDowne** [comment]
@vazquez or @sabrinang I think I need image assets for the two images at the bottom of the page in a 1x and 2x.

If there are any colours you think I'll need now might be a good time. I have the blues for the n-n participants icons already.

**Comment by iamjessklein** [comment]
ping @sabrinang - do you have these assets handy?

**Comment by sabrinang** [comment]
Photography assets that are seen on the bottom of the page can be found here (original & @2x sizes): https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eTExVZ25OLUNjTU0&usp=sharing

According to the mockup it seems all the logo & assets being included are on https://party.webmaker.org/en-US/resources - I am unsure if anything else needs to be included here. @hannahkane do you know if any other assets need to be included?

I will supply asset thumbnails (original & @2x) and any outstanding colours soon.

**Comment by hannahkane** [comment]
All of the logos, etc. should all be on the Maker Party page. Thanks!

**Comment by sabrinang** [comment]
![event-resource-colours](https://cloud.githubusercontent.com/assets/2492510/6972038/da477e10-d935-11e4-9dd4-6ad704a26da2.png)

If you spot any different colours are issues please let me know (in the design doc there are a variation of border colours but let's use that one since they are similar).

**Comment by sabrinang** [comment]
Resource thumbnails (1x and 2x sizes) can be found here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eY0NobUlPajF2S2c&usp=sharing

**Comment by ScottDowne** [comment]
Pretty much done, very close.

Few things I think I'm still missing. Chances are there is an etherpad around with content I need.

Mostly, the content missing is anything behind 3 of the four tabs I need.

Any links, I need their targets.

The blue behind the image containers and the un selected tabs seems to be missing.

@vazquez mentioned the top four links were changing. Right now I left them pretty simple until I know what we're doing with them.

**Comment by vazquez** [comment]
Go to sleep.

On Sunday, April 5, 2015, ScottDowne <notifications@github.com> wrote:

> Pretty much done, very close.
>
> Few things I think I'm still missing. Chances are there is an etherpad
> around with content I need.
>
> Mostly, the content missing is anything behind 3 of the four tabs I need.
>
> Any links, I need their targets.
>
> The blue behind the image containers and the un selected tabs seems to be
> missing.
>
> @vazquez <https://github.com/vazquez> mentioned the top four links were
> changing. Right now I left them pretty simple until I know what we're doing
> with them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/teach.webmaker.org/issues/388#issuecomment-89728338>
> .
>


-- 
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by toolness** [comment]
:+1: I hope you followed @vazquez's advice @ScottDowne :)

**Comment by jgmac1106** [comment]
+1

**Comment by hannahkane** [comment]
gDoc is here: https://docs.google.com/document/d/1yORrrsU4lN7itEC7BLTLHSR8JqRevppVPABxlmJqxXg/edit#heading=h.we4ed4g5or25

@ScottDowne - let me know if anything isn't clear

**Comment by ScottDowne** [comment]
@hannahkane yeah, so based on the gdocs link you gave me above, and the designs, I am a bit confused.

The designs have four tabs "the basics" "before event" "during event" and "after event"

But in the gdocs, I only have three and some of the before items are in the basics tab in the designs.

**Comment by ScottDowne** [comment]
Oh, I think I see. The designs have "before event" split into "before event" and "basics"

**Comment by hannahkane** [comment]
Yeah, sorry I didn't specify that. We needed to cut up that section because it was too long, but I never adjusted in the gDoc.

**Comment by ScottDowne** [comment]
Closing!
