### ISSUE TITLE
Rework curriculum index page to redirect to clubs curriculum page

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#392]
from http://mozilla.github.io/webmaker-curriculum/ "basics 21st century skills" will link to Curriculum page on teach[dot]

this
http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/ page will be replaced by the curriculum page designed in #106 – but we'll need to build in a redirect so people coming via gh-pages don't get lost.

**Comment by hannahkane** [comment]
Just fyi, the url will be teach.mozilla.com/clubs/curriculum

**Comment by LauraHilliger** [comment]
depends on #42

**Comment by LauraHilliger** [comment]
https://github.com/mozilla/webmaker-curriculum/pull/190

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/102"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/102.
Please don't comment on it here.
