### ISSUE TITLE
Fix copy in the email

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#393]
This is the letter I received:

![screen shot 2015-03-24 at 12 50 19 pm](https://cloud.githubusercontent.com/assets/535012/6807394/9a901272-d224-11e4-8ca5-01ee0241fd66.png)

- [x] Capitalize the first letter of the person to whom the letter is addressed. 
- [x] Change p.s. to P.S. 
- [x] Copy edit:  should read "Join the conversation <strong>in </strong> our discussion forum.
- [x] Add comma after Michelle Thorne's name 
- [x] Change the P.S. message to: "Be sure to check out our clubs toolkit to help you get support, find training opportunities, increase the impact of your club, and much more."
- [ ] I assume this will be done, but make sure the email comes from a normal user name, such as "Mozilla Learning" 
- [ ] Do Not Launch until we have a working link for the Toolkit page to include

cc/ @hannahkane @ldecoursy

**Comment by hannahkane** [comment]
Thanks, @iamjessklein. Added an item to the checklist about not launching until we have the Toolkit page.

**Comment by iamjessklein** [comment]
good point @hannahkane :email:

**Comment by toolness** [comment]
Regarding capitalizing the name: we're currently showing the user's username, which is all we've got... usernames usually are preserved in the same case that the user entered them. Once we're hooked up to the new login server though, we should get auto-capitalized first names from it, if the user entered them on account creation at least.

**Comment by toolness** [comment]
Also, if you want to submit a PR to fix some of these things @iamjessklein, you can hack on https://github.com/mozilla/teach-api/edit/master/clubs/email.py from within GitHub's UI if you like!

**Comment by iamjessklein** [comment]
:+1:  on capitalization. Thanks @toolness 

Yep, I'll work on that.

**Comment by iamjessklein** [comment]
I made the changes in the pull request mentioned above. I am going to close this issue and then note somewhere to make sure the email comes from a normal user name, such as "Mozilla Learning"

cc/ @hannahkane @toolness

**Comment by toolness** [comment]
Yep, official email address stuff is being covered in #536.
