### ISSUE TITLE
Decision over ownership and name of @Webmaker Twitter account

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#394]
**My suggestion: Change @Webmaker to @MozillaLearning on Twitter**

Because,
•Learning Networks + Learning Tools both fall into the broader ‘learn’ category so we can tweet about both from one account. 
•One account will alleviate the burden of the product or engagement team assigning someone to manage a separate @ Webmaker account. Information specific to tools can be shared through both @ MozillaLearning and @ Mozilla 
•Followers are primarily educators and activists tied to past teaching initiatives so an audience that is more skewed towards Mozilla Learning Networks team priorities.
•The Learning Networks team has put in considerable amount of time and energy to build up a large following in the last year of said audience (11K follower increase in 1.5 year).

There currently is no Twitter account with the name @ MozillaLearning meaning that we would be able to easily switch handles and update text on site/urls including Webmaker Blog and teach.mozilla.org. We can work on transition messages and updated descriptions asap. 

Thoughts? @chrislarry33 @ldecoursy @HPaulJohnson @kevzawacki @LucyeoH

**Comment by amirad** [comment]
@hannahkane thoughts?

**Comment by LucyeoH** [comment]
I think we've already got a lot of educators and people who would be interested in both the learning networks and tools on the account right now. For the group who are invested in the current tools I think it would make it easier for transition if @ webmaker (even if in a different name) remained the account where tools were discussed. 

However I understand the thinking that the tool may attract a group of people who are purely learners with no interest in the educator perspective, but I feel like the "pure learners" primary interaction with any "new tool" account would be primarily for technical/help support, which we could still provide from this one. Is this still in line with the product team's thinking?

**Comment by davidascher** [comment]
No strong opinion.

We're going to need a @Webmaker twitter account at some point even if we
migrated the existing followers to a new handle.  So it may be weird if
you're following @webmaker to all of a sudden be following a new handle,
and still see a "new, unfollowed" @webmaker.

That said, I'm sure we can figure out a path either way. Probably need to
explain it all to the followers regardless.

**Comment by hannahkane** [comment]
No strong opinion, either. 

Is there a content strategy for the new product beyond tech support? Will there be a need for regular off-site messaging?

**Comment by amirad** [comment]
@davidascher any idea what the specific need would be for Webmaker to have it's own Twitter account? And when? 
My thoughts would be to relay proper messaging around this and have a fresh Webmaker account targeting the 'new audience' for tools.

**Comment by KevZawacki** [comment]
We can easily communicate handle renames, etc. with a pinned tweet. We should aim to leave it pinned for ~two months.

**Comment by ldecoursy** [comment]
I think the @webmaker account is and should still be used for things like "Check out what I made with @webmaker", but also for tech support, engaging with the learners and others using the tools, product-specific announcements/changes/updates, etc. 

Should we consider just using @mozilla for Learning Networks vs. trying to rebuild or transfer existing audience to a new/separate account? 

If there are reasons to not do that, I'm also confident we can communicate the final decision clearly and in a way that retains as many active followers as possible. Just seems like then we're talking about three separate accounts with potential for a lot of overlap and RT'ing between them.

**Comment by HPaulJohnson** [comment]
Original proposal was to use @mozilla for Learning Networks. Concern was existing Webmaker community was largely made up of mentors/teachers and we would need to move them to a new account (though there is likely some amount of overlap already). Advantage is a larger megaphone for Learning Networks (110K @mozilla followers). Disadvantage is that @mozilla will also communicate non-Learning Network content adding some level of noise. In this scenario, we'd leave @webmaker as is and use it for product-specific comms going forward. 

Alternative is what @amirad is proposing here. Change the handle to @MozillaLearning under the assumption that existing followers are mostly interested in Learning Network comms. This would require us to build a new following for product-specific news around webmaker; we would build this new profile via promotion on @mozilla. 

I prefer the first but understand if we want to handle existing @webmaker followers with special care (i.e not ask them to move to a new account) as they are key mentor/educators who can help us build Learning Network program and a lot of time/energy has been invested in building this following over the last year+.

**Comment by ldecoursy** [comment]
Very helpful @HPaulJohnson - will defer to you and Amira then, unless @chrislarry33 has strong opinion? 

Would just add two more thoughts: should we consider @mozlearning to save on characters (since we'll also likely still use #teachtheweb and #makerparty) or perhaps wait until after branding conversation to finalize a name? Also, I think this change should be part of a comms effort that explains why the change, and what's happening with the existing tools - so people, including our mentor/educator community - are clear about what kind of support is or isn't available.

**Comment by jgmac1106** [comment]
It is the hashtags you curate on Twitter that will matter more than the
individual accounts. I more often than not see, including myself, people
put @mozilla @webmaker together in the same tweet. I always assumed it
@Mozilla was the Foundation writ large and @webmaker was the #teachtheweb
stuff.

What ever handles are most active on the hashtags used by the Learning
Networks will be the handles most associated with those networks.

**Comment by amirad** [comment]
Re-visited this today with @HPaulJohnson and @KevZawacki -- we decided that @Webmaker would change to an account that strictly supports tools and is managed by Kevin. Moz Learning Networks will revert back to @Mozteach account and be managed by Amira. 

Next steps: 
•Kevin to inquire into feasibility of changing users of the two accounts (though this is not a blocker, it's potential a nice to have) so that the educator/activist audience moves with the account
•Kevin to create transition plan with comms to community and updated account info
•Goal to implement changes is May 18th

cc: @chrislarry33 @ldecoursy @davidascher @hannahkane --> let us know if there are any problems

**Comment by davidascher** [comment]
What does "Tools" mean?  I'd like us to be clear re: what the @Webmaker
account would be used for, because our current plan has things like Thimble
under the Teach.mozilla.org domain, but it's a "tool".

**Comment by amirad** [comment]
I believe in May/June it would be support for the previous tools as they transition to different homes and moving forward, July and beyond, it would be Webmaker App only. @HPaulJohnson correct me if I'm wrong.

**Comment by HPaulJohnson** [comment]
That's right, @amirad 

Long-term @webmaker is about the new content creation product only. As we go through the transition over the next few months, starting with a blog post about legacy tools and followed by this social media transition, we expect to handle questions about existing tools from this handle as well. 

Related question for @davidascher is who should be technical point person for product support on @webmaker (and @help email) - both in the context of legacy tools communications and new app/product - once we are through transition?

**Comment by davidascher** [comment]
I don't think there's a clear answer there.  I doubt we'll end up with a
single named owner, more likely a role, as part of either those folks on
the teach crew or on the webmaker crew at any point in time.

@simonwex owns helping resolve technical uncertainties in the transition
phase.

**Comment by amirad** [comment]
@KevZawacki made a transition plan. Will close this ticket and issue a new one for successful transition. 
https://docs.google.com/a/mozilla.com/document/d/1vjjhStCsuON_QJnJjFavYbv4ZaHEPVCUVlUH_X48gAw/edit?usp=sharing

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/103"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/103.
Please don't comment on it here.
