### ISSUE TITLE
Create Learning Networks Engagement Calendar for Q1/Q2

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#395]
Map schedule of how we will be engaging existing audience throughout April-Oct, on what channels and what the narrative sounds like.

**Comment by amirad** [comment]
@HPaulJohnson and I mapped out an arc here: https://teach.etherpad.mozilla.org/2015LearningEngagmentCalendar

@ldecoursy @chrislarry33 @thornet @hannahkane @kevzawacki do you want to give a quick look based on our call yesterday to see if this aligns with what we were thinking before we continue to build this out.

**Comment by KevZawacki** [comment]
+1 Looks great to me!

**Comment by hannahkane** [comment]
Also looks good to me. Added a couple things.

**Comment by thornet** [comment]
cc @Saallen to review for Mozfest comms. Think the Save The Date should be sooner. Sarah knows preferred dates. 

Made some edits in the etherpad. Also, @amirad do you want to move this to a heartbeat milestone (i.e. April 10?)

**Comment by Saallen** [comment]
@thornet I have added the MozFest Save the date as April asap and added all other engagement dates across the next 8 months. I have not included internal comms here :+1:

**Comment by amirad** [comment]
Thanks all. This was super helpful to seeing the full narrative arc of our team throughout the rest of the year. 
@ldecoursy I'm interested in some points you made in the pad and to work with you on how we can leverage our channels to do more clubs marketing earlier in the year? Feel free to drop notes here, hack the pad or we can chat :)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/104"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/104.
Please don't comment on it here.
