### ISSUE TITLE
Design first time experience for teach.webmaker.org

### ISSUE THREAD

**Issue by cassiemc** [mozilla/teach.webmaker.org#4]
What does a first-time experience feel like for teach.webmaker.org?

Here's an example from @simonwex a la http://stackoverflow.com/tour

**Comment by toolness** [comment]
Oh shoot, when we imported my code into this repository, a bunch of unrelated tickets erroneously got closed, including this one. I'm re-opening this issue.

**Comment by hannahkane** [comment]
I'm going to close this ticket for now, because we haven't yet determined it's a need. Will re-open if the need emerges.
