### ISSUE TITLE
Build homepage for site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#40]
### RACI
* Phase: Build
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: NA
* Dev Lead: 
* Quality: @davidascher 

### Requirements
* Responsive
* Latest versions of all major browsers

Tasks:
 - [ ] Design review
 - [ ] Content review

**Comment by hannahkane** [comment]
Not sure if this ticket is needed since @toolness has basically finished this already, but want to make sure we capture all "Done Criteria" — must be responsive, passing in whatever browsers we support (is there a definitive list somewhere?)...do we have other Done Criteria?

**Comment by toolness** [comment]
That's a good question! I wrote all the ones I could think of in the repository here:

https://github.com/toolness/mozilla-learning-html/issues

**Comment by toolness** [comment]
Ok, so @hannahkane's questions are being addressed in #151 and #119, and with that I am closing this issue!
