### ISSUE TITLE
Mozilla logo needs more prominence on page header

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#401]
As of 31004e0b28cb4bed1c874fb9486b5c4e098cabda, the header of our site now looks like this:

![2015-03-25_8-24-31](https://cloud.githubusercontent.com/assets/124687/6824422/8f1a6d58-d2c8-11e4-9fe0-9244cb222d7a.jpg)

I'm not sure if people will understand that the site is part of Mozilla. As such, I recommend adding a third wordmark in the center of the page.

**Comment by iamjessklein** [comment]
LOL! :laughing: 
In all seriousness, I think that we need to de-emphasize the wordmark. What if we pulled the color bar on the left up to the top and then ghosted and reduced the size of the wordmark? 

cc/ @vazquez

**Comment by iamjessklein** [comment]
I'm thinking something along the lines of this:
![revisedm](https://cloud.githubusercontent.com/assets/535012/6824764/69bf79e2-d2cb-11e4-8f66-2d1e9e710090.png)

**Comment by toolness** [comment]
That looks better! That said, I am a bit bummed because it means my nifty [SVG triangle](https://github.com/mozilla/teach.webmaker.org/blob/d315385fddae44d2db92f7409f32f78fe0dba1fc/components/sidebar.jsx#L7-L27) will have to be dropped. Alas.

**Comment by hannahkane** [comment]
+1 to @iamjessklein's solution, though a scrolling marquee of the wordmark might also help clarify that this is a Mozilla site.

**Comment by iamjessklein** [comment]
R+ @toolness

**Comment by vazquez** [comment]
The Mozilla logo feels like its floating now. I suggest adding a light white background to it.

![screenshot 2015-03-25 10 28 34](https://cloud.githubusercontent.com/assets/1119821/6826712/c9e9910a-d2d9-11e4-8442-9c995ea1886b.png)

**Comment by iamjessklein** [comment]
agreed. I think that looks nice, and echoes the interaction that happens on hover etc. 
cc/ @cassiemc

**Comment by cassiemc** [comment]
wfm!

**Comment by toolness** [comment]
This issue has been superseded by #412.
