### ISSUE TITLE
Update the site with the new footer

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#402]
The current footer on the site is incorrect. It should be [the simplified footer](http://invis.io/7X2FVXRN9)

![footer-desktop](https://cloud.githubusercontent.com/assets/535012/6825076/f9f58b4e-d2cd-11e4-9442-8aef69fcc4c9.png)
![footer-mobile](https://cloud.githubusercontent.com/assets/535012/6825078/fb1117e6-d2cd-11e4-89e1-3c3198e5d242.png)

cc/ @toolness @ScottDowne

**Comment by toolness** [comment]
Ah I can bust this up I 'spose.

**Comment by hannahkane** [comment]
Should I be seeing the simplified footer on the staging site now? I'm not. :(

**Comment by toolness** [comment]
Hmm, I think this has something weird to do with the travis jobs hanging on friday. Hopefully the new footer will show up soon, as the code in the repository does seem to reflect the simplified footer.

**Comment by toolness** [comment]
Ah looks like it's up there now!

**Comment by hannahkane** [comment]
Yay! Looks so nice.
