### ISSUE TITLE
[MIGRATED] Gather and collate "best of" Teaching Kits for web literacy competencies

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#404]
We need to search through a couple years worth of curricular resources made by the community and begin reworking content to serve as a “best in show” library. We may need to remix / rebuild the kits to update the content, make 'em pretty and remixable. 

Related resources can be found in #27

**Comment by LauraHilliger** [comment]
So. Much. Stuff.
https://teach.etherpad.mozilla.org/best-in-show
https://webmaker.etherpad.mozilla.org/best-makes-call
https://blog.webmaker.org/?s=community+literacies

**Comment by ldecoursy** [comment]
This too - has some recent curation to narrow down 10 to feature on Teaching Activities page: https://teach.etherpad.mozilla.org/contentreview

**Comment by LauraHilliger** [comment]
depends on #27

**Comment by LucyeoH** [comment]
Oh I have a list for this!! https://teach.etherpad.mozilla.org/BestTeachingKits @LauraHilliger

**Comment by LauraHilliger** [comment]
https://keyboardkat.makes.org/thimble/MTEzODQyNjExMg==/appmaker-for-educators-teaching-kit

**Comment by ldecoursy** [comment]
Here's another one from Global Kids (Hive NYC member) that's all about using littleBits to learn about design thinking, make simple circuits, and create a project based on a theme–in this case, disaster relief. 

https://jrubio.makes.org/thimble/Mjk3NTk5MjMy/make-change-with-little-bits

If we like it I can find out about getting photos or examples of things students made during a workshop they ran on this activity last fall.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/105"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/105.
Please don't comment on it here.
