### ISSUE TITLE
design 404 page 

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#406]
It should be amazing. 

cc/ @vazquez

**Comment by iamjessklein** [comment]
I've always wanted to make a 404 page that teaches what a 404 page is - could this be the opportunity?

**Comment by hannahkane** [comment]
indeed

**Comment by jgmac1106** [comment]
+1

**Comment by hannahkane** [comment]
@iamjessklein - should we take this one out of the heartbeat? Finishing up the homepage feels more important.

**Comment by iamjessklein** [comment]
yes.

**Comment by iamjessklein** [comment]
I made a few sketches for a few directions that we could go with the 404 page. Overall the idea I have here is that we teach what a 404 page is - on the 404 page.

idea 1: The "0" in 404 is broken and you can drag the pieces together. When you drag it together you get feedback explaining to you what the 404 page is. 

![kwgpbzp50x09ztot1af0sbjtle7zyvkoyu_fuflddrl4p_rg_pwtdic8nengsa7su0mskxpskqjt162ebco1fxttyjlkzbef12brxzbr64g7gisfazvh3pi23e5__kvtmpogcvhxsiyqomgntav1fmp4lki1hixplssgzsbwb-bckhxzdjnyqqzr3e8jtryoxiauvgsqj5m7tbbborktxtkwtl](https://cloud.githubusercontent.com/assets/535012/7541062/52fd93ec-f580-11e4-9f4b-ce8a74787c87.jpg)

idea 2: a game where you have tubes that need to be connected - you connect pipes from a computer to a server. 

![ueki8ebers6br5fp9cgepxoywdgbd4_lfpv0tauh3wnjjgudgjpcite-9qwsxgqgvd_gbggrwjoxwkrrwni9fzbvbt5p1httpbyzgeqedyj4il06zet0imv9f9qunaf0bfgzdyt79g9zi_rtx_l7yfuxti-cv0l9p_jwmtpo6x3pp5vxjtt5cq7vc4rkflejaamxjfrfepd2ufmlkty8c82kf6](https://cloud.githubusercontent.com/assets/535012/7541081/78f04554-f580-11e4-9483-ed225dc7d170.jpg)

idea 3: you explain that 404 pages are either a typo or page that doesnt exist and then have user fix a typo to get to an existing page

![ies8clakseuljyxn5xqd-kttwiqnysxj-r0tdpuiqwuabvh9ncni_yjt4_2y5equ4fhunpcksqf4gnpertbvr-ctac9bk3fuhrxk8axgc7augjhgguxfswpr0unpgaw4yst1rpfej98asqjezisvdxqp-6pyiuo_iyayoxl9a5qwimg_ubbhl_3gqf-adne9u38d6zdsz5poe2ygqmxlmxinp2](https://cloud.githubusercontent.com/assets/535012/7541123/c730a2e0-f580-11e4-8a58-68acc4e01496.jpg)

**Comment by toolness** [comment]
As @LauraHilliger just mentioned in #998, our current 404 page *really* sucks:

<img src="http://i.imgur.com/W8kpRHN.png">

Would be quite splendid to get something more user-friendly in there!

**Comment by iamjessklein** [comment]
agreed. :+1:

**Comment by vazquez** [comment]
JESSSSSSSSSSSSSSSSSSS

**Comment by vazquez** [comment]
:star: :star2: :rainbow:

**Comment by adamlofting** [comment]
I was about to file a bug to say we need a 404 page, then found this.

I love these concepts, but if it's going to take a while to build, we should ship something basic in the meantime.

**Comment by hannahkane** [comment]
That's a good point, @adamlofting. I'll put this as a candidate for the next heartbeat.

**Comment by hannahkane** [comment]
removing this from the heartbeat because it's a half-heartbeat

**Comment by cassiemc** [comment]
This could be a good contributor-bug but may need a bit more direction for someone to start. cc @hannahkane

**Comment by hannahkane** [comment]
Thanks, @cassiemc. Agreed this could be a good contributor bug, especially for someone who wants to be a little creative! The look of the 404 page should match the teach.mozilla.org site generally, but otherwise we're open to ideas! Here's some inspiration: http://www.creativebloq.com/web-design/best-404-pages-812505

**Comment by toolness** [comment]
I was just looking at https://teach.mozilla.org/healthcheck/ and realizing that its design actually makes for an extremely simple, no-frills 404 page. It wouldn't be hard to make another page that looks very similar but says something like "Oops, we couldn't find what you were looking for!" in the header, or something like that. Would be a lot more friendly than our current 404 page, albeit a lot worse than the cool ideas jess mocked up too. But it's something we could easily have live by the end of the day, so long as we've got official copy to put in there.

**Comment by hannahkane** [comment]
Some ideas:

/ playing off of "teach"

Hey, this 404 is a teachable moment!
Did you know that a 404 is the generic error code used across the internet to mean "page not found"? It might mean that the page used to exist, but doesn't anymore. Or it might mean that someone made a typo somewhere. Regardless, there's no page at this address.

/ reference curriculum

This page doesn't exist.
You know what else might not exist? The Kraken! Can you prove it using this Kraken the Code activity? [link to http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-kraken.html] 

/ silly

How'd you get in here?
You might consider launching a career tracking down lost unicorns or making maps of leprechaun villages, because you've got a natural talent for finding things that don't exist, like this page.

Also open to other ideas, including the generic "Oops..."

**Comment by cassiemc** [comment]
I still love the teachable moment version. Nice hack to simplify the concept.

**Comment by chrislarry33** [comment]
my vote:

/ playing off of "teach"

Hey, this 404 is a teachable moment!
Did you know that a 404 is the generic error code used across the internet to mean "page not found"? It might mean that the page used to exist, but doesn't anymore. Or it might mean that someone made a typo somewhere. Regardless, there's no page at this address.

**Comment by LauraHilliger** [comment]
feel free to reuse the text we worked on in training: https://training.webmakerprototypes.org/adad

**Comment by hannahkane** [comment]
@LauraHilliger!!!! Thanks for this.

I don't have a strong opinion either way between the "teachable moment" and "the more you know" (though I'm not sure that is a globally-understood reference?)

**Comment by LauraHilliger** [comment]
I probably wouldn't go with More You Know for teachDOT. It's fair use, but you're right it's not a global reference :)

**Comment by toolness** [comment]
Hi @LauraHilliger !!

Another totally possible alternative we could do is actually have a **random** selection of 404s appear--it doesn't always have to be the same thing! Or we could do A/B testing to see who actually learns something from it... though we'd have to define a metric for "learns something", which is the hard part.

Anyhow, another thing I think we should do aside from teaching them what a 404 is, is actually help build their **navigational** literacy by giving them suggestions on how to find whatever it is their looking for. For instance, they could do a web search that's constrained to the teach.mozilla.org domain, or they could go back to the homepage, and so on.

**Comment by hannahkane** [comment]
Fun ideas, @toolness!

In the interest of getting something up soon, why don't we go with the simple Teachable Moment copy now, and then open up another ticket for fancifying later on.

**Comment by hannahkane** [comment]
this ticket is crowded. opening a new, fresh ticket.
