### ISSUE TITLE
Build Events landing page for site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#41]
### RACI
* Phase: Build
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: NA
* Dev Lead: 
* Quality: @davidascher 

Design is here: http://invis.io/TY2GT8GBX

**Comment by cassiemc** [comment]
@hannahkane For MVP could this be just porting over the existing Events app from webmaker.org?

**Comment by hannahkane** [comment]
Will spec this out a little further in #35, but the emphasis is likely to be more about porting the "How To" content that's currently here: https://party.webmaker.org/resources. 

But, yes, I was imagining we'd either port the events app or simply link to it.

**Comment by toolness** [comment]
Ricardo said this page needs a carousel, and [react-slick](https://github.com/akiran/react-slick) looks like it might fit the bill.

**Comment by toolness** [comment]
Note that the e-mail signup at the bottom of this page is supposed to do the same thing as the form at the bottom of https://party.webmaker.org/. That form appears to issue a POST request to https://sendto.mozilla.org/page/s/maker-party-signup.

**Comment by hannahkane** [comment]
@vazquez - can you provide the assets for this page when you have a chance?

**Comment by hannahkane** [comment]
Photos here:
https://www.flickr.com/photos/mozilladrumbeat/14592186080/in/set-72157647305286970
https://www.flickr.com/photos/mozilladrumbeat/14592256638/in/set-72157647305286970
https://www.flickr.com/photos/mozilladrumbeat/15213220651/in/set-72157647305286970
Cannot seem to find that picture with Lucy!

MP logo is available here: https://party.webmaker.org/en-US/resources

**Comment by vazquez** [comment]
Assets are available here: https://dl.dropboxusercontent.com/u/43783651/Mozilla/Events%20Assets.zip

**Comment by iamjessklein** [comment]
@toolness check it out!
thanks @vazquez
