### ISSUE TITLE
Copy/Functionality QA for Teach site v1

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#411]
### How to test ###
 * Go to http://teach.mofostaging.net/
 * Please file any issues you find and link back to this ticket

### General site review ###
For each of the pages below, please conduct a through review for:
 * Copy and language—any typos or weirdnesses? Keep an eye out for jargon that might not be localizable
 * Links—any 404s?
 * Image and graphic review—do the images communicate what you’d expect? Could the imagery be construed as offensive or have questionable localization?

* [ ] Homepage
* [ ] Teaching Activities
* [ ] Events [not on staging yet]
 * [ ] Events Resources [not on staging yet]
* [ ] Teach Like Mozilla
 * [ ] Web Literacy
* [ ] Clubs
 * [ ] Clubs Curriculum
 * [ ] Clubs Toolkit
* [ ] Footer links, including About page [needs updating]

### Functionality ###

 - [ ] Can you add a club? (Go to the Clubs page and click "ADD YOUR CLUB" button, authenticate if needed, complete and submit form)
  - [ ] Were error messages useful?
  - [ ] Did you receive an email confirmation?
 - [ ] Can you edit your club? 
 - [ ] Can you delete your club?
 - [ ] ~~@secretrobotron to add stuff about login/sign-up/password~~
 - [ ] Try logging in & out

### Browser/Device Coverage ###

Once you've completed all of the above, please check the box, and add your name and what version you used next to the browser/device you used.

 - [ ] Firefox desktop 
 - [ ] Chrome desktop 
 - [ ] IE desktop 
 - [ ] Safari desktop
 - [ ] Opera desktop
 - [x] iPhone (@hannahkane tested on Safari on iPhone 5)
 - [x] Android phone (@ldecoursy tested on Firefox 21.0 on Android 4.4.4)
 - [ ] iPad
 - [ ] Android tablet
 - [ ] I tested with javascript disabled

**Comment by hannahkane** [comment]
@iamjessklein - this look okay to you? Bobby suggested we put it in a ticket, which makes sense. :)

**Comment by iamjessklein** [comment]
@hannahkane we have been decoupling the QA tickets for the past few :heart: beats and it worked out pretty well. To do that we have separate issues for: Technical QA, Design QA and Copy QA

**Comment by hannahkane** [comment]
@iamjessklein - so I should split this into three tickets? Where does functional testing go? Like, testing the "Add Your Club" workflow?

**Comment by hannahkane** [comment]
OK, added #441 and #442 for Design and Technical QA, respectively.

**Comment by KevZawacki** [comment]
Suggested copy edits in this etherpad: https://etherpad.mozilla.org/TeachCopyEdits

**Comment by hannahkane** [comment]
Thanks, @KevZawacki. This is awesome.

**Comment by hannahkane** [comment]
I'm closing this since we had a QA party and lots of tickets were generated!
