### ISSUE TITLE
URL validation on 'website' field in club modal should be friendlier

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#424]
As mentioned in https://github.com/mozilla/teach.webmaker.org/issues/352#issuecomment-84214121, we are currently relying on `type="url"` to validate the website field in Club modals. This ultimately means that the validation is at the discretion of the host browser's built-in HTML5 form validation; on some browsers it says "Please enter a URL" while on others it may say "Please enter a web address that starts with http:// or https://" while others may say something different.

This isn't super ideal. Also, if the user enters "example.org" we could always prepend "http://" before sending the data to the server (the server uses a [`URLField`](https://docs.djangoproject.com/en/1.7/ref/models/fields/#urlfield) and thus expects any non-blank value to be a http or https URL).

**Comment by toolness** [comment]
Ack, I think GitHub accidentally auto-closed this because I mentioned it in #593, but it actually *shouldn't* be closed, because #593 didn't actually resolve it! We need to figure out exactly how we want this field validated before implementing it: do we want the user to essentially be able to enter anything, and we just prefix it with "http://" if it doesn't look like a URL? Or do we want to force the user to type "http://" or "https://" at the beginning?

I should also add that with the explosion of top-level-domains in recent years, it's actually somewhat nontrivial to detect whether a string looks like a URL without the http/https at the beginning, these days.

**Comment by hannahkane** [comment]
I defer to @iamjessklein for the best practices on this. :icecream:

**Comment by iamjessklein** [comment]
We should definitely <em>not</em>force the user to type http:// or https:// - should prefix it. We can hit at this by having the http:// already written in the field as part of the prompt.
