### ISSUE TITLE
"gulp beautify" pollutes dist directory

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#426]
I know I ought to know this since I reviewed #187, where the related code was first introduced, but I'm quite confused by our `gulp beautify` task:

```js
gulp.task('beautify', function () {
  gulp.src(LINT_DIRS)
      .pipe(beautify({ config: 'node_modules/mofo-style/linters/.jsbeautifyrc' }))
      .pipe(gulp.dest('dist'));
});
```

As far as I can tell, this just puts the beautified versions of some of our JS files in `dist`, which are completely separate from the bundles that webpack is creating. These files don't ever seem to be loaded by any code (which makes sense, since they're also being included in webpack's bundles). They just seem to pollute the `dist` directory and I've occasionally made the mistake of accidentally editing one of them (I've actually had to tell my Sublime Text 2 editor to ignore the `dist` directory to prevent this from happening).

~~I *assume* that we're running our code through beautify as a form of linting, so that any errors raised by beautify make our test suite fail... If that's the case, I wonder if there's a way to pipe the file output into the Vinyl equivalent of `/dev/null`, or at least a different directory than `dist`.~~ Nope, I think the intent here is to actually rewrite our code to conform to style guide. See #851 for more thoughts on this.

**Comment by toolness** [comment]
Oh we don't really need to worry about this for March 27 or v1, methinks, it's just a nice-to-have for post-launch.

**Comment by hannahkane** [comment]
Cool. :)
