### ISSUE TITLE
Build "Teach Like Mozilla" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#43]
### RACI
* Phase: Build
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: NA
* Dev Lead: 
* Quality: @davidascher 
* Consulted: @dajbelshaw @LauraHilliger 

The design of the page is here: https://projects.invisionapp.com/share/YB2EPJQUF#/screens. Just needs to be coded up.

**Comment by dajbelshaw** [comment]
Could you add @LauraHilliger and I as 'Consulted' for this one please, @hannahkane?

**Comment by hannahkane** [comment]
This is now unblocked. See #37.

**Comment by hannahkane** [comment]
@ScottDowne - assigning this one to you. 

@vazquez should be able to answer questions about the design, and @toolness or @gesa should be able to answer questions about implementation.

**Comment by vazquez** [comment]
@ScottDowne I'll get you the assets in a few minutes

**Comment by vazquez** [comment]
Teach Like Mozilla Assets are available here: https://dl.dropboxusercontent.com/u/43783651/Mozilla/Teach%20Like%20Mozilla%20Assets.zip

**Comment by ScottDowne** [comment]
Finished: https://github.com/mozilla/teach.webmaker.org/pull/321

Needs review.

**Comment by ScottDowne** [comment]
Forgot to close.

This landed.
