### ISSUE TITLE
Dev ribbon overlaps hamburger on mobile view

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#431]
Our "dev mode" ribbon overlaps Tabzilla on desktop, which isn't a big deal since we don't use it that often as developers. However, on mobile it overlaps the hamburger--it doesn't look that bad in the screenshot below, but in practice, because fingers are so big, it is actually quite challenging to poke the hamburger:

![2015-03-27_6-15-04](https://cloud.githubusercontent.com/assets/124687/6865859/b1ae1050-d448-11e4-9bd1-d864fb1b4cee.jpg)

This could probably be resolved by making the ribbon a bit wider, which would push it away from the top-right corner of the page, giving the hamburger a bit more space to be poked.

**Comment by iamjessklein** [comment]
:+1:  am happy to lend a :hand: to that if you need @toolness 

I know that the ribbon is the convention, and this is a good fix for the time being, however I wonder if there are other metaphors that would be appropriate here.

I also am reminded of [this concept I had mocked up](http://jessicaklein.blogspot.com/2014/04/prototype-evaluating-prototypes-that-we.html) at an All-Hands a while back - that let's you rate or feedback on the prototype.(#fileundertangent)

![1](https://cloud.githubusercontent.com/assets/535012/6866903/17865874-d453-11e4-96c5-9e02a8ed9760.png)

**Comment by toolness** [comment]
Oh, I fixed this in e18f47a383821e68a8e0953920ea902de3ce75c3 actually, so I'm closing this issue... @iamjessklein, I'm not sure what to do about your idea for a more useful widget than a ribbon, though--should we file a new bug for it?

Also, while I like the idea of the feedback widget, one thing I do like about the dev ribbon is that it's (hopefully) obvious to visitors that it will only appear on the dev version of the site, and not the final product. If we do anything that doesn't literally have the words "dev version" or something similar on it, I'm concerned that visitors might be confused as to whether the widget is actually a feature of the site itself (i.e. something that will appear in production too).
