### ISSUE TITLE
Swap out middle CTA on Teach Like Mozilla page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#438]
Let's replace the middle CTA on the page (currently "Attend") with a different one.

Illustration: use the, um...atomic cell phone illustration that's currently on the /clubs/curriculum page
CTA: "Learn"
Text: "See our Web Literacy Map"

**Comment by ScottDowne** [comment]
I'm going to need an atomic cell phone image in a matching colour with the rest of the icons.

**Comment by ScottDowne** [comment]
It should link to web literacy?

Right now in https://github.com/mozilla/teach.webmaker.org/issues/324 it is destined to be linked to: attend: https://wiki.mozilla.org/MozillaWiki:Teach_the_Web_Talks

I take it, this ticket replaces the link in #324?

**Comment by hannahkane** [comment]
Yes, to both—should link to the Web Lit page, and should replace the link in #324. Thanks!

**Comment by vazquez** [comment]
The asset needs to be JPG because of the radial gradients we are using. 

https://dl.dropboxusercontent.com/u/43783651/Mozilla/New%20icons.zip

**Comment by ScottDowne** [comment]
@vazquez did you forget to upload the icon to the new icons dir in that zip? It's empty.

Or is this some sort of commentary that less is more?

**Comment by vazquez** [comment]
Try this out. https://dl.dropboxusercontent.com/u/43783651/Mozilla/New%20icons.zip

**Comment by ScottDowne** [comment]
Cool thanks, totally did it.

**Comment by ScottDowne** [comment]
Merged, closing.
