### ISSUE TITLE
Design QA of Teach site v1

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#441]
@iamjessklein to lead this process!

**Comment by iamjessklein** [comment]
@vazquez can you share with me that design qa document that you started on?

**Comment by vazquez** [comment]
It's available on the DesignHandbook repository. I am having trouble
finding it right now since I'm mobile.

On Friday, March 27, 2015, iamjessklein <notifications@github.com> wrote:

> @vazquez <https://github.com/vazquez> can you share with me that design
> qa document that you started on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/teach.webmaker.org/issues/441#issuecomment-87092989>
> .
>


-- 
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by iamjessklein** [comment]
The QA  checklist for design can be found [here](https://github.com/MozillaFoundation/Mofo-Design-Handbook/issues/15) for future reference. I am copying and pasting everything below for good measure.

Step 1: Visit the staging site 
Step 2: Methodically go through each page and identify design bugs and inconsistencies, using the checklist below as a guide.
Step 3: Go to this repo and file a new issue with the design concern that you identified. Whenever possible include a screenshot and the name of the device and browser that you are using. 
Step 4: Give your github issues the [QA](https://github.com/mozilla/teach.webmaker.org/labels/QA) label.

<strong>Cross-Browser</strong>

- [ ] Displays & functions correctly in IE10
- [ ] Displays & functions correctly in Firefox (latest 2)
- [ ] Displays & functions correctly in Chrome (latest 2)
- [ ] Displays & functions correctly in Safari (7+)
- [ ] Displays & functions correctly on Mobile Safari (7+)
- [ ] Displays & functions correctly on Mobile Chrome (latest)
- [ ] Displays & functions correctly on Mobile Firefox (latest)

<strong>Content and Typography</strong>
- [ ] The use of H1, H2, and H3 headings is appropriate
- [ ] There are no outlier fonts
- [ ] All screen prompts are specified in the correct screen font
- [ ] All text is properly aligned
- [ ] All text free from spelling and punctuation errors
- [ ] Content has been placed consistently
- [ ] Content is marked-up semantically
- [ ] List styles are consistent
- [ ] There are no broken links
- [ ] Line height is appropriate
- [ ] Letter-spacing is appropriate
- [ ] Ensure all the content for respective words to be in lower and upper case
- [ ] Copy is clear, concise, and meaningful

<strong>Images</strong>
- [ ] Are all graphics properly aligned?
- [ ] Are graphics being used the most efficient use of file size?
- [ ] Are graphics optimized for quick downloads?
- [ ] Does text wrap properly around pictures/graphics?
- [ ] Is it visually consistent even without graphics?
- [ ] Images have appropriate alt text
- [ ] SVG assets are being used where possible
- [ ] Favicon has been created and displays correctly

<strong>Forms and Instructions</strong>
- [ ] Are all error messages text spelt correctly?
- [ ] Are all micro-help text (i.e tooltip) spelt correctly?
- [ ] Do forms have placeholder information?
- [ ] Do forms have success states?
- [ ] Are labels properly aligned?
- [ ] Form elements span full width when in mobile layouts

<strong> Other UI Elements</strong>
- [ ] Buttons contain border-radius
- [ ] Buttons contain box-shadow
- [ ] Buttons contain inset box-shadow
- [ ] Button text is properly aligned
- [ ] Buttons have a hover state
- [ ] Buttons have an active state
- [ ] Links have a hover state

**Comment by iamjessklein** [comment]
@vazquez @sabrinang and I did a design review, and filed issues. Next step = fixing those issues.

**Comment by iamjessklein** [comment]
The QA is complete, we are now just triaging the bugs. :bug:
