### ISSUE TITLE
[MIGRATED] Kick-off call with Q2 testers

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#456]
Goal: Have a kick-off call(s) with 200 Q2 testers. 

Agenda could include: 
* Elements from Teach like Mozilla module to on-board. 
* Option to test i) privacy module, ii) Webmaker app extension, or iii) Web Lit Basics.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/106"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/106.
Please don't comment on it here.
