### ISSUE TITLE
  Design scalable solution for Web Lit Curriculum on Teach site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#457]
### RACI ###
Driver: @hannahkane
Design Lead: ??
Decision-maker: @chrislarry33 
Consulted: @cassiemc @thornet @LauraHilliger 

The v1 of the Teach site displays the Clubs Curriculum here: http://teach.mofostaging.net/clubs/curriculum/

We specifically designed the page to show off the first module (module = six activities) that was thoroughly tested by community members.

Now we need to design a solution that will accommodate the Curriculum as we add new modules.

(from comment below)

1) We are designing a solution that will accommodate any future amount of Web Lit curriculum (whether Mozilla-created, or user-submitted). That likely means the content should be searchable and filterable, rather than just scan-able.

2) This was not intended to necessarily be a solution for the Teach Like Mozilla curriculum, though perhaps it will be broadly applicable enough to work there as well. I would not consider that a requirement.

3) Based on initial user testing results, I think we should combine the Teaching Activities content and the Clubs Curriculum content. After all, each of the activities within the Clubs Curriculum is a Teaching Activity! The design needs to preserve (and promote!) the ability to see a "Clubs Curriculum" view of content, though. (A good metaphor is a recipe site, where any given recipe might also belong to a "menu".)

4) The filterable piece should be based on the Web Literacy map, among other facets (including skill level, recommended age group, duration, etc.)

**Comment by iamjessklein** [comment]
Can @LauraHilliger @thornet @chrislarry33 or @hannahkane  give me a sense of how much content will go here and if there is any system or framework currently in place to organize that content?

**Comment by hannahkane** [comment]
You can see the curriculum plans here: http://mozilla.github.io/webmaker-curriculum/. Eventually the Clubs Curriculum page will include all of the Web Literacy content, though I think the "Teaching and Leadership" curriculum likely fits better on the Teach Like Mozilla page. @LauraHilliger and @thornet to confirm.

**Comment by LauraHilliger** [comment]
The curriculum plans page is outdated, we need to be more refined in that (hence issue #91), but it gives an idea.

Might be 2 solutions necessary:

### Solution 1: Curriculum for end learners (web literacy)
This one has 2 components to think about (though a "playlist" kind of idea might solve the distinction)
* *Teaching Activities* – free-for-all, random curriculum from all over the  place. All aligning to the Web Literacy Map. Currently curated by staff / community, eventually curated via annotative features(?)
* *Club Curriculum* – Still teaching activities, but specifically reviewed, remixed and scaffolded for Clubs. They look different, but [this is still a Teaching Kit](http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/index.html) and this is [still an Activity](http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-kraken.html).

### Solution 2: Curriculum for professional development ('open fluency' - meta-naming TBD)
* *Teach Like Mozilla* curriculum – Slightly different in that the main CTA is to interact w/ the curriculum as a learner, and the secondary CTA is to 'train the trainer' w/ the curriculum (reversed from the Web Lit stuff). This is the evolution of the [Webmaker Training curriculum](http://training.webmakerprototypes.org) and will include Teaching Kits for that train the trainer component.

The organizing framework for TLM will be something like this:

![webliteracy-lens-open-fluency](https://cloud.githubusercontent.com/assets/539017/7063689/174006ac-dea9-11e4-9949-0d598a394f79.png)

and I'm happy to help out @iamjessklein!!

**Comment by iamjessklein** [comment]
Can you clarify for me - are we creating ALL of the curriculum here, or are we creating a portion of it, the featured portion, and then hoping that users will contribute their own curriculum as well?

**Comment by jgmac1106** [comment]
I would assume the curriculum,  at least the first basics modules, would
have activities for each competency.

Maybe down the road somewhere on the page we could add a "community created
resources" and this will have kits and activities from mentors that the
Learning Network team approves. Then there could be a section for "outside
resources" and this would be a link to any thing tagged using the web lit
mapper for the corresponding skill or competency.

I hope I am even talking about the right thing. Getting a little lost in
the "club curriculum," "web journey, " and" train the trainer/PD/leadership
development" elements of the discussion.

**Comment by LauraHilliger** [comment]
+1 to Greg

We are working with community and partners to create curriculum that covers the map. Specific activities are curated into Club curricular arcs. Additionally, we continue to see people producing their own curriculum (like the Hive Toronto Privacy stuff), sometimes we use it for clubs arcs, sometimes it's curated as for "Teaching Activities" section.

We hope that our future organizing structures and tools encourage other people to submit curriculum for teaching web literacy. Tooling for that is TBD (e.g. web lit mapper, community curation tools, submission processes, remixability etc)

We are currently creating all of the Teach Like Mozilla stuff, though we are working *across Mozilla* with this effort.

**Comment by hannahkane** [comment]
I'd like to add some details about the scope and requirements of this ticket.

1) We are designing a solution that will accommodate any future amount of Web Lit curriculum (whether Mozilla-created, or user-submitted). That likely means the content should be searchable and filterable, rather than just scan-able.

2) This was not intended to necessarily be a solution for the Teach Like Mozilla curriculum, though perhaps it will be broadly applicable enough to work there as well. I would not consider that a requirement.

3) Based on initial user testing results, I think we should combine the Teaching Activities content and the Clubs Curriculum content. After all, each of the activities within the Clubs Curriculum is a Teaching Activity! The design needs to preserve (and promote!) the ability to see a "Clubs Curriculum" view of content, though. (A good metaphor is a recipe site, where any given recipe might also belong to a "menu".)

4) The filterable piece should be based on the Web Literacy map, among other facets (including skill level, recommended age group, duration, etc.)

**Comment by jgmac1106** [comment]
@hannahkane great ideas and thanks for the clarification. I wonder though
if drop down menu would work better than tagging. Look at the activities in
the current gallery. Tagging is a mess.

We spent a lot of time debating skill level with the map. Good amount of
talk of this being subjective, but I think well intentioned folks could
agree on activities and kits being basic, intermediate, and advanced.

It seems the second round of Club curriculum will be much more themed based
rather than an overview of specific categories. So we are doing menus
already.

I dig the metaphor.

**Comment by hannahkane** [comment]
Thanks, @jgmac1106. I don't think I specified tagging anywhere, and if I did, I didn't mean to. I try to leave UX questions pretty open so that UX designers can come up with a variety of ideas for the rest of us to respond to.

**Comment by jgmac1106** [comment]
Yeah the tagging and gallery  it was my only reference point. I left more
detailed feedback as a comment on your blog but this seems to be an issue
with users. They are looking for an easy navigable library of resources.

**Comment by thornet** [comment]
+1 to all of Hannah's points. I like the menu metaphor.

**Comment by LauraHilliger** [comment]
> This was not intended to necessarily be a solution for the Teach Like Mozilla curriculum, though 
> perhaps it will be broadly applicable enough to work there as well. I would not consider that a 
> requirement.

I think the solution will / should be applicable to the TLM content because:

> A good metaphor is a recipe site, where any given recipe might also belong to a "menu"

This is the same for the TLM curriculum. The difference between these two streams is the intended delivery and audience, but that modular, customizable model is the same.

I think we should make it a requirement that both streams of curriculum are scalable and that they use the same mechanisms / display features. I worry that if we have 2 batches of curriculum on the site, using 2 display strategies, users AND makers will be confused.

@iamjessklein Happy to help you think around / provide feedback / explain mo' betta for this tricky design problem!

**Comment by LauraHilliger** [comment]
throwing @soapdog into the mix in relation to Club guides

**Comment by hannahkane** [comment]
I'd really like to keep this issue narrowed to the Clubs Curriculum page. I'm sure the solution will be very similar to what we use for TLM, but there may be some differences (examples I can think of include different search filters, perhaps a different emphasis on user-submitted content).

I think it's important that we keep individual tickets as narrow as possible, as a best practice.

**Comment by LauraHilliger** [comment]
good point on different filters. We'll file a remix ticket when the time comes. Thanks @hannahkane

**Comment by chrislarry33** [comment]
Hi all, I think much of this is why we have the job listing for the curriculum product director position, so I don't want to walk to far down this road. I am much more concerned about getting disparate content collected, organized and annotated. And then having that immediately service the production of smaller units of content that are immediately helpful for our network of clubs, hives and practitioners i.e. the "Your first month of club" or "Running a great Hive meet-up"

**Comment by hannahkane** [comment]
Just to be clear, this ticket has nothing to do with producing content. It's purely a UX ticket. I think I'm actually going to close it, because it seems to have caused a lot of confusion. Am going to open a new ticket to clarify.
