### ISSUE TITLE
Determine solution for integrating Webmaker blog into Teach site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#458]
### RACI ###
Driver: @hannahkane
Design lead: ???
Decision maker: @chrislarry33 
Consulted: @ldecoursy @LucyeoH @amirad @thornet 

### Deliverable ###
 * A decision about whether to link, integrate, or build 
 * Design for whichever solution we choose

**Comment by hannahkane** [comment]
Discussed this with @ldecoursy, @amirad, and @HPaulJohnson yesterday. We like the idea of embedding a feed of Webmaker blog articles that have been tagged with "teach."

@chrislarry33 - how does that sound to you?

 cc @sabrinang and @iamjessklein who will eventually do the design work for this. We'll do the actual design work in a later heartbeat, but wanted you to see this in case you have any flags about this approach.

**Comment by iamjessklein** [comment]
We should consider where this content will be embedded. I think that it would make the most sense to add it to primary navigation and then have recent and featured posts highlighted on the landing page.

![screen shot 2015-04-02 at 10 48 18 am](https://cloud.githubusercontent.com/assets/535012/6966334/4844083a-d926-11e4-975c-c729b620df2c.png)

**Comment by ldecoursy** [comment]
+1

**Comment by hannahkane** [comment]
wfm

**Comment by amirad** [comment]
+1

**Comment by hannahkane** [comment]
I'mma close this because we figured it out. Design and implementation will show up in an upcoming heartbeat.
