### ISSUE TITLE
Implement Google OAuth2 on Discourse

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#461]
Goal : upgrade Google's OpenID authentication on Discourse. Google will be ending support for OpenID by April 20, 2015. We need to start using Google OAuth2 as soon as possible. See this guide to learn more: https://meta.discourse.org/t/configuring-google-oauth2-login-for-discourse/15858

Driver: @hannahkane 
Decision:@laurahilliger
Lead design: n/a
Lead dev: @toolness 
Quality: @laurahilliger 

Whomever takes on this task – I can give you the admin rights in Discourse if you don't already have them.

**Comment by toolness** [comment]
Er, since Webmaker login uses OAuth2 too, should we just use Webmaker login for the Discourse? An advantage of this is that usernames on discourse would be guaranteed to be the same as usernames on webmaker (though I'm not sure what a good migration strategy would be).

**Comment by toolness** [comment]
To clarify, having a 1:1 mapping between Webmaker users and Discourse users could have lots of benefits--for instance, it would allow us to show a mentor's latest Discourse posts in their user profile on the Teach site. With Google login that's completely independent of the Webmaker account system, there's no way to do that.

**Comment by LauraHilliger** [comment]
We did build a webmaker login for Discourse, it still works :)

I've always had mixed feelings on the idea of removing social logins completely, but it's probably time. Guessing @thisandagain or @adamlofting knows something about conversion rates in relation to social media sign-ons. If we're happy with the drop* in signups, I would say we should ditch google, implement OAuth2 and ping @hannahkane just so she knows the wider scope of embedding Discourse ;)

* based on personal practices, I'm assuming there's a drop whenever a site doesn't use social media signons

**Comment by toolness** [comment]
Yeah, what I'm talking about is really [Discourse SSO](https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045), which is distinct from the current system. As an example, the Hive Directory provides a Discourse SSO endpoint for the Hive Discourse, which means that there is an enforced 1:1 mapping between the two userbases.

With an *optional* Webmaker login it means that someone's username in the Discourse isn't necessarily their username on Webmaker, which could lead to confusing situations (for instance, someone else could have logged in via Google auth and taken a Webmaker user's preferred username).

In any case, I suspect there will be things you'll want to do in the future that create a more seamless experience between Discourse and the Teach site (and/or the rest of Webmaker in general), but these things will be a lot harder (or even impossible) if Discourse uses a completely different user table than the rest of Webmaker.

There's also some evidence from an [old post by Crystal Beasley](http://skinnywhitegirl.com/blog/how-people-think-facebook-connect-login-logout-work/861/) that one sign-in system is better than two (or more):

> As much as your business case allows, use only one identity provider. If you’re using Facebook Connect, don’t have a standard log-in. Too often, two log-in systems are less than the sum of their parts.

**Comment by toolness** [comment]
Um, all that said, just upgrading to Google OAuth2 will likely be very easy. In fact, I'm guessing that it probably just requires upgrading Discourse and maybe changing a few configuration settings in the Admin panel. In contrast, changing Discourse to use Webmaker SSO will require writing code, and also figuring out a migration strategy for all our current users who are logging in via Google. So given all our other priorities, I guess we should probably just do the Google thing.

**Comment by LauraHilliger** [comment]
@toolness can you do the update, then close this bug? I've filed this to track the bigger convo: https://github.com/MozillaFoundation/plan/issues/420

**Comment by davidascher** [comment]
cc @acabunoc who probably has a similar issue w.r.t. science's discourse
setup.
​

**Comment by toolness** [comment]
Ok, it's done! I granted @LauraHilliger and @jbuck ownership access on the Google OAuth2 Project in case anything ever needs to be changed with it and I'm not around... I tried giving @simonwex ownership too but it said "an error occurred" :(
