### ISSUE TITLE
Finalize the header for the Webmaker blog visual refresh

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#462]
Roberto did some great work on a refresh of the design. Before we can implement, we need to make some changes to the header based on branding conversations. @HPaulJohnson - can I hand this to you to finalize before we move to implementation?

Design files are available here: https://bugzilla.mozilla.org/show_bug.cgi?id=967770
Redpen here: https://redpen.io/p/pkfbf34a0e1d1ab57e

**Comment by HPaulJohnson** [comment]
Works for me, thanks. @KevZawacki and I are working on header copy now and will share ideas here soon.

**Comment by KevZawacki** [comment]
Here are three suggestion from @HPaulJohnson and me regarding header/subhead copy:

Mozilla Learning
Where Web teachers, learners and makers come together

Mozilla Learning
People, products and programs to teach, learn and make the Web 

Mozilla Learning
Teaching web literacy through global communities and the Webmaker app

**Comment by hannahkane** [comment]
Sweet. Thanks.

@chrislarry33 @ldecoursy @amirad - opinions?

**Comment by amirad** [comment]
There's a lot of comma's but the **middle one** seems best to me. The emphasis on web teachers feels too educator to our audience and we've learned that people don't necessarily resonate or get what web literacy is without us defining it. 

Mozilla Learning
People, products and programs to teach, learn and make the Web

**Comment by ldecoursy** [comment]
+1

**Comment by hannahkane** [comment]
OK, I'm going to call this good, since we've agreed on copy for the header. Implementing the refresh with the revised copy will be in an upcoming heartbeat.
