### ISSUE TITLE
double check teach site design inconsistency

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#464]
:warning: The main pages of Teach have a big, nice header EXCEPT for the Teaching Activities page, which, though top level, matches the sub pages in layout.

just struck me as odd, and I'm not sure it was intentional

**Comment by iamjessklein** [comment]
Thanks for flaggin @LauraHilliger - we are doing design qa this week. I am going to add this to the milestone and product tag for review.

cc/ @vazquez @sabrinang @hannahkane

**Comment by hannahkane** [comment]
Resolved.
