### ISSUE TITLE
Conduct user testing on staging site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#468]
User test script is here: https://docs.google.com/a/mozillafoundation.org/document/d/11TZH_HBmCo4D9MaYcAW-eHz4cXRVnAxfap0rRBa4O0s/edit#

@iamjessklein to conduct tests in NYC office + one community member (I'll email you with contact info)

@hannahkane to conduct tests with two add'l community members

**Comment by iamjessklein** [comment]
I am scheduled to do testing in the Brooklyn office on Thursday, April 2. :clock1: :watch:

**Comment by hannahkane** [comment]
I have a test scheduled for Thursday.

@iamjessklein - how did last Thursday's testing go?

**Comment by hannahkane** [comment]
I have a second test scheduled for Thursday.

**Comment by iamjessklein** [comment]
The Thursday test was a bit of a fail because everyone who showed up had already tested the site. Working on a do-over on Friday.

**Comment by jgmac1106** [comment]
I would have no problem giving you a litany of complaints once the staging
is done. Have really only checked out the page on @toolness softest of
launch mock up. Though I want it noted for posterity that the Learning
Network team labeled it a slaunch first.

**Comment by iamjessklein** [comment]
:pen + :notebook:  = noted

**Comment by hannahkane** [comment]
Closing this as we've completed a minimum amount. This now becomes an ongoing task.
