### ISSUE TITLE
Design Teach site referral from Webmaker.org

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#469]
The implementation ticket is in the webmaker repo and will happen in a later milestone: https://github.com/mozilla/webmaker.org/issues/1377#issuecomment-88168688

I thought I'd put the design ticket in this repo, so that it's in the backlog for the Teach team's current milestone. Will let Teach team designers and Webmaker product team make decisions about the best way to promote the Teach site from Webmaker.org (tab? button? ad?).

### RACI ###
Design Lead: @sabrinang or @iamjessklein 
Decision-makers: @cassiemc @thisandagain @secretrobotron

**Comment by iamjessklein** [comment]
@cassiemc @thisandagain - how do you feel about using the "promo content" real estate that we used for Privacy Day for this and updating the teaching link in the fat footer to go to the site ( it currently directs to training.webmakerprototypes.org)?

![screen shot 2015-04-01 at 12 27 17 pm](https://cloud.githubusercontent.com/assets/535012/6945863/b5d8db8a-d86a-11e4-947a-8c8a829f574c.png)

![screen shot 2015-04-01 at 12 27 09 pm](https://cloud.githubusercontent.com/assets/535012/6945866/b91e1d1e-d86a-11e4-8513-1a8e3819ea0a.png)

**Comment by thisandagain** [comment]
Yup! That seems ideal. :+1:

**Comment by cassiemc** [comment]
+1

**Comment by iamjessklein** [comment]
awesome, thanks! :hibiscus:

**Comment by iamjessklein** [comment]
@hannahkane @ldecoursy - can you please provide the copy for this section? It should include:

- [ ] title
- [ ] descriptive sentence(s)
- [ ] cta on button

**Comment by iamjessklein** [comment]
@sabrinang  [here are the design files](https://www.dropbox.com/s/rpbrqlnbn6e0odd/teach-referral.ai?dl=0) for you to work from.

**Comment by KevZawacki** [comment]
@iamjessklein @hannahkane @ldecoursy 

Possible copy to get the ball rolling:

Title: Already a Pro? Start Teaching Others
Description: Join Mozilla's community of educators who teach digital skills and web literacy through making.
Button text: Start Teaching

**Comment by iamjessklein** [comment]
:heart: this direction

**Comment by ldecoursy** [comment]
Alternate title suggestions: Want to teach the web to others? or Teach others about the wonders of the web

Might want to say "educators and mentors" or just "mentors"?

**Comment by sabrinang** [comment]
I made a few iterations on [Red Pen](https://redpen.io/p/qrad2d47304f4b313e) and here are two directions I like:

![teach-referral1](https://cloud.githubusercontent.com/assets/2492510/7079167/20d9e6b0-ded6-11e4-9cdf-3d83d732d5cd.png)
![teach-referral2](https://cloud.githubusercontent.com/assets/2492510/7079168/221b4f96-ded6-11e4-9c94-8c4b2bdf5594.png)

**Comment by jgmac1106** [comment]
I would lose the "through making"  at the end of a sentence. Sentence seems
wordy but I do have a bias against most modifiers.

**Comment by jgmac1106** [comment]
And do we want to use the word mentor instead of educators to let folks
know it is open to informal learning spaces?

**Comment by hannahkane** [comment]
I'm going to designate some decision-makers:
 - @KevZawacki and @ldecoursy - can you guys decide on final copy?
 - @sabrinang @iamjessklein and @vazquez  - can you make the final decision on design/colors, since @cassiemc is out?

Thanks!

**Comment by KevZawacki** [comment]
I vote for @sabrinang's first version ("Want to teach the web to others?") 

Note: We should be capitalizing "Web" throughout. And I think it's a good idea to tighten up the text by dropping "through making."

**Comment by jgmac1106** [comment]
Especially given recent data on the FB adwords. Making as learning seems to
be a topic folks must be taught.

**Comment by iamjessklein** [comment]
The gray background seems to be the most on brand. @sabrinang can you provide a mockup with the 2 different patterns on 2 gray backgrounds so we can make a decision from those?

**Comment by sabrinang** [comment]
## Preview
![teach-referral-patterns](https://cloud.githubusercontent.com/assets/2492510/7098433/2a203138-df95-11e4-8447-8568b837d64d.png)

## Downloads
You can download all these (transparent .png) patterns here: 
small white pattern: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eS1ZDMzh4cEl5V0E/view?usp=sharing
small grey pattern: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eeUo3STNZSVhjbFE/view?usp=sharing
large white pattern: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eSXpZUTk1bm1rTVU/view?usp=sharing
large grey pattern: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_edC1jdWRDOV9ZUk0/view?usp=sharing

## Mockups
### small white pattern mockup
![teach-referral-27](https://cloud.githubusercontent.com/assets/2492510/7098532/795ee93c-df96-11e4-8512-a71b7cff615a.jpg)

### small grey pattern mockup
![teach-referral-24](https://cloud.githubusercontent.com/assets/2492510/7098529/795c87be-df96-11e4-990b-5273bd6cc6ad.jpg)

### large white pattern mockup
![teach-referral-26](https://cloud.githubusercontent.com/assets/2492510/7098530/795e0742-df96-11e4-8d21-1e359694a486.jpg)

### large grey pattern mockup
![teach-referral-25](https://cloud.githubusercontent.com/assets/2492510/7098531/795e8758-df96-11e4-9952-a4b0b6884764.jpg)

**Comment by iamjessklein** [comment]
@cassiemc - can you take a look at these? :eyes:

**Comment by cassiemc** [comment]
Yes, they're great! I like the small white on grey -- feels like it conflicts less with the text.

**Comment by hannahkane** [comment]
Wondering if we can close this ticket now, or if there is more work needed?

**Comment by cassiemc** [comment]
Ready to close if @sabrinang can just post the final design and assets here, for clarity.

**Comment by iamjessklein** [comment]
@cassiemc Here is the final asset that @sabrinang provided:
small white pattern: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eS1ZDMzh4cEl5V0E/view?usp=sharing

:shipit:

**Comment by cassiemc** [comment]
Great, thanks @iamjessklein! Let's close. Here's the final design:
![teach-announce-small-white](https://cloud.githubusercontent.com/assets/1186326/7125625/8c4247b2-e200-11e4-8f5a-19ee44b5b713.jpg)

**Comment by hannahkane** [comment]
@HPaulJohnson - do you mind if we DON'T capitalize "web" in the above? I think it will be the better aesthetic choice in this case. (Asking you because I know @KevZawacki is on PTO.)

**Comment by HPaulJohnson** [comment]
Works for me (i.e. I don't mind).

**Comment by mmmavis** [comment]
@sabrinang could you tell me what font sizes I should be using?

**Comment by mmmavis** [comment]
@sabrinang  is the heading in `@brand-secondary` or `@lightnavy`?

**Comment by sabrinang** [comment]
Title: 36px Open Sans Regular #01527D @lightnavy
Description Copy: 21px Open Sans Light #4d4e53 @grey

**Comment by mmmavis** [comment]
thanks @sabrinang !

just wanted to confirm - should the button text be in all caps or camel case?

**Comment by sabrinang** [comment]
Oh thanks for pointing that out - use the existing button styles so use capitals

**Comment by mmmavis** [comment]
:dancers:
