### ISSUE TITLE
LANDING: Image needs to be re-treated or replaced

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#471]
It's quite dark.
![screen shot 2015-03-31 at 3 52 07 pm](https://cloud.githubusercontent.com/assets/535012/6927809/eba6ae3e-d7bd-11e4-9eff-2e9f0360a6b8.png)

**Comment by sabrinang** [comment]
Some options on photographic banner treatments that removes the colour tints and corner decoration:

dark overlay
![banner-iteration2](https://cloud.githubusercontent.com/assets/2492510/6953855/2b86fe14-d881-11e4-8e8b-6b8f9a2e9434.png)

blur with dark overlay
![banner-iteration](https://cloud.githubusercontent.com/assets/2492510/6953856/2c79b3a2-d881-11e4-96df-7055ad4b7d31.png)

dark overlay in the centre
![banner-iteration3](https://cloud.githubusercontent.com/assets/2492510/6953857/2d9eade6-d881-11e4-971c-e4f29cb6a5df.png)

**Comment by iamjessklein** [comment]
@vazquez

**Comment by vazquez** [comment]
I personally prefer option 2. Blur with Dark Overlay. It is what I have right now on /teach-like-mozilla. I think it works great. We would still have to source new images that have a better composition, but I do think that the blurring makes the text crisp and easy to read.

**Comment by iamjessklein** [comment]
My preference is the 3rd option. Since the goal of the site is to bring a face to the community of educators, we should be highlighting (vs. blurring) out the identities of the individuals. That said, the blurring treatment is the best option for heading legibility. 

@hannahkane @ldecoursy thoughts?

**Comment by hannahkane** [comment]
I'd prioritize legibility, so I'd vote for option 2.

**Comment by ldecoursy** [comment]
I also prefer #3, but is there a way to crop the image a bit to rid of some of the white space at the top of the photo? Also the teach like mozilla page seems only blurred on one side, and the events doesn't have any blur.

**Comment by sabrinang** [comment]
I tried a mixture of option 2 & 3 where the center has a dark overlay and blur effect applied to it.
![herobanner-treatment](https://cloud.githubusercontent.com/assets/2492510/7036179/e0488458-dd45-11e4-9e88-88dbf64af43d.png)

**Comment by hannahkane** [comment]
+1

**Comment by ldecoursy** [comment]
+1

**Comment by iamjessklein** [comment]
:+1:  nice. I would just test that when we place the foxy image, if it needs to be dodged and burned or touched up in the center top area.  Let's move forward with these files. Can you share the final image files?

**Comment by sabrinang** [comment]
Photos (original and 2x size) can be found here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efndNS2hoYXM3allJYm5mQ1RCamMxbS1pVjc0Qm56YVhqdE1penRMc1paZFU&usp=sharing

reassigning to @iamjessklein to implement
