### ISSUE TITLE
LANDING: Descriptive copy should be added

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#472]
At the moment there is no substantive content that explains what the goal of the site is, and what people can expect to do here.

This is all of the content on the page:

![screen shot 2015-03-31 at 3 55 12 pm](https://cloud.githubusercontent.com/assets/535012/6927891/62c3bdc2-d7be-11e4-84cc-bc537a2fe0ef.png)

**Comment by hannahkane** [comment]
Will be addressed in an upcoming homepage redesign ticket.
