### ISSUE TITLE
TEACHING ACTIVITIES: Side panel should be pink

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#474]
The side panel here should be pink (not blue).

**Comment by hannahkane** [comment]
@ldecoursy raises a good point. Why is it the same color as the homepage?

**Comment by iamjessklein** [comment]
@hannahkane @ldecoursy it shouldn't be - the home page will be blue and this page will be pink.

**Comment by hannahkane** [comment]
Ah, ok, got it. Thanks!

**Comment by iamjessklein** [comment]
This will be fixed once @ScottDowne reviews this PR: https://github.com/mozilla/teach.webmaker.org/pull/614
