### ISSUE TITLE
TEACHING ACTIVITIES: Labels and globe illustration should be pink

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#475]
They are currently blue, but will need to match the sidebar color changes referenced in #474

**Comment by iamjessklein** [comment]
Let's decouple the globe from the labels and only deal with the globe in this issue. 

Globe: 

![screen shot 2015-04-07 at 1 15 19 pm](https://cloud.githubusercontent.com/assets/535012/7029032/46628d6a-dd28-11e4-9efc-d009eb28cd25.png)

**Comment by sabrinang** [comment]
![img-globe-line-pink](https://cloud.githubusercontent.com/assets/2492510/7032110/3f792656-dd25-11e4-9cc9-61a9e75d9724.png)
Pink line: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eNkdvUHdHNDNvdWs/view?usp=sharing
![img-global-movement-pink](https://cloud.githubusercontent.com/assets/2492510/7032105/32884daa-dd25-11e4-8697-91a6134ae2a4.png)
Pink globe illustration: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eLThBZTNKaEZNeEU/view?usp=sharing

**Comment by sabrinang** [comment]
ready to be updated - reassigning to @iamjessklein

**Comment by iamjessklein** [comment]
great. I fixed the labels with the sidepanel PR. Will work on this one.
