### ISSUE TITLE
TEACHING ACTIVITIES: Condense or remove "more resources"

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#477]
The "More Resources" section feels like it doesn't have a natural relationship to the rest of the content on the page. We should decide if we want to condense it by removing all of the individual clubs links and just linking out to the Hive Networks site or if we should remove it completely as the Hive logo is in the footer. cc/ @hannahkane @ldecoursy 
![screen shot 2015-03-31 at 5 05 07 pm](https://cloud.githubusercontent.com/assets/535012/6929395/6662eab6-d7c8-11e4-9327-3eac0ae256f2.png)

**Comment by ldecoursy** [comment]
We wanted a place to more overtly connect some of the Hive content - these should link to individual city portfolio pages - not currently another place to get directly to that.

**Comment by iamjessklein** [comment]
What about linking to [the locations page](https://hivelearningnetworks.org/locations/) on Hive Learning Networks site?  My concern that this list is going to grow and misrepresent that the Hive is a global initiative.

**Comment by ldecoursy** [comment]
These links go directly to existing portfolios so people can find additional programs/projects/curriculum/etc. while they're on a page to find teaching activities. Tried to make that clear in the copy but let me know if that's not working. I don't think linking to the locations page will be helpful here - the relevant info will be way too buried. Longer-term, I think we'll uplevel more Hive content directly onto this page of a la carte activities...

**Comment by iamjessklein** [comment]
After discussing this with @ldecoursy this appears to be a temporary measure to surface Hive content in a non-dynamic way. I am closing this issue and will readdress when more content becomes available and we work on the larger curricular content organization.
