### ISSUE TITLE
EVENTS: More images need to be added to the carousel

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#479]
Either more images should be added or one image should be removed - a slide carousel with 2 images feels pretty weak. 
![screen shot 2015-03-31 at 5 12 03 pm](https://cloud.githubusercontent.com/assets/535012/6929494/2a5af454-d7c9-11e4-8664-91bfac5f0c10.png)

**Comment by hannahkane** [comment]
How many should we have?

**Comment by iamjessklein** [comment]
If we are keeping the carousel - a minimum of three.

**Comment by hannahkane** [comment]
What about this as a third? https://www.flickr.com/photos/mozilladrumbeat/14710363742/in/set-72157647527636985

**Comment by sabrinang** [comment]
If we need a fourth: https://www.flickr.com/photos/newyouthcity/14715964794/in/faves-mozilladrumbeat/

@iamjessklein Does the carousel take the images directly from flickr? If yes, we do not need to edit the photos then?

**Comment by hannahkane** [comment]
pinging @iamjessklein to make sure this issue keeps moving :)

**Comment by iamjessklein** [comment]
It pulls the images from flickr, so they don't need to be uploaded, just linked to by @mmmavis

**Comment by mmmavis** [comment]
@iamjessklein are we pulling images from a Flickr album? a photostream? or? Could you link me to the collection? :rabbit:

**Comment by iamjessklein** [comment]
@mmmavis we appear to be linking to a few individual photos.
* https://www.flickr.com/photos/newyouthcity/14715964794/in/faves-mozilladrumbeat/
* https://www.flickr.com/photos/mozilladrumbeat/14710363742/in/set-72157647527636985
plus the two that are already there.

**Comment by mmmavis** [comment]
Hey @iamjessklein ,

So we are NOT pulling photos directly like a **feed** from the 2 links above, we preselected 4 photos and tell the carousel to link to the 4 photos on Flickr?

**Comment by iamjessklein** [comment]
@mmmavis - when I look at the existing code it seems like they are currently just linking to the 4 photos on flickr - no feed.
