### ISSUE TITLE
[MIGRATED] Design assets for Learning Pathways whitepaper

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#48]
Repo here: https://github.com/mozilla/learning-pathways-whitepaper/issues

Suggesting that @iamjessklein might like to spend a heartbeat thinking through ways we can visualise the different types of learning pathways we discuss in the whitepaper *(forthcoming)*

**Comment by dajbelshaw** [comment]
Specific issue is here: https://github.com/mozilla/learning-pathways-whitepaper/issues/26

**Comment by hannahkane** [comment]
What's the state of this? Is it still a need?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/25"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/25.
Please don't comment on it here.
