### ISSUE TITLE
EVENTS: Carousel images should be smaller 

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#480]
![screen shot 2015-03-31 at 5 12 03 pm](https://cloud.githubusercontent.com/assets/535012/6929648/80d63c2a-d7ca-11e4-828e-fd15dae6c6ff.png)

**Comment by iamjessklein** [comment]
this is related to issue #483 @sabrinang

**Comment by sabrinang** [comment]
Initial mockup for reference:
![screen shot 2015-04-06 at 10 22 39 am](https://cloud.githubusercontent.com/assets/2492510/7008393/0dc381da-dc47-11e4-8eca-1f3ae414a438.png)

**Comment by mmmavis** [comment]
@sabrinang 

For the carousel are we using what's on https://party.webmaker.org/ as a reference or http://getbootstrap.com/javascript/#carousel (Bootstrap, currently seen on staging: http://teach.mofostaging.net/events/)?

**Comment by mmmavis** [comment]
@iamjessklein 
Other than navigating the 4 photos in the carousel using the < and > controls, does the carousel have any other functionality? e.g., lightbox etc?  If we are only showing 4 photos I'm thinking maybe a carousel is not needed.

**Comment by iamjessklein** [comment]
@mmmavis I just looked at the carousel on party.webmaker.org and now understand the context for your questions. 

I think that we should just have the video and then the thumbnails below (no carousel) and then have the link to the flickr stream in the text below.

**Comment by mmmavis** [comment]
Does anyone know where the "Flickr gallery" goes to?

**Comment by hannahkane** [comment]
Looks like we link to this from current Maker Party site: https://www.flickr.com/photos/mozilladrumbeat/galleries/72157643962655534/

@admirad - can you confirm that's the right gallery to link to on the MP page of the new site?

**Comment by mmmavis** [comment]
@amirad ^ :smile:

**Comment by amirad** [comment]
admirad say's that it goes to that album of 18 of our top pictures. :P 
We have other albums with many more pictures or can even stream to #makerparty hashtag on flickr though those already curated by us album is probably best.

**Comment by hannahkane** [comment]
@hananah is sorry for the typo. :)

@amirad - can you pick an album that you like?

**Comment by amirad** [comment]
haha, we can just use that one you already linked to. (unless you want a scroll of hundreds of pictures)

**Comment by iamjessklein** [comment]
:carousel_horse:
