### ISSUE TITLE
EVENTS: Add mailinglist sign up form

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#481]
There is an itsy bitsy button underneath the carousel. It needs to be enlarged. It should link to the Clubs page. 
![screen shot 2015-03-31 at 5 25 07 pm](https://cloud.githubusercontent.com/assets/535012/6929718/08d23a7a-d7cb-11e4-8334-022a8177dea3.png)

**Comment by hannahkane** [comment]
This is actually meant to be the sign-up form you can see here: https://projects.invisionapp.com/share/TY2GT8GBX#/screens

**Comment by iamjessklein** [comment]
oops, sorry about that, yes, see here: 

![screen shot 2015-04-02 at 9 59 34 am](https://cloud.githubusercontent.com/assets/535012/6965394/1c6131ea-d91f-11e4-99e1-a0edaffc0e56.png)

**Comment by toolness** [comment]
@mmmavis want to take this one?

**Comment by mmmavis** [comment]
I have a WIP PR open: https://github.com/mozilla/teach.webmaker.org/pull/654

Question:
- is there any form validation library I should be using?
- need blue vertical bar asset to match the sidebar colour

**Comment by mmmavis** [comment]
@sabrinang @iamjessklein can either of you provide the vertical bar file? :blush:

**Comment by sabrinang** [comment]
you can find the vertical line here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eM05mRzB5cVN4RTQ/view?usp=sharing

**Comment by mmmavis** [comment]
@iamjessklein @sabrinang 
wondering if we have to include the privacy policy checkbox as well?

**Comment by iamjessklein** [comment]
I'm actually not sure about that. I would assume so. @hannahkane do you know?

**Comment by hannahkane** [comment]
Hmm...looks like we didn't do that on the Maker Party site, but, yes, we should include it here. Thanks!

**Comment by mmmavis** [comment]
We did include this line below the form @hannahkane :relaxed: , I'll just copy what we have there!

![screen shot 2015-04-13 at 11 20 34 am](https://cloud.githubusercontent.com/assets/2896608/7122267/2f9ec5d4-e1cf-11e4-83b3-f2d0805ae9ed.png)

**Comment by hannahkane** [comment]
I don't know why I didn't see that. Yes, please. :)

**Comment by iamjessklein** [comment]
I'm wondering if we should have this checked so that when someone clicks the button, it implies they agree with the privacy policy. This is the way it looks on the soon to be implemented login page:

![screen shot 2015-04-14 at 10 52 55 am](https://cloud.githubusercontent.com/assets/535012/7139448/7912137c-e294-11e4-9f7d-5cf8a88cf146.png)

**Comment by mmmavis** [comment]
@iamjessklein did you mean the ":heavy_check_mark: By signing up, I agree to...] becomes like a note instead of an option for users to toggle?

**Comment by mmmavis** [comment]
What happens after the form is successfully submitted?  Do we redirect users to a thank you page or ...?

**Comment by iamjessklein** [comment]
First of all, fantastic use of the :heavy_check_mark: emoji, @mmmavis - and yes, it's just a note vs. an additional action.

Second, yes, I was just looking and it doesn't look like a flow is mocked up, but we should have a confirmation of signup message. I will mock that up today.

**Comment by mmmavis** [comment]
Screencaps of the my [latest commit](https://github.com/mmmavis/teach.webmaker.org/commit/9b55f4e0d24d50b608f9f07b7285c5903e29eec5).  Note that the privacy policy link currently links to https://www.mozilla.org/privacy/websites/

![screen shot 2015-04-21 at 5 32 56 pm](https://cloud.githubusercontent.com/assets/2896608/7265317/8e510d7a-e84c-11e4-96db-6f0415bbb171.png)

The actual checkbox field is hidden from UI and is always set to "true".  So that "I'm okay with you handling this info as you explain in your privacy policy." just acts like a note.



![screen shot 2015-04-21 at 5 33 16 pm](https://cloud.githubusercontent.com/assets/2896608/7265319/906e4d7a-e84c-11e4-8b4a-03fb11660763.png)

I'm preserving the error message styling (font colour, border, background) that we used for the Club form.

**Comment by toolness** [comment]
Nice, this looks great Mavis! :+1:

**Comment by mmmavis** [comment]
(moving our techy convo from https://github.com/mozilla/teach.webmaker.org/issues/777#issuecomment-97565660 to here instead)

@toolness 

> Yep, that should work. Where is the configuration for the redirect stored? Does the form submitted to BSD contain a redirect URL as a hidden input, or is it configured in BSD somewhere?

I think it's stored in the backend somewhere.  This is the BSD from I created: https://sendto.mozilla.org/page/s/maker-party-signup-for-teach-site (please ignore the janky look).  Currently the redirect is set to `teach.mozilla.org` but I couldn't find it in that page's source code.

> Just curious b/c we might end up w/ a situation where e.g. user is on staging and signs up for the mailing list which redirects them to produciton--not that big a deal but might be a bit confusing/hard to notice.

If that really causes problem I guess we can have 2 identical BSD forms, one for staging and one for production?

**Comment by toolness** [comment]
Ok, no big deal! Let's just use the one BSD form for now, and if it ends up being a problem we can set it via an environment variable and have separate forms for staging/prod.
