### ISSUE TITLE
EVENTS: Video missing above the carousel

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#483]
This was in the initial mock-ups. If this is still the plan, we will need to identify the video and place it.

**Comment by hannahkane** [comment]
The video is here: http://www.youtube.com/watch?v=oko6TzPQE6Y

**Comment by iamjessklein** [comment]
Thanks @hannahkane - is this enough for @ScottDowne @toolness or @mmmavis to implement the fix?

**Comment by toolness** [comment]
Oh, sorry, I think I had assumed that video was just a photo that was part of the carousel widget...

**Comment by sabrinang** [comment]
Initial mockup for reference:
![screen shot 2015-04-06 at 10 22 39 am](https://cloud.githubusercontent.com/assets/2492510/7008377/f10271d2-dc46-11e4-9403-6a511e4dbd5e.png)
