### ISSUE TITLE
EVENTS: Add link to "Events Resources"

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#485]
The bottom left icon of the page with the words "Events Resources" should be linked.

**Comment by hannahkane** [comment]
blocked because the Events Resources page doesn't exist yet

**Comment by iamjessklein** [comment]
valid reasoning. :bulb:

**Comment by iamjessklein** [comment]
Can link now that @ScottDowne made the page! w00t :postal_horn:
