### ISSUE TITLE
TEACH LIKE MOZILLA: reconsider "hero" image

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#486]
![Uploading Screen Shot 2015-03-31 at 6.13.00 PM.png . . .]()

**Comment by hannahkane** [comment]
I don't see the screenshot. :(

**Comment by iamjessklein** [comment]
yikes - I was moving too fast for github!

![screen shot 2015-03-31 at 6 13 00 pm](https://cloud.githubusercontent.com/assets/535012/6945581/cb96b4f8-d868-11e4-95d4-5de595513f0c.png)

**Comment by hannahkane** [comment]
What's wrong with this image? I like it.

**Comment by sabrinang** [comment]
We will be using this image for now and it is treated in #471. Closing this bug and if there is a better photo we find we can reopen this.
