### ISSUE TITLE
TEACH LIKE MOZILLA: design the "learn icon" 

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#487]
![screen shot 2015-03-31 at 6 14 25 pm](https://cloud.githubusercontent.com/assets/535012/6930493/c99e8b0e-d7d1-11e4-875b-6a836c12e988.png)

The current image is a placeholder.

**Comment by sabrinang** [comment]
![icon-learn](https://cloud.githubusercontent.com/assets/2492510/6976744/e778e39e-d962-11e4-8eda-83967cf174e0.png)

This idea for the learn icon can be found here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eYjNueHp1ZjVGZ1E/view?usp=sharing

**Comment by sabrinang** [comment]
@iamjessklein what do you think of this learn icon?
/cc @vazquez

**Comment by iamjessklein** [comment]
@sabrinang why don't you try simplifying this by singling out the brain elements.

**Comment by sabrinang** [comment]
![icon-learning](https://cloud.githubusercontent.com/assets/2492510/7030466/bf2e7632-dd19-11e4-8986-6cdb712dd224.png)
Another alternative can be found here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_edlVzZm4xS09lUzA/view?usp=sharing

**Comment by sabrinang** [comment]
![icon-learning-green](https://cloud.githubusercontent.com/assets/2492510/7032420/8e3544da-dd27-11e4-8740-73d38789e0f6.png)
teach like mozilla page icons are green and updated the learn icon to match: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eZWZlVGVWdVZLbDg/view?usp=sharing
