### ISSUE TITLE
TEACH LIKE MOZILLA: Listen Icon - fix line weight

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#488]
Clean up the listen icon to unify the line width to match "say hello" icon

![screen shot 2015-03-31 at 6 16 13 pm](https://cloud.githubusercontent.com/assets/535012/6930535/2229d09e-d7d2-11e4-9f75-30f071f918de.png)

**Comment by sabrinang** [comment]
![icon-listen](https://cloud.githubusercontent.com/assets/2492510/6976035/b695ec7c-d958-11e4-84ef-9f3cc2d7dec7.png)

I unified the "listen icon" line width with the "say hello" icon.

You can find it here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eWWpPVG5HbF9VTHM/view?usp=sharing

**Comment by iamjessklein** [comment]
:point_up_2:  @sabrinang will reassign to myself
