### ISSUE TITLE
TEACH LIKE MOZILLA: add "mission" video

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#489]
Consider adding the Mozilla "mission" video that can be found here: https://www.mozilla.org/en-US/mission/ to this page.

**Comment by hannahkane** [comment]
@chrislarry33 @ldecoursy — can you guys weigh in on this?

**Comment by chrislarry33** [comment]
not sure its needed, @iamjessklein whats the reason to add?

**Comment by ldecoursy** [comment]
It's Ryan! ;) I think perhaps linking to the page makes more sense than embedding the video.

**Comment by iamjessklein** [comment]
Indeed . the voice. :microphone:  
It was on the original mockup and there was a request from @dajbelshaw to incorporate the Mozilla mission into the site. This page, in general is a little light on content, but if this is unnecessary

**Comment by hannahkane** [comment]
also cc @LauraHilliger who is organizing the future content on this page. I don't expect it will be light on content for long. It's going to be epic. :)

**Comment by iamjessklein** [comment]
I'm definitely not doubting the capabilities of this team to provide content ;)

**Comment by LauraHilliger** [comment]
Maybe write some marketing text about our plans for "teach like mozilla", e.g. training and professional development modules for people who want to teach the web. Could link out to preexisting things and explain that we're honing and refining our offering. 

QA point: I think it's kind of strange to say "learn" and send people to the Web Literacy Map. The map provides an organizing structure for Teaching Activities, whereas our in-development competencies for PD & training frames Teach Like Mozilla.

**Comment by iamjessklein** [comment]
@LauraHilliger - I've decoupled the QA note and added it to #544

**Comment by hannahkane** [comment]
I'm closing this ticket. The mission video is about the larger mission, and Firefox, so I think it would be confusing to have it on the "Teach Like Mozilla" page, which is about the educational aspect of our mission.
