### ISSUE TITLE
Teach the Web talk - 4th installment February

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#49]
Starting new issue around the next TTW Talk in February- with @LucyeoH 

- [x] review Januarys call and feedback from community
- [x] analyse all comms channels, discourse, twitter, wiki and hangout
- [x] Speaker shortlist required
- [x] Date for Feb talk confirmed

**Comment by LucyeoH** [comment]
February's TTW Talk Details: 

Shoot It - How To Use Photography To Tell Your Story
with JP Pullos from 100cameras on Thursday February 26th at 3pm ET,  12pm PT, 8pm GMT, 9pm CMT, 1:30am IST

Join us as we sit down JP Pullos the Photography Education Coordinator for 100cameras to find out how you can better use photography to share the story of your event, your work, or your organization.

100cameras is a non-profit that teaches kids to share their perspectives through photography and then turns their stories into sellable products that directly fund tangible change in their communities.

RSVP to the event here: http://mzl.la/100cameras

**Comment by LucyeoH** [comment]
You can see up to date data from the previous call, speaker shortlists and planning details for the upcoming talk here: https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1ZLe-40ZsYEem4hg5Tia6OR0RNeC0Xw0XHUIA5xuRL8c/edit#gid=0

**Comment by Saallen** [comment]
Discourse page for Febs TTW talk http://discourse.webmaker.org/t/teach-the-web-talk-shoot-it-how-to-use-photography-to-tell-your-story/1204

**Comment by ldecoursy** [comment]
Closing this since the call happened and was awesome!

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/26"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/26.
Please don't comment on it here.
