### ISSUE TITLE
TEACHING ACTIVITIES: Typo Hive Pittsburgh

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#490]
Typo: "hive pittsbergh" should be Pittsburgh

**Comment by hannahkane** [comment]
@KevZawacki started a pretty long list of typos, including this one. Wondering if we can add typos there, rather than filing a separate issue for each typo. 

https://etherpad.mozilla.org/TeachCopyEdits

**Comment by iamjessklein** [comment]
:+1:
