### ISSUE TITLE
WEB LITERACY: All blue elements should be converted to shades of green

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#492]
The blue tinted elements need to match the new side bar color : the tabs, the graphics, illustrations etc. 
![screen shot 2015-03-31 at 6 24 57 pm](https://cloud.githubusercontent.com/assets/535012/6930675/6405e736-d7d3-11e4-8739-17a9f1c372d6.png)

**Comment by mmmavis** [comment]
@iamjessklein could you provide the colour codes plz?

**Comment by hannahkane** [comment]
made obsolete by #1005
