### ISSUE TITLE
WEB LITERACY: Revise the "Read more" icon

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#493]
The m style does not match the rest of the icons, either restyle or redesign. 

![screen shot 2015-03-31 at 6 26 44 pm](https://cloud.githubusercontent.com/assets/535012/6930707/a2b61a1e-d7d3-11e4-9598-a21510005283.png)

**Comment by sabrinang** [comment]
![screen shot 2015-04-01 at 1 41 28 pm](https://cloud.githubusercontent.com/assets/2492510/6952152/d3e094ba-d874-11e4-8afc-ac0dd85df7b2.png)
An option is to make the "m" match the style by following the line art style seen in the other two. 

![icon-m-lines](https://cloud.githubusercontent.com/assets/2492510/6951989/c1d95028-d873-11e4-9345-5069c86ae1d4.png)
The .svg can be found here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_edmM2RkI0Vnhncm8/view?usp=sharing

**Comment by iamjessklein** [comment]
It certainly matches the look and feel better, but I am concerned that this messes a bit with the brand intention. 
@vazquez @cassiemc thoughts?

**Comment by vazquez** [comment]
Hmm, now I feel that by removing the fill it doesn't really look like the mozilla logo anymore.

What about an open book?

**Comment by iamjessklein** [comment]
:book:

**Comment by sabrinang** [comment]
![icon-read](https://cloud.githubusercontent.com/assets/2492510/7014033/552ec35e-dc74-11e4-90af-a9e47cc181ea.png)

An open book in a similar icon style for "get reading" can be found here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eSjRaZ3V2TkpCWGc/view?usp=sharing

**Comment by iamjessklein** [comment]
@sabrinang this looks great, I like the direction that you are heading in. Some thoughts: 

- [ ] try reducing the amount of solid shapes in the icon
- [ ] remove the bookmark so that it uses different forms from the "Learn More" icon

**Comment by sabrinang** [comment]
![icon-reading](https://cloud.githubusercontent.com/assets/2492510/7030054/b137009c-dd16-11e4-9ae5-81c8899d24ac.png)
Here is another alternative: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eT2VmNWtXZDJiNnc/view?usp=sharing

**Comment by sabrinang** [comment]
![icon-reading-green](https://cloud.githubusercontent.com/assets/2492510/7032771/c6ee30c8-dd29-11e4-95f9-a9755130cbf4.png)
this icon should be green as well.

Green get reading icon: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eelJfbldmVzRTeWc/view?usp=sharing

**Comment by iamjessklein** [comment]
Nice job @sabrinang
