### ISSUE TITLE
CLUBS: Design the desktop map "tiles"

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#495]
Should be informed by the mobile version.  #245 

![screen shot 2015-03-31 at 6 31 53 pm](https://cloud.githubusercontent.com/assets/535012/6930775/409981da-d7d4-11e4-9566-8382f9069a45.png)

**Comment by hannahkane** [comment]
closing because MLN directory will likely trigger related design changes
