### ISSUE TITLE
CLUBS: Remove the shadow circles in "Connect" icon

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#496]
The circles from underneath the people should be removed. 
![screen shot 2015-03-31 at 6 33 35 pm](https://cloud.githubusercontent.com/assets/535012/6930795/817beaa8-d7d4-11e4-9600-1538090e6612.png)

**Comment by sabrinang** [comment]
![icon-connect-shadowless](https://cloud.githubusercontent.com/assets/2492510/6950184/e82b8b02-d86d-11e4-9be2-ee760e37dee7.png)

You can find the updated .svg here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eMzh1SUFraWV2aGs/view?usp=sharing

**Comment by iamjessklein** [comment]
Thanks @sabrinang 

cc/ @ScottDowne @toolness this needs to be replaced with the current image on the bottom of the Clubs page.

**Comment by ScottDowne** [comment]
@iamjessklein do you need me to update this or are you updating it? It's just a file replace/link url replacement so it should be easy.

**Comment by iamjessklein** [comment]
I just updated @ScottDowne
