### ISSUE TITLE
CLUBS: Spacing between page sections needs to be tightened up 

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#498]
![screen shot 2015-03-31 at 6 35 23 pm](https://cloud.githubusercontent.com/assets/535012/6930816/c53248c8-d7d4-11e4-83ed-615992ed0e54.png)

**Comment by iamjessklein** [comment]
![screen shot 2015-03-31 at 6 38 03 pm](https://cloud.githubusercontent.com/assets/535012/6930851/1c8b3238-d7d5-11e4-8d1d-9d4359d7cd07.png)

**Comment by hannahkane** [comment]
this page is being redesigned
