### ISSUE TITLE
CLUBS CURRICULUM: Re-evaluate "What is Web Lit" design

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#499]
![screen shot 2015-03-31 at 6 40 12 pm](https://cloud.githubusercontent.com/assets/535012/6930881/7e1afe20-d7d5-11e4-9b0f-b5e8b05ff745.png)

**Comment by iamjessklein** [comment]
It is inconsistent with the rest of the site.

**Comment by hannahkane** [comment]
no longer applicable
