### ISSUE TITLE
CLUBS TOOLKIT: Add circular image/ line art and copy to be consistent with other pages

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#501]
The page should have this kind of header:

![screen shot 2015-03-31 at 6 46 07 pm](https://cloud.githubusercontent.com/assets/535012/6930961/373adc36-d7d6-11e4-9a9f-dbb6c4736ecc.png)
![screen shot 2015-03-31 at 6 46 26 pm](https://cloud.githubusercontent.com/assets/535012/6930965/41daad74-d7d6-11e4-95af-9e4ae7811c06.png)

**Comment by sabrinang** [comment]
![icon-toolkit](https://cloud.githubusercontent.com/assets/2492510/7011366/47cd5a66-dc5d-11e4-8134-93220e25505f.png)
toolkit circle line art can be found here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eVWZySjg1bHpPYmc/view?usp=sharing

**Comment by sabrinang** [comment]
@iamjessklein what do you think this line art? (I couldn't find a good photo to mask in the circle)
/cc @vazquez

**Comment by iamjessklein** [comment]
:+1:  this looks great to me.

**Comment by iamjessklein** [comment]
assigning to myself to implement.
