### ISSUE TITLE
ABOUT: Graphic is clipped 

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#503]
![screen shot 2015-03-31 at 6 50 19 pm](https://cloud.githubusercontent.com/assets/535012/6931031/d32a6e18-d7d6-11e4-95a6-0faecfec3610.png)

Re-supply the graphic here.

**Comment by sabrinang** [comment]
![icon-about-illustration](https://cloud.githubusercontent.com/assets/2492510/6950297/d047f9ca-d86e-11e4-9fd2-098345366c9d.png)
You can find the unclipped .svg file here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eaXhVdjg3WDY1NzQ/view?usp=sharing

**Comment by iamjessklein** [comment]
Thanks @sabrinang

**Comment by sabrinang** [comment]
this icon needs to be blue

**Comment by sabrinang** [comment]
blue unclipped version can be found here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eOG1lQUt1Z0VCM3c/view?usp=sharing

**Comment by iamjessklein** [comment]
closing this as there is now duplication with #595
