### ISSUE TITLE
Build Web Literacy page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#51]
### RACI
* Phase: Build
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: NA
* Dev Lead: 
* Quality: @davidascher 

Approved design is here: http://invis.io/RQ2HY7A7G

**Comment by hannahkane** [comment]
This is no longer blocked by design. @vazquez - can you please add design assets to this ticket?

**Comment by vazquez** [comment]
Assets available here: https://dl.dropboxusercontent.com/u/43783651/Mozilla/Web%20Literacy.zip

**Comment by vazquez** [comment]
Copy for the panels is available here: http://literaci.es/web-literacy-map-v1-5

**Comment by ScottDowne** [comment]
@vazquez can I also get the colors for the blues in the web-lit maps? The background and the text.

Example, the clickable part in your example, can click navigation, what is the text and background color for that.

**Comment by vazquez** [comment]
Sorry @ScottDowne, I'm away from the computer. Can this wait until tonight?

**Comment by vazquez** [comment]
I think it's $halfSeriousGrey

**Comment by ScottDowne** [comment]
@vazquez it can wait until tomorrow, I just wanted to make a note of now so if I forgot I needed it, we would have it here.

**Comment by ScottDowne** [comment]
Hm, @halfSeriousGrey didn't work, but I did find a @letMeKnowWhenYoureUsefulGrey

**Comment by vazquez** [comment]
Here is an annotated snapshot of the colours being used.

![screenshot 2015-03-25 10 18 44](https://cloud.githubusercontent.com/assets/1119821/6826518/6c18dff0-d2d8-11e4-8b0c-726c42ba38be.png)

**Comment by iamjessklein** [comment]
sketch3 plugins ftw!

**Comment by vazquez** [comment]
I did it by hand lol :stuck_out_tongue_closed_eyes:, don't trust that Sketch plugin yet

**Comment by iamjessklein** [comment]
what?! learn to love @vazquez

**Comment by ScottDowne** [comment]
https://github.com/mozilla/teach.webmaker.org/pull/396

**Comment by ScottDowne** [comment]
Totally!
