### ISSUE TITLE
MOBILE: Reduce size of Maker Party logo

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#515]
shrink maker party logo (it takes up the whole screen... reduce it by 50-75%)

**Comment by hannahkane** [comment]
@iamjessklein - is this duped by #478?

**Comment by iamjessklein** [comment]
When this is being updated, make sure to look the mobile treatment is reduced as well.

**Comment by hannahkane** [comment]
@ScottDowne - if you're no longer working on Teach, do you want to un-assign yourself from this one?

**Comment by ScottDowne** [comment]
@hannahkane I just couldn't fit it in for today, but for the most part I'm going to keep working on teach.

**Comment by hannahkane** [comment]
Ah, got it. Okay, thanks!

**Comment by ScottDowne** [comment]
Merged, let me know if it still needs work, kinda still looks a bit out of place but I don't think it's the size alone that's the issues.

@iamjessklein thoughts? Maybe some top margin would help?

**Comment by ScottDowne** [comment]
Closing.
