### ISSUE TITLE
MOBILE: photography takes a while to load

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#520]
photography takes a while to load - optimize image sizes

**Comment by sabrinang** [comment]
All [hero banners] (https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efndNS2hoYXM3allJYm5mQ1RCamMxbS1pVjc0Qm56YVhqdE1penRMc1paZFU&usp=sharing) file sizes have been reduced with [ImageAlpha] (http://pngmini.com/) so they should load quicker now. Closing this bug.
