### ISSUE TITLE
Sidebar submenu items need some hover text

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/teach.webmaker.org#522]
Right now, I think only one of the sidebar submenu items has hover text, the rest are using placeholder text.

We should figure out what needs to go in there, or display nothing if that is the best thing.

**Comment by hannahkane** [comment]
I don't see any hover text right now. I'd vote for none, though.

**Comment by ScottDowne** [comment]
![hover](https://cloud.githubusercontent.com/assets/197334/6947662/c388e1a6-d876-11e4-88c2-c3694de8ee60.png)

This is what it's doing now. It looks like wet-lit and Curriculum already have correct text, so it's just toolkits that needs text.

Can still remove it, and that's what I'll do if I don't hear back in a bit.

**Comment by hannahkane** [comment]
I vote remove!

**Comment by hannahkane** [comment]
duped by #803
