### ISSUE TITLE
"Join us" from homepage needs to initiate authentication process

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#523]
The yellow "Join Us" button on the homepage needs to launch the authentication process.

Or! @iamjessklein - do you think we should just remove that button, and have no CTA on the homepage?

**Comment by ldecoursy** [comment]
Also experiencing this with all "Create an account" links on subpages (testing on Android)

**Comment by hannahkane** [comment]
Oh man, good call, @ldecoursy. I'm going to file that as a separate issue. Thanks!

**Comment by iamjessklein** [comment]
The separate issue that @ldecoursy identified should be addressed with the new login process. 

As this is a newly released site, it makes sense to maintain a prominent call to action in the hero element on the landing page.  In issue #523 I addressed an issue with the ambiguity of the CTA on landing.

**Comment by hannahkane** [comment]
Hey, @iamjessklein, this *is* #523. Did you mean to reference a different issue?

**Comment by iamjessklein** [comment]
Ha! I did indeed. I am hunting for it.

**Comment by hannahkane** [comment]
I found it. It's #545.

**Comment by hannahkane** [comment]
Because of #545, I think we can close this one.

**Comment by iamjessklein** [comment]
woot :+1:
