### ISSUE TITLE
Design treatment of image on home page isn't consistent with subpages

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#524]
There is a pink design treatment on the bottom right-hand corner of the homepage main image that isn't on any other pages. Not sure if that's connected to the "Dev Version" placeholder. I'd vote to remove it - the page in general already skews very pink.

**Comment by hannahkane** [comment]
@iamjessklein and @sabrinang - can't remember if this was intentional or otherwise addressed somewhere?

**Comment by iamjessklein** [comment]
Yes this needs to be removed. It's a remnant of an outmoded design. :+1:

**Comment by ldecoursy** [comment]
Closing this since addressed in #471
