### ISSUE TITLE
Change support email on http://teach.mofostaging.net/about/

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#525]
Can we change the email that visitors use for support from help@webmaker.org to teachtheweb@mozillafoundation.org

**Comment by hannahkane** [comment]
Yes, we can! `</ObamaReference>`

**Comment by jgmac1106** [comment]
You didn't build that
</RomneyReference.></NoItsAnObamaReference></Youstink></StateOfAmericanPolitics>

**Comment by amirad** [comment]
![let's do this](http://cdn.meme.am/instances/500x/55256315.jpg)

**Comment by amirad** [comment]
Oh and a heads up to the remaining people on this email address that this is happening so you know where the emails are coming from. Feel free to reply and bcc the teachtheweb@mozillafoundation.org address so we all know someone is responding. @thornet @LauraHilliger @Saallen

**Comment by LauraHilliger** [comment]
I haven't checked help@ since Zimbra days – can you say approximately how many emails this is per day? [Gulp]

**Comment by amirad** [comment]
Just to be clear, I am still managing all support emails (makerparty, help, info) BUT we decided for the new site to have the support email be teachtheweb@mozillafoundation.org as the others didn't really make sense. No idea how many emails that will be @LauraHilliger but my guess is a few a week.

**Comment by LauraHilliger** [comment]
a few and a few :100: are very different :) Your teammates are always happy to help!

**Comment by iamjessklein** [comment]
@hannahkane are you coding it? I am happy to.

**Comment by amirad** [comment]
haha, I'll deal with the hundreds but the help on this flow would be greatly appreciated. And if it gets to be too much we can re-evaluate :)

**Comment by hannahkane** [comment]
you can take this, @iamjessklein. Thanks!
