### ISSUE TITLE
Teaching Activities page should have different color treatment from home page

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#528]
Same color on homepage and Teaching Activities page (pink) makes it harder to distinguish you're on a separate page, especially on mobile when the main thing on the screen is the navigation (unless you scroll down)

https://www.dropbox.com/s/lhynkpit4nj5rbt/Screenshot_2015-04-01-15-37-07.png?dl=0

QA using Firefox for Android

**Comment by hannahkane** [comment]
Adding this as a comment on #474 (related issue), and closing here.

**Comment by iamjessklein** [comment]
This is in fact the error that we are dealing with int #474 - the main feedback that we got from the Teach team is that the pink should not be the landing page color, so we are changing that to blue and adjusting the other colors accordingly.
