### ISSUE TITLE
Button appears clickable but nothing happens on http://teach.mofostaging.net/events/

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#529]
![screen shot 2015-04-01 at 3 38 46 pm](https://cloud.githubusercontent.com/assets/10170768/6949918/488bb726-d885-11e4-91a4-9ab8fb0ddef5.png)

The yellow button appears to be clickable, when you hover over you get a hand that let's you click, but nothing happens when you press it.

**Comment by hannahkane** [comment]
Good catch. This is actually meant to be the "sign up for more info about MP" form.

Covered in #481.
