### ISSUE TITLE
Round photo on homepage not appearing correctly 

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#532]
Firefox on Android

https://www.dropbox.com/s/pdgb1fr9f0njrir/Screenshot_2015-04-01-15-20-58.png?dl=0

The round photo on the homepage is oddly cropped - the top is round, the bottom is square

**Comment by hannahkane** [comment]
Woah...crazytown.

**Comment by ldecoursy** [comment]
Not just on homepage - also Clubs Curriculum page https://www.dropbox.com/s/cq7slae9y51m8en/Screenshot_2015-04-01-16-02-06.png?dl=0

**Comment by ldecoursy** [comment]
And on About page https://www.dropbox.com/s/7c2akr5vocclygl/Screenshot_2015-04-01-16-18-08.png?dl=0

**Comment by iamjessklein** [comment]
Hmmm this is crazy. @sabrinang and I will try to recreate the problem so that we can correct.

**Comment by ScottDowne** [comment]
Firefox on android working for me.

**Comment by iamjessklein** [comment]
I haven't been able to recreate this issue. Can anyone else?

**Comment by iamjessklein** [comment]
@hannahkane - can you provide some insight here?

**Comment by hannahkane** [comment]
I don't have an Android device. @ldecoursy - is this still happening for you?

**Comment by ldecoursy** [comment]
It is. Think @toolness also has and Android, maybe its just me?

**Comment by hannahkane** [comment]
@ldecoursy - What version of Firefox and Android are you using?

**Comment by ldecoursy** [comment]
Firefox 21.0 on Android 4.4.4

**Comment by ScottDowne** [comment]
I'm on FF 37 and android 4.1.2, and it displays fine for me.

My guess is it's the older version of firefox. We should try to reproduce it with that.

**Comment by hannahkane** [comment]
Taking this out of Inspector Gadget, since it seems to be an edge case.

**Comment by hannahkane** [comment]
@ldecoursy - is this still an issue for you?

**Comment by ldecoursy** [comment]
Nope, all good!
