### ISSUE TITLE
Transactional email when adding clubs should come from official email acct

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#536]
Received an email after adding a club, but it came from atultestacct@gmail.com.

**Comment by ldecoursy** [comment]
![screen shot 2015-04-01 at 4 05 50 pm](https://cloud.githubusercontent.com/assets/4885898/6951423/3d043bb8-d889-11e4-9d17-5f7bbd88317b.png)

**Comment by hannahkane** [comment]
@toolness - I was assuming the sender's email is specific to the staging server, but you know what they say about assuming...

Will file a separate ticket for the link, or track down the one that I swear already exists. :)

**Comment by toolness** [comment]
Should the email literally be from @thornet's email address? Or is it ok if it comes from, say, "The Mozilla Learning Team <no-reply@mozillafoundation.org>" or something?

**Comment by hannahkane** [comment]
@thornet - do you have a preference?

**Comment by toolness** [comment]
Hmm, I should also note that right now *all* emails from teach-api are coming from the same address. Presently the only other email being sent is the one to teach staff, informing them that someone just added a club... So if we change the default from email address to be Michelle, then it will look like those teach staff emails are being sent from michelle too. If we don't want that to be the case, then I will have to add an additional configuration parameter to the site that allows those two emails to come from different addresses.

**Comment by hannahkane** [comment]
I don't have a strong opinion. Could use a no-reply for both.

**Comment by hannahkane** [comment]
Let's go with The Mozilla Learning Team <no-reply@mozillafoundation.org>

**Comment by hannahkane** [comment]
actually, @ldecoursy - can you approve the above? Or would you rather use a more human email?

**Comment by ldecoursy** [comment]
I only wonder if a no-reply email will generally land in people's spam? If that's not a concern, then it seems ok to me. Another option would be to use the teachtheweb@mozillafoundation.org email that we link to from the About page - however I'm not sure who receives that. @thornet do you know?

**Comment by thornet** [comment]
I'd prefer teachtheweb@mozillafoundation.org. I receive those emails as well as @amirad @Saallen @LauraHilliger and others. So we'll have more eyes on the inbound.

**Comment by chrislarry33** [comment]
+1 for teachtheweb@mozillafoundation.org

**Comment by jbuck** [comment]
+1 for teachtheweb@mozillafoundation.org because it's already setup for outbound email :+1:

**Comment by toolness** [comment]
Ok, I just configured this, with jbuck's help!
