### ISSUE TITLE
MOBILE: Modal can't be easily scrolled

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#539]
Also, once I click the phone's "Done" button, the "Add Your Club To The Map" or "Change Your Club" button isn't accessible unless I put the focus on one of the fields.

**Comment by toolness** [comment]
Hmm, that is odd, since that form is structured like any other HTML form and has an `onSubmit` handler like any other HTML form... hmmm.

What version of iOS/Safari are you using?

**Comment by hannahkane** [comment]
iOS 8.1.3.

**Comment by toolness** [comment]
Hmm, where is your phone's "Done" button? I'm using an iPad with iOS 8.1.2 and I'm not seeing a done button. Can you write out the steps you use to reproduce the error?

**Comment by toolness** [comment]
Oh wait, nevermind, I'm seeing it now. Investigating!

**Comment by hannahkane** [comment]
K. Let me know if you need screengrabs or anything.

**Comment by toolness** [comment]
Hmm, are you sure that the "done" button is actually supposed to submit the form? From the [Apple developer docs on designing forms](https://developer.apple.com/library/mac/documentation/AppleApplications/Reference/SafariWebContent/DesigningForms/DesigningForms.html):

> It contains the Previous, Next, and Done buttons. The user taps the Next and Previous buttons to move between form elements. The user taps Done to dismiss the keyboard.

It says that "Done" just dismisses the keyboard, not submits the form. I'm also noticing that the search field at the top of imdb.com has similar behavior as our form--tapping "done" just dismisses the keyboard, it doesn't actually submit the search query.

**Comment by hannahkane** [comment]
We could definitely chalk this up to user error. But the problem isn't that I'm expecting the Done button to submit the form. It's that the form's Submit button only appears if the cursor is in an active field. If I click the Done button, it advances to the next field (as expected), until I get to the last field. Then, when I click the Done button, I'm back on the form, but the form submit button isn't there, because my cursor isn't active.

**Comment by hannahkane** [comment]
Just realized it's not that the form submit button isn't there, it's that I can't scroll to it without the modal being active which requires clicking into the field.

I think this is technically a user error issue that we don't necessarily need to resolve.

**Comment by toolness** [comment]
Oh, weird, hmmm. Well, I think we can do better--if it confused and frustrated you then I'm sure it will happen to lots of other folks, so lemme noodle on other possible solutions to this!

**Comment by toolness** [comment]
That's interesting that the submit button can't be scrolled-to without the modal being active... I wonder if we can fix it so that the modal doesn't need to be active in order for the user to scroll the modal on mobile, because that is a really annoying usability flaw.

**Comment by toolness** [comment]
omg I just experienced this problem and IT IS SO ANNOYING.

**Comment by hannahkane** [comment]
haha. I feel so redeemed. :)

**Comment by toolness** [comment]
Argh, so this appears to be a known issue with the latest version of bootstrap and iOS 8 (but not iOS 7!):

https://github.com/twbs/bootstrap/issues/14839

I will try some of the fixes listed there and see if that helps with anything...

**Comment by toolness** [comment]
Ok, so at first I tried this CSS:

```css
.modal-open .page {
  position: fixed;
  height: 100vh;
  overflow: hidden;
}
```

This basically forces the page in the background to be no taller than the viewport whenever modals are shown. However, it has the annoying side effect of scrolling to the top of the page, too, and I'm worried that it might cause other weird side effects in other browsers.

I'm about to submit a much better fix as a PR, though!
