### ISSUE TITLE
MOBILE: Didn't receive proper error message when I left required field blank on Clubs form

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#540]
When using Safari on an iPhone (iOS 8), I didn't receive a proper error message when I left the "What is the name of your Club" or the "What do you focus your efforts on?" field blank. 

I got, "Unfortunately, an error occurred when trying to change your club. Please try again later." 

Should have received a message similar to "Please provide a location for your Club" (which is what I see if I leave the location field blank."

Suggested copy:

"Please provide a name for your Club"
"Please provide a description for your Club"

**Comment by toolness** [comment]
What version of Safari/iOS are you using?

Right now we're relying on HTML5 Form Validation to do a lot of our form validation, but we may end up needing a polyfill or writing our own thing to do custom validation for older browsers.

**Comment by hannahkane** [comment]
iOS 8.1.3.
Maybe we should just indicate that the fields are required with an asterisk? That would help a bit I think.

**Comment by toolness** [comment]
Oh, that is a great idea!

Very interesting that such behavior is occurring on iOS 8--I totally thought all modern browsers supported HTML5 form validation now, but [apparently that is not the case](http://caniuse.com/#feat=form-validation) :(

**Comment by toolness** [comment]
So we might want to actually split this issue into two bugs: one for providing a fallback/polyfill for HTML5 Form Validation when browsers don't support it, which we can punt to v2, and another for adding asterisks or some other kind of indication for required fields, so at least users know what they're supposed to fill out. Sound OK?

**Comment by hannahkane** [comment]
Done. Changed the title of this one and added #577.
