### ISSUE TITLE
Make decision about how to handle unsupported browsers

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#543]
Options include:
 * Do nothing 
 * Offer a warning to users, suggest they upgrade
 * Use non-js as fallback

@iamjessklein - best practices or recommendations on this one?

**Comment by iamjessklein** [comment]
I've looked around so, the best practice seems to be to use non-js as a fallback and if it interferes with major functionality to flag it to the user with message suggesting an upgrade.

**Comment by hannahkane** [comment]
ok, let's go with that then. @toolness - is there work to be done to implement the non-js as a fallback? should I file a separate ticket for it?

**Comment by toolness** [comment]
Sounds good! I can file the bugs since I'd like to add some technical deets about them in the description. The one for non-js fallback is #572.

**Comment by toolness** [comment]
Just filed the one about the warning in #573!

**Comment by hannahkane** [comment]
Sweet. Closing this ticket then. Thanks!
