### ISSUE TITLE
Ambiguous yellow button

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/teach.webmaker.org#546]
Re: #411

On the Events subpage, under the second image, there's a line leading to yellow button. The button can be clicked, but doesn't do anything. 

![screen shot 2015-04-02 at 10 14 25 am](https://cloud.githubusercontent.com/assets/11045250/6965710/8805e1e6-d921-11e4-9b55-1046c93a51de.png)

 
I'm using Firefox 37.0 on a MacBook.

**Comment by hannahkane** [comment]
Good catch, and I really like this ticket title. :) This is covered #481, so I'm closing this.
