### ISSUE TITLE
Determine Privacy Module secondary Web Lit skills

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#547]
Obviously this module focuses on privacy, what other competencies do the selected activities refine? Related #285

We've selected:
Reading: https://hivetoronto.makes.org/thimble/MTkyODM5NzA1Ng==/ip-address-tracer-activity-kit
Writing: https://hivetoronto.makes.org/thimble/MTg3ODA2NTQwOA==/data-trail-timeline-activity-kit
Participating: https://hivetoronto.makes.org/thimble/MTkxMTYxOTg0MA==/privacy-coach-activity-kit

from the [Hive Toronto privacy curriculum](http://hivetoronto.org/portfolio/privacybadges/).

**Comment by LauraHilliger** [comment]
Alternative Reading: https://stacy.makes.org/thimble/MTY3NjY3MzI4MA==/testing-password-strength
Alternative Writing: https://stacy.makes.org/thimble/MjUwMDg1NjMy/creating-strong-passwords
alternative participating: https://laura.makes.org/thimble/lightbeam-activity <-- need to add a social component to this activity to make it more participatory

**Comment by LauraHilliger** [comment]
secondary skills listed here: https://teach.etherpad.mozilla.org/weblitbasics

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/107"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/107.
Please don't comment on it here.
