### ISSUE TITLE
Review "What's Wrong with your Password" for Clubs Privacy curriculum

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#548]
We need alternative Reading, writing, participating activities for privacy module, and Stacy Martin had created:

https://stacy.makes.org/thimble/MjAxMjIxNzYwMA==/whats-wrong-with-your-password

What can we use?

related #547 #91

**Comment by LauraHilliger** [comment]
Alternative Reading: https://stacy.makes.org/thimble/MTY3NjY3MzI4MA==/testing-password-strength
Alternative Writing: https://stacy.makes.org/thimble/MjUwMDg1NjMy/creating-strong-passwords

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/108"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/108.
Please don't comment on it here.
