### ISSUE TITLE
Document curriculum roadmap on github page landing

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#549]
blocked by #91
http://mozilla.github.io/webmaker-curriculum/

**Comment by LauraHilliger** [comment]
https://github.com/mozilla/webmaker-curriculum/pull/173

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/109"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/109.
Please don't comment on it here.
