### ISSUE TITLE
Remove redundant teach-related pages from Webmaker.org

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#55]
Once we launch v1 of the teach site, we should retire or otherwise address all redundant content from Webmaker.org:
 * Teach tab
 * party.webmaker.org
 * training content on prototypes
 * Web Lit content

Also, see redirects in #266.

**Comment by dajbelshaw** [comment]
Could you clarify what you mean by 'Web Lit content', @hannahkane?

**Comment by hannahkane** [comment]
@dajbelshaw  - meant that webmaker.org/resources and webmaker.org/literacy should redirect to the new Web Lit page, and that the entire Teach section of the Webmaker nav will be removed. (Ideally, Webmaker will include a link to the Teach site, but I'll leave it up to that team to decide how best to implement that.)

**Comment by dajbelshaw** [comment]
Gotcha. Thanks @hannahkane :)

**Comment by hannahkane** [comment]
Duped by #266
