### ISSUE TITLE
Change CTAs on Teaching Activities page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#550]
Right now this is one of the only pages that doesn't have the three CTAs at the bottom. Wondering if we should replace the single Clubs CTA with three:

1) Clubs
2) Teach Like Mozilla
3) Web Literacy

@LauraHilliger @ldecoursy @iamjessklein - what do you think?

**Comment by iamjessklein** [comment]
That seems appropriate for consistency. 

Thoughts @LauraHilliger @ldecoursy

**Comment by ldecoursy** [comment]
+1

**Comment by LauraHilliger** [comment]
Agree to those 3 for v1, but the other pages use that space for "subpages" as opposed to cross thinking. Structurally, we might want to consider what's special about this stuff in particular. Tiny braindump:

"Explore our curriculum model" - could refine/build/link to [pro tips](https://support.mozilla.org/en-US/kb/pro-tips-webmaker-teaching-kits)
"Remix a kit" - link to v1 How to Remix, Adapting for context (will live inside Teach Lik Mozilla). versionL8R links to our curriculum tool
"Built in Community" (curate and show the story, for example, a process from zero to hero w/ multiple community members. Lo Fi, No Fi or Net Neutrality kits have impressive "built w community" stories.

**Comment by hannahkane** [comment]
+1 to those ideas. @LauraHilliger - as you develop content for those pages, I'm happy to prioritize making updates to the Teach Like Mozilla page and sub-pages.

**Comment by iamjessklein** [comment]
For V1: 
- [ ] clubs icon = connect icon in pink
- [ ] teach icon = ???? in pink
- [ ] Web lit icon=  brain (learn) icon in pink 

Let's try to use existing icons if possible for consistency.

**Comment by sabrinang** [comment]
![icon-connect-pink](https://cloud.githubusercontent.com/assets/2492510/7098173/1dcde82e-df92-11e4-86e9-402fa20f0911.png)
Clubs/Connect icon: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ecVBJam42WGl6VHM/view?usp=sharing

![icon-curriculum-pink](https://cloud.githubusercontent.com/assets/2492510/7098174/1dce3f22-df92-11e4-83bb-eb907a9e9206.png)
Teach/Curriculum icon: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eVWJRd3pydFRoMDA/view?usp=sharing

![icon-learning-pink](https://cloud.githubusercontent.com/assets/2492510/7098175/1dd17fca-df92-11e4-806b-fc49e5bdd429.png)
Learn/Web Lit icon: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eRGxsMlU3ejVsUWs/view?usp=sharing

**Comment by mmmavis** [comment]
@hannahkane I can't tell if this is ready for implementation.  If it is, feel free to assign it to me.

**Comment by hannahkane** [comment]
It is.

**Comment by mmmavis** [comment]
![screen shot 2015-04-17 at 4 35 50 pm](https://cloud.githubusercontent.com/assets/2896608/7212688/05bb5b0c-e520-11e4-9e17-cfb06a974e06.png)
Hello all, this is what the bottom CTA section currently looks like on my PR.  I think we are still missing subheads and links.  :wink:

**Comment by hannahkane** [comment]
Looks good, @mmmavis. The headings actually need to be verbs, to match other pages. Let's go with this for now:

1) CTA: Build;  Subhead: Start a Club in your community; Link: /mozilla-web-clubs/
2) CTA: Grow; Subhead: Learn about our approach to teaching; Link: /teach-like-mozilla/
3) CTA: Explore; Subhead: See our Web Literacy Map; Link: /teach-like-mozilla/web-literacy/

**Comment by mmmavis** [comment]
cool, will update my PR, thanks @hannahkane :dancers:
