### ISSUE TITLE
[MIGRATED] Rio: scope curriculum module for LAN Houses

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#56]
We want to animate 10+ LAN Houses in Rio with great, relevant activities. Andre and Mario will lead the effort to review our existing clubs curriculum and think of how to modify it for LAN houses. 

Planning: https://foundation.etherpad.mozilla.org/lan-houses
Inspiration: http://speedshow.net/

**Comment by soapdog** [comment]
I am familiarizing myself with speedshow and talking to local people who held similar events. Will post relevant information and planning here.

**Comment by thornet** [comment]
Next steps: 

- [ ] Andre & Michelle talk to Melissa Romaine about advocacy element into curriculum

**Comment by soapdog** [comment]
We're first targeting the Web Literacy Basics. Advocacy is a great next step for us. Do we have material or activities focusing this area?

**Comment by LauraHilliger** [comment]
We built a number of things for advocacy around Net Neutrality, there's definitely things we could remix to focus on other specific issues, or even remix to be more general policy and advocacy activities. Some are even good as is:

https://keyboardkat.makes.org/thimble/LTQzNjIwNzM2MA==/net-neutrality-teaching-kit
https://laura.makes.org/thimble/LTIwMDkzMzEyMA==/host-a-maker-party-net-neutrality
http://discourse.webmaker.org/category/training/net-neutrality
https://training.webmakerprototypes.org/en/net-neutrality/concepts/

We should also check in with @melechuga

**Comment by soapdog** [comment]
Will check them. Thanks a lot!

**Comment by LauraHilliger** [comment]
@soapdog I was roadmapping our curriculum production stuff, and I realized that I needed insight from you on how you've modified the Clubs curriculum for LAN Houses. We were planning on using your insights in a module called "Basics II: Digital Inclusion", so I just thought I would get the conversation rolling!

**Comment by soapdog** [comment]
Yes we need to get this conversation rolling. Right now we don't have the modifications ready, we're still selecting a curriculum expert to help us. We have a short list of names and we're reviewing it this week. In the meanwhile I am doing the translation and adaptation of our Web Literacy Basics I for our work in here.

I think we should arrange a call later this week to talk about this. =)

**Comment by LauraHilliger** [comment]
Ok! Shall we wait until after you've had the time to talk to the curriculum person you're hiring/contracting? 
Digital Inclusion is highly contingent on locale, and I think it's a strange topic for Clubs curriculum – we might rethink this as a professional development module (e.g. How to Foster Digital Inclusive). @thornet did you have a different idea here for club learners?

**Comment by soapdog** [comment]
ITS already made a shortlist of curriculum experts and we have a tentative candidate that we'd like to approach. I am going there on 16th of April and will check out everything. I will get back and update this task as soon as I have more information.

**Comment by soapdog** [comment]
We're contacting the possible curriculum expert this week.

**Comment by thornet** [comment]
:+1:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/27"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/27.
Please don't comment on it here.
