### ISSUE TITLE
LANDING: Replace pink icons with blue ones

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#563]
This is due to the page color change.

**Comment by sabrinang** [comment]
I don't see any pink icons on this page?
![mozilla learning - http___teach mofostaging net_](https://cloud.githubusercontent.com/assets/2492510/6974836/e635dea0-d94a-11e4-96ca-51c7fec9134b.png)

If there are pink icons can you clarify which ones they are?

**Comment by iamjessklein** [comment]
you are correct!
