### ISSUE TITLE
ABOUT: Replace pink icons with blue ones

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#564]
This is due to us changing the sidebar color.

**Comment by sabrinang** [comment]
![screen shot 2015-04-02 at 3 01 32 pm](https://cloud.githubusercontent.com/assets/2492510/6974643/4aea3320-d949-11e4-9b5d-b8890fbef953.png)

The blue icons can be found in this folder: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_edjM3THhDWjQ5cXM&usp=sharing

I'm don't know why the rays behind this icon don't export and appears as such:
![screen shot 2015-04-02 at 3 01 59 pm](https://cloud.githubusercontent.com/assets/2492510/6974653/69ca4c6c-d949-11e4-9b07-bd620b25cd6f.png)

@iamjessklein @vazquez any tips on export the rays? 
I'll continue to figure it out and will be in that folder when I export it.

**Comment by vazquez** [comment]
It needs to be a JPG. The rays don't export to SVG properly

**Comment by toolness** [comment]
Bummer about the JPG! If it weren't for that, changing the icons would just be a matter of changing the `fill` or `stroke` in the SVG file, which we could even do programmatically as part of the build process!

**Comment by sabrinang** [comment]
![icon-building-blue](https://cloud.githubusercontent.com/assets/2492510/7010038/72080178-dc53-11e4-8f19-c7fe154e6ed8.png)
transparent .png can be found here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eN215bV9wdXFwV0U/view?usp=sharing

**Comment by sabrinang** [comment]
follow us: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eNHBWMlYyTE9qSXc/view?usp=sharing
get help: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eRmRmSWJRUGRwcTA/view?usp=sharing
say hello: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ea2V6eGc0RThQeHM/view?usp=sharing

**Comment by sabrinang** [comment]
horizontal divider: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_edm5nNHdhZjdTb1U/view?usp=sharing
