### ISSUE TITLE
Add bullets to distinguish skills within web lit map

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#571]
On the web literacy page, when you click on the individual terms and see a pull-down of the skills, it might help readability to add bullets/asterisks/dashes to distinguish them as a list.

**Comment by mmmavis** [comment]
I added the default list bullets in.  Does this help?  @ldecoursy @iamjessklein 

![screen shot 2015-04-21 at 1 44 53 pm](https://cloud.githubusercontent.com/assets/2896608/7262222/ba9412c6-e82c-11e4-8cd4-e8006bf1e118.png)

**Comment by ldecoursy** [comment]
wfm! :dancers:

**Comment by jgmac1106** [comment]
I don't see the bullets on the live page. I think it looks better when they
are there.

**Comment by toolness** [comment]
Yeah, sorry, haven't pushed this change to the live site--it's on staging though:

https://teach.mofostaging.net/teach-like-mozilla/web-literacy/

will push it to production later today!

**Comment by toolness** [comment]
Hey @jgmac1106, still haven't pushed this to production, but I started a [`CHANGELOG.md`](https://github.com/mozilla/teach.webmaker.org/blob/develop/CHANGELOG.md) file that you can peruse to keep track of what's been developed vs. what's been pushed to production. Basically, everything in "unreleased" is on teach.mofostaging.net, while the latest release is what's on teach.mozilla.org.

Still have to figure out a QA process for pushing new releases (discussing that in #806) but it's a start!

**Comment by jgmac1106** [comment]
Thanks this helps. Still amazed at how fast and efficient the team moves.
