### ISSUE TITLE
Show warning/upgrade message if major functionality is disabled for user's browser

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#573]
Currently we have a suboptimal list of minimum browser requirements for core functionality in the site; as mentioned in #572, we'll be disabling JS entirely for now if the user's browser doesn't meet them. Unfortunately, this means the loss of some rather core functionality for v1:

* Login won't work (and therefore adding/removing clubs won't work).
* The map on the clubs page won't work.
* The clubs list on the clubs page won't be shown (we can fix this for v1 if absolutely necessary, but it'll be a lot easier to fix for v2 due to [changes in architecture](https://github.com/mozilla/teach.webmaker.org/issues/585)).
* The carousel on the events landing page will likely be permanently stuck on the first image (hopefully not too big a deal).
* ~~It may be impossible to un-collapse the skills in the web literacy page and the sections of the clubs toolkit page (I'm unfamiliar with that code so I'm not sure; if needed, we could potentially have those sections always be un-collapsed when JS is disabled, the same way we currently do for the sidebar, but we'll need to file a separate issue for it).~~ Whoa I think a `:focus` rule is making it so those collapsible sections un-collapse when clicked/focused without requiring any JS, which is [brilliant](https://github.com/mozilla/teach.webmaker.org/commit/f0981c96352f2da5031bd865f38f70d50a17b8b7#commitcomment-10569879).

Some stuff will still work, but in a "gracefully degraded" way:

* Clicking on the tabzilla tab will take the user to mozilla.org instead of sliding down the tabzilla tab.
* Moving to different pages on the site will force full page refreshes and won't show cool transition effects.
* The sidebar will always be un-collapsed on mobile.

As the site evolves, more of the items in the first list ("doesn't work") will move to the second list ("gracefully degrades"). But in the meantime, we should show a warning to users letting them know that some parts of the site won't work for them, with links to information on upgrading their browser.

I don't know exactly how this warning should be worded, but we should probably keep in mind the fact that--at least in our experience with other Webmaker products--most folks on older browsers aren't actually in control of their browser choice, e.g. because they're at a library or workplace.

**Comment by toolness** [comment]
Oh, I should add that we might want to simply hide some of the interactive elements on the page that require JS when JS is disabled. This can be done via CSS rules that start with `html.no-js`.

The warning can also be displayed via CSS rules that start with `html.no-js`.

**Comment by hannahkane** [comment]
@toolness - do you need a UI for this?
