### ISSUE TITLE
Use CSS transitions for modal show/hide

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#574]
Right now they just appear/disappear without any transition, which is a bit jarring. Shouldn't be hard to add some nifty transition effects via [`ReactCSSTransitionGroup`](https://facebook.github.io/react/docs/animation.html).

**Comment by mmmavis** [comment]
What kind of animation do we have in mind? slide in/out? fade in/out?

**Comment by hannahkane** [comment]
@iamjessklein - thoughts on @mmmavis's question?

**Comment by toolness** [comment]
I suggest we just go with fade, as it looks nice and is easiest to implement from a technical standpoint. CSS Transitions get tricksy with sliding and there might also be weird issues w/ it on different-sized devices.

**Comment by iamjessklein** [comment]
Let's go with the fade. :sun_with_face:

**Comment by mmmavis** [comment]
+1 yay!

**Comment by iamjessklein** [comment]
who is working on this?

**Comment by mmmavis** [comment]
I can take this on.  Hopefully it's not too hard to implement :ok_woman:

**Comment by mmmavis** [comment]
Hey @toolness (and @ScottDowne :wink: ),

Can I get some help on this?  I followed the [animation doc](https://facebook.github.io/react/docs/animation.html#getting-started) and simply just 
1. wrapped our modal component in `<ReactCSSTransitionGroup>`, see [here](https://github.com/mozilla/teach.webmaker.org/pull/712/files#diff-04ec77825926d271a38170cfb92cddddR27)
2. added `key` attribute to, see [here](https://github.com/mozilla/teach.webmaker.org/pull/712/files#diff-04ec77825926d271a38170cfb92cddddR27)
3. added CSS for the animation, see [here](https://github.com/mozilla/teach.webmaker.org/pull/712/files#diff-b080de50a5c717fb5500ca4f10330429)

I'm not sure what I'm missing but the seem-to-be-easy animation doesn't work for me at all.  I don't even see those relevant classes(e.g. `modal-enter-*, modal-leave-*`) being added to our modal `<div class="modal ...">`.  Mind taking a look? :scream: 

WIP PR here: https://github.com/mozilla/teach.webmaker.org/pull/712/files

**Comment by toolness** [comment]
Ah ok, I just issued a PR to #712 at https://github.com/mmmavis/teach.webmaker.org/pull/1 which fixes things! The description of that PR hopefully explains what was going on.
