### ISSUE TITLE
Add CC licensing to Teaching Activities and Clubs Curriculum pages

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#578]
**UPDATE Apr 13 Decision:** Please add the following text to bottom of the Clubs Curriculum page and to the Teaching Activities page (under the 10 activities): "All featured content, unless otherwise noted, is covered under the CC BY-SA license." Please link "CC By-SA license" to https://creativecommons.org/licenses/by-sa/2.0/

--------
During the legal review of the site, the issue was raised that we should try to have consistent licensing for teaching content on the site. The suggestion is to use CC-BY-NC-SA, the same license that has already been selected by a few of our community-featured content partners. 

Let's confirm this is the license we want, then add it to the Teaching Activities and Clubs Curriculum pages on teach.mozilla.org.

cc @thornet @LauraHilliger @hannahkane

**Comment by jgmac1106** [comment]
non-commercial. Shucks there goes my plan of world domination on the using
the work of @thornet <https://github.com/thornet> @LauraHilliger
<https://github.com/LauraHilliger> @hannahkane
<https://github.com/hannahkane>

**Comment by davidascher** [comment]
I'm not convinced by the NC bit. If someone wants to make a micro business
teaching this stuff in Kenya I think we should not prevent them.

**Comment by ldecoursy** [comment]
@davidascher That might be a decision we make on content we create, but some of the existing and remixed content by community/partners have CC-BY-NC-SA licensing. Another option is not to put licenses on the pages as noted above, but have individual licenses on each activity. Not sure that's ideal but might be better option.

**Comment by jgmac1106** [comment]
@davidascher Brings up a great point. Maybe when remixing  future content
we need to be cognizant of making sure it can be used commercially.

Until then,  especially if original content already used has different
licenses, we will need to license each activity.

**Comment by chrislarry33** [comment]
I think for we put up at launch they need individual licensees as some of these are co-created with partners. Going forward we can have a commercial license on our stuff and  negotiate on partner stuff. Its hard though to make this case top partners retroactively.

**Comment by davidascher** [comment]
I'm not suggesting we relicense others' stuff. Only that our content be
liberally licensed.

**Comment by toolness** [comment]
+1 to nixing the NC on our own content whenever possible. IMO it supports [Mozilla Manifesto](https://www.mozilla.org/en-US/about/manifesto/) commandment 9:

> Commercial involvement in the development of the Internet brings many benefits; a balance between commercial profit and public benefit is critical.

**Comment by LauraHilliger** [comment]
I [swapped out the CC-By](https://github.com/mozilla/webmaker-curriculum/pull/171) on those activities where partners had used a different license. For clubs, the only one we need to solve is the Radio Rookies one, which was originally made in partnership with HiveNYC, but both orgs have standard copyright footers.

Otherwise, we currently have CC-BY on the club *activities* (check the footer). 

AFAIK we've always used either cc-0, cc-by or cc-by-sa [see](https://www.mozilla.org/en-US/foundation/licensing/website-content/) on our work. +1 to liberal licensing, our community needs it.

**Comment by hannahkane** [comment]
@ldecoursy - let me know if you want a statement about licenses to appear on the /clubs/curriculum and /activities landing pages, or if it's adequate to have them on each of the individual activity pages.

**Comment by ldecoursy** [comment]
I'm reaching out to content partners today so will have a better sense shortly!

**Comment by ldecoursy** [comment]
Trending towards all agreeing to CC BY-SA but still waiting on a few responses.

**Comment by ldecoursy** [comment]
Nearly all content partners have signed off on CC BY-SA licensing (still waiting on two). I think best solution is to add CC BY-SA license to both the Teaching Activities page (under the 10 individual activities) and at the bottom of the Clubs Curriculum page. Can we say "All featured content, unless otherwise noted, is covered under CC BY-SA." 

@hannahkane let me know if you prefer I close this issue and file a separate design ticket for that!

**Comment by hannahkane** [comment]
Thanks, @ldecoursy. I updated the original comment in this ticket, and just assigned it to @mmmavis. Mavis - let me know if you have any questions or need a design decision. This is adding a line of copy to two pages.

**Comment by mmmavis** [comment]
@hannahkane , I didn't read all the convos above and just added the copy to the 2 pages.  See screencaps below.  PR open here: https://github.com/mozilla/teach.webmaker.org/pull/684

#### ===  Clubs Curriculum page === ####
![screen shot 2015-04-13 at 6 36 13 pm](https://cloud.githubusercontent.com/assets/2896608/7128779/052445a8-e20c-11e4-82c2-69d305dd7523.png)

#### === Activities page === ####
![screen shot 2015-04-13 at 6 35 58 pm](https://cloud.githubusercontent.com/assets/2896608/7128780/072edf3e-e20c-11e4-9f1a-38eef32d4f22.png)

**Comment by hannahkane** [comment]
+1. Thanks!
