### ISSUE TITLE
hive logo at bottom of hive activities page is low contrast

### ISSUE THREAD

**Issue by davidascher** [mozilla/teach.webmaker.org#584]
yellow on grey feels off-brand

![screenshot 2015-04-03 20 22 18](https://cloud.githubusercontent.com/assets/51278/6991281/55204bb2-da3f-11e4-94d8-18a7f6cb16f4.png)

**Comment by hannahkane** [comment]
footer will be getting a re-design shortly, so I'm closing this as it will become redundant.
