### ISSUE TITLE
Remove references to Login for the softest of launches

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#589]
As per discussion with @toolness and @simonwex, we'll plan to deploy to production without authentication in place, so that we can deal with any deployment hiccups now, rather than later.

The site will be on production, but we won't link to it or promote it until the login project is finished and incorporated into the Teach site.

In order to make it not weird for anyone who stumbles across the site, we'll remove login-dependent functionality:
 - [ ] Remove "Create an account" and "Sign in" from sidebar nav
 - [ ] Remove "Join Us" button from homepage hero image
 - [ ] Remove "Add Your Club" button from /mozilla-web-clubs hero image
 - [ ] Remove map and list of clubs from /mozilla-web-clubs
 - [ ] Remove "Add Your Club to the Map" CTA at the bottom of /mozilla-web-clubs and  /clubs/toolkit

**Comment by toolness** [comment]
Hooray, thanks @hannahkane!

If we need to give this milestone a name I suggest we call it "The Softest of Launches" (TSoL).

Also, while this isn't directly related to removing references to login, the other big thing that needs to be done for TSoL, as @simonwex mentioned in IRC, is add a `robots.txt` at the root of the site that tells search engines not to index it just yet. Will also have to do a bit of research on how long search engines cache this information for, so we know how long we'll have to wait post-real-launch for the site to show up in their indexes.
