### ISSUE TITLE
Rio: set up regular team meetings and project management

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#59]
Michelle to coordinate with Andre, Mario and @benrito  to set up regular meetings and project management tools.

**Comment by thornet** [comment]
Andre is now joining regular team calls, contract is signed, and he's in Github. 

Next step: 
- [ ] Get Andre an LDAP
- [ ] Get Mario an LDAP

**Comment by thornet** [comment]
Mario's contract also signed. 

Check-in call scheduled for this Tuesday with Ford. cc @soapdog @benrito

**Comment by thornet** [comment]
@soapdog is this okay to close?

**Comment by soapdog** [comment]
@thornet we still don't have our LDAPs or email accounts, I would like to close this after we get those working.

**Comment by thornet** [comment]
LDAPs secured. @soapdog is meeting regularly with Mozilla Learning team and with local partners. Closing the ticket.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/29"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/29.
Please don't comment on it here.
