### ISSUE TITLE
Add Club description to list view

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#592]
Currently, the Club description is included in the Map callout view of Clubs, but not the list view. Please add it, right below the location and above the "Led by" field.

**Comment by ScottDowne** [comment]
@hannahkane could you elaborate a bit more? I'm not sure what needs to be done yet.

**Comment by ScottDowne** [comment]
I think I figured it out by reading a few more tickets and seeing a pattern.

**Comment by hannahkane** [comment]
Just trying to make the list view and the map view consistent in terms of what information they display!

**Comment by toolness** [comment]
Hey is @iamjessklein cool with this? I actually originally included it in the list but she wanted it removed bc it added clutter to the whole thing.

**Comment by ScottDowne** [comment]
@toolness ah, that's fair.

**Comment by iamjessklein** [comment]
see my comment on #611
