### ISSUE TITLE
Design 'Clubs' page for teach.webmaker.org

### ISSUE THREAD

**Issue by cassiemc** [mozilla/teach.webmaker.org#6]
### RACI
* Phase: Design
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: Ricardo
* Dev Lead: NA
* Quality: @davidascher 

### Background docs

* Clubs Wiki Page: https://wiki.mozilla.org/Webmaker/2015/Mentors/Clubs
* Summary of calls conducted with 38 potential Club Captains: https://teach.etherpad.mozilla.org/club-calls-analysis
* Most recent requirements doc: http://mzl.la/1xZgfKQ
* Michelle's blog entry about Clubs pilot: http://michellethorne.cc/2015/01/clubs-first-test-kicks-off/

### Primary CTA - "Add your Club to the map"
* Map with existing Clubs pinned and a CTA to "add your Club to the map"

### Primary content - explanatory information about Clubs + Map

 * Suggested headline copy: Mozilla Web Literacy Clubs are local groups where learners are empowered with web literacy skills so that they have agency on the web as creators, citizens, and future leaders.
 * Suggested body copy:
Mozilla Web Literacy Clubs: 
  * have a local leader, or leaders, who work to sustain the Club over time
  * are in classrooms, libraries, and coffee shops, as well as around kitchen tables
  * make use of and contribute to our modular, remixable curricula [link to Teaching Activities page]
  * embody our approach to teaching and learning: we learn by making projects together and openly reflecting on the process in an inclusive and locally relevant environment 
  * are connected to regional communities and the global community of teachers and learners through shared campaigns

 * Users should be able to see specific Club information by interacting with the map, though Club profiles and search may not be needed at launch

### Secondary content - Resources [maybe these could be presented with just icons; not sure]:
 * Modular, remixable Web Literacy curriculum [link to Teaching Activities Page]
 * Connect with other Club Leaders [link to discourse thread]
 * Tips for running your Club [link to "Tips" page #62 ]

Also see the ticket for designing the "Add Your Club" workflow: #70

### Future planning
* In the future, we'll likely have rich Club pages with portfolios, members, events, etc.
* We may also have Region pages with profiles of Regional Coordinators, and lists of all the Clubs in a certain region

**Comment by hannahkane** [comment]
These may be relevant background:
 * Clubs Wiki Page: https://wiki.mozilla.org/Webmaker/2015/Mentors/Clubs
 * Summary of calls conducted with 38 potential Club Captains: https://teach.etherpad.mozilla.org/club-calls-analysis
 * Most recent requirements doc: http://mzl.la/1xZgfKQ
 * Michelle's blog entry about Clubs pilot: http://michellethorne.cc/2015/01/clubs-first-test-kicks-off/

**Comment by hannahkane** [comment]
@cassiemc, I updated the description with some suggested copy

**Comment by hannahkane** [comment]
Super speedy nice work from Ricardo: https://redpen.io/p/jza7e4f541a24313ff

Could use feedback from @thornet, @amirad, @Saallen and others

**Comment by thornet** [comment]
Added some comments in the redpen! 

The pages are looking great.

**Comment by hannahkane** [comment]
I believe the Clubs page itself is good to go (distinct from the "Add Your Club" workflow which is in #70). Need to ship assets to engineers.

**Comment by chrislarry33** [comment]
I added some comments in RedPen. I have a few copy and image issues. Should be easily solvable and I agree looks awsm and would like to pass off soon.

**Comment by hannahkane** [comment]
Thanks for feedback.

This has been a bit confusing. The redpen has two versions of both the Clubs page and the "+ your Club" modal. We landed on the "Add Your Club" version, but some relevant comments are on the "Start Your Club" version. @vazquez - I can help synthesize.

Also, there are some comments about the page wrapper (navigation/footer) that are outside the scope of the Clubs ticket. I'll move those to a separate ticket.

I'd like to formally end the commenting period on the redpen, because it's getting a little confusing. Will follow up on the few remaining copy/image issues separately.

**Comment by vazquez** [comment]
Thanks Hannah :). I'm still at the workweek. I'll reach out to you on Monday so we can catch up and synthesize feedback.

**Comment by toolness** [comment]
Oh shoot, when we imported my code into this repository, a bunch of unrelated tickets erroneously got closed, including this one. I'm re-opening this issue.

**Comment by vazquez** [comment]
The assets and the design is available in the build ticket, #44

**Comment by hannahkane** [comment]
I'mma close this. :)
