### ISSUE TITLE
Build Calendar for Learning Networks community events

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#60]
Using this etherpad : https://teach.etherpad.mozilla.org/events2015 I will build a calendar for all the Learning network team to use.

Location of Calendar: TBC
Working with : @amirad

**Comment by LauraHilliger** [comment]
We have the teachtheweb calendar we could repurpose:
https://www.google.com/calendar/embed?src=zythepsary.com_q6ugl9iepetabcp9eg9ltmruic%40group.calendar.google.com&ctz=Europe/London

I know @LucyeoH is using it too :+1:

**Comment by Saallen** [comment]
Awesome
I was thinking about this calendar.
How do I add items and change name @LauraHilliger ?

**Comment by LauraHilliger** [comment]
I've just added you as someone who can manage, so you should be able to add items and stuff. If you can't change the name, let me know and I'll change it :tada:

**Comment by Saallen** [comment]
Boom. got it. Thanks :)

**Comment by LucyeoH** [comment]
@LauraHilliger can you add me too! The Teach The Web Talk dates that are listen on there are actually out of date :flushed:

**Comment by LauraHilliger** [comment]
done! I added @amirad as well. Is there anyone else I should be adding? At the moment it's the 4 of us.

**Comment by Saallen** [comment]
Let me build it out with our events first and then we can the entire Learning networks team :eyes:

**Comment by LauraHilliger** [comment]
note: @emmairwin added me to her new Community Education calendar. Maybe there's a way we can cross streams here?  @emmairwin – could you add @Saallen and @LucyeoH to this calendar as well? Maybe we can cross post certain things...

https://www.google.com/calendar/render?mode=day&date=20150227T214856&pli=1#h|day-1+23131+23131+23131

**Comment by Saallen** [comment]
Hey
@emmairwin and myself have already chatted about our new calendar cross over
I would love access Emma if possible and our calendar is almost ready too. I can add you to this calendar if you wish :smile:

**Comment by ldecoursy** [comment]
Here's the link for the calendar! https://www.google.com/calendar/embed?src=zythepsary.com_q6ugl9iepetabcp9eg9ltmruic%40group.calendar.google.com&ctz=Europe/London 

Closing this ticket.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/30"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/30.
Please don't comment on it here.
