### ISSUE TITLE
[MIGRATED] Add remixable resources to activity pages

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#602]
a few EDITABLE resources @thornet received from Mouse. We should figure out how / where to link to these resources:

(kraken legitometer) https://docs.google.com/a/mozillafoundation.org/document/d/1bX7-G1rn-8BY5DNMIWHhS1utHoxcKi73RTmCuOL6CGU/edit#
(kraken tip sheet): https://docs.google.com/a/mozillafoundation.org/document/d/1k4QHueV4a88L1X4-Qoji4lMhJ5TUrUioWvk7Uei0gtA/edit
(ping utility tip sheet): https://docs.google.com/a/mozillafoundation.org/document/d/18qe8mdhb9lfheaz1tJw_mqC9hmLPPuGxUJZmL-CnnRk/edit

**Comment by thornet** [comment]
And now their German localizations: 

* Kraken legitometer: https://docs.google.com/a/mozillafoundation.org/document/d/1t6B06QR5Xd-wq-7i5vN-EHBtT00jy1aTmLJf-ifiGuk/edit
* Kraken signs: https://docs.google.com/document/d/1sCXYEaFfoo7gCUord3Uxrx7Mr1E_DqUlQxvXNqz3DF4/edit?usp=sharing

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/110"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/110.
Please don't comment on it here.
