### ISSUE TITLE
Implement Webmaker blog visual refresh

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#604]
Design files are available here: https://bugzilla.mozilla.org/show_bug.cgi?id=967770
Redpen here: https://redpen.io/p/pkfbf34a0e1d1ab57e

Please note: we made a decision to use different copy in the header.

Header: Mozilla Learning
Subhead: People, products and programs to teach, learn and make the Web

**Comment by mmmavis** [comment]
@iamjessklein @sabrinang just tagging you girls here in case there is any design tweak that you want to suggest :dancer:

**Comment by mmmavis** [comment]
@hannahkane 
I'm gonna put this in Inspector Gadget milestone for now (mainly just for it to appear in this [list](https://github.com/mozilla/teach.webmaker.org/issues?q=assignee%3Ammmavis+is%3Aopen)).  Feel free to move it to the next milestone if that makes more sense.

**Comment by hannahkane** [comment]
Good by me. Thanks, @mmmavis. :)

**Comment by edrushka** [comment]
tagging this so I can follow

**Comment by hannahkane** [comment]
@cassiemc - wondering if you can shed some light on whether the design was approved or not. Have heard some comments that it may not be fully on brand, so wanted to check before we move forward with implementation.

**Comment by cassiemc** [comment]
@hannahkane Thanks for flagging! This is the first I've seen it, and it doesn't look like it's gone through design review. We could probably do that quickly, let's follow up on IRC re. timing, I'll ping you.

**Comment by edrushka** [comment]
This was something Roberto did in his free time. Not sure about urgency of this task @hannahkane, I'll leave to you to prioritize (or not!)

**Comment by hannahkane** [comment]
Implementing the refresh was in this heartbeat, because I had assumed the design was reviewed. I have learned my lesson. :) Now that I know the design isn't ready to go, I'm going to pull it out of this heartbeat. Would love to get a design review of it soon, though, so I know how much work we'll need to do in order to eventually implement it.

**Comment by cassiemc** [comment]
Flagging @vazquez for design review of this whenever you have a sec. TIA Ricardo!

**Comment by vazquez** [comment]
@hannahkane - Just for clarification, everything in that design is up for review right? Or is it just one element of the page?

**Comment by hannahkane** [comment]
The whole thing. Thanks!

**Comment by vazquez** [comment]
Okay I believe I'm done @hannahkane!

**Comment by hannahkane** [comment]
Super. Thanks very much, @vazquez!

@mmmavis - should I create a design ticket for @sabrinang  to implement @vazquez's changes before we get to this implementation ticket?

**Comment by mmmavis** [comment]
Thanks @vazquez :clap: 

@hannahkane : I'd prefer giving @sabrinang the time to review comments on https://redpen.io/nx6ba404aaca4936ab and leave feedback.  So yea, a separate design ticket will be great!

**Comment by hannahkane** [comment]
Cool. #799.

**Comment by mmmavis** [comment]
@ldecoursy 
Could you remind me what "subscribe to our blog" does (see [sidebar](https://cloud.githubusercontent.com/assets/2492510/7419266/da271874-ef28-11e4-8edc-7396d06e44fb.png))?  Is it like a RSS feed subscription?  Mailinglist subscription? or?

@hannahkane could you give me the link to G+ please?

Thank you both!

**Comment by hannahkane** [comment]
G+: https://plus.google.com/u/2/communities/106022863174952221205

**Comment by hannahkane** [comment]
@mmmavis - do you have an update on this one? Just wondering if there are any other blockers.

**Comment by mmmavis** [comment]
I haven't heard back from @ldecoursy yet.  Maybe we can leave that section for now?

**Comment by ldecoursy** [comment]
Sorry, missed this yesterday. I was thinking it would be a way to receive email updates when new blog posts are added. Here's a screenshot of what this looks like when I receive an email from the Hive NYC blog (also wordpress):  
![screen shot 2015-05-06 at 5 28 32 pm](https://cloud.githubusercontent.com/assets/4885898/7504089/715a7baa-f415-11e4-9b60-49e1d5f511fe.png)

**Comment by mmmavis** [comment]
no worries @ldecoursy  :smile: could you point me to where that "subscription form" is on http://hivenyc.org/ ?

**Comment by mmmavis** [comment]
ah, @hannahkane showed me: http://hivenyc.org/blog/.  Lainie do you mind grant me access so I can check what plugin HiveNYC uses?  I don't have that privilege currently.

**Comment by ldecoursy** [comment]
Just updated you as admin http://hivenyc.org/wp-login.php with your mofo email address - let me know if you have trouble getting in.

**Comment by mmmavis** [comment]
@ldecoursy thanks! I can view plugins settings fine now.  :+1:

**Comment by mmmavis** [comment]
Hello allll, the new skin of Webmaker blog is ready for review :sparkling_heart: There's no staging for `blog.webmaker.org` so I'm sharing screencap of my local instance instead. Please have a look and let me know if there's anything that needs to be fixed.  If all is good hopefully we can push this out tomorrow :sun_with_face: :sun_with_face: :sun_with_face: 

![mozilla learning i people products and programs](https://cloud.githubusercontent.com/assets/2896608/7505842/6f3a4462-f40c-11e4-85b4-45633c46489f.png)

**Comment by ldecoursy** [comment]
Should @HPaulJohnson have final signoff? Looks good to me.

**Comment by HPaulJohnson** [comment]
Looks great! Good to go. Thanks.

**Comment by mmmavis** [comment]
:dancers: :dancers: :dancers: HOORAY https://blog.webmaker.org/ GOT A NEW SKIN!!! :dancers: :dancers: :dancers: 

I'm unable to install the subscription plugin due to server restriction.  I'll open a separate ticket to get devops help on that.

**Comment by hannahkane** [comment]
Looks fantastic!

**Comment by edrushka** [comment]
Ohh! Beautiful! I can now close a bugzilla ticket filed Feb 4, 2014 :grimacing:
