### ISSUE TITLE
Variations for design/copy to test for new Teach site

### ISSUE THREAD

**Issue by cassiemc** [mozilla/teach.webmaker.org#61]
Will be keeping track of design and copy variations here that have been suggested in redpen feedback. Could be tested via A/B or focus groups or with @LauraReynal's work in the field.

* pink vs. blue <--maybe a better user test than a/b
* 'join' vs. 'meet'
* some of the nav language & descriptions

cc @hannahkane @adamlofting

**Comment by hannahkane** [comment]
Thinking on this more...not sure how useful testing this stuff will actually be. I know I advocated for this a lot in the redpen comments, but I think that was largely to avoid things being framed as opinion battles.

I'd like to do general usability testing after April 1 to validate that users can easily accomplish key tasks, but I don't think we'll be tracking conversion rates (e.g. "join" v "meet") until we're working up to a proper marketing push. (Also, the pink v. blue question seems moot, given that each page of the site uses a different color.)

**Comment by adamlofting** [comment]
It's always worth keeping a list of things to test :+1: and even keeping this list helps mitigate opinion battles.

But start with user testing, and later in the year as we build up traffic we can add some quantitative testing too. 

At this stage, we're not going to find the "perfect" button color for example, but we will notice if users are not seeing a particular call to action and successfully navigating the site. (FWIW, specific color is usually less important that the contrast of the color with the rest of the design).

**Comment by hannahkane** [comment]
This feels out of date now. Closing. Can file a new ticket as our testing needs emerge.
