### ISSUE TITLE
WEB LITERACY: change blue icons to match green side bar

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.webmaker.org#613]
Currently, the side bar is green and the rest of the page are blue. Change blue icons to match green side bar.
![fireshot capture 2 - mozilla learni_ - http___teach mofostaging net_teach-like-mozilla_web-literacy_](https://cloud.githubusercontent.com/assets/2492510/7032634/c36c8afe-dd28-11e4-9940-8b930c0ac2d9.png)

/cc @iamjessklein @vazquez the latest design will be green right? (sketch mockups I see are blue but I think it is outdated and wanted to confirm before I do so)

**Comment by davidascher** [comment]
The number of 'change color X to Y' tickets makes me wonder whether we can
not solve this programmatically.  @toolness, any ideas?

**Comment by toolness** [comment]
Yeah! I mentioned in https://github.com/mozilla/teach.webmaker.org/issues/564#issuecomment-90019866 that we could potentially do them programmatically as part of the build process, but in that issue there was an exception with one of the icons, which wasn't exporting to SVG very nicely.

Another option (at least for the ones that are exporting to SVG properly) might be to make our very own custom font set, in which case all colors could be busted up from CSS-land.

@iamjessklein, @sabrinang - Do you think colors will change much in the future? Would it be useful to be able to change them w/o having to re-export stuff from Sketch or whatever you're currently doing?

**Comment by iamjessklein** [comment]
+1 to making this a programmatic change. It's hard to tell at this point what we will be doing as we move forward with this site. We are just experimenting with and introducing the palette with this release, so we would want a solution that allows for us to maintain a certain level of flexibility at this stage.

**Comment by sabrinang** [comment]
![icon-web-literacy-illustration-green](https://cloud.githubusercontent.com/assets/2492510/7058424/87aaa6e2-de16-11e4-855e-2e5caafc0da9.png)
Web Literacy circle line art (green version): https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_edVhub0VDXzMzczQ/view?usp=sharing

![icon-contribute-green](https://cloud.githubusercontent.com/assets/2492510/7058435/aa490996-de16-11e4-96b2-796c878f4f98.png)
Contribute icon (green version): https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eSGJpY1U2X2dEa3c/view?usp=sharing

![icon-learn-more-green](https://cloud.githubusercontent.com/assets/2492510/7058439/bbd4a314-de16-11e4-9387-256d316fd66c.png)
Learn More icon (green version): https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eR0VVRHpndmpzM1U/view?usp=sharing

![icon-reading-green](https://cloud.githubusercontent.com/assets/2492510/7058440/c2c27070-de16-11e4-9e3d-57f5fb66e6ef.png)
Get Reading icon (green version): https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eelJfbldmVzRTeWc/view?usp=sharing
