### ISSUE TITLE
add youtube video from FOSS Asia to HTML Puzzle Box

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#617]
puzzles start at 1:02 https://www.youtube.com/watch?v=_LFaWJqRi64

**Comment by LauraHilliger** [comment]
fixed https://github.com/LauraHilliger/webmaker-curriculum/commit/1fd530ecdfc6afc8925210445de9d90c8a1f35cd

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/111"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/111.
Please don't comment on it here.
