### ISSUE TITLE
Determine content for "Tips for Running Your Club" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#62]
### RACI
* Phase: Design
* Owner: @amirad 
* Decision Maker: @amirad 
* Consulted: @LauraHilliger 
* Design Lead: 
* Dev Lead: NA
* Quality: @chrislarry33 @thornet 

### Background
This page is linked to from the main Clubs page.

### Content

See: http://mozilla.github.io/webmaker-curriculum/Experiments/StartHere/starting-club.html

**Comment by LauraHilliger** [comment]
We have content started for this that should be modified and remixed for clarity and prettiness:

http://mozilla.github.io/webmaker-curriculum/Experiments/StartHere/starting-club.html

**Comment by hannahkane** [comment]
Thanks @LauraHilliger. That's perfect. Added to ticket description. We should finalize the content, and then we can build it right onto the new teach site.

@thornet — who should be responsible for finalizing the content?

**Comment by chrislarry33** [comment]
I think we need to pair this way down and get crisp on the issue and/or create one level deeper of detail (could even be links to a wiki or google doc in the meantime)

**Comment by chrislarry33** [comment]
But the you should scan your options in <10 seconds

**Comment by thornet** [comment]
+1 to deeply editing it down. @LauraHilliger do you want to take a stab at a condensed version?

**Comment by LauraHilliger** [comment]
linking out to more information after quick grok is a good idea, we have loads of stuff. Not finished, but have started an index: http://mozilla.github.io/webmaker-curriculum/Experiments/StartHere/starting-club-index.html

**Comment by LauraHilliger** [comment]
Ok, I've updated this page (@hannahkane note that the URL is different from description URL) : http://mozilla.github.io/webmaker-curriculum/Experiments/StartHere/starting-club-index.html

and have made two new subpages:
http://mozilla.github.io/webmaker-curriculum/Experiments/StartHere/coordinate.html
http://mozilla.github.io/webmaker-curriculum/Experiments/StartHere/advocate.html

"Collaborate" takes the user to the training material on connecting with other people, and "Deliberate" takes folks to the webmaker-curriculum overview.

Feedback more than welcome, it's still a lot of information on those subpages. Maybe we can get someone to suggest edits / photos that make this better. 

cc/ @Saallen @amirad @LucyeoH as well, as you might have ideas on the types of support resources we need for clubs...

**Comment by chrislarry33** [comment]
This is an essential piece of this sites launch in the V1 construct. We are responsible for the content being clear, tight and actionable. During the Brooklyn Clubs workweek we decided that Amira was leading the community curration of this content and culling the previous iterations of. Clarity and usable information is this pages #1 goal. Design, layout etc is domain of DA's team. @amirad will lead getting this contented collected, curated and to design.

**Comment by chrislarry33** [comment]
@thornet

**Comment by thornet** [comment]
Thanks, @LauraHilliger for the content refresh. Lots of great stuff. 

@amirad will lead merging your doc with her doc that she wrote with community members: https://docs.google.com/a/mozillafoundation.org/document/d/1syswSeON-0o1svFz8F457uCncg8Kvx5IW8-2Xi3RBpw/edit

and getting it to the product team in a format that will be used for the site. 

We're getting better at using Github to track this docs but still a bit scattered. Sorry if I should've help set this one up better!

**Comment by amirad** [comment]
@LauraHilliger your github pages look so lovely! I would *really* appreciate your help in seeing what the google doc (http://bit.ly/1Dxa3zQ) is missing and adding comments to it based on the info in pages you have already done. I'm traveling next week but the group of community members who have been providing input on what it should look like have all been asked to also add their comments and feedback. 
Aiming for V2 to be ready March 9-10th.

**Comment by LauraHilliger** [comment]
Looks like you and I have very similar information, so I don't think you've missed anything. I made some comments, and sorry for jumping the gun.

**Comment by LauraHilliger** [comment]
Emma has some good tips on running her club too: http://tiptoes.ca/webmaker-exploratory-in-review/

**Comment by dajbelshaw** [comment]
That's *such* a good blog post. I like her tenacity and honesty. :)

**Comment by hannahkane** [comment]
@amirad and I met today to talk about how this overlaps in some ways with #84. She will work on the two pieces in tandem. She is a hero.

**Comment by amirad** [comment]
Did a second round of edits and made the tips more reflective of a club. @hannahkane @thornet @LauraHilliger thoughts? what's missing? Also asked sent a few more nudges to community members to get some last minute input on what we might have missed. 

https://docs.google.com/document/d/1syswSeON-0o1svFz8F457uCncg8Kvx5IW8-2Xi3RBpw/edit?usp=sharing

**Comment by LauraHilliger** [comment]
I don't think anything is missing, at least not off the top of my head. I made a round of edits, mostly copy suggestions and typo/semantic fixing. Hope that's helpful and this is getting nice and tight. Nice job @amirad

**Comment by hannahkane** [comment]
Looks awesome, @amirad. I added a couple comments - mostly around accentuating how the Clubs model is different from Maker Parties or other one-off activities.

**Comment by amirad** [comment]
Thanks @LauraHilliger @hannahkane 

We also identified that we will test this in Q2 and see what else we might have missed and need to adjust. 

@thornet @chrislarry33 can you give it a quality overview please so we can have it ready for end of heartbeat.

**Comment by thornet** [comment]
Did some copyediting in the doc. Thanks for putting this together, @amirad!

**Comment by amirad** [comment]
Did a last review and believe it's ready. @hannahkane over to you for the site implementation. Note: there is a "teach like Mozilla" hyperlink in there that needs to be changed once the site is live.

**Comment by hannahkane** [comment]
Thanks, @amirad. Will get design and implementation tickets ready to go. Closing this!
