### ISSUE TITLE
Swap lo fi/no fi kit URL on the Teaching Activities page

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#621]
NEW URL: https://laura.makes.org/thimble/MTUyODMwNDY0/lofi-nofi-teaching-kit

**Comment by ScottDowne** [comment]
@LauraHilliger I added your name to the list of authors for this kit too, I hope that's alright. Your name is a link to your twitter.

If you want that changed or removed let me know and I can do that before landing this.

**Comment by LauraHilliger** [comment]
thanks! It's perfect :+1:

**Comment by ScottDowne** [comment]
merged
