### ISSUE TITLE
Footer links overflow their container on mobile

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#624]
I noticed that the mobile/small-screen version of our site is now horizontally scrollable, with a bit of empty space on the right side. I tracked this down to the footer links:

![2015-04-09_8-26-16](https://cloud.githubusercontent.com/assets/124687/7066621/65b601d6-de92-11e4-9cef-467e96954782.jpg)

Removing the links removes the horizontal scrollbar and extra space on the right, so I am guessing we need to fix something about the margins there. This may or may not be related to #622.

**Comment by toolness** [comment]
Hey @mmmavis, want to work on this one?

**Comment by mmmavis** [comment]
This was fixed in https://github.com/mozilla/teach.webmaker.org/pull/646
