### ISSUE TITLE
Copy review of Teach site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#63]
### RACI
* Phase: Copy
* Owner: @hannahkane 
* Decision Maker: @KevZawacki
* Design Lead: 
* Dev Lead: NA
* Quality: @edrushka @HPaulJohnson 

When we're farther along in the design/build process, let's make sure we do a thorough copy review of the full site for mechanics, consistency, and tone.

**Comment by edrushka** [comment]
Switched the RACI to Kevin as decision-maker. He's the word-man now :)

**Comment by hannahkane** [comment]
This is now duped by the QA ticket.
