### ISSUE TITLE
/activities page is missing hero h1 copy

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#630]
I've added the hero section to the /activities page(see PR https://github.com/mozilla/teach.webmaker.org/pull/629).  h1 copy is still needed.

**Comment by iamjessklein** [comment]
For starters H1 copy should be "Teaching Activities"

Then, on the paragraph below, delete the title "Teaching Activities"

**Comment by iamjessklein** [comment]
cc/ @ldecoursy @kevinzawacki ^^ :eyes:
