### ISSUE TITLE
[MIGRATED] Close Hive Global Calls and fold into TTW Talks

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#634]
Close Hive Global call in next meeting on April 16th. Transition over to TTW talks (add Hive global mailing list to monthly BSD emails). Start mapping Hive needs and potential Hive speakers for TTW talks.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/112"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/112.
Please don't comment on it here.
