### ISSUE TITLE
[MIGRATED] Improve communication and sharing across local Hive calls

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#635]
Simona to email Elsa, Julia, Lindsay, and Kari to see how far in advance these calls are planned and how we can share call/themes across cities and share information/tweets for social. \\

Make sure all the hives have their calls in the calendar, and share it at the top of each of their monthly call pads for guests to see what else they can join this month. As well as share on social networks.

**Comment by simonaramkisson** [comment]
• Teams will begin adding me to invites so the calls/hangouts are in my calendar. I can share this information in office hours with new emerging communities
• All teams are excited to have new cities join their calls especially if the content will be useful

Elsa: 
• plans Hive Chicago call at least a week in advance, canvasses for speakers via member updates and Minigroup

Julia: 
• plans calls a month in advance, the more time the better
•

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/113"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/113.
Please don't comment on it here.
