### ISSUE TITLE
Update link in Lo-Fi, No-Fi teaching kit

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#636]
@LauraHilliger Do you mind updating the first link in the second section, titled "No-fi and paper-based activities."

The activity is currently called "HTML Puzzle Boxes" which is a duplicate of the activity below. The current link is correct but the activity should be called "Learning with LEGO"

Thanks!

**Comment by LauraHilliger** [comment]
updated https://laura.makes.org/thimble/MTUyODMwNDY0/lofi-nofi-teaching-kit

**Comment by ldecoursy** [comment]
Hi - one more change please @LauraHilliger !

Update link for Hacking My Media to: https://stephguthrie.makes.org/thimble/ODU3ODAxMjE2/hacking-my-media-with-x-ray-goggles

Steph just updated your latest version to include names of other contributors.

**Comment by LauraHilliger** [comment]
filed #695, as we need to update the URL on the teaching activities page

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/115"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/115.
Please don't comment on it here.
