### ISSUE TITLE
[MIGRATED] Transactional Email: Sign up for mentor and mp BSD lists

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#637]
Once teach.mozilla.org launches, individuals who sign up for our mailing lists should receive automated information directing them to the new site and resources to get started.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/116"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/116.
Please don't comment on it here.
