### ISSUE TITLE
[MIGRATED] Transactional Email: Sign up to Hive Learning Networks Mailing List

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#639]
We need to update this email to include new information and a link to teach.mozilla.org (which is launching in the next heartbeat)
CTA of email: Get information and access resources

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/117"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/117.
Please don't comment on it here.
