### ISSUE TITLE
See how many of last year's contributors we have permission to contact

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#64]
Of the 10K contributors we reached last year, we are looking to continue engagement in 2015. Q1 goal is to first group 4K of the 2014 contributors into a place where we can communicate with them

**Comment by amirad** [comment]
@adamlofting to first cross-check badge receivers and other contributor lists against existing mailings lists to see which of those 10k we can legally send comms to.

**Comment by adamlofting** [comment]
I've crossed checked these databases now, and 2486 of the contributors have opted in to hear from Mozilla via various sign-up forms.

**Comment by ldecoursy** [comment]
@adamlofting Is there any way for us to know where these contributors are located? Looking to build a baseline to know where activity is happening, to track towards our goal of 500 cities this year.

**Comment by adamlofting** [comment]
@ldecoursy we don't have any location data stored against these email addresses. We'd have to ask these people to tell us more about themselves (perhaps something they could do if and when they register on the new site).

**Comment by amirad** [comment]
Thanks @adamlofting - can we port this list into an easy to access group in BSD for future communications?

**Comment by chrislarry33** [comment]
Great question @amirad b/c if we could, that would be amazing. Also if/when we did can we have a plan for adding to it?

**Comment by amirad** [comment]
@chrislarry33 - do you have an idea of who you would want to add to it?

**Comment by chrislarry33** [comment]
i'd want to drive new people there

**Comment by adamlofting** [comment]
I'll setup the list in BSD for you. I've just filed an issue for that here: #122 

For getting new people into this list, you'll want a sign-up form built and this probably lives somewhere in the new teach site. This may be covered in the new site plans already, but best to coordinate this piece with @hannahkane / @ldecoursy as it will need design/dev/planning of some kind.

**Comment by adamlofting** [comment]
Pasting this summary here from an email thread, for easy reference:

### Summary

I took the database of all contributor email addresses from last year (all those that counted towards the 10k). This includes all the hive badge, skill-sharer, mentor badges, and other ad-hoc contributors who we logged but who didn't earn badges.

And then I cross checked this list against our existing webmaker.org mailing lists, and email opt-ins via the webmaker product.

The ~2500 list are those who were contributors last year AND have already told us during another interaction that it's OK for Mozilla to email them. So the ~2500 is a mix of hive badges, mentor badges and other mofo contribution activity.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/31"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/31.
Please don't comment on it here.
