### ISSUE TITLE
the download icon in teach is wrong

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/teach.webmaker.org#640]
When I first set it up I didn't have access to the icon I needed, so I need to go back and do that.

**Comment by iamjessklein** [comment]
@sabrinang can you determine the appropriate glyphicon?

**Comment by sabrinang** [comment]
We can use the glyphicon glyphicon-download-alt icon: 
![screen shot 2015-04-10 at 2 36 05 pm](https://cloud.githubusercontent.com/assets/2492510/7097906/2d9cf86a-df8f-11e4-9b9b-6e0f6cc0e0f1.png)

**Comment by ScottDowne** [comment]
I already have a pull request to update it to what was in the original mockups.

No idea how to link to specific icons: http://ionicons.com/

It's the one that looks like this: http://uxrepo.com/static/icon-sets/ionicons/svg/ios7-download-outline.svg

**Comment by iamjessklein** [comment]
Oh! I believe that I confused glyphicons with ionicons.

**Comment by ScottDowne** [comment]
Merged
