### ISSUE TITLE
mobile view for the tab content in event resouces is kinda busted

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/teach.webmaker.org#642]

**Comment by ScottDowne** [comment]
It displays the tabs then the content, kinda confusing.

**Comment by iamjessklein** [comment]
@ScottDowne are you referring to this (below)?

![screen shot 2015-04-10 at 4 33 53 pm](https://cloud.githubusercontent.com/assets/535012/7096929/75aa9576-df9f-11e4-8074-d7fc8328e3a0.png)

**Comment by ScottDowne** [comment]
Merged
