### ISSUE TITLE
[MIGRATED] Transactional Email: Sign up for Mozfest updates

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#643]
Can we re-look and update this email. Sarah, what is the CTA for people who have signed up? Does it make sense to include the new teach.mozilla.org site?

**Comment by Saallen** [comment]
The CTA will be as follows
* Submitt a proposal
* Register for a ticket
* Sign up as a volunteer
* remote participation

post festival I think it makes the most sense to push the audience to teach.mozilla.  
Pre festival I am not sure there is a clear link just yet

**Comment by amirad** [comment]
Great! That's a lot of CTA's - I'm assuming the emails will need to change over time? 
Can we start drafting text?
Agree - teach.mozilla is a great push after mozfest

**Comment by Saallen** [comment]
I have drafts from last year for all emails- I had imagined I would update as per send date arrived rather than pre draft these.

**Comment by amirad** [comment]
Cool. Maybe set out new tickets for each of those emails with dates of expected completion? And then close this one.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/118"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/118.
Please don't comment on it here.
