### ISSUE TITLE
Transactional Email: Sign up for TTW talks lists

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#644]
Update to the automated messaging that users see. Should probably include a link to teach.mozilla.org

**Comment by Saallen** [comment]
Sure, I can defintely do this on the footer of the mail out

**Comment by amirad** [comment]
Perfect! LMK when you update and we can check it out/close this ticket.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/119"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/119.
Please don't comment on it here.
