### ISSUE TITLE
[MIGRATED] Transactional Email: Sign up to Hive Mailing Lists and Blogs

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#645]
The mobilizing team is on a mission to update all of our transactional emails with the best CTA's and links. This includes all of the Hive lists/blogs that users sign up for and receive an automated email or message. Can each Hive take a peek at their transactional emails and make sure they are updated with the best cta's. Some notes
•With teach.mozilla.org launching within the next heartbeat, please consider linking to the site for resources and activities. A great potential CTA would be for people to map their clubs or programs to our new map. 
•Link to other ways they can stay in touch through social and discourse
•Links to where they can find events or connect with the local Hive community

**Comment by amirad** [comment]
@omnignorant @smithisgeneric @simonaramkisson @LindseyFrost @jvallera see above.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/120"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/120.
Please don't comment on it here.
