### ISSUE TITLE
[MIGRATED] Plan message arc to 4000 contributor list and write first copy

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#65]
Once we group the 4000 contributors in Q1 we need to dive into a plan on when we will be communicating messages to them and what the CTA will be. Should have rough copy ready for Q2 and launch of club material.

**Comment by amirad** [comment]
@HPaulJohnson - we should plan out the arc and plan for rough copy

**Comment by HPaulJohnson** [comment]
@amirad let's schedule a time to discuss and invite @KevZawacki

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/32"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/32.
Please don't comment on it here.
