### ISSUE TITLE
Rio: Recruit 10 LAN houses to be part of the pilot

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#66]
Get commitments from 10 LAN houses in Rio to be part of the web literacy pilot project.

**Comment by soapdog** [comment]
We're setting an initial group of 6 Lan Houses. Not all the Lan Houses we visited during the field research wanted to be a part of the project so thats why we don't have 10. We expect that as the project moves along, other Lan Houses with a similar mindset will want to join in and then the numbers will climb up again.

We already selected these six Lan Houses based on recommendation by Laura and the field work team.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/33"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/33.
Please don't comment on it here.
