### ISSUE TITLE
Update Teach Like Mozilla Scoping Doc

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#660]
now that #91 is in order, and the clubs curriculum follows a particular organizational structure, it makes sense to revise the Teach Like Mozilla scope to reflect the new "open fluency" map:

https://teach.etherpad.mozilla.org/weblitbasics

**Comment by LauraHilliger** [comment]
[Updated scoping document](https://docs.google.com/document/d/1quD8jfETB3_vuRc6IqWlbKAcn9bMcLGQOnpBiuH66Mw/edit)

Still need to figure out the 3 module - Idea is for a master level, project based guidebook that helps community members sustain the momentum in their local areas through global connection and promotion.

**Comment by LauraHilliger** [comment]
need to include "Your First Month" content. Should be compiled from existing as well as new pathways https://teach.etherpad.mozilla.org/sustainingengagement

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/122"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/122.
Please don't comment on it here.
