### ISSUE TITLE
Title the Teach Like Mozilla modules

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#661]
I'm not sure I'm happy with the module naming for Teach Like Mozilla, could use some help:

### Teach I: Teaching and Learning in the 21st Century
learning objectives center around understanding our pedagogies, working openly, finding collaborators, diversity, getting started in our world. (cognitive)

### Teach II: Designing for Global Engagement
learning objectives center around using open, participatory practices. This course is all about using open resources and technology to organize and collaborate with more people. (logistical)

### Teach III: Educational Expertise 
this one is half-baked, but my idea is to have this be the expert level, write a business plan / be consistent / participation rockstars, for local and global learning programming. A final "project" that prepares community members for sustained engagement with a specific program (e.g. Club or Hive or whatever level)

Who has other naming suggestions?

**Comment by davidascher** [comment]
In the canadian educational system, “21st century learning” is code for a lot of stuff that the school board is forcing on the schools — maybe not relevant, but I just want to flag that as a general class of things to be aware of.

**Comment by jgmac1106** [comment]
How about Digital Teaching and Learning for TEACH I. 21st Century (now that
we are a decade and half in is a little vapid). If you are striving for
parallelism Teaching and Learning in Digital Spaces or Teacing and Learning
in Open Spaces (no binary here)

I like TEACH II

TEACH III Building and/or Sustaining a Movement... or...Teaching locally,
Learning Globally....or.... Something that gets at learning at a sense of
advocacy and agency

**Comment by LauraHilliger** [comment]
Perfect! Thanks both :) I <3 "Teaching and Learning in Open Spaces" for the first one and Sustaining a Movement is nice too. Going to run those by the sustaining engagement team later this week. Thanks!  (/me goes to change the titles in all the docs.)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/123"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/123.
Please don't comment on it here.
