### ISSUE TITLE
[MIGRATED] Write final report on Maker Party grant

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#662]
We need to write a final report for the Maker Party grant. I've sent an email to Angela to get templates of previous reports for us to use as a base. 

@chrislarry33 can you provide more info on what needs to be included?
cc: @edrushka @ldecoursy

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/124"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/124.
Please don't comment on it here.
