### ISSUE TITLE
[MIGRATED] Rio: Start a bi-lingual blog about project

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#67]
Andre kicking this off

**Comment by davidascher** [comment]
Nice!

**Comment by soapdog** [comment]
I need a contact to set this up. I think Michelle sent me one but I still need to set LDAP and email so that I can do this blog with a Moz account and not my personal one.

**Comment by soapdog** [comment]
Can someone provide me with a contact to set the LDAP account and email?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/34"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/34.
Please don't comment on it here.
