### ISSUE TITLE
Develop links to Teach Like Mozilla from within activities.

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#671]
from @hannahkane's blogpost:

>We need to design a stronger connection between teaching activities and the Teach Like Mozilla >content. A short-term solution might be to link to the TLM page from every individual activity page, but >we should also be working towards a better longer-term solution.

This might be a little trickier said than done because some activities exist on user accounts, but we should promote our professional development curriculum through the activities. We can, however, start with all clubs curriculum, and whatever is published under team makes.org profiles.

**Comment by hannahkane** [comment]
Closing this ticket, as it feels premature.
