### ISSUE TITLE
[Basics II: Privacy] Remix IP Address Activity to fit into Club Curriculum template

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#672]
https://hivetoronto.makes.org/thimble/MTkyODM5NzA1Ng==/ip-address-tracer-activity-kit

- Section 1: Reading
- 30 - 45 minutes
- We should include pinging IPs via the Terminal

**Comment by LauraHilliger** [comment]
https://github.com/mozilla/webmaker-curriculum/pull/181

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/125"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/125.
Please don't comment on it here.
