### ISSUE TITLE
[Basics II: Privacy] Remix Data Trail Activity to fit into Club Curriculum template

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#673]
https://hivetoronto.makes.org/thimble/MTg3ODA2NTQwOA==/data-trail-timeline-activity-kit

- Section 2: Writing
- 45mins - 1 hour
- Ping @k88hudson for links to any documentation surrounding the IRC decoding game you ran at a Hive Toronto(?)
- Review browser fingerprint, panoptiklink.eff.org and/or browser add ons for expanding the activity

**Comment by LauraHilliger** [comment]
first draft, leaving issue open to discuss if we should add extensions (time is short already...)

https://github.com/LauraHilliger/webmaker-curriculum/commit/93b914866e72e5fa31b9231f86b83b4068a2ad13

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/126"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/126.
Please don't comment on it here.
