### ISSUE TITLE
[Basics II: Privacy] Remix Privacy Coach Activity to fit into Club Curriculum template

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#674]
https://hivetoronto.makes.org/thimble/MTkxMTYxOTg0MA==/privacy-coach-activity-kit

- Section: 3: Participating
- 45mins - 1 hour

**Comment by LauraHilliger** [comment]
https://github.com/mozilla/webmaker-curriculum/pull/186

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/127"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/127.
Please don't comment on it here.
