### ISSUE TITLE
[Basics II: Privacy] Remix Testing Password Strength Activity to fit into Club Curriculum template

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#675]
https://stacy.makes.org/thimble/MTY3NjY3MzI4MA==/testing-password-strength

- Section I: Reading
- 30 - 45 mins
- Learning objectives need documented

**Comment by LauraHilliger** [comment]
https://github.com/mozilla/webmaker-curriculum/pull/182

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/128"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/128.
Please don't comment on it here.
