### ISSUE TITLE
[Basics II: Privacy] Remix Creating Strong Passwords Activity to fit into Club Curriculum template

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#676]
https://stacy.makes.org/thimble/MjUwMDg1NjMy/creating-strong-passwords

- Section 2: Writing
- 30 - 45 mins
- learning objectives need documented

**Comment by LauraHilliger** [comment]
https://github.com/mozilla/webmaker-curriculum/pull/184

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/129"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/129.
Please don't comment on it here.
