### ISSUE TITLE
[Basics II: Privacy] Remix Lightbeam Activity to fit into Club Curriculum template

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#677]
https://laura.makes.org/thimble/lightbeam-activity

- Section 3: Participating
- 30 - 45 mins
- need to add a social component to this activity to make it more participatory

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/da8c8a61c0d32ecaf16ebd3da87b7b24f1c88935

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/130"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/130.
Please don't comment on it here.
