### ISSUE TITLE
[MIGRATED] [Basics II: Privacy] Augment privacy curriculum with icebreaker activities and further modules

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#678]
@smithisgeneric has great icebreakers in the Privacy badges facilitators guide. We should pull from here:

http://hivetoronto.org/wp-content/uploads/2015/03/PrivacyBadgesFacilitatorsGuide_ENG.pdf

**Comment by jgmac1106** [comment]
Question about Basics II overall.

 Basics I didn't have an overarching  theme (maybe telling your story) and focused on competencies. 

Looking at the new tickets it seemed Basics II is focusing on one skill in one competency across all three strands. 

My assumption was we would finish club curriculum for all the competencies. Am I wrong?

**Comment by LauraHilliger** [comment]
We've shipped "Protecting Your Data" ( #838 )

We determined that we have enough good ideas to create a second Privacy module. We can use this ticket to decide what the theme of that module should be. See notes starting line 65: https://teach.etherpad.mozilla.org/club-calls

**Comment by chrislarry33** [comment]
Hi Greg, you are both right and wrong. We are being opportunistic because Hive Toronto had good, youth driven, educator vetted, tested curriculum here and we need more offerings soon (yesterday, last week, last year etc) so we fast tracked it b/c we need it and b/c its an example of pulling up good stuff from our networks and getting it into a pipeline. This is admittedly a bit haphazard but I don't think detrimentally so. You are correct that we do want to get to full coverage of the map, buts so far that has proven to be slow and a bit directionless. We are also in the process of hiring a curriculum product director and that will/would be become their purview so we are stalling a bit there. 

Hope that makes sense, we are also very keen to have the community produe activites for skills and competencies and get added to the package in a similar way we are doing with the Toronto work.

**Comment by jgmac1106** [comment]
Chris,

Apologize for a brain dump that doesn't really fit this ticket;

Makes perfect sense and I really like the idea of building in themed
pathways that cut across the map. I just spent some time reflecting on
Basics I and its a large leap. The work that Laura is doing with Privacy is
great though I may suggest not calling it Basics II.

Rolling out privacy now makes total sense with the work Toronto has already
done and it captures the advocacy we have built in the Web Literacy Map
subjectives.

I saw on the site map the word "playlist" not sure if that is what we are
using for curriculum but if it is I love the idea. Playlists by their very
nature are remixable. I dig the idea of a privacy playlist.

I have some comments somewhere about different ways to build in basics for
basics II. They were in reference for privacy but I was thinking the
scaffolds necessary to get from basics I to the story of us.

These were the random comments. They probably don't belong here but I was
thinking about the three teaching activities I think best teach basic
html/css: The make-a-meme, movie poster, and the about me page.

Might be something to think about for the next basics module. The three can
also be remixed for any "themed pathway"

Another idea would be to bake these into the club first month activities as
a way to advertise and promote the club. The content is endless I just like
these three makes as I have been most successful in introducing them with
novice learners and teachers.

okay the random comments:

@amirad @thornet @epilepticrabbit reading over Basics I again
https://teach.mozilla.org/clubs/curriculum/ we should have included
make-a-meme. Needs more scaffolding between writing the web and
participating on the web. I found using the make-a-meme remix to be a good
way to teach basic CSS and HTML. It fits nicely after Hacking the News.
There are also easy no-fi and lo-fi options.

@amirad @thornet @epilepticrabbit The About Me page is also a good
scaffold. The movie poster make is a good step-up scaffold,
https://teach.mozilla.org/clubs/curriculum/

Maybe we add all of these to privacy. I could see "make a meme" some kind
of advocacy or awareness meme, about me page: deciding to shape your own
identity, movie poster- tell the story of a past or current threat.

**Comment by smithisgeneric** [comment]
This may be a bit "off-thread" but in-line with the conversation happening here.  

It looks like there is some interest in putting "make a meme" in privacy.  I think this can be a very successful and engaging privacy activity and I facilitated this as an offline activity (i.e. paper pictures + craft supplies) as described in the [Facilitators' Guide!] (http://hivetoronto.org/wp-content/uploads/2015/03/PrivacyBadgesFacilitatorsGuide_ENG.pdf) for the Hive Toronto privacy badges project.  

![privacymeme](https://cloud.githubusercontent.com/assets/6931814/7395467/11544ed2-ee68-11e4-82e8-509583aaec42.jpg)

**Comment by chrislarry33** [comment]
Love memes, love the meme work in Thimble. Question, should we wait for new Thimble/migration to teach site?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/131"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/131.
Please don't comment on it here.
