### ISSUE TITLE
Determine curriculum modules we'll produce and test in Q2

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#679]
This ticket is to discuss the in-progress roadmap. Production intentions can be found here:
http://mozilla.github.io/webmaker-curriculum/
and the wiki has a timeline: https://wiki.mozilla.org/Webmaker/2015/Mentors/Clubs/Curriculum

cc/ @amirad @ldecoursy @Saallen @thornet @hannahkane @simonaramkisson @chrislarry33 

@jgmac1106 said in #678 

> Question about Basics II overall. Basics I didn't have an overarching theme (maybe telling your story) 
> and focused on competencies. Looking at the new tickets it seemed Basics II is focusing on one skill in > one competency across all three strands.
> My assumption was we would finish club curriculum for all the competencies. Am I wrong?

@jgmac1106 - Yes, with Basics I we were basically doing a "get your feet wet" web literacy module. For the next one, we planned to take a prevalent topic (which also happens to be a competency: Privacy), and focus in. I'd like to cover ALL the skills underneath privacy, so we should look at the individual activities as we remix and test to see if we can hit them all. Would love to hear your thoughts on this!

**Comment by jgmac1106** [comment]
Laura,

Thanks this timeline and wiki make sense now. Sorry for the confusion. It
looks like we are making different pathways through the web literacy map
after Basics I (possibly after Basics II) privacy.

We will want to make sure that no matter what path is chosen the majority
if not all competencies are hit by the time clubs complete Basics II.

**Comment by toolness** [comment]
I keep reading this issue as "discuss circular roadmap" and then having nightmares about finishing the site, only to go back to square one because our project roadmap is circular.

**Comment by jgmac1106** [comment]
What is most telling was the confusion of users in Hannah's testing about
the club curriculum and the learning activities.

They wanted more and couldn't tell the difference.

They were also slightly confused by navigation.

We are at the limits of my knowledge (its a short journey) but current
curriculum is on github pages.

Will this continue? Can curriculum development occur separate of the site
and just added as modules develop?

**Comment by LauraHilliger** [comment]
In the short term, github pages will continue. But it's likely not sustainable b/c github is a huge lift for most of the folks who actually DO instructional design. If we want to exponentially expand the curricular library we'll need to consider other submission methods.

**Comment by jgmac1106** [comment]
I don't mind using Thimble until Thimble 2.0 launches.

The hardest part  of using the old kits and activities was trying to get
the external CSS working.

I could do it now but when I started I would mess it up as I tried to copy
and paste the code from Thimble into WordPress.

We should try to keep the external stylesheets minimal so people can grab
code for their own websites.

Does this mess up the metrics though? Did folks intend on counting how
often pages were pulled to track anything?

**Comment by hannahkane** [comment]
Just a quick note to say that the question of easier submission of activities is represented on what is currently line 112 of the product roadmap (http://wiki.webmaker.org/Teach)—"allow users to easily create beautiful activities and kits." That one little line encompasses a whole lot of thinking we'll need to do. Personally, I can't wait! :)

**Comment by LauraHilliger** [comment]
@hannahkane Me neither! Should do some braindumping...

**Comment by thornet** [comment]
@LauraHilliger and I did some updating of the curriculum queue: 
http://mozilla.github.io/webmaker-curriculum/

I still think the TLM stream needs some edits. Maybe: 

* Your first month: How to Club for Regional Coordinators [Producing, Q2]
* Your first month: How to Club for Club Captains [Producing, Q2]
* Teach I: Teaching and Learning in Open Spaces [In Queue, Q3]
* Teach II: Designing for Global Engagement  [In Queue, Q3]	
* Teach III: Sustaining a Movement [In Queue, Q3]

Also, I suggest we add another item in the Web Literacy stream:

* Basics II [In Queue, Q3]. This will cover the rest of the basics and build on module 1. Likely a "best of" sequence from the content we curated for the launch of teach.mozilla.org. 

The rest can be parking lot or removed to de-clutter.

**Comment by LauraHilliger** [comment]
Just noting that TLM isn't that clean from the production standpoint. Your 1st Month is a compilation from I, II or III, so really we're producing all the things in parallel.

Waiting to add a new one to the WebLit Stream – was thinking it would be good to produce privacy and then cross-check what competencies we missed b/w Web Lit Basics and Privacy Basics. Then cover those in the 3rd "basics"

**Comment by thornet** [comment]
@LauraHilliger let's move the Your 1st Month guides into a heartbeat structure. We can set that up in our 1:1 this week. Our TLM content this quarter should primarily fuel and support these guides, since we have an acute need and a testing group ready to use. The remainder of the TLM content can come in Q3.

**Comment by thornet** [comment]
Renaming to: Determine curriculum modules we'll produce and test in Q2.

**Comment by thornet** [comment]
@LauraHilliger let's also talk about a Web Lit module aimed at web creation and participation on mobile. That was a big focus Mark has requested -- could prepare us for activities to feature in July during MP.

**Comment by ldecoursy** [comment]
Here's an awesome start from Digital Corps :) https://theanimal.makes.org/thimble/MTMyMTY2NDc2OA==/digicorps-mobile-media-teaching-kit

**Comment by LauraHilliger** [comment]
>web creation and participation on mobile
would mean *with* the Webmaker App, right? We have loads on mobile ideation, appmaker and external app building tools. Shouldn't be hard to pull some things together and augment with extra special Webmaker App sauce.

https://laura.makes.org/thimble/MTM0NzM1NDg4MA==/mobile-app-ideation-for-entrepreneurs-kit
https://jess.makes.org/thimble/MTMyMzM2ODQ0OA==/mobile-design-kit (3 kits in 1!)
https://laurey.makes.org/thimble/MTY2Nzk1Njk5Mg==/mobile-app-ideation-exploratory-kit

**Comment by thornet** [comment]
Summarizing and closing: 

TLM stream: 

Q2: 
* Your first month: How to Club for Regional Coordinators [Producing, Q2]
* Your first month: How to Club for Club Captains [Producing, Q2]

Q3:
* Teach I: Teaching and Learning in Open Spaces [In Queue, Q3]
* Teach II: Designing for Global Engagement [In Queue, Q3]
* Teach III: Sustaining a Movement [In Queue, Q3]

Web Literacy stream:

Q2:
* Privacy [Producing, Q2]
* Mobile creation [Producing, Q2]

Q3:
* Basics II [In Queue, Q3]. This will cover the rest of the basics and build on module 1. Likely a "best of" sequence from the content we curated for the launch of teach.mozilla.org.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/132"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/132.
Please don't comment on it here.
