### ISSUE TITLE
[MIGRATED] Rio: propose how to engage and on-board local volunteers for LAN house events

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#68]
Andre & Mario beginning to draft what this volunteer strategy would look like.

**Comment by soapdog** [comment]
The plan is to start with a group of volunteers from the local Mozilla/WebDev community and then use this group to train volunteers in the local neighborhood of the Lan Houses. This way we can tap in the local amazing web community and also engage them in social cause. In the end we have a mixed group of highly talented and accomplished web developers working with new volunteers full of energy and potential.

On 11th of April we'll have a web dev event here in Niterói called NiteroiJS where I plan to recruit some volunteers. I already have a group of close to four volunteers (besides our current team of 3 or 4 people). My aim is to have 12 volunteers engaged with the project which would make it 2 per Lan House in this initial phase.

After we collect contact with interested volunteers-to-be, we'll have an informal meeting to present the project and do a train the trainers session.

Once we start doing the workshops on the Lan Houses we plan to spot people that are keen to take the web as their own and are aligned with our mission. We plan to further empower them by doing "train the trainer" workshops with those folks and leveraging their help as mentors for new workshops thus engaging the local/neighborhood community.

**Comment by soapdog** [comment]
Also approaching key web developers with a strong desire to cause an impact and social transformations here in Rio to help with awareness to this project and with an initial set of volunteers.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/35"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/35.
Please don't comment on it here.
