### ISSUE TITLE
Implement teach site referral on Webmaker.org

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#681]
Once the design is finalized in #469 and once we release the site #152, let's implement the ad!

**Comment by hannahkane** [comment]
@mmmavis - I'm assigning this to you in advance, but let's not do it until the next heartbeat.

**Comment by mmmavis** [comment]
Copy should be
**[Head]** Want to teach the web to others? 
**[Subhead]** Join Mozilla's community of educators who teach digital skills and web literacy.

**Comment by mmmavis** [comment]
@hannahkane do you know when we want this to be live (sooner the better or on a specific date/time)?

**Comment by hannahkane** [comment]
@chrislarry33 - are you okay with rolling the Teach site promo banner to Webmaker.org now?

**Comment by hannahkane** [comment]
hey @mmmavis - got a verbal ok from @chrislarry33, so we're good to go on this as soon as you can.

**Comment by mmmavis** [comment]
cool, thanks for checking.

**Comment by mmmavis** [comment]
Hi @gvn (don't know who to ask, though you would know :grin: )

I'm gonna add a section to `webmaker.org` home page like: https://github.com/mozilla/teach.webmaker.org/issues/469#issuecomment-92501292. Question: which view file should I be editing?  I see under `public/views/` there are `home.html`, `home-2.html`, ..., `home-6.html` but I'm not sure if I'm making changes to one file only or all of them.

**Comment by gvn** [comment]
I'm honestly not sure either. I'd check the history and see who has been working on those files recently...

**Comment by mmmavis** [comment]
oh yea, nice suggestion! @vazquez  that will be you :stuck_out_tongue_winking_eye: (see https://github.com/mozilla/teach.webmaker.org/issues/681#issuecomment-98058455)

**Comment by vazquez** [comment]
Hey @mmmavis :). Aki set the pages up like that in order for us to do A/B testing on them. We have since finished the A/B testing, so I'm pretty sure we don't need `home.html` all the way to `home-6.html`. Right now on `webmaker.org` we seem to be loading `variant-3`, but I don't specifically know what this layout corresponds to (home-1, home-2, etc) :(

![screenshot 2015-05-01 14 10 21](https://cloud.githubusercontent.com/assets/1119821/7434806/da0fd3ce-f00b-11e4-965a-bc81a4498c14.png)

**Comment by mmmavis** [comment]
thanks @vazquez , that `variant-3` appear to be in [home-3.html](https://github.com/mozilla/webmaker.org/blob/master/public/views/home-3.html#L3).  I guess that will be the file I'm making changes to :bowtie:

**Comment by mmmavis** [comment]
@hannahkane ,
Is `https://teach.mozilla.org/` the url to use on the button?  I wonder if we should include a GA referral code or something there?

cc @adamlofting

**Comment by hannahkane** [comment]
Good call. We should definitely track referral traffic. I'll defer to @adamlofting for the best way to do that.

**Comment by mmmavis** [comment]
Let's use "https://teach.mozilla.org" for now and @adamlofting can suggest what referral code we can append when he's back from PTO.

PR submitted on webmaker.org repo: https://github.com/mozilla/webmaker.org/pull/1400

**Comment by mmmavis** [comment]
live on https://webmaker.org :dancer:

**Comment by hannahkane** [comment]
woohoo!

**Comment by adamlofting** [comment]
Here's the URL with GA referral codes to help with analytics:
* https://teach.mozilla.org?ref=webmaker_homepage_promo&utm_campaign=webmaker_homepage_promo&utm_source=webmaker.org&utm_medium=referral

For future use cases, you can use this handy tool to generate these parameters: 
* http://mozilla.github.io/mofo-campaignurl/ :sunglasses:

**Comment by mmmavis** [comment]
@adamlofting 
:+1: coooool!  didn't realize that tool existed :laughing: I'll try to make use of it next time (but might bug you if I need additional guidance) Thanks!!!

**Comment by mmmavis** [comment]
live on https://webmaker.org

**Comment by toolness** [comment]
Whoa cool, I didn't realize we could add referral codes and stuff to our site either. Thanks @adamlofting!
