### ISSUE TITLE
Three small copy changes on Teaching Activities page

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#685]
For the Creative Commons GIF Exchange and CSS Story Cards activities, the "Developed By" text should read as follows: MOUSE (Hive NYC member)

For the last activity featured on this page https://teach.mofostaging.net/activities/, entitled "Girls in Tech: Hacking My Media," under Developed By, please change from Stephanie Guthrie to Steph Guthrie.

Thank you!

**Comment by ldecoursy** [comment]
One additional small change. 

For the last activity featured on this page https://teach.mofostaging.net/activities/, entitled "Girls in Tech: Hacking My Media," under Developed By, please change from Stephanie Guthrie to Steph Guthrie.

Thanks!

**Comment by hannahkane** [comment]
@mmmavis - would you be able to do this one as well?

**Comment by mmmavis** [comment]
for sure, PR open here: https://github.com/mozilla/teach.webmaker.org/pull/691

**Comment by ldecoursy** [comment]
Hi @mmmavis, can you please remove the second reference to Hive NYC for the CC Gif Exchange and CSS Story Cards activities?

Currently reads: MOUSE (Hive NYC member), and Hive NYC
Should read: MOUSE (Hive NYC member)

Thanks!

**Comment by mmmavis** [comment]
np, i have a PR open now.
