### ISSUE TITLE
Clone mofo-example app and push to https://learning.mofostaging.net/

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.webmaker.org#69]
It's time to start! 

* [ ] Clone mofo-example-app
* [ ] Strip out all but basic UI web site
* [ ] Replace home page with current redpen image
* [ ] File issue for DNS
* [ ] Push to heroku

**Comment by davidascher** [comment]
We're likely going to end up with learning rather than teach in the domain, so changing the issue title to match.

**Comment by hannahkane** [comment]
@simonwex - can we close this one?

**Comment by hannahkane** [comment]
Closing. Re-open if needed.
