### ISSUE TITLE
"Each child in an array should have a unique "key" prop" warning in tests

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#694]
Full log message:

> Each child in an array should have a unique "key" prop. Check the render method of `ModalAddOrChangeYourClub`. See http://fb.me/react-warning-keys for more information.

Should be pretty easy to fix.

**Comment by toolness** [comment]
Hey @mmmavis would you be interested in hunting down this bug and fixing it?

**Comment by mmmavis** [comment]
YES! :metal:
