### ISSUE TITLE
Expander component doesn't have unit tests

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#698]
I noticed that `components/expander.jsx` doesn't seem to have any unit tests, which is concerning because there are JS event handlers in it.

@ScottDowne would you be interested in writing tests for this? I think you could probably use the [sidebar tests](https://github.com/mozilla/teach.webmaker.org/blob/develop/test/browser/sidebar.test.jsx) as a jumping-off point.

**Comment by ScottDowne** [comment]
Yeah, I should do this. It'll be a p2 for me though.

**Comment by ScottDowne** [comment]
Is the idea we just test cs related things? And not css/html related things?

If that's the case, I think this only has one js interaction, and it's an enhancement and not required. So this should be a good starting point for my test making experience. (It's been a long time)

**Comment by toolness** [comment]
Rad!

Yeah, I think testing css/html is hard for various reasons, so just JS stuff would be great.

**Comment by toolness** [comment]
Hey @mmmavis, it looks like Scott's pretty busy with other stuff, would you be interested in taking this one on, to familiarize yourself with unit testing?

**Comment by mmmavis** [comment]
YEAH! :metal:
