### ISSUE TITLE
Implement button design with Webmaker logo

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#700]
This is to signal to the user the connection between Teach and Webmaker, in terms of authentication.

We decided to use option 3 here: https://redpen.io/vy733a8b80210605bd

The svg for the logomark is here: https://www.dropbox.com/s/4yndkmm0b1b92u3/logo-webmaker-flat.svg?dl=0

**Comment by hannahkane** [comment]
@mmmavis - can I assign this one to you?

**Comment by secretrobotron** [comment]
Do we have some assets for the button floating around? (the webmaker logo image, really)

**Comment by hannahkane** [comment]
Hmmm...I got the dropbox link from the design ticket, but it doesn't seem to work. @cassiemc - can you please provide?

**Comment by cassiemc** [comment]
This link wfm @hannahkane (it's a white svg) - can anyone else test?

**Comment by secretrobotron** [comment]
WFM: https://dl.dropboxusercontent.com/u/7054348/logo-webmaker-flat.svg

**Comment by mmmavis** [comment]
Does "Create an account" go first or "Log in"?  [Staging](https://teach.mofostaging.net) doesn't match what we have on [mockup](https://redpen.io/vy733a8b80210605bd).

**Comment by hannahkane** [comment]
Let's match the mock-up.

**Comment by secretrobotron** [comment]
@mmmavis just a heads-up: @toolness didn't push new login stuff to staging yet. The latest is on http://mozteach.toolness.org/ which does point to login already.

**Comment by hannahkane** [comment]
w00t. looks good!
