### ISSUE TITLE
@darkBlueSidebarColor is defined twice in variables.less

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#701]
```less
@darkBlueSidebarColor: #5791CE;
@darkBlueSidebarColor: #2D4A8C;
```

Which one wins? We should probably remove whichever one we don't want...

**Comment by mmmavis** [comment]
cc @iamjessklein @sabrinang

**Comment by vazquez** [comment]
This is the correct one: ` @darkBlueSidebarColor: #2D4A8C;`
