### ISSUE TITLE
Add links to Events Resources page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#706]
THE BASICS
* Make Some Gear: 
  * "logo" should link to eps logo file
  * "shirts" in "what your shirts could look like" should link to https://party.webmaker.org/img/makerparty_tshirtpreview.jpg (let's move that file to teach, though)
  * "this activity" should link to https://tbx.makes.org/thimble/stencil-a-tshirt
  * "certificates" should link to https://makerparty2014.makes.org/thimble/LTEzNDM3NTAxNDQ=/maker-party-love-bomb
* All About The Wifi:
  * "activities that require no Internet access" should link to https://keyboardkat.makes.org/thimble/LTIxMDA3NTY0ODA=/lofi-nofi-teaching-kit

BEFORE EVENT
 * Add Your Event to the Map:
  * link "our global map" to https://events.webmaker.org
 * Recruit Mentors:
  * "Sample Volunteer Package" should link to https://party.webmaker.org/party-resources/pdf/Sample_Volunteer_Package.pdf (let's host that on Teach, though)
 * Promote Your Event:
  * "poster" should link to https://techkim.makes.org/thimble/maker-party-movie-poster
 * Press:
  * "Maker Party Press Kit" should link to https://wiki.mozilla.org/Maker_Party/Communications/Press_Kit
  * "social media toolkit" should link to https://wiki.mozilla.org/Maker_Party/Communications/Social_Media_Guide
  * "#makerparty" should link to https://twitter.com/search?f=realtime&q=%23makerparty

DURING EVENT
 * Design a Fun Experience:
  * "spectrogram" should link to https://mozteach.makes.org/thimble/how-to-run-a-spectrogram-icebreaker
 * Set-up:
  * "event checklist" should link to https://party.webmaker.org/party-resources/pdf/Event_Set_Up_Checklist.pdf (let's host that on Teach) 
 * Activities:
  * "some of ours" should link to /activities
 * Documentation:
  * "#makerparty" should link to https://twitter.com/search?f=realtime&q=%23makerparty
 * Wrap-up:
  * "event take down checklist" should link to https://party.webmaker.org/party-resources/pdf/Event_Take_Down_Checklist.pdf (let's host on Teach)

AFTER EVENT
 * Share What You Learned:
  * "#makerparty" should link to https://twitter.com/search?f=realtime&q=%23makerparty
  * "sample guidelines" should link to https://party.webmaker.org/party-resources/pdf/Sample_Blog_Post_Guidelines.pdf (let's host on Teach)
 * Thank You's:
  * "Send a heartfelt "Thank You!"" should link to https://party.webmaker.org/party-resources/pdf/Sample_Thank_You_Letters.pdf (host on Teach)

**Comment by hannahkane** [comment]
@mmmavis, this one is a doozy, similar to the one you did for the Clubs Toolkit, though it includes some resources that are currently hosted on party.webmaker.org that I'd like to move over to teach.mozilla.org. Is that possible?

**Comment by mmmavis** [comment]
@hannahkane 
I think it's doable.  Do you have a preferred directory/path for the few assets you mentioned above to go? e.g. `teach.mozilla.org/PATH_YOU_WANT/helloworld.pdf`

cc @toolness

**Comment by hannahkane** [comment]
hmmm.... is /assets/ appropriate?

**Comment by toolness** [comment]
HMM.

What about `/event-resources/`, since it seems like the stuff on the other site is in `/party-resources/`? I like that a bit better just b/c `/assets/` could be interpreted as kind of ambiguous--e.g., does it mean assets the website needs to function properly, or assets that others can use to host their own events?

Perhaps `/downloads/` might be even more clear, as it makes it obvious that everything in there is to be explicitly downloaded by end-users, rather than seamlessly embedded in the site like our other files?

**Comment by hannahkane** [comment]
I'm good with either. Let's go with /event-resources since that's super un-ambiguous.
