### ISSUE TITLE
Add photo credits on Participating on the Web activity

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#709]
Hi - 

Just heard back from Rookies - we need to add two photo credits on this page: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session03-storyofus.html

* On the the photo of the four girls in the sidebar, credit should be: WNYC Radio Rookies
* On the photo of the two boys on the bench doing the interview, credit should be: Sanda Htyte

@thornet or @LauraHilliger, can you please update?
Thanks!

**Comment by LauraHilliger** [comment]
https://github.com/LauraHilliger/webmaker-curriculum/commit/bd25ffb7fcfbf6e2da1837765f5ecc014f2dc173

**Comment by ldecoursy** [comment]
Hi - the sidebar photo says photo credit to WYNC, but it should be WNYC. 

Also, is there a way for us to link directly to the Story Planning Worksheet and the Recording and Interviewing Basics handouts that are referenced as optional in the sidebar and under Preparation? Those links currently go to this site: http://www.wnyc.org/story/diy-radio-rookies-toolkit/ where you need to scroll down to the handouts section to find them.

**Comment by LauraHilliger** [comment]
all fixed up: https://github.com/LauraHilliger/webmaker-curriculum/commit/0ffee73c461fe5106d83768eace34f9347465722
