### ISSUE TITLE
Add link to Clubs confirmation email

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#716]
The p.s. in the email with subject line "Thanks for joining the global movement to teach the web!" has  placeholder copy.

Should read: "Be sure to check out our tips for running clubs" where "tips for running clubs" is linked to the Clubs page.

**Comment by toolness** [comment]
Oh, we're actually sending a plain-text email, not an HTML email (it's required for accessibility and stuff). Is it ok if it instead says this:

```
P.S. Be sure to check out our tips for running clubs at https://teach.mozilla.org/clubs/ !
```

99% of the mail clients out there will automatically hyperlink the URL, which is nice at least.

**Comment by hannahkane** [comment]
+1

**Comment by toolness** [comment]
Ok, fixed in https://github.com/mozilla/teach-api/commit/477a75504a2acd478dd103298754b9a949d0dc72 !
