### ISSUE TITLE
Can't logout on Safari in iOS

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#718]
When I click the logout link, it seems to get stuck on teach-api.herokuapp.com. Then even if I refresh, so I'm back on teach.mofostaging.net, I'm still authenticated. Tried about 25 times and then it worked. Logged in again, and experienced the same problem, though I didn't try to log out 25 times this time.

**Comment by hannahkane** [comment]
cc @secretrobotron and @cadecairos in case this is actually an id.webmaker issue

**Comment by toolness** [comment]
Hey, I think this is a duplicate of https://github.com/mozilla/id.webmaker.org/issues/254... Does Safari logout work ok now?

**Comment by hannahkane** [comment]
Yes, wfm now.

**Comment by toolness** [comment]
woot!
