### ISSUE TITLE
Organize /img and its subdirectory

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#720]
We should find time to organize assets and directories in `/img`.  

[`/img/activities-page`](https://github.com/mozilla/teach.webmaker.org/tree/develop/img/activities-page) is a case that the assets organization is different from all other directories for pages.  It has subdirectories for relevant assets to go.
vs
[`/img/about-page`](https://github.com/mozilla/teach.webmaker.org/tree/develop/img/about-page) where all assets live on the same level.

We should set a convention to follow and reorganize the `/img` folder after.

cc @toolness

**Comment by toolness** [comment]
Yeah, this is a great idea. It also seems like we might be duplicating some of our assets across pages, e.g. the [maker party logo shared between "Events" and "Event Resources"](https://github.com/mozilla/teach.webmaker.org/pull/582#issuecomment-91021330).
