### ISSUE TITLE
[MIGRATED] Draft minor policy for website

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#730]
With legal team, review our options around age-related pieces of the site. Learn from how other orgs deal with this. Prepare and publish our own minor policy before June.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/133"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/133.
Please don't comment on it here.
