### ISSUE TITLE
[MIGRATED] Create TLM "recruitment template"

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#731]
For *Your first Month as a Club Captain/Regional Coordinator*, there's an action for people to "recruit". In one instance for club leaders, and in another for learners. We should provide a spreadsheet that they can remix to help them track of who they talk to and outcomes. 

I'd imagine we have good and better spreadsheets to remix for this purpose. Got something low bar and suitable Mobilizers? @amirad @Saallen @simonaramkisson @ldecoursy @Elsamozilla

**Comment by thornet** [comment]
cc @soapdog who's prototyping some of our RC materials. He might have a document for tracking recruitment. 

Also @ldecoursy and @adamlofting were helping with some activity tracking spreadsheets.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/134"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/134.
Please don't comment on it here.
