### ISSUE TITLE
Write up 3-5 club case studies

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#732]
Showcase the kinds of clubs that can exist. Highlight diversity: geography, targeted age, topical, duration, meeting place. Stand-alone and embedded. For next version of site. 

Bonus: illustrations, photos. Visual assets.

**Comment by thornet** [comment]
Closing because #756 is a duplicate and has more action.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/135"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/135.
Please don't comment on it here.
