### ISSUE TITLE
Design Maker Party promotion on Teach site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#736]
### RACI ###
Driver: @hannahkane
Decision-maker: @HPaulJohnson 
Design lead: TBD
Consulted: @amirad @chrislarry33 @kevzawacki

In the weeks leading up to and during this year's Maker Party campaign (July 15 - 31), we'll want to be promoting it loudly on the Teach site. This may look like a banner on the homepage, or even in the header, but I think we're open to other ideas as well. 

The destination will be /events, which explains the campaign pretty well.

We made need two versions: one leading up to MP, and one during MP, but they'll likely be pretty similar if not the same.

**Comment by sabrinang** [comment]
![teach_homepage_makerparty_edition_ideas](https://cloud.githubusercontent.com/assets/2492510/7802887/4b4207be-02f5-11e5-81ba-6c78e0461b05.png)

Some ideas for a banner below the hero image on redpen: https://redpen.io/p/wma08a6ac2cc6555f1
NOTE: all copy are placeholders for now to show design

The design can change according to the CTA for Maker Party, where we want to direct users and corresponding copy we will need to promote it.

**Comment by amirad** [comment]
The first two (which emphasis the button) and seem more 'clickable'. 
All look well branded. 

Copy needs a lot of work to make it feel less like a 2 week thing and more year-around. Suggestions for Paul: "Maker Party is Mozilla's global campaign to teach the web. Celebrate our year-round party with individuals and organizations from around the world who host events to teach the web."

**Comment by HPaulJohnson** [comment]
+1 to the first two which have clearest CTA's, in particular I like the first one. 

RE: copy, @KevZawacki and I can come up with something that does a better job of conveying year-round. I'd like to keep it very short and leave the longer explanation for the MP page (/events) when a user clicks through.

**Comment by ldecoursy** [comment]
I also +1 the first one, although wonder if another color for the background might be better (makes the site above the fold seem very blue). 

@HPaulJohnson @KevZawacki copy for the /events page is in #843 and ready for your eyes/approval ;)

**Comment by KevZawacki** [comment]
I like the first two, too. Especially the second -- the button is prominent and the coloring draws the eye.

+1 to Amira's copy, with small tweaks:
"Maker Party is Mozilla's global campaign to teach the web. Participate in our year-round party by hosting or attending events to teach, build and share amazing things online."

**Comment by chrislarry33** [comment]
#1 WFM

**Comment by chrislarry33** [comment]
I am good with the copy trusting @KevZawacki as final reviewer

**Comment by sabrinang** [comment]
Updated mockups with new copy
![teach_homepage_makerparty_edition_ideas2](https://cloud.githubusercontent.com/assets/2492510/7832985/0309ec86-0418-11e5-88ac-61bb8e6d95fb.png)

**Comment by ldecoursy** [comment]
Thanks @sabrinang! My vote is still for # 1

**Comment by amirad** [comment]
#1

**Comment by ldecoursy** [comment]
Re: copy, I think we could stand to shorten it a bit (very helpful to see in the mock-up). Also think we want to have the dates listed here to signify timeliness/urgency. The "year-round" messaging will be on the updated /events page. 

Suggestion:
"July 15-31 Participate in Mozilla's global campaign to teach the web."

**Comment by hannahkane** [comment]
+1 to both of Lainie's points above.

Also, just to clarify - this banner will no longer appear on the site after July 31st. It's meant to promote the two-week campaign, not to be a permanent CTA that competes with the other main CTAs.

**Comment by hannahkane** [comment]
ping @HPaulJohnson @KevZawacki and @amirad re: Lainie's copy suggestion above. That work for you guys?

**Comment by KevZawacki** [comment]
Yep, +1!

**Comment by amirad** [comment]
Yes

**Comment by HPaulJohnson** [comment]
yes!

**Comment by sabrinang** [comment]
Updated copy on mockups
![teach_homepage_makerparty_edition-updatedcopymockups](https://cloud.githubusercontent.com/assets/2492510/7949458/cbc68542-0942-11e5-8f12-3e52bf3e29ee.png)
* variation on bold date, line break and July 15th–31st/July 15–31
* included yellow bg option in case there was not enough contrast against the other blues on teach homepage

**Comment by amirad** [comment]
Looks good....preference is for line break, bold date and july 15-31

**Comment by hannahkane** [comment]
My preference is also for line break, bold date, and July 15-31. I think the top one, with the blue background, is pretty perfect.

**Comment by KevZawacki** [comment]
Likewise -- I vote line break and bold date. Looks great!

**Comment by sabrinang** [comment]
Assets for Promo: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efkJQcEJseDlNOUlMUGNhdWwzMVFkcWp1anh6NEVZX0hMT1hiWTk5TExVWnM&usp=sharing
Tile pattern
![maker-party_pattern-tile](https://cloud.githubusercontent.com/assets/2492510/7997641/421dd12a-0ae5-11e5-8a22-27e196b1e172.png)
Logo (with ribbon)
![maker-party_certificate-header](https://cloud.githubusercontent.com/assets/2492510/7997643/47e255a4-0ae5-11e5-9b59-e8606aacd2f2.png)
BG Colour: #CAE8EF
Text Size: 18px (Semibold & Light)
