### ISSUE TITLE
Design Maker Party promotion on Webmaker site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#737]
### RACI ###
Driver: @hannahkane
Decision-makers: @HPaulJohnson 
Design lead: TBD
Consulted: @thisandagain @amirad @chrislarry33 @kevzawacki @xmatthewx 

In the weeks leading up to and during this year's Maker Party campaign (July 15 - 31), we'll want to be promoting it loudly on the Webmaker site. 

The destination will be teach.mozilla.org/events.

**Comment by hannahkane** [comment]
@HPaulJohnson - wondering if there's a pre-step for this, before I put it into a heartbeat? Do we need to have some time to just think through look & feel, or can we just start designing?

**Comment by HPaulJohnson** [comment]
@amirad, @KevinZawacki and @ldecoursy are meeting tomorrow to do some deliverables planning for MP. I'll update this ticket tomorrow after that discussion but should be close to getting this into a heartbeat.

**Comment by hannahkane** [comment]
@thisandagain / @xmatthewx  - can you provide some guidance on what the promotional opportunities will be on Webmaker after June 19th? Wondering if we can promote Maker Party there. Could temporarily replace the Teach promotion though the end of July.

**Comment by thisandagain** [comment]
The existing landing page will be replaced completely, but I'm 100% open for continuing to provide a space for promotions. I don't have a spec for what that would look like yet, but we could by the end of this heartbeat. Work for you @xmatthewx ?

**Comment by xmatthewx** [comment]
Sure thing. https://github.com/mozilla/webmaker-desktop/issues/68 

@hannahkane - is there a folder with prior Maker Party artwork you can share?

**Comment by chrislarry33** [comment]
@thisandagain awsm, much appreciative of that openness @amirad can you connect @xmatthewx with MP photos?

**Comment by ldecoursy** [comment]
Brand palette is here: https://teach.mozilla.org/events/resources/#logo-assets @sabrinang also has the original files.

**Comment by amirad** [comment]
Also, here's the layout and design for banners on the teach site #736

**Comment by sabrinang** [comment]
Maker Party 2014 assets are found here: https://www.dropbox.com/sh/atolz2eyfob8cj7/AAD6R1WGqNLQK7H6JsjkHjaOa?dl=0

**Comment by xmatthewx** [comment]
We have a design for Teach promotion for the new Webmaker site. 

We also have draft guidelines for utilizing the spot for other things in the future, including Maker Party. The goal: make it quicker to add new items in the future; maintain brand coherence; reduce the need to consult so many people. 

Take a look:
https://github.com/mozilla/webmaker-desktop/issues/68#issuecomment-108458057

**Comment by hannahkane** [comment]
Makes sense to me. It sounds like we can't just re-purpose the MP banner we're putting on the Teach homepage, because it doesn't meet the guidelines.

@sabrinang - does this give you everything you'd need to create a different banner for the Wm site, if we prioritize this into the next heartbeat?

**Comment by xmatthewx** [comment]
Guidelines with color palette will be documented in https://github.com/mozilla/webmaker-desktop/issues/79

**Comment by sabrinang** [comment]
Exploring iterations on the Maker Party promo and using Paradise Green or Viking Yellow from webmaker palette that is most similar to existing MP teal and yellow colours. I won't be using blue or teal as it is used in the hero gradient and doesn't provide enough contrast to the promo callout.

_NOTE: Copy for banner is TBD (placeholder on mockups)._

__Palette__
![webmaker-maker-party-promo-banner-04](https://cloud.githubusercontent.com/assets/2492510/8196410/9f4db3c4-1440-11e5-8d68-3f895921db75.png)

__Green (no logo)__
![webmaker-maker-party-promo-banner-03](https://cloud.githubusercontent.com/assets/2492510/8196413/a33d97ec-1440-11e5-8e88-b56e1e1f98da.png)
__Yellow (no logo)__
![webmaker-maker-party-promo-banner-01](https://cloud.githubusercontent.com/assets/2492510/8196412/a15b8b96-1440-11e5-8420-0115cd9baa23.png)
__Yellow (with logo)__
![webmaker-maker-party-promo-banner-02](https://cloud.githubusercontent.com/assets/2492510/8196418/b1d42b40-1440-11e5-8e36-f58abf28e119.png)
If we choose to include a logo, will it have a centered layout or have any size restrictions on it?

**Comment by hannahkane** [comment]
Thanks, @sabrinang.

Will let @cassiemc and @xmatthewx offer feedback on design. (I think it looks great! :))

Re: copy—my suggestion would be to remove "year-round," and instead add the dates, to create urgency. Also want to de-emphasize "attending," since we don't help facilitate that. So my suggestion is: "Maker Party is Mozilla's global campaign to teach the Web. Participate by hosting an event between July 15th and 31st. Teach, build and share amazing things online." / cc @KevZawacki @amirad

**Comment by xmatthewx** [comment]
I think these look great. Nice work @sabrinang. 
cc @vazquez re: the logo position and size

**Comment by cassiemc** [comment]
I also think they're great! Fresh palettes, nice and clean, great work @sabrinang! I especially like the yellow one for mirroring the background in the app screen. I would shorten the width of the paragraph of text. Maybe break after 'year-round party' or even shorter would be fine. After that, R+. 

One subtle enhancement might be to try a slight gradient on the yellow to mirror the gradient above, as I get the slight feeling of tension between the two styles.

**Comment by hannahkane** [comment]
Even shorter copy suggestion: "Maker Party is Mozilla's global campaign to teach the Web. Join us between July 15th and 31st." cc @KevZawacki @amirad

**Comment by amirad** [comment]
WFM

**Comment by KevZawacki** [comment]
Me, too. Quick nitpick:

"Maker Party is Mozilla's global campaign to teach the Web. Join us between July 15 and 31."

**Comment by vazquez** [comment]
Guideline is now updated @sabrinang :)

https://github.com/mozilla/webmaker-desktop/issues/79

**Comment by hannahkane** [comment]
@vazquez - if @sabrinang provides the final assets, is this something you could add to the webmaker homepage? I'm not sure who's able to do the actual implementation.

**Comment by vazquez** [comment]
@hannahkane I can definitely do this. My time for the rest of the week is tight. When do you need this by?

**Comment by xmatthewx** [comment]
@hannahkane if things go well today @gvn might be able to lend a hand tomorrow. Or, is this a task that can wait til next week?

**Comment by hannahkane** [comment]
I think @amirad wants it as soon as possible, but shouldn't get in the way of your other priorities. An alternative is to let @mmmavis or @toolness know whatever they'd need to know to do this?

**Comment by hannahkane** [comment]
I think it can probably wait until next week. I don't want to distract your team! just not sure the Teach team knows what they need to know to do it.

**Comment by vazquez** [comment]
The https://github.com/mozilla/webmaker-desktop repo is very straight-forward. It runs on React.js.

All modifications should be done to `splash.jsx` and `splash.less` https://github.com/mozilla/webmaker-desktop/tree/develop/src/pages/splash.

There currently aren't any styles of markup for partner promotion, this would be the very first :)

**Comment by vazquez** [comment]
@hannahkane - @toolness or @mmmavis and I can set up a call to walk-through, that would not be a problem :)

**Comment by xmatthewx** [comment]
@hannahkane - I filed an issue to build the component that will contain this stuff. It's probably safer to launch this next week, rather than tomorrow. Either way, I'm sure that @toolness or @mmmavis could set this up without much trouble. Ping me as needed and I will find the hands to help.

**Comment by sabrinang** [comment]
__Logo__
[maker-party_logo-white.png](https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eanFDb3JYVUkzakk/view?usp=sharing) (100 x 114px)
[maker-party_logo-white@2x.png] (https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eN3FiaVNJbjJlakU/view?usp=sharing) (200 × 227px)

__Background Pattern__
[maker-party_pattern-tile.png](https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eZFdRNjlMU0VuMTg/view?usp=sharing) (171 x 122px)
[maker-party_pattern-tile@2x.png](https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eQ0dUYS1pOXNUdjQ/view?usp=sharing) (342 x 243px)

All MP promo assets can be found in this gdrive folder: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efkJQcEJseDlNOUlMUGNhdWwzMVFkcWp1anh6NEVZX0hMT1hiWTk5TExVWnM&usp=sharing

**Comment by hannahkane** [comment]
Closing this since the design is complete. Thanks, all!

**Comment by sabrinang** [comment]
updated 30% opacity white patterns:
original: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eNHB3RHRreDhYUjQ/view?usp=sharing
retina: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ea0RnZmRYcUpFajQ/view?usp=sharing
