### ISSUE TITLE
[MIGRATED] Create form for collecting MP events

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#738]
As discussed with stakeholders, we'll be collecting MP data through a google form, rather than through a public-facing events tool. 

We need to determine what information we want to collect and create the form.

Here's an example to draw inspiration from: https://www.madewithcode.com/events#add

**Comment by hannahkane** [comment]
Who should this be assigned to? @amirad ? @ldecoursy ?

**Comment by ldecoursy** [comment]
I'll assign myself - here's a draft of fields I think we should include https://teach.etherpad.mozilla.org/eventform

@amirad @chrislarry33 @adamlofting anything here you think we don't need or that's missing?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/136"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/136.
Please don't comment on it here.
