### ISSUE TITLE
EVENTS: point to google form, rather than events.webmaker.org

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#739]
This is blocked on #738, but once the form exists, we should update /events to point to that form rather than to events.webmaker.org. (Currently linked from "our global list" in the "Join us for the global..." paragraph.)

We may want to make it a bit more prominent visually, so I'm tagging this with the design label.

**Comment by ldecoursy** [comment]
No longer planning to have an Events form, closing this ticket.
