### ISSUE TITLE
Design "remixing" functionality for Curriculum

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#74]
### RACI
* Phase: Design
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: ?
* Dev Lead: NA
* Quality: @davidascher 

We know from testing that users want remixed curriculum. e.g. Module 1: Remixed for Librarians, Module 1: Remixed for Mobile-Only.

There are three pieces to this:

1) Soliciting remixes and remix ideas. UX possibilities: allow users to submit remix suggestions as comments on the activity pages themselves; create a "remix" form; create a Thimble-style remix tool

2) Curation. UX possibilities: allow users to upvote the remix suggestions of others, depend on staff to curate

3) Display. How will featured remixes be displayed and how will they be discovered?

Related tickets to write: 
 * Build tickets for whatever is decided through the design process
 * Ticket for allowing users to indicate when they've used a piece of curriculum, and perhaps whether they'd recommend it

**Comment by LauraHilliger** [comment]
Another aspect we should think about is the submission flow. How does a community member or partner or staff member bring it to our / the community's attention that they have created a resource that they think should be displayed?

**Comment by hannahkane** [comment]
Closing this for now. Needs lots more thought and is a ways down the roadmap.
