### ISSUE TITLE
[MIGRATED] Collect Maker Party case studies for site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#743]
In order to help scaffold the Maker Party experience for potential hosts, we want to showcase a few typical Maker Party styles. Case studies might include photos, basic information (# of attendees, age range of attendees, budget, etc.), and stories/lessons from the hosts.

The case studies should reflect the different types/formats of common Maker Parties.

**Comment by hannahkane** [comment]
cc @amirad - What do you think about this? Does this already exist? Would you be up for collecting these case studies?

**Comment by hannahkane** [comment]
@amirad - are you okay with me putting this into the next heartbeat and assigning to you?

**Comment by amirad** [comment]
Sure. I have a lot of this info already in different places. I can collect and share.

**Comment by amirad** [comment]
Created a pad filled with past events: https://teach.etherpad.mozilla.org/MPcasestudies
It's broken down into my 2014 favs, other 2014 stories and some 2013 stories. I can maybe dig up more from each depending on which ones you like.

**Comment by amirad** [comment]
@hannahkane let me know if that's usable ^

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/137"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/137.
Please don't comment on it here.
