### ISSUE TITLE
Visual treatment to indicate required fields on forms

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#744]
As I was reviewing a [PR](https://github.com/mozilla/teach.webmaker.org/pull/688) related to the Add Your Club form validation I realized we currently don't have any visual indication for required fields.  

Re: @toolness's https://github.com/mozilla/teach.webmaker.org/issues/577#issuecomment-91236434 on the same matter.

I +1 on adding an asterisk next to required fields and a "* indicates required field" note somewhere near the bottom (just above the submit button?).  I personally dislike seeing "required" repeatedly as it feels a bit demanding and pushy to me.

cc @hannahkane @iamjessklein for suggestions

**Comment by hannahkane** [comment]
I'm good with an asterisk, though I defer to @iamjessklein

**Comment by sabrinang** [comment]
![teach-formux-ideas](https://cloud.githubusercontent.com/assets/2492510/7574414/02da9680-f7e2-11e4-9dd6-a63559e7f3f8.png)
option 1 - the required field asterisk direction as mentioned above
option 2 - grouping optional fields at the end with less emphasized (optional) label

I think either option works fine but option 2 may be the visually cleaner version that groups required fields at the top so it feels easier to get through which indicates the optional fields instead. We shouldn't have too many optional fields when possible anyway and I think optional 2 helps showing that.

Any thoughts? @mmmavis @hannahkane

**Comment by mmmavis** [comment]
Um I have some thoughts on this.  Grouping optional fields works fine for this particular form since `website` field doesn't have much relationship with other fields in the form --- it doesn't matter much that we play around with the ordering and put that field at the bottom.  Not sure what other forms we will have in the future but I'm worried this kind of grouping might not work well on all cases.

Also, the mockup above demonstrated how we show up error messages on **non-HTML5 compatible browsers**(e.g., mobile).  

For **HTML5 compatible browsers** we simple rely on HTML5's form validation (see screencap below)
![screen shot 2015-05-13 at 9 59 54 pm](https://cloud.githubusercontent.com/assets/2896608/7626354/a88448a2-f9bc-11e4-9cbe-fc01b740b0ef.png).  
That is, users will have to hit the "submit" button to trigger form validation.  In that sense it is still unclear what fields are required when users see the form.

For this particular ticket I would vote for adding a red \*.  If we want to tweak how we are displaying error messages on **non-HTML5 compatible browsers** we should open another ticket.  (or wait till we get to https://github.com/mozilla/teach.webmaker.org/issues/670)

cc @toolness

**Comment by toolness** [comment]
Thanks for the design sabrina, and thanks for the technical clarifications mavis. I agree with your option 2--basically just adding ` (optional)` next to the website field label would be both helpful for users and extremely easy to implement. :)

**Comment by hannahkane** [comment]
Let's do option 2, and prioritize #670 for the next heartbeat. Sound ok?
