### ISSUE TITLE
Remove "Start a Mozilla Club" button from homepage header

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#746]
The homepage doesn't need a button right now

**Comment by toolness** [comment]
Hey @iamjessklein wanna do this one?

**Comment by iamjessklein** [comment]
sure!

**Comment by hannahkane** [comment]
I still see the button. Was this merged?

**Comment by iamjessklein** [comment]
I do not see the button. Maybe, refresh, delete cookies? :cookie:

**Comment by toolness** [comment]
Yup, it's removed on both staging and production for me...

**Comment by hannahkane** [comment]
Ok, yup, me too. Sorry. :)
