### ISSUE TITLE
Rename /mozilla-web-clubs/ to /clubs/

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#750]
We discussed this in another issue and decided it was a good idea, particularly since we'd like it to be a permalink yet the names of clubs in flux (it was "mozilla web clubs", then just "mozilla clubs", etc).

Most importantly, though, in #716 we include a link to this page in the email we send out to users when they've added a club. **The email uses the /clubs/ URL** so we really need the page to exist there. (And if we decide on a different URL, we need to update the email text to refer to that URL instead.)

**Comment by thornet** [comment]
Awesome! Was just about to file this ticket as well. ^^

**Comment by hannahkane** [comment]
We'll need to change the link in the id.webmaker email, since that uses /mozilla-web-clubs/

cc @secretrobotron

**Comment by ScottDowne** [comment]
@hannahkane Should we file something somewhere to change the link in the email?

**Comment by hannahkane** [comment]
I'll file it on id.webmaker
