### ISSUE TITLE
[TLM] Produce "Finding Your Crew" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#751]
Doc for this module: https://docs.google.com/document/d/1qnFQSNoztEjP2UdSTrlY4GZan67wIHpnpYZxVqyNy6Q/edit#heading=h.l98pr8wyxqfo

The Clubs toolkit also has relevant content: https://teach.mofostaging.net/clubs/toolkit/

**Comment by LauraHilliger** [comment]
need URL to #731 to complete, but this is ready for someone else's input.

https://docs.google.com/document/d/1qnFQSNoztEjP2UdSTrlY4GZan67wIHpnpYZxVqyNy6Q/edit#heading=h.nxjaa578n0li

**Comment by LauraHilliger** [comment]
remixed based on RC guide, meta structure complete. Closing and will file specific templating issues.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/139"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/139.
Please don't comment on it here.
