### ISSUE TITLE
[TLM] Produce "Reflecting Openly" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#752]
Doc for this module: https://docs.google.com/document/d/1ZYAsSM858SK_Pljo-jpwEzL4uuOE-jTcMfHmwuex_Ag/edit#

other (shortened list of) relevant content: 
https://wiki.mozilla.org/Working_open
https://training.webmakerprototypes.org/en/onlinepresence/concepts/
http://hivechicago.org/working-open-hive-chicago-style/
http://schoolofopen.org
http://literaci.es/working-openly-a-manifesto

**Comment by LauraHilliger** [comment]
ready for input: https://docs.google.com/document/d/1ZYAsSM858SK_Pljo-jpwEzL4uuOE-jTcMfHmwuex_Ag/edit#

@amirad @thornet @chrislarry33 @ldecoursy @soapdog

**Comment by jgmac1106** [comment]
Great job. Really like where this is going. One bit of feedback, IMO too
many objectives. Technically an objective should be the focus on the module
and something an outsider can quickly measure.

Having that many can make it difficult for a learner to know if they hit
his or her target.

**Comment by LauraHilliger** [comment]
Oh, good point @jgmac1106. One thing to note, the objectives are more for us to narrow down content. I don't think we should surface them...

**Comment by jgmac1106** [comment]
Okay. Hoping I get some capacity to help next week. Stuff so far is great.

**Comment by chrislarry33** [comment]
Is the goal for this to be a series of lessons/activities in a series?

**Comment by LauraHilliger** [comment]
have combined with open tools, closing #753

**Comment by LauraHilliger** [comment]
meta finished, remixed based on RC guide in #755. Will file template specific issues, once RC and CC guides are shipped.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/140"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/140.
Please don't comment on it here.
