### ISSUE TITLE
[TLM] Produce "Open Tools" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#753]
Doc for this module: https://docs.google.com/document/d/1dlTbEQM2u8yvhJhUyZGbdWbdUul2sAdTEBqUkqqJYQs/edit#

Other relevant content: EVERYTHING WE DO – need to seriously question and parse our methods, tools and processes. We have more documentation that we can use, so I suggest going at this from the practical standpoint the doc outlines.

**Comment by LauraHilliger** [comment]
This is ready for input too: https://docs.google.com/document/d/1dlTbEQM2u8yvhJhUyZGbdWbdUul2sAdTEBqUkqqJYQs/edit#

Needs ACTIONS section. We wanted to cover: 
* Protocols & patterns for coordinating clubs
* How to connect with RCs and regions (video bridge / cross-region comms & connection)

these should be templated in some way, I guess. I've filed #802...

**Comment by LauraHilliger** [comment]
closed via #752

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/141"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/141.
Please don't comment on it here.
