### ISSUE TITLE
[TLM] Produce "Sharing and Storytelling" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#754]
Doc is here, this one is pretty naked and messy, but we should pull in some master storytellers from the team ;) https://docs.google.com/document/d/1mjlLHE1U7DMZs1YNkGGeHkfMm7khcyGZkndr5K7GGBA/edit#

Other relevant content:
https://mozteach.makes.org/thimble/a-brief-history-of-storytelling
https://mozteach.makes.org/thimble/online-storytelling-teaching-kit
(video) http://www.mozillapopcorn.org/storycamp/cinema5.html
https://juliahivenyc.makes.org/thimble/hive-nyc-cohort-guide
http://education.mozilla-community.org/modules/reps_mentor_training/communication/

**Comment by thornet** [comment]
Resources via Rosana & Participation team: 

http://impactinvesting.marsdd.com/social-impact-measurement/how-social-impact-measurement-tools-and-methods-fit-into-your-logic-model/

http://my2.ewb.ca/site_media/static/library/files/399/actions-to-impact-workshop.pdf

**Comment by chrislarry33** [comment]
where/what is the organized master list of this material.

**Comment by LauraHilliger** [comment]
@chrislarry33 the master outline (organizing structure, courses, modules, learning objectives) is here:
https://docs.google.com/document/d/1quD8jfETB3_vuRc6IqWlbKAcn9bMcLGQOnpBiuH66Mw/edit

I also updated the curriculum wiki: https://wiki.mozilla.org/Webmaker/2015/Mentors/Clubs/Curriculum

**Comment by LauraHilliger** [comment]
meta is finished, open for commenting https://docs.google.com/document/d/1mjlLHE1U7DMZs1YNkGGeHkfMm7khcyGZkndr5K7GGBA/edit#

closing this issue will file for refinement in a later heartbeat

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/142"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/142.
Please don't comment on it here.
