### ISSUE TITLE
[MIGRATED] Produce 3 -5 Case Studies on Clubs

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#756]
We need a snazzy reportage on clubs that currently exist in our network. Rio LAN houses, Chicago public schools, individual contributor clubs – profiling pre-existing clubs will help new RCs and CCs imagine clubs for themselves. Suggest Research Report / Final Report like look and feel.

Resource will be used in "Your First Month" modules #755

**Comment by thornet** [comment]
Let's list the elements we think these case studies should have: 

* Target participants
* Relationship of club captain to participants
* Learning goals of club
* Location
* Setting (i.e. library, school, makerspace)
* Meeting frequency
* Favorite activities

**Comment by LauraHilliger** [comment]
I would add:

History
Motivation

This case study should profile both RCs and CCs (we'll need to be able to separate those pieces for #755 and #758 )

**Comment by jgmac1106** [comment]
I will work on a model example for the formal higher ed school setting
later today. Maybe we can get @chadsansing to do one for K12 setting.

**Comment by hannahkane** [comment]
I'd add that it would be great to collect photos for each of the case studies! Also, I'd love to include a super pared down version on the Clubs section of the site.

**Comment by jgmac1106** [comment]
Here is my quick example:
http://jgregorymcverry.com/how-i-forked-mozilla-web-clubs-for-a-formal-educational-setting/

Wish I had pictures but I didn't do media releases.

**Comment by LauraHilliger** [comment]
@jgmac1106 this is excellent. Full on excellent. I think we should stick with the personal voice (e.g. have the case studies produced by club leaders/coordinators, and then edit as opposed to "official" reporting style). Greg, would you be ok with us using your language and remixing into something (read on)?

I think these stories would work well as 1 page infosheets. Something like this:
![club-report-idea](https://cloud.githubusercontent.com/assets/539017/7318209/985d1126-ea89-11e4-8477-c30ad7bebbd2.png)

but with the club map, look and feel of teach [dot]... 

What do you all think?

**Comment by jgmac1106** [comment]
Everything I do is licensed for remix. Feel free to do anything. I am going
to go in and fix some grammar. It was late and I too often publish then
proofread.

**Comment by thornet** [comment]
@jgmac1106 <3! Great post, and your learner portfolios are brilliant. Such an inspiration. Would you be up for sharing your case study in the next club call on May 5?

**Comment by jgmac1106** [comment]
If I am available for the call.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/144"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/144.
Please don't comment on it here.
