### ISSUE TITLE
[MIGRATED] [TLM] Produce "Remixing for Context" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#757]
(empty) doc for this module: https://docs.google.com/document/d/1q5p1ID6CyMomfs_S5uf7Jki_agWWQQMUs8HfN97zBv0/edit

Other relevant content:
http://mozillascience.github.io/instructorTraining/designAndAdaptation/index.html
https://github.com/mozilla/school-of-webmaking/issues/240
https://github.com/mozilla/webmaker-curriculum/wiki/How-to-remix-Webmaker-Club-activities
http://www.zythepsary.com/techie/prove-that-people-want-to-remix-curriculum/
https://wiki.mozilla.org/Hackasaurus/FAQ

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/145"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/145.
Please don't comment on it here.
