### ISSUE TITLE
Design badges landing page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#76]
Landing page that showcases the Mozilla Learning badge offerings and clearly differentiates the several types of badges we offer. The landing page should also illustrate the progressive nature of our badge offerings.

Blocked by #86

**Comment by dajbelshaw** [comment]
Just flagging that we're currently using: http://blog.webmaker.org/badges

**Comment by chrislarry33** [comment]
Thanks Doug, collecting the disparate assets is very helpful.

**Comment by ldecoursy** [comment]
Also in case it's helpful, here are badge counts from 2014 https://docs.google.com/spreadsheets/d/1ENxvCwrAFyLsaI6R83EpkdKXql1E2Bg9n1fos9BQV4M/edit#gid=0

**Comment by hannahkane** [comment]
Closing for now. Will create new tickets when badge project launches.
