### ISSUE TITLE
[MIGRATED] [TLM] Produce "Making is Learning" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#760]
Doc for this module: https://docs.google.com/document/d/1TgnkR64WfRPn0ICJyZ7L4DP236vqeCYj_8rh6d3gpdE/edit#heading=h.j9411nx9ut08

Needs images and example “make”, reword “makes” as “activity or projects, make them tool agnostic, Connected Learning section needs review from Hivers, review “makes”, add examples and resources

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/147"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/147.
Please don't comment on it here.
