### ISSUE TITLE
[MIGRATED] [TLM] Produce "Modeling Making" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#761]
Doc for this module: https://docs.google.com/document/d/1rqLQweX4HHFZFIW0H_jQBjjbnBYHt9pfYEtXXqDzb3w/edit

This is different from #760 in that #760 is theoretical and this module should be practical. This focuses in on how to develop content for your specific group of learners. 

**Possible redundancy with #757**

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/148"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/148.
Please don't comment on it here.
