### ISSUE TITLE
[MIGRATED] [TLM] Produce "Facilitating" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#763]
Doc: https://docs.google.com/document/d/1IjdRKaQ7ctHGAPzx2BzxQXlpg8YCYNRUB2XwQ0DkzfQ/edit#

Other relevant content:
http://mozillascience.github.io/instructorTraining/compellingInstruction/index.html (includes metacog)
https://training.webmakerprototypes.org/en/host-a-training/ training agendas may need remix

**Comment by ldecoursy** [comment]
This may also be helpful, from Digital Corps: https://www.scribd.com/fullscreen/241612718?access_key=key-Bg478gqESrAGRd9vGINd&allow_share=false&escape=false&show_recommendations=false&view_mode=scroll  

And this: https://theanimal.makes.org/thimble/MTYzMzIyMjkxMg==/facilitating-digital-corps-workshops

Both found here: http://rldc.weebly.com/teaching-kits.html

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/149"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/149.
Please don't comment on it here.
