### ISSUE TITLE
[MIGRATED] [TLM] Produce "Encouraging Diversity" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#764]
doc for this module: https://docs.google.com/document/d/1ltx2AJV8uwoFY6ihukz-4zC7LuUmQAo2eVRsyML66HA/edit

content to inspire/remix:
http://www.omnignorant.com/2014/09/cultivating-diversity-networked-digital-age/
http://ascendproject.org/

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/150"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/150.
Please don't comment on it here.
