### ISSUE TITLE
[MIGRATED] [TLM] Produce "Finding Cohesion & Collaboration" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#765]
doc for this module: https://docs.google.com/document/d/1BBQWj-cYrbkzbnKE_80NwtUz9jZO6Iivl84d4-9b3as/edit#

other relevant content:
https://wiki.mozilla.org/Webmaker/HiveCookbook
http://hivechicago.org/working-open-hive-chicago-style/
 http://hivechicago.org/moonshots/moonshot-working-groups/
https://juliahivenyc.makes.org/thimble/hive-nyc-cohort-guide

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/151"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/151.
Please don't comment on it here.
