### ISSUE TITLE
[MIGRATED] [TLM] Produce "Web Literacy" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#766]
doc for this module: https://docs.google.com/document/d/1GT1iJ5HVS2c7yov4YldvcBXj1oKIY6c247xmeCYPimU/edit#

needs tightening, edits on teaching kit references, new projects, fleshed out thinking, reduce web literacy map references

Other relevant content:
http://mozillascience.github.io/instructorTraining/designAndAdaptation/index.html
http://akenygren.tumblr.com/mymakerboxes

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/152"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/152.
Please don't comment on it here.
