### ISSUE TITLE
[MIGRATED] [TLM] Produce "Design Thinking" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#767]
doc for this module: https://docs.google.com/document/d/1IhNSm6faR_2jVFcgBlZZLp3VnhbYaOb6D51mcHDQW0c/edit#

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/153"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/153.
Please don't comment on it here.
