### ISSUE TITLE
[MIGRATED] [TLM] Produce "Finding Funding and Support" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#768]
(empty) doc for this module: https://docs.google.com/document/d/1pNlGBncjcubxvpJonSjytA8Vt9SekylaoL6md-BXY-0/edit

Need learning objectives.

Relevant content:
(project briefs, local partnerships, grant writing – need to make determinations of how much of this is DIY doable)
https://wiki.mozilla.org/Webmaker/HiveCookbook
Geoffrey’s blog / fundraising team might have some basic tips and tricks

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/154"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/154.
Please don't comment on it here.
