### ISSUE TITLE
[MIGRATED] [TLM] Produce "Playtesting and Iteration" module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#769]
doc for this module: https://docs.google.com/document/d/18SlaxsmMKyDZePyzNMKBWPh8ZM6s-8bgbrOONH619rA/edit#

needs tightening, rearranging and new projects

Relevant content: 
http://mozillascience.github.io/instructorTraining/feedback/index.html (loads of good content to build out this module.)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/155"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/155.
Please don't comment on it here.
