### ISSUE TITLE
We have a travis failure merged into develop

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/teach.webmaker.org#771]
Not sure what it is yet, but Travis is complaining and running npm test on develop shows errors.

Something with less.

**Comment by mmmavis** [comment]
It's probably something to do with `gulp-less`.  See https://github.com/mozilla/teach.webmaker.org/pull/770#issuecomment-94865623.

**Comment by ScottDowne** [comment]
I have a pull request incoming with the fix.

**Comment by toolness** [comment]
Oops sorry, I didn't see this issue and I just pushed a fix in af25115156a69c1d62bc203ef1b29a411712a305...
