### ISSUE TITLE
Create a BSD malinglist signup form for Teach site to use

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#776]
In https://github.com/mozilla/teach.webmaker.org/issues/481 we initially decided to use [the same BSD form](https://sendto.mozilla.org/page/s/maker-party-signup) that was used on the [Maker Party site last year](https://party.webmaker.org/#form-get-updates).  

Due to various technical difficulties (see [discussion here](https://github.com/mozilla/teach.webmaker.org/pull/654)) we decided to have a workaround instead - create/duplicate a new form, make sure users are added to the right Constituent Group "Maker Party 2014", make thank you page direct back to the Teach site.

cc @amirad to make sure the Constituent Group "Maker Party 2014" is the right one to for users to go to.

**Comment by mmmavis** [comment]
Just duplicated the form on BSD: https://sendto.mozilla.org/page/s/maker-party-signup-for-teach-site
Configs can be found on **BSD -> Signup Forms -> Maker Party Signup (for Teach site)**

**Comment by hannahkane** [comment]
@mmmavis - what do you need to finish this ticket? Confirmation from @amirad that "Maker Party 2014" is the right constituent group?

**Comment by mmmavis** [comment]
Yes, that is correct.  :rabbit:

**Comment by amirad** [comment]
Ops sorry guys. Don't think we need a new group. Can we add them to the "Maker Party singup list" which is the list from 2014 but renamed. 

https://sendto.mozilla.org/page/s/maker-party-signup

**Comment by mmmavis** [comment]
Hey @amirad , we have to create a new form to overcome some BSD problems.  However, we can make sure users signed up using the new form get assigned to the same constituent group that we used for the old Maker Party form.  That's why I would like to confirm if "Maker Party 2014" is the constituent group to use.

**Comment by amirad** [comment]
I never used the MP constituent group, I only ever sent/used the sign-up list I mentioned. So we can either update that constituent group you mentioned (which only has 300 ppl in it right now) or make a new one.

**Comment by mmmavis** [comment]
Hey @amirad , do you mind telling me how you "used" the sign-up list so I can go into BSD and take a closer look?  I actually don't know how people like you or Michelle make use of the list of people who have signed up for a particular mailinglist.  :grimacing: Thanks!

**Comment by amirad** [comment]
Mainly just sending emails to that signup group or sending other large emails to multiple signup groups. I don't usually group into constituencies

**Comment by mmmavis** [comment]
Hey @amirad , I'm sorry but could you be more specific about how you sent emails to that **singup group**?  Like where on BSD did you go to send emails.

**Comment by mmmavis** [comment]
@amirad 
> I never used the MP constituent group, I only ever sent/used the sign-up list I mentioned. So we can either update that constituent group you mentioned (which only has 300 ppl in it right now) or make a new one. 

So I followed your steps... and
![screen shot 2015-04-30 at 10 59 24 pm](https://cloud.githubusercontent.com/assets/2896608/7427285/bfa59a66-ef8c-11e4-9208-3c24fee51f01.png)
:open_mouth: how come I got ~4000 people (instead of 300) back :open_mouth: 

Anyways, I think we will have to use a new form - users will still be added to the same `Make Party 2014` constituent group (not sure if you would like to rename it).

**Comment by mmmavis** [comment]
Hi @amirad ,

I'm not sure if the [original Maker Party signup form](https://sendto.mozilla.org/page/s/maker-party-signup) is being used anywhere *other* than on party.webmaker.org footer so I'm hesitant to make that form redirected back to the Teach site after signing up.

So I created another form... the next time when you search for people by signup form, please make sure that your include **Maker Party signup (for Teach site)** as well (see screencap below)
 
![screen shot 2015-05-05 at 11 14 20 am](https://cloud.githubusercontent.com/assets/2896608/7479654/ef01b1a8-f317-11e4-9bb6-5eb81d98824d.png)

If you think we can just go ahead and make changes to the original form, let me know!  :hamster:

**Comment by amirad** [comment]
Okay thanks @mmmavis
