### ISSUE TITLE
Design: Confirmation message for signing up for mailinglist

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#777]
As seen in https://github.com/mozilla/teach.webmaker.org/issues/481#issuecomment-93380431

@iamjessklein if you don't mind, I'm gonna assign this task to you.  Thanks! :hamster:

**Comment by sabrinang** [comment]
![email-confirmation-idea](https://cloud.githubusercontent.com/assets/2492510/7398480/2ae3f112-ee64-11e4-96e7-b5468e43c2d0.png)

I made a quick mockup and I have some questions:
Are we able to stay on the same page and switch that section out for text? I don't think its necessary to redirect to another page unless we need to include some CTA we can probably do it here as well.

@hannahkane  What copy should we include for the confirmation message?

**Comment by hannahkane** [comment]
I think we can just say "Thank you for signing up!". I don't know how BSD works - will they need to confirm their subscription?

**Comment by mmmavis** [comment]
@toolness 

Due to BSD and other limitations we decided to go with [option 2](https://github.com/mozilla/teach.webmaker.org/pull/654#issuecomment-94160823) to handle the form submission.

Just wanna check with you that my proposed approach would work :eyes: 

- use `<form>` submit to submit the form
- have BSD's thank you page redirected to the Teach site, I guess same page but with a query string? (e.g., `https://teach.mozilla.org/events/?mailinglist=yes` or something)
- check if that `query param` is presented, if yes, show the corresponding "Thank you for signing up!" message

**Comment by toolness** [comment]
Yep, that should work. Where is the configuration for the redirect stored? Does the form submitted to BSD contain a redirect URL as a hidden input, or is it configured in BSD somewhere?

Just curious b/c we might end up w/ a situation where e.g. user is on staging and signs up for the mailing list which redirects them to produciton--not that big a deal but might be a bit confusing/hard to notice.

**Comment by mmmavis** [comment]
Let's continue the tech related convo to https://github.com/mozilla/teach.webmaker.org/issues/481 instead so @sabrinang can close thisticketttttttt :dancer:

**Comment by sabrinang** [comment]
:+1:
