### ISSUE TITLE
Redirect teach.webmaker.org to teach.mozilla.org

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#778]
So sometimes when I try going to this github repository, I fail at using my address bar and my browser tries going to teach.webmaker.org, which doesn't exist.

It makes me realize that some people might actually try *going* to teach.webmaker.org. Would it be hard to have that redirect to teach.mozilla.org, just so it goes *somewhere* and doesn't leave folks scratching their head?

/cc @jbuck

**Comment by jbuck** [comment]
Should we just rename the repository to teach.mozilla.org ?

**Comment by toolness** [comment]
OMG NO NOT ANOTHER RENAME

**Comment by toolness** [comment]
@LauraHilliger mentioned on #961:

> just got sent a journal article that points readers to teach.webmaker.org, which doesn't exist. Would be good to redirect.

So apparently even folks who know nothing about this repository now think it's teach.webmaker.org! Can we bust a redirect and NEVER EVER RENAME THIS REPOSITORY EVER AGAIN PLEASE.
