### ISSUE TITLE
Design Badge Manager page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#78]
### RACI
* Phase: Design
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: ?
* Dev Lead: NA
* Quality: @davidascher 

### Scope
From the Badge Manager page, people will be able to:
1. **see the badges they've earned.** Including the evidence that was provided
2.  **see their pending applications.** And respond to any questions from reviewers

**Comment by dajbelshaw** [comment]
Would be really good to have a visual workflow for this, so that both applicants and reviewers can see what stage the application is at (and what they can attempt next!)

**Comment by chrislarry33** [comment]
I agree on that asset, but may be premature until the tool matures.

**Comment by hannahkane** [comment]
Will spec this out much more thoroughly closer to the milestone.

**Comment by thornet** [comment]
* see total # of badges issues
* include city data

**Comment by OpenMatt** [comment]
@thornet: 
* the audience for this page is badge **earners**, so do we really need / want to display city data here? 
* can you say more about total # of badges issued and the goal for that, from an earner's point of view?

**Comment by chrislarry33** [comment]
I think that info is what we need to collect on the back-end, not that needs to be displayed.

**Comment by hannahkane** [comment]
Yup, this ticket is about a badge manager for earners. Backend data is covered in #79.

**Comment by OpenMatt** [comment]
@k88hudson says this one is likely to be the most difficult

**Comment by k88hudson** [comment]
@hannahkane hey, is there a wiki or other documents somewhere with badges requirements beyond these tickets? sorry, I've probably asked this before

**Comment by hannahkane** [comment]
@k88hudson - there are three different badge-related milestones spec'ed out a bit here: https://wiki.mozilla.org/Learning/Networks/Product-Roadmap (I suggest just doing a search for the word "badge")

**Comment by hannahkane** [comment]
Closing this, in light of decision to use a third-party solution.
