### ISSUE TITLE
[MIGRATED] Contact Q2 Privacy curriculum testers

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#783]
- [ ] Make list of orgs and people to invite to testing 
- [ ] Invite to fortnightly calls 

Ideas: 

* EFF
* Advocacy (Melissa)
* Privacy (Stacy)
* Leah
* many more

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/156"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/156.
Please don't comment on it here.
