### ISSUE TITLE
Clubs toolkit page is no longer keyboard-accessible

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#784]
Hmm, so @ScottDowne's [original solution](https://github.com/mozilla/teach.webmaker.org/commit/f0981c96352f2da5031bd865f38f70d50a17b8b7#commitcomment-10569879) to make the Clubs toolkit sections collapsible without JS was actually dependent on the toolkit sections not having any focusable elements inside them. Unfortunately, links were added in #683, which breaks this.

You can see the problem if you use solely the tab key to navigate through the links on the page. When one of the collapsible section headers is focused, that section is expanded, but as soon as you tab to one of the hyperlinks *inside* that expanded section, the section is collapsed, preventing you from actually navigating to the link. :(

**Comment by toolness** [comment]
I should note that the Web Literacy page is, I think, implemented using the same mechanism--but it's still working fine for keyboards because AFAIK there are no hyperlinks or other focusable elements inside the collapsible sections. If that ever changes, however, it'll have the same problem as the Clubs Toolkit page.

**Comment by ScottDowne** [comment]
Interesting. I thought because all the contents including the links were in a button that is focused, it would work.

Example, you can select text and it stays open.

I think we can fix this with some css.

**Comment by ScottDowne** [comment]
Hm, maybe cannot do this in css.

**Comment by toolness** [comment]
Yeah, I think until CSS supports that funky thing where you can style an ancestor based on its descendants, this may be impossible to do with CSS >.<

**Comment by ScottDowne** [comment]
We can make this a js thing and just open them all if js disabled. It was an interesting experiment but I think it's more of a hack now than useful.

It would still be tabbable with js, and if you tab to a child anchor, it would use js to set a class on the parent to keep it open.

**Comment by toolness** [comment]
Rad!

We could potentially use `react-bootstrap`, although I don't know how awesome its collapsible/accordion component is when JS is disabled.

**Comment by toolness** [comment]
This was fixed by #788!
