### ISSUE TITLE
Every page on teach.webmaker.org (production site) has identical HTML

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#785]
I noticed that when disabling JS in my browser, every page on teach.webmaker.org (the production site, that is) looks identical. The pages look fine with JS enabled, presumably because react-router is instantly changing the page content to match the current URL.

Further investigation using `curl` yielded the following for staging:

```
$ curl -I https://teach.mofostaging.net/teach-like-mozilla/
```

```http
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 3096
Connection: keep-alive
Date: Wed, 22 Apr 2015 14:48:27 GMT
Content-Encoding: gzip
Cache-Control: max-age=600, public
Last-Modified: Wed, 22 Apr 2015 13:19:51 GMT
ETag: "e505d959a52694338d53e8212ec8fc9e"
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 cf036bc8e3cce4c84534e4d8da35e7b3.cloudfront.net (CloudFront)
X-Amz-Cf-Id: FrhQvxWQt7bycdiDtQ6qmCbyrj7DYdLu6FctKY-DTKHGw2sJsCyO5w==
```

While querying the identical path on production gave me this:

```
$ curl -I https://teach.mozilla.org/teach-like-mozilla/
```

```http
HTTP/1.1 404 Not Found
Content-Length: 0
Connection: keep-alive
x-amz-error-code: NoSuchKey
x-amz-error-message: The specified key does not exist.
x-amz-error-detail-Key: teach-like-mozilla/error.html
Date: Wed, 22 Apr 2015 14:46:47 GMT
Server: AmazonS3
Age: 78
X-Cache: Error from cloudfront
Via: 1.1 c3cc01d8b1148d0e48721b827b368bc0.cloudfront.net (CloudFront)
X-Amz-Cf-Id: -ebZDS8wfCTGSbmDNNP8BUqlqZHDk9dyk9IDb9MRyaigSABdXM_NHA==
```

That's particularly weird that it's actually a 404 with no content, yet my browser is not showing me a 404, regardless of whether JS is on or off.

@jbuck, any idea what might be going on here? The Travis configurations are so similar that I doubt it could be the deployment process, but I could be wrong...

**Comment by simonwex** [comment]
Looks to me like a misconfiguration of cloudfront.

**Comment by jbuck** [comment]
gg typing me 

![oops](https://photos-2.dropbox.com/t/2/AAAYf4UcO5m_JoY4KfTeJJzpBIFi3-kEUgaanTcXUzczew/12/4403845/png/1024x768/3/1429725600/0/2/Screenshot%202015-04-22%2012.40.36.png/CIXljAIgASACIAMoASgC/meCKjH0TASS9w77ON6aAH_sl1t-lQrRvHRfSRN18ExM)

All fixed up now:

```
$ curl -I https://teach.mozilla.org/teach-like-mozilla/
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 3053
Connection: keep-alive
Date: Wed, 22 Apr 2015 16:42:18 GMT
Content-Encoding: gzip
Cache-Control: max-age=600, public
Last-Modified: Wed, 22 Apr 2015 13:32:23 GMT
ETag: "de07af2dc129d410f6726bf11bd9f0e2"
Server: AmazonS3
Age: 25
X-Cache: Hit from cloudfront
Via: 1.1 5b675dde158fcaea3779baed452866a1.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 2v6pqCZ0ia4l1pDmbNE4eyFSJMDpCkfzY0MVyl7rHhYxSQ_9bL_wNw==

```

**Comment by toolness** [comment]
LOL

Awesome, thanks for fixing it so fast!
