### ISSUE TITLE
Add background color to header images

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/teach.webmaker.org#786]
Page load is quick. Images behind the header text take a moment longer. I'd recommend adding a light gray background-color so that the white text still reads. 

:boom: Congrats on the site launch!! :boom: 

![screenshot 2015-04-22 11 28 56](https://cloud.githubusercontent.com/assets/53411/7278335/cfce684c-e8e2-11e4-8e83-0688815cc859.png)

![screenshot 2015-04-22 11 24 36](https://cloud.githubusercontent.com/assets/53411/7278281/6b54ac50-e8e2-11e4-8f97-39359f8b7c35.png)

**Comment by toolness** [comment]
Ah good idea, thanks @xmatthewx !

**Comment by mmmavis** [comment]
Thanks @xmatthewx !  I used the existing grey (#4D4E53) 'cuz I didn't want to introduce another colour.  Hopefully that turns out fine otherwise I can tweak the colour.
