### ISSUE TITLE
I can't download the guides?

### ISSUE THREAD

**Issue by adamlofting** [mozilla/teach.webmaker.org#787]
Am I missing some UX here, or are we missing links to download the guides on this page? 

https://teach.mozilla.org/events/resources/#event-guides

![screenshot 2015-04-22 17 51 22](https://cloud.githubusercontent.com/assets/1901816/7280052/3e86f1fc-e918-11e4-94c9-73deab66ae50.png)

**Comment by hannahkane** [comment]
Whoops. Good catch.

Links are here:

Small: https://michelle.makes.org/thimble/LTE2NjE1MzQyMDg=/how-to-host-a-maker-party-small
Medium: https://michelle.makes.org/thimble/LTE1Nzc2NDgxMjg=/how-to-host-a-maker-party-medium
Large: https://michelle.makes.org/thimble/LTEzMDkyMTI2NzI=/how-to-host-a-maker-party-large:

**Comment by mmmavis** [comment]
@hannahkane which elements should be hyperlinked?  Is it the title (eg. SMALL EVENT)?

**Comment by hannahkane** [comment]
Yes, let's link the titles. Thanks!
