### ISSUE TITLE
Design improved badge issuing experience

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#79]
### RACI
* Phase: Design
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: ?
* Dev Lead: NA
* Quality: @davidascher 

### Scope:
1. **Show counts of outstanding badge applications.** And allow admins to view and sort those applications by submission date and badge type.
2. **Enable search for issued badges**. Allow admins to search issued badges by date, badge type, location of applicant, or reviewer. Make these search results exportable. (This would enable us to contact everyone who has received a certain badge, for example)
3. **Improve the design of the application reviewer pane.** By adding (in addition to the applicant-provided evidence):
 * a) badge criteria 
 * b) information about the applicant, including other badges they have received or applied for
4. **Display badge applicant location data.** e.g., Where the applicant lives. To help us track against our city KPIs. [NOTE: This requires collecting location data as part of the badge application process.] [OTHER NOTE: I think this might be better addressed by adding badge data to the Learning Networks dashboard.]

**Comment by ldecoursy** [comment]
Additional note: explore what kind of location data is available (or is ok to ask for) to help us track against city goals

**Comment by OpenMatt** [comment]
cc @simonwex 
@hannahkane: I took a pass at further refining the requirements here. look good?

**Comment by hannahkane** [comment]
Thanks, @OpenMatt. Looks good. Also added location data to the searchable fields in the second item on the list.

**Comment by hannahkane** [comment]
Closing this, in light of decision to use a third-party solution.
