### ISSUE TITLE
Ensure propTypes is always used?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#791]
Wondering if we should *always* include `propTypes` when building React components so that React can handle some [prop validation](https://facebook.github.io/react/docs/reusable-components.html#prop-validation) for us.

**Comment by toolness** [comment]
Yeah, I think it's definitely a good idea! It also helps us self-document our code better. :+1:

**Comment by toolness** [comment]
Are there particular components you think should have validation that don't currently? Maybe we should file bugs for each one, or you could just issue a PR that adds it to a bunch of them.

**Comment by mmmavis** [comment]
Ummm there are a few, I guess I'll open a meta ticket to track all the components that need to have `propTypes` added.

**Comment by toolness** [comment]
Cool, sounds good. Thanks Mavis!

**Comment by mmmavis** [comment]
please refer to https://github.com/mozilla/teach.webmaker.org/issues/792.  closing this ticket now.
