### ISSUE TITLE
Update CC licensing on individual Clubs curriculum activities

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#797]
@thornet @LauraHilliger 

Hi - noticed that while we have the CC BY-SA licenses on the main Clubs curriculum and Teaching Activities pages, the six individual activities within the Clubs curriculum still have a range of licenses.

**Comment by LauraHilliger** [comment]
the three activities that have a different license were originally more liberally licensed with CC-BY. We don't HAVE to keep them that way, but IMHO it seems a little off to replace them with a more restrictive license.

**Comment by thornet** [comment]
While I agree with having things more liberally licensed in general, we got clearance for CC BY-SA from the module 1 contributors. 

@LauraHilliger would you mind updating the licenses on the module landing page and the individual activities? You can use the CC license chooser to get good metadata: http://creativecommons.org/choose/

@ldecoursy can share the attribution preferences of each of the content partners.

**Comment by LauraHilliger** [comment]
Yes, please do @ldecoursy the last word was not clear: https://github.com/mozilla/teach.webmaker.org/issues/578#issuecomment-92500078

Did all content partners say "yes" to cc-by-sa? Mouse had cc-by-NC-sa (i've changed this twice already) and I know Yofie and our stuff had cc-by originally. 

Just let me know if everything should be cc-by-sa, and I'll fix 'er up.

**Comment by ldecoursy** [comment]
They all agreed to cc by-sa including mouse.

**Comment by LauraHilliger** [comment]
https://github.com/mozilla/webmaker-curriculum/pull/191

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/157"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/157.
Please don't comment on it here.
