### ISSUE TITLE
Finalize design for blog refresh

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#799]
Now that @vazquez has done a first round of review on the design, we need to do a round of edits.

https://redpen.io/nx6ba404aaca4936ab

Once we finalize the design, we'll implement it in #604.

**Comment by sabrinang** [comment]
I updated the design here with the comments from before: https://redpen.io/cff6040a27e1486ed5 (I didn't have access to he original redpen project so it is not uploaded in the same project but as a single)

![webmakers-blog-proposal-updated-4-29](https://cloud.githubusercontent.com/assets/2492510/7395796/3f65b980-ee51-11e4-98b2-bdefca91d439.jpg)

**Comment by sabrinang** [comment]
@mmmavis I just wanted to ask if the social media (like and tweet) buttons on the mockup that are proposed to go after each blog post would cause any privacy and security issue? I remember previously when we have social media plugins on wordpress it caused some sort of issue and I'm unsure if this is related. 

If these are an issue - I can return back to the original idea where we just link to webmaker social channels (and not after every blog post) on the side bar.

**Comment by sabrinang** [comment]
Any more feedback @vazquez ? (I incorporated your feedback from the [previous redpen] (https://redpen.io/nx6ba404aaca4936ab) )

R? @cassiemc

**Comment by cassiemc** [comment]
Hey @sabrinang might be good to get an R? from @vazquez or @flukeout, I have a ton of meetings for the rest of the day and tomorrow. Sorry!

**Comment by vazquez** [comment]
I'll do the review, give me 10 minutes. :)

**Comment by vazquez** [comment]
Sabrina this is looking so much better! 

R+ with small comments left in Redpen.

**Comment by mmmavis** [comment]
> @mmmavis I just wanted to ask if the social media (like and tweet) buttons on the mockup that are proposed to go after each blog post would cause any privacy and security issue? I remember previously when we have social media plugins on wordpress it caused some sort of issue and I'm unsure if this is related. 

I worry so @sabrinang , since we'll have to "link" them to our accounts somehow.  I'd suggest to keep it simple.

**Comment by sabrinang** [comment]
Thanks Ricardo - I updated it here: https://redpen.io/rgb2bdafa0720316d7
![webmakers-blog-proposal-updated-sn2](https://cloud.githubusercontent.com/assets/2492510/7400396/8a424b10-ee71-11e4-928e-8a9cf3804083.png)

**Comment by iamjessklein** [comment]
It's :eyes: looking :eyes: much cleaner. The spacing and text, and social media integration is nice as well.

**Comment by sabrinang** [comment]
@mmmavis If we can't incorporate social media for each blog post we can put it on the side bar - I made a Stay Connected section as an alternative
![webmakers-blog-proposal-updated-sn3](https://cloud.githubusercontent.com/assets/2492510/7402338/e250c9f4-ee7f-11e4-99f1-3580fd664f28.png)

**Comment by sabrinang** [comment]
The dates looked unpolished so I put some circles to frame it:
![webmakers-blog-proposal-updated-sn4](https://cloud.githubusercontent.com/assets/2492510/7419266/da271874-ef28-11e4-8edc-7396d06e44fb.png)
kinda like how www.mozilla.org upcoming events dates look (except this doesn't show year so it looks less crowded):
![screen shot 2015-04-30 at 10 57 38 am](https://cloud.githubusercontent.com/assets/2492510/7419105/c422a4a4-ef27-11e4-8e23-efb8082731bd.png)


@mmmavis  the .psd is here: https://drive.google.com/open?id=0B4Q8pzCpDS_ebl9RUFZDZHlzeHM&authuser=1

**Comment by sabrinang** [comment]
you can find background and logo assets here as well: https://drive.google.com/open?id=0B4Q8pzCpDS_efmpFa2ZQMEJkUEhKT3U2Z01ESzY2ODRHaW04MjhBb1VwZkVSTi01QkxlVTg&authuser=1
