### ISSUE TITLE
Create HTML/CSS templates from redpen

### ISSUE THREAD

**Issue by simonwex** [mozilla/teach.webmaker.org#80]
Regardless of the final solution for content editing, we need the designs converted to HTML/CSS. The home page is something we promised we'd test with and the redpen is here:
https://redpen.io/pub30ddf619bc2bcf3

**Comment by simonwex** [comment]
@cassiemc could you export a version with the grid layout you used?

**Comment by toolness** [comment]
woooooooot

are there any existing mockups of what this should look like on mobile? Or should I not care about mobile for now, or just use my best guess at what would be decently responsive?

**Comment by simonwex** [comment]
Ah, @cassiemc never-mind, I found it!

@toolness this might help: https://redpen.io/fk3c9fa74d54f34dee

**Comment by simonwex** [comment]
@toolness, there's no mobile-friendly version yet, since we don't plan on doing content-editing from mobile as a P1. We'll be visiting mobile once we've selected the final solution.

**Comment by davidascher** [comment]
@toolness but we will definitely be doing mobile before april 1st, so use your noggin.  (i.e. use a css framework that won't make that hard)

**Comment by toolness** [comment]
Ok, will do!

I am hacking on this at https://github.com/toolness/mozilla-learning-html. It does not look particularly faithful to the original mockups yet.

Also, from a technical perspective, it uses <code>[React.renderToStaticMarkup()](http://facebook.github.io/react/docs/top-level-api.html#react.rendertostaticmarkup)</code> to generate a static site, just because I thought that would be fun to explore. If it is disliked we can just lift the generated static markup, which is quite readable, and throw out the React stuff.

**Comment by toolness** [comment]
Ok, it's getting close I think. This is what I have so far:

![2015-02-25_19-25-50](https://cloud.githubusercontent.com/assets/124687/6383959/44174ce0-bd24-11e4-8efc-8703293b7d25.jpg)

It's working fine in the latest versions of Firefox, Chrome, and IE11. Safari seems to be a bit wonky but shouldn't take much to fix.

It's also somewhat responsive, though I didn't focus a ton on it as per the conversation earlier in this issue.

There's some things still missing, which I've [filed as issues](https://github.com/toolness/mozilla-learning-html/issues), but I don't think they're a blocker for the purposes of #75 (let me know if any of them are).

**Comment by davidascher** [comment]
yay!

**Comment by hannahkane** [comment]
Rad!

Will let others comment on whether the remaining issues are blockers, as I don't know what our standard "Done Criteria" is. :)

**Comment by simonwex** [comment]
Hey @toolness, when you're happy with this, could you flag Cassie for review?

**Comment by hannahkane** [comment]
@toolness - are we good to close this one, or does it still need review?

**Comment by toolness** [comment]
Yep you can go ahead and close it, we have already filed follow up issues!

This message was typed with haste on a tiny keyboard with no tactile feedback.
