### ISSUE TITLE
Iterate on homepage (Design)

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#800]
v1 is alive! Now, let's iterate. 

Feedback from users has highlighted that the homepage needs to do a better job of answering the question, "What can I do on this site?"

We also want to use more plain language wherever possible, to ensure that we're appealing to the broadest audience (though it is still a relatively niche audience).

### Suggested copy changes and CTAs ###

Headline: “We Teach the Web”
Intro copy: “Join our community of educators and activists: we teach kids and adults how to read, write, and participate on the Web.” 

Present three pathways on homepage itself:
* “Teach an activity” (helper text could be: “Browse our list of lesson plans”)
* “Host a Maker Party” (helper text could be: “Hold an event or workshop in your community”)
* “Start a Mozilla Club” (helper text could be: “Provide ongoing learning opportunities”)

We also need to account for the blog. This likely means displaying a teaser of recent content, and linking to the full blog.

**Comment by chrislarry33** [comment]
Huge agreement on these, to me the activities page is most pressing

**Comment by hannahkane** [comment]
See #821 for an idea of how the homepage might work.

**Comment by hannahkane** [comment]
@iamjessklein and @sabrinang - did you two have a chance to check in on this today? Any progress to report or questions/obstacles to raise?

**Comment by iamjessklein** [comment]
I did three new mockups that experiment with the layout and the calls to action. [Please add you feedback in redpen](https://redpen.io/p/ht0fcf05ad7ddc4ef4)

![desktop1](https://cloud.githubusercontent.com/assets/535012/7417314/51eb35d4-ef33-11e4-9536-117f5567e48e.png)

![desktop2](https://cloud.githubusercontent.com/assets/535012/7417316/559e61a6-ef33-11e4-9ef1-9a0bc991ed68.png)

![desktop3](https://cloud.githubusercontent.com/assets/535012/7417319/5897a610-ef33-11e4-985b-8f6a9db74de6.png)

**Comment by hannahkane** [comment]
Commented on redpen. I like many aspects of these treatments, but want to make sure we're really making the three primary pathways clear to users (activities, maker party, and clubs).

**Comment by sabrinang** [comment]
Note: think about incorporating a blog (https://blog.webmaker.org/tag/teachtheweb) or social element to give users a sense of what is currently happening when they land on the homepage

**Comment by hannahkane** [comment]
@sabrinang, @iamjessklein, and I met on this today. Notes here: https://etherpad.mozilla.org/teachhomepage

Key takeaways: 
 * the three main sitewide CTAs (teach an activity, host a maker party, start a club) should not compete with any other CTAs on the homepage
 * we should present those CTAs as clear pathways (see Adam's example of a product comparison on #821)
 * unlike the product comparison, though, we need to not only illustrate that the three options vary in terms of time commitment ("price" in the product model), but they are also a kind of workflow, each potentially leading to the next (perhaps the product equivalent is "upgrade")
 * featured content will be more useful as we add more ways for users to add content to the site
 * this ticket can be narrowed to the homepage-specific content. We can address the page wrapper (navigation, header, footer) in other tickets

**Comment by iamjessklein** [comment]
I put up the revised [concept on redpen](https://redpen.io/vn810ea3c32ef9d68c)

One piece that I could use some direction on is the top "hero" image. Right now it's an image, with a tagline. What was the original thought in terms of the content that would go here? Is this current content with the latest and greatest CTA? Is it more of an overarching ... this is what the Teach site is all about (which I suspect it is)? I am sort of wondering if this is wasted real estate.

cc/ @vazquez @hannahkane @sabrinang 

![desktop](https://cloud.githubusercontent.com/assets/535012/7454884/ed91547c-f245-11e4-9282-78d5426c8f36.png)

**Comment by sabrinang** [comment]
From the discussion last week (https://etherpad.mozilla.org/teachhomepage), I think for now we don't have the main CTA to be placed on the hero yet but with the 3 pathways in proximity I think it will work until we have a main place we'd want to funnel users too. 

Example using some of the copy:
![screen shot 2015-05-04 at 10 31 51 am](https://cloud.githubusercontent.com/assets/2492510/7458594/64148566-f24a-11e4-9cf1-37b80a8d235e.png)

The banners do take up a quite of screen real estate and may be reconsidered across the other pages as well down the road.

**Comment by iamjessklein** [comment]
just to reiterate what @sabrinang and I discussed, we need to just incorporate the blog from my wireframe and then we are good to go in terms of page structure.

**Comment by sabrinang** [comment]
Also, refine how we show progression and relationship of the 3 pathways (referring to #821)

**Comment by hannahkane** [comment]
+1 to all of the above, including the idea of considering using less real estate for the mission-y language.

**Comment by iamjessklein** [comment]
One thing that I was just wondering was if the visual was less dense, there might be an opportunity to move the CTAs up. Something kind of like this from Aetna.com

![screen shot 2015-05-04 at 2 35 41 pm](https://cloud.githubusercontent.com/assets/535012/7459630/414b802c-f26b-11e4-9b88-d2c867b126c7.png)

**Comment by chrislarry33** [comment]
Love the directness of Aetna site, we need that

+1 to less mission language as sales language

**Comment by iamjessklein** [comment]
Revised - I think that a lot of this layout will depend on if we can find a complimentary photo or graphic. 

![desktop](https://cloud.githubusercontent.com/assets/535012/7517106/06f07a58-f4a1-11e4-86d0-3e5b1117d86c.png)

**Comment by iamjessklein** [comment]
This is where I am at the moment. I am going to work on the icons that go where the little blue squares are currently acting as placeholders. 

![ttw](https://cloud.githubusercontent.com/assets/535012/7522582/35e83008-f4c4-11e4-8581-4812ea1939d6.png)

**Comment by hannahkane** [comment]
Nice! 

I like the three CTAs as a layer over the hero image. I wonder what it will look like with icons or photos next to them. Will it seem too busy?

I like the copy changes you made, with the exception of "Small to medium sized experiments," which I think is a little confusing. I really liked "Browse our list of lesson plans" (from the ticket description), though I see it doesn't fit with the other two copy changes. Perhaps, "Short lesson plans."

I think the line break in the "We are a community of...." text is off. Should be after the word "adults."

**Comment by hannahkane** [comment]
Also, I think the "See all blog posts" button is the loudest thing on the page. Maybe we could make that a link instead of a button?

**Comment by chrislarry33** [comment]
Love where this is heading

For "Teach an Activity" can the copy just say "Lessons and Curriculum"

+1 on loudness of "see all posts"

**Comment by iamjessklein** [comment]
Updates: 

* Added icons 
* Added more quotes (PLEASE NOTE ARYA IS PLACEHOLDER)
* Adjusted copy
* Changed button to link

![bravos](https://cloud.githubusercontent.com/assets/535012/7525781/613a74b2-f4da-11e4-81e5-b9b2d4aa23af.png)

**Comment by hannahkane** [comment]
Like! This seems like a solid next iteration from a product perspective. @iamjessklein - should we have someone do a design review next?

**Comment by iamjessklein** [comment]
Yes. I pinged @vazquez to do a review. But, I'll do it officially here, hey @vazquez can you :eyes: at this? Thanks.

**Comment by hannahkane** [comment]
@vazquez - have you had a chance to take a look at this?

**Comment by vazquez** [comment]
@hannahkane - Sorry for the delay Hannah, I've posted my comments in Redpen. https://redpen.io/ev1973a49294855f03

**Comment by hannahkane** [comment]
Thanks very much, @vazquez! We'll have @sabrinang make these final tweaks next heartbeat.

**Comment by sabrinang** [comment]
You can find some WIP iterations on redpen: https://redpen.io/p/uebb1e58b38f67faf7

I'm working on sorting through visual treatment on the banner section and content hierarchy on the page and iterating on what information to exclude or include from other pages:
![screen shot 2015-05-12 at 4 49 52 pm](https://cloud.githubusercontent.com/assets/2492510/7601120/2e9915d6-f8c7-11e4-99d9-06a1d5c404b5.png)

**Comment by toolness** [comment]
This looks rad!

One concern I have is that I've heard it's good practice to put the newest, most frequently-changing content "above the fold", so that repeat visitors can easily see what's changed, and to give the site itself a feeling of being alive and dynamic rather than static. The "on the blog" section is the only dynamic content on this page, but it's below the fold.

Anyhow, that "best practice" might not be relevant anymore (I heard about it like 10 years ago lol), or it might not be relevant to our particular audience, but I figured I'd mention it just in case.

**Comment by hannahkane** [comment]
Thanks for turning out so many variations! Left my comments on the redpen.

Agree with @toolness that the fresh content would ideally be above the fold, but for now I agree that a short About paragraph might be necessary for basic context. I hope we'll eventually sort out our branding enough that we may not need that context, because we won't have to worry about people mistaking the site for the Mozilla homepage.

cc @ldecoursy @thornet and @chrislarry33 for feedback as soon as you can.

**Comment by ldecoursy** [comment]
Loving the iterations! Left a few comments here: https://redpen.io/ruae7488775739dafe

One q for @HPaulJohnson @chrislarry33 - thoughts on if it's ok to have the title copy on the home page for teach.mozilla.org say "Mozilla Learning Networks?" We want to be clear this isn't the home page of Mozilla... Currently sayes "We Teach the Web."

**Comment by HPaulJohnson** [comment]
100% ok with the title copy Mozilla Learning Networks. Think it's a big improvement.

Unrelated, taking a quick spin through the iterations I'd advocate for the ones which have the clear calls-to-action integrated in the main promo space, above the fold.

**Comment by chrislarry33** [comment]
+1 to MLN...could it be The Mozilla Learning Network? If not, not a blocker for me. Does raise Hive placement for me to so it feels cohesive. Could it even be a sidebar link/section?

+1 to Paul's second point as well

**Comment by hannahkane** [comment]
@sabrinang - thanks for the speedy iterations. It sounds like we'd like to see a version with:
* Mockup 1's button style
* "The Mozilla Learning Networks" as the headline, with no sub-head
* Hero image followed by About text, blog, color-blocked quote, and three blue CTAs

@chrislarry33 - I hear your point about Hive placement. Let's address that in other tickets (perhaps #861) to keep the scope of this ticket narrowed to just the homepage content.

**Comment by chrislarry33** [comment]
WFM

Should be "The Mozilla Learning Network"

**Comment by hannahkane** [comment]
thanks, updated.

**Comment by sabrinang** [comment]
![teach_iteration11](https://cloud.githubusercontent.com/assets/2492510/7642077/ef688e1e-fa42-11e4-93e5-3db2260a1869.png)


redpen: https://redpen.io/ejc900cf7e4b532df6

**Comment by hannahkane** [comment]
<3

**Comment by sabrinang** [comment]
Updated copy: "The Mozilla Learning Network" and "About Us"
redpen: https://redpen.io/ejc900cf7e4b532df6
![teach_homepage_mockup](https://cloud.githubusercontent.com/assets/2492510/7657465/dcfb75f8-fae6-11e4-9354-73a5c6f226e6.png)

**Comment by hannahkane** [comment]
Ship it! Will unblock the implementation ticket.

Nice job, Sabrina. :)

**Comment by ldecoursy** [comment]
:trophy:

**Comment by chrislarry33** [comment]
Agreed, awsm work. Thank you very much all!

**Comment by sabrinang** [comment]
Going though photos to finalize the banner: https://redpen.io/ro3d3a2d36dc9f1e24
![teach_wireframes_banner_photos](https://cloud.githubusercontent.com/assets/2492510/7717046/888eb0fe-fe4f-11e4-8ae4-2ccef875ae1f.png)

Many photos are busy but I think 4 has most of the image out of focus so it doesn't interfere with the text too much
@cassiemc any feedback?

**Comment by sabrinang** [comment]
![teach_homepage](https://cloud.githubusercontent.com/assets/2492510/7733509/4fdcc30a-fee4-11e4-963b-186f1ce750f0.png)
redpen: https://redpen.io/er45927e5cf11b9297
R? @cassiemc

**Comment by sabrinang** [comment]
Updated redpen: https://redpen.io/er45927e5cf11b9297
NOTE: yellow button is the hover state
![teach_homepage2](https://cloud.githubusercontent.com/assets/2492510/7739303/7e5177ce-ff13-11e4-957f-0ea36495cabd.png)
R? @cassiemc

**Comment by cassiemc** [comment]
We R'd on design crit, and these adjustments look great. Nice work Sabrina! R+

**Comment by sabrinang** [comment]
Hero banner photo:

![herobanner-homepage](https://cloud.githubusercontent.com/assets/2492510/7756474/50d17996-ffb0-11e4-83f1-d4f6ff509385.png)

(original) https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eVHB0RmV5a0FQQkE/view?usp=sharing
(retina) https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eRjY2Y1pSUk9zUGs/view?usp=sharing

.ai file for reference: https://drive.google.com/open?id=0B4Q8pzCpDS_ecmVIekZmVHFRdjg&authuser=0

**Comment by mmmavis** [comment]
@sabrinang could you help export the svgs that are used in hero unit button **hover state**?  Thanks!
