### ISSUE TITLE
[MIGRATED] Compare iRights 10 Steps with Web Literacy Map

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#801]
We have a big opportunity for a thought partner + storyteller around web literacy. iRights is a project led by the UK Member of Parliament, Beeban Kidron. 

Her team is drafting "10 Steps to Digital Literacy". 

Let's review her steps and think where we have overlap / divergence with the web literacy map. This will be the basis of a shared learning pathway(s) and possible campaign to promote and teach it.

Please leave your comments in the Gdoc! 

https://docs.google.com/document/d/1NgewYMqA9BZ8nFSB7Y5JEftSCNMFBmapKdayUCuXpMY/edit?usp=sharing

cc @LauraHilliger @jgmac1106 @omnignorant @smithisgeneric @amirad

**Comment by thornet** [comment]
PS. The 10 Steps are still in active development. Not a super public / refined doc yet. Sharing here so we can think out loud and easily invite in others to reflect.

**Comment by chrislarry33** [comment]
Good work to do here, if we can find the right areas of alignment it might help us contextualize and better connect web lit competencies and skills to youth development outcomes. That's hyper relevant for lots of our work. Might be good to add Meghan to this thread. Even identifying one mutual thrust could Forge good relationship here.

**Comment by davidascher** [comment]
Are there relevant deadlines to think about?  (Some of the making steps I'd
like Webmaker to be able to explicitly support, but timing may get in the
way).

**Comment by thornet** [comment]
Thanks, @chrislarry33 @davidascher! I'll invite Meghan to take a look as well. 

Beeban wants to know by early May if we see substantial enough overlaps. Then in late Q3 - Q4 we want to produce some materials (ideally with things we already have) to illustrate and teach the steps. Dave Steer is helping shape that opportunity. + a million to seeing where Webmaker could plug in.

**Comment by chrislarry33** [comment]
Can we set a time/date for a team to do some alignment mapping? I think the right people, 90 minutes of co-analysis and writing gets us a good step down the road here. As i suggested in the call, also good to get at least a rough sketch of "Smart-Ons" planned through EOY and see how that overlaps. This also seems primed for some discussions with Brett Gaylor about a 20 second PSA length version of some of his work might play out and provide us a template for reusing with content and engagement strategies. Some fun ideas there that i think we should think about seriously.

**Comment by thornet** [comment]
I put this in the May 8 milestone. If we meet next week and jam on this, think we'll make good progress. @chrislarry33 do you have other suggestions for who'd be a good fit for co-analysis?

**Comment by LauraHilliger** [comment]
hmmm - I didn't spend a ton of time because I saw how much there is to be done here. How much input will we have? Are they coming to us as the experts on web + digital literacy or does their team include thinkers in this arena? I ask because this document is overly raw and divergent in ways it doesn't need to be - not just from Web Literacy, but from a generally accepted understanding of Digital Literacy. Before making any suggestions, I would like to understand the partnership a little better.  

I can, however, see plenty of places we could demonstrate WebLit overlap. I think there's a lot to work with, and second the idea to do some co-analyzing and otherwise have an internal conversation.

**Comment by DaveSteer** [comment]
Hi all - Here's the work-in-progress deck that captures the opportunity. Would love any feedback as we package this together for Mark and Mary Ellen. 

One consideration that Dia and I are talking about is whether this initiative is a 'Smart On' or whether it is something bigger. This thinking will play into whether we recommend the 'gold', 'silver', 'bronze' concepts (with 'bronze' being limited to a 'Smart On' template)

https://docs.google.com/a/mozillafoundation.org/presentation/d/19rBpOH6ByS9_lUQw3RfIj2pynPlr4e-OW4i6phjKgZE/edit#slide=id.g91935e2c7_2_79

**Comment by smithisgeneric** [comment]
I went through the Google doc and made a few comments in the margins but would also benefit from more context like @LauraHilliger suggested.  Happy to participate in a group session to dive deeper here since that is where it looks like it is headed.

**Comment by thornet** [comment]
Going to review this in our Sustaining Engagement call on Wed., so will have final list of overlap by then.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/158"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/158.
Please don't comment on it here.
