### ISSUE TITLE
[MIGRATED] Template an Etherpad and Discourse thread for Coordinating Clubs

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#802]
In the Open Tools module, we need actions around:

* Protocols & patterns for coordinating clubs
* How to connect with RCs and regions (video bridge / cross-region comms & connection)

My idea would be to set up a template etherpad and discourse thread that shows how online coordination might look like. Then the actions in #753 would be to copy/paste/create.

@soapdog how are you coordinating your club captains in an online environment? Do you have some things we could pull from?

**Comment by soapdog** [comment]
@LauraHilliger its early days, we're yet to have club captains. Right now we're playing all roles. My main idea for our Rio project is to have the following things:

* private mailing list for LAN House owners and project stakeholders and captains. This list will be used to logistics.
* public mailing list for everyone including all members of above list plus learners and interested parties. This is our discussion list. Mailing list is low attrition and doesn't require its members to learn something new. I don't know if discourse is fully localized into Portuguese and we can't use webapps in English in our context.
* Bilingual blog about the project where all posts are duplicated in English and Portuguese. This could be a simple site about the project. Need to ask the infrastructure folks for a place to host it.
* Planet page on our site. We want each LAN House (aka cybercafes) to maintain their own blog and we plan to aggregate them in a planet.

I was waiting for my contract and my LDAP account to pursuit these. Now that things are settled, I will figure out how to ask about these things.

**Comment by chrislarry33** [comment]
@soapdog This looks like a strong plan to get going and gain momentum. Glad you have your LDAP so you can start to move quickly. Looking forward to seeing how this progresses,  important work for our team.

**Comment by LauraHilliger** [comment]
@soapdog on the localization + Discourse question, it appears that the software is, indeed, fully localized into Portuguese. https://www.transifex.com/projects/p/discourse-org/

We'll need to investigate from the tech perspective how we accomplish this, therefore I've filed https://github.com/MozillaFoundation/plan/issues/440

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/159"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/159.
Please don't comment on it here.
