### ISSUE TITLE
Correct missing and incorrect alt tags

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#803]
if you hover over the "Clubs Toolkit" link on https://teach.mozilla.org/clubs/ the tooltip says "todo hover tooltip"

On "Event Resources" there is no existing alt tag.

**Comment by mmmavis** [comment]
@hannahkane would you know what the tooltips are supposed to say?  (for "Clubs Toolkit" and "Event Resources")

**Comment by hannahkane** [comment]
I don't think we need tooltips at all.

**Comment by mmmavis** [comment]
duplicates: #522
I vote for remove them all as well.

**Comment by hannahkane** [comment]
Let's remove them!
