### ISSUE TITLE
Investigate l10n tooling for static content

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#808]
The expected outcome of this ticket is a recommendation for what tool to use to manage translations of static content on Teach

This is in preparation for beginning localization of the static content in June, once the content on the EN version of the site stabilizes.

**Comment by toolness** [comment]
I believe we use [Transifex](https://www.transifex.com/) for this, though I've heard some complaints from localizers about its usability. I know there's at least one other service, [localizeJS](https://localizejs.com/), which could be worth exploring, but I'm okay with going with whatever all the other mofo projects are using here.

**Comment by deimidis** [comment]
Like @toolness says, Transifex is what we are using. Has the advantage of translation memory, but with lasts changes, maybe there is some complaints. Did you see the last development of [Pontoon](https://pontoon.mozilla.org/) is a Mozilla tool that has some advantages for localizers (see the space and context) but I don't know how easy is to add to your project

**Comment by deimidis** [comment]
Also, we were talking with Alvar Maciel that a place where we could create a glossary and have terminology discussion could be useful too. Maybe it's not part of this project.

**Comment by toolness** [comment]
Thanks deimidis!

Looks like alicoding is doing some thinking on this at https://github.com/MozillaFoundation/plan/issues/424#issuecomment-97825903 too.

**Comment by hannahkane** [comment]
I think this ticket is redundant of https://github.com/MozillaFoundation/plan/issues/424. Let's continue the conversation there.
