### ISSUE TITLE
Determine content for "Teaching Activites" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#81]
RACI

* Phase: Planning
* Owner: @ldecoursy
* Decision Maker: @chrislarry33 @thornet 
* Consulted: @LauraHilliger @dajbelshaw 
* Quality Verifier: @hannahkane 

Proposal: We have a "Clubs Curriculum" page for the sanctioned and tested series of sequential activities that we want Club Leaders to use (see #36). We create a separate "Teaching Activities" page to fulfill the "Grab and Go" needs of some users.

For April 1, our goal is to feature 10 best in show activities - quality over quantity

- [x] @ldecoursy to create checklist to use when reviewing/considering existing content  
- [ ] @ldecoursy @LauraHilliger @dajbelshaw use that to review/propose content (starting with etherpads below)
- [ ] Page should also link to existing Hive portfolios (links below)

Existing resources:
* https://teach.etherpad.mozilla.org/BestTeachingKits
* https://teach.etherpad.mozilla.org/best-in-show
* Hive NYC Portfolio http://hivenyc.org/portfolio/
* Hive Chicago Portfolio http://hivechicago.org/portfolio/#/*
* Hive Toronto Portfolio http://hivetoronto.org/portfolio/#/*
* Hive Chattanooga Portfolio http://hivecha.org/portfolio

**Comment by LauraHilliger** [comment]
I started to comment in RedPen, wrote too much, but the TLDR is "Do we **really** need a separate page?":

Clubs curriculum is still a scaffolding of activities, e.g. a series of "kits", just presented differently. We have a lot of great kits from the past years that we should be displaying as well.  

We might have "Web Literacy: 21st Century skills" and underneath might be Web Literacy Basics 1 (clubs curriculum) as well as "Privacy and Security Teaching Kit" (partner developed content). Both are kits, we just need to work out how we group stuff.

For this issue, the question is - do we have a page for kits (e.g. leading with club kits, but including lo-fi, mobile, whatever) and a page for singular activities (e.g. NO scaffolding included, just a mishmash of spectrograms and stuff)? Or is this accomplished through some sort of search / or a display technique? We have the benefit of organizing against the Web Lit Map, so maybe it's all a filtering approach as opposed to a separate page... 

In any event, we have already curated and collected some stuff back in the day, and my brain is holding URLs to a lot of stuff too. @ldecoursy this pad might still be helpful: https://teach.etherpad.mozilla.org/best-in-show

**Comment by ldecoursy** [comment]
Our goal is sustained engagement, so highlighting the Clubs curriculum is key. Of course also recognize some people will want to sample/try individual activities, or set up scaffolds of their own, and that there's lots of existing content. I think for MVP for this site, we really want to highlight the best of what's been created so far. Thanks for the etherpad @LauraHilliger - I'll dig in!

**Comment by dajbelshaw** [comment]
If there's a RACI for this, could you add @LauraHilliger and me to it please, @hannahkane? :)

**Comment by ldecoursy** [comment]
Checklist for selecting content for this page started here: https://teach.etherpad.mozilla.org/contentreview

**Comment by chrislarry33** [comment]
@thornet

**Comment by thornet** [comment]
Added my recommendations to the etherpad.

**Comment by LauraHilliger** [comment]
added a couple too. Should we be combing these kits for activities, or do we want to present whole kits? The criterion "Doesn't take more than 60 minutes" won't work for whole kits, and the criterion about learning objectives is tricky too because while activities have them, they're listed on the kit overview page as opposed to on the activity page. 

Let me know how/if I can help :)

**Comment by ldecoursy** [comment]
@thornet @chrislarry33 Do you want to +1 the 8-10 you like best? Then I can draft some quick intro copy for each.

**Comment by chrislarry33** [comment]
I added my +1s. I think there is some ones in second list to use.
Perhaps @LauraHilliger could clean up a few we like but that are missing pieces

Also where are the ones from the stay ay home dad?

**Comment by LauraHilliger** [comment]
They're here: https://webmaker.org/en-US/user/fourtonfish/teaching-resources

Currently there are 7 +1's in the "no need to modify" section and 5 in the tweaking section. Happy to make changes / do cleanup once the list is chosen.

**Comment by ldecoursy** [comment]
I've updated the etherpad so top picks start at line 31. I suggest removing the SEO Battle - Meredith said it takes a few days for Google search results to reflect new pages, so not really a payoff at the end. That leaves us with 11, and I'm currently adding a few notes about tweaks we might want to make to 4 of them. @LauraHilliger can you help with that, and maybe select one from Stefan if there's one that doesn't require tweaking?

**Comment by chrislarry33** [comment]
One thought I had is should we highlight "Tools we like" section that could have like Scratch etc? Also should we catalogue some aligned activities repositories like North Western's Fuse, Common Sense Media and NWP's Youth Voices?

**Comment by LauraHilliger** [comment]
How do you feel about this one from Stefan? It's involved, but timings are given, it's well documented and seems to be broken up nicely: https://fourtonfish.makes.org/thimble/creating-for-the-modern-web

I will start remixing tomorrow.

**Comment by dajbelshaw** [comment]
+1 for the web fonts stuff, @LauraHilliger. The API stuff seems a bit high-bar for this context, though.

**Comment by LauraHilliger** [comment]
Remixes:
* [Hack your notebook](https://laura.makes.org/thimble/LTU1NDA0MTA4OA==/hack-your-notebook-teaching-kit) (really just needed to remove "day" and a hashtag from this resource. Added an image, checked subsequent resources, and they don't need updates).
* [Minecraft] (https://laura.makes.org/thimble/LTE4NDk0MjMzNg==/minecraft-a-flavor-of-java-epik) The old kit was all kinds of broken. I replaced all the activities with tutorials EPIK has on their site, added images and otherwise remixed the whole shebang.
* [E.A.K](https://laura.makes.org/thimble/LTEzNDYxMDY4OA==/eak-activity-guide) Built on the newer activity template, added LOs, images and lite text edits
* [Girls in Tech](https://laura.makes.org/thimble/MjE3Nzc2Mzg0/hacking-my-media-with-x-ray-goggles) The noted activity relied on thimble, so I chose the Goggles activity instead. Built on the newer activity template, added LOs and lite text edits

**Comment by ldecoursy** [comment]
AWSM @LauraHilliger! Can you check the links to XRay Goggles - now if we want to link to install goggles, we might want to link direct to https://webmaker.org/en-US/goggles/install because the link to install on the main page is not highlighted. I filed a separate bug re: that here: https://github.com/mozilla/goggles.webmaker.org/issues/195

**Comment by LauraHilliger** [comment]
yep and done.

**Comment by ldecoursy** [comment]
We're currently at 11 (it goes to 11!) grab-and-go activities: https://teach.etherpad.mozilla.org/contentreview

The Image Seeking for Visual Metaphors activity also relies on a Thimble make, in case we want to cut that from the list for now.  I also really liked this other Girls in Tech Thimble activity - https://techkim.makes.org/thimble/girls-in-tech-role-models. Perhaps we can plan to update this one for next round.

**Comment by chrislarry33** [comment]
I am OK going to 15 if we have enough we like/are cleaned up.

@LauraHilliger truly awsm work cleaning these up, they are very much improved

**Comment by hannahkane** [comment]
Thanks, all, for the great work so far.

Aiming to finalize this content by EOD Thursday.
 - [ ] Final list of activities w/ links
 - [ ] Brief description of each (should reference the creator of the activity/kit)
 - [ ] Intro paragraph for top of page

**Comment by ldecoursy** [comment]
Hi - final list of activities with descriptions and intro copy for the page and Hive portfolio links is here: https://teach.etherpad.mozilla.org/teachingactivitiespagecopy

**Comment by hannahkane** [comment]
Hooray! Thanks, @ldecoursy. Looks awesome, so I'm closing this ticket.
