### ISSUE TITLE
Verify sidebar colours

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#812]
I'm not sure if the sidebar colours we applied match what's in the specs.

Here's what I discovered:

- Home (blue, #1E92CE)
- Teaching Activities (hot pink, #D64262)
- Events (blue, #2D4A8C)
  - Event Resources (blue, #1F93D0, a lot lighter than what we have for Event's sidebar but very similar to Home's)
- Teach Like Mozilla (green, #6BB387)
  - Web Literacy (same green, #6BB387)
- Mozilla Web Clubs (orange, #E78832)
  - Clubs Curriculum (lighter orange, #EA9549)
  - Clubs Toolkit (same light orange, #EA9549)

**Comment by toolness** [comment]
Seems like this has some intersection with #701.

**Comment by mmmavis** [comment]
problem solved in https://github.com/mozilla/teach.webmaker.org/pull/826

turns out subpages should be in the same colour as their parent
