### ISSUE TITLE
Missing links and images on Event Resources

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#813]
- [x] links to Brand Palette
  - use https://party.webmaker.org/party-resources/MakerPartyBrandPalette.eps and https://party.webmaker.org/party-resources/MakerPartyBrandPalette.png ?
- [x] thumbnail(retina) for Poster Image
  - need file
- [x] "discussion forum" link in Ask The Community section
  - need link
- [x] "contact us" link in Request Support section
  - need link

**Comment by hannahkane** [comment]
Gah! Good eye!

* Brand palette - yes, let's use those
* Poster image - hmm...not sure. @iamjessklein or @sabrinang - do you know?
* Discussion forum: http://discourse.webmaker.org/category/maker-party
* Contact us: mailto:teachtheweb@mozillafoundation.org

**Comment by hannahkane** [comment]
@mmmavis - is it okay if I add this to the current milestone? These are kind of embarrassing, so would be good to fix.

**Comment by mmmavis** [comment]
Definitely! It should only take 1 min to prepare the PR once I have the retina poster image :)

**Comment by sabrinang** [comment]
thumbnail for poster image (retina): https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eUFE4dmR5X3BpZnc/view?usp=sharing
