### ISSUE TITLE
Hero images are quite large / slow to load

### ISSUE THREAD

**Issue by thisandagain** [mozilla/teach.webmaker.org#820]
On the landing page, the image `hero-unit@2x.png` is about 737KB. I noticed this as every time I load `teach.mozilla.org` I notice a long loading delay (even on Mozilla Wifi). Doing a quick test, exporting as JPG at 60% quality (no noticeable degradation in quality) cuts that in half. Other hero images also appear to be about half a megabyte or more.

**Comment by hannahkane** [comment]
I think this is a dupe of #790.
