### ISSUE TITLE
Optimize user flow on teach.mo.org to add a club

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#821]
If one of our needs for teach.mozilla.org is to grow clubs, then we should optimize the path to do that. 

Inspired by a chat with @adamlofting on going about that. He suggested something a bit "decision tree" like. From a user coming to the site cold to learning more about our work and then either i) taking activities to grab and go or ii) learn more about clubs. 

@hannahkane is working on the next iteration of the site already. Hannah, would you have a suggestion of the best way to map out this flow? In your Gdoc? Elsewhere?

We should combine forces! 

cc @ldecoursy

**Comment by hannahkane** [comment]
The next iteration is largely about making the user pathways clearer. Though it's not visualized as a tree, you can see the thinking here: https://docs.google.com/document/d/1Nw9iaocU7E41E6jKCWPh_InA0dMg-8AqBSVO3W6ycXA/edit#

I can make it a tree!

**Comment by hannahkane** [comment]
Setting up a call with @adamlofting to think through optimized pathways as a next step.

**Comment by adamlofting** [comment]
I had another idea this morning that might work for this, which is to use the typical choice / pricing layout used for selling software products.

Here's a quick example of how this could be laid out, using a screenshot from another service:

![pricing idea](https://cloud.githubusercontent.com/assets/1901816/7344653/6b01ba40-ecc5-11e4-94ed-f7ad20c4e511.jpg)

With the 'cost' to the user being the amount of time they need to commit. And a clear chance for us to layout the benefits that come from getting involved in each of the options and how they relate to each other.

**Comment by thornet** [comment]
@adamlofting Love it! I think we need that kind of explicitness. It shows expectations, benefits and also our theory of progression / tiers of involvement. 

@hannahkane this reminds me of the menu approach you had in your Gdoc. Do you think this kind of visualization would work well in the next iteration?

**Comment by hannahkane** [comment]
Yes, this is great. Linking to this from #800 which is where the design work for the homepage will happen.

Can we clarify what the outcomes of this ticket might be?

**Comment by HPaulJohnson** [comment]
I really like this "tiered" presentation Adam has above and think it could work well here. One of the things that it gives you is the ability to show a short-list of features and benefits for each tier. 

In looking at the gdoc (and the existing site), I think that's one thing missing right now - the "what's in it for me" from a user's perspective. Creating a clear funnel to our key CTA's is one part of this, answering the "why" is the other key piece IMO.

**Comment by hannahkane** [comment]
+1 to clarifying the value add. I've tried to spell that out a little more in the copy on the doc, and reframed several things to be more user-centric.

Also tried to clarify the two different use cases that I think we have - the person coming to start a Club, and the person who has a Club and needs resources.

Please take a look at the document again and add more comments/questions. They've been very useful!

**Comment by iamjessklein** [comment]
:+1: Thanks this is a really great idea, I am going to try to incorporate it into the #800

**Comment by hannahkane** [comment]
I think this is now being handled through a few other tickets, and this one no longer seems actionable.
