### ISSUE TITLE
Event Resources page should be dark blue

### ISSUE THREAD

**Issue by vazquez** [mozilla/teach.webmaker.org#824]
Currently Events Landing Page and Event Resources page have different colours. All we need is to change the main colour of event resources page to be dark blue.

**Comment by mmmavis** [comment]
@vazquez could you provide the colour code? `@darkBlueSidebarColor` is defined twice in our code, see https://github.com/mozilla/teach.webmaker.org/issues/701

(a could be related ticket: https://github.com/mozilla/teach.webmaker.org/issues/812)

**Comment by vazquez** [comment]
Commented in #701 @mmmavis!
