### ISSUE TITLE
Host Maker Party assets on S3 (for now)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#828]
As mentioned in https://github.com/mozilla/teach.webmaker.org/issues/266, we eventually will have party.webmaker.org redirected to teach.mozilla.org/events.  Currently there are still links that link out to the Maker Party site (https://github.com/mozilla/teach.webmaker.org/blob/develop/pages/event-resources.jsx search for party.webmaker.org), we should grab those assets and have them hosted on the Teach site before the redirect is in place.

**Comment by hannahkane** [comment]
Oh! Now I get what you mean. Yes, we have to avoid the infinite loop. :)

**Comment by mmmavis** [comment]
Heh, sorry didn't explain it well enough earlier.  Yeah I think they would probably be 404s instead but yea we shouldn't let that happen.

**Comment by toolness** [comment]
ACK I messed up reviewing #828! I failed to notice that there are multiple files in that PR that are over 20mb, which is huuuuuuuuge.

I'd really prefer to keep those external to the repository--perhaps using [Git Large File Storage (LFS)](https://github.com/blog/1986-announcing-git-large-file-storage-lfs) once it's fully rolled-out. Until then, though, is it ok if we either put these on S3 somewhere, or leave them on the maker party site for now?

**Comment by mmmavis** [comment]
> I'd really prefer to keep those external to the repository--perhaps using [Git Large File Storage (LFS)](https://github.com/blog/1986-announcing-git-large-file-storage-lfs) once it's fully rolled-out. Until then, though, is it ok if we either put these on S3 somewhere, or leave them on the maker party site for now?

@toolness this is currently blocking https://github.com/mozilla/teach.webmaker.org/issues/266 ("party.webmaker.org should go to teach.mozilla.org/events"). I guess it really depends on the urgency of that ticket.  @hannahkane would you know?

**Comment by hannahkane** [comment]
I don't want to wait for LFS. Can we put them on S3?

**Comment by toolness** [comment]
Sure!

Hey @jbuck, do we have an existing S3 bucket where we could put large-ish (20mb+ per file) downloadable resources for maker party events, like logos and flyers and such? We'll eventually want to migrate these to Git Large File Storage but until then we'd like to host them on S3.

If we don't have an existing bucket, do we have the quota to make a new one?

**Comment by jbuck** [comment]
@toolness Yeah, you can throw it in the "stuff.webmaker.org" S3 bucket which has https enabled already

**Comment by toolness** [comment]
Thanks! @mmmavis do you have access to write to that bucket? If so, could you put the assets in there--perhaps under a directory called `teach.mozilla.org` so it's obvious what the files are for--and re-submit a new PR that links to them?

**Comment by mmmavis** [comment]
@jbuck @toolness 

ummm I don't think I do actually.  Can someone grant me access?

**Comment by jbuck** [comment]
@mmmavis do you have AWS credentials already?

**Comment by mmmavis** [comment]
@jbuck nope, no access to AWS at all :scream:

**Comment by mmmavis** [comment]
@jbuck could you get me on AWS when you get a chance? :bowtie:

**Comment by jbuck** [comment]
Filed https://github.com/MozillaFoundation/mofo-devops/issues/54 for creds

**Comment by mmmavis** [comment]
Thanks! @jbuck

**Comment by mmmavis** [comment]
Yeah I got my creds back :dancers: .  Gonna create a dir `teach.webmaker.org` and upload all the event resources there.
