### ISSUE TITLE
Identify two real quotes for Teach site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#83]
One for the homepage (general quote, e.g. "teaching web literacy is great! I love being a mentor!" )

One for the Clubs page (more specific, e.g. "running a club is aces!")

**Comment by dajbelshaw** [comment]
Are these new quotations (i.e. ones we're *asking* for) or ones from material we've already gathered (e.g. survey responses)?

**Comment by chrislarry33** [comment]
We should be culling these from existing assets/resources

**Comment by ldecoursy** [comment]
I'd like to get quick approvals from folks before we use them. Let me know what you think of the options below. I can also reach out to a few folks individually.

These are pulled from our initial 1:1 conversations.
* Mikko Kontto "The idea teachers and students learning at same time is what makes me excited about this work. This kind of free and open club approach is the only way to go about it, really." (He teaches middle school students in Helsinki, Finland)
* Maurya Couvares "Web literacy is about more than coding - it's how you can be a better web citizen, how can you remix media, understand your privacy online, and more." (She runs ScriptEd program in NYC) 

These are pulled from club cohort calls:
* Priyanka Nag "Some of these activities were the most fun things I have done and seen till now for teaching sessions." (Developer in Pune, India)
* Su Adams "We've done the Hack the News activity before with nearly 300 kids in one day! Fantastic FUN!! (IT Coordinator at Staplehurst School in the UK)

**Comment by hannahkane** [comment]
I really like the quotes from Mikko and Maurya, though I wonder if they could be made shorter. Perhaps for the homepage: "Web literacy is about more than coding - it's about how you can be a better web citizen." And for the Clubs page: "The idea of teachers and students learning at the same time is what makes me excited about this work."

I'd reserve Priyanka and Su's quotes for if we ever decide to add quotes to the Clubs Curriculum and/or Teaching Activities pages.

**Comment by ldecoursy** [comment]
Sounds good to me - do you need headshots of them too? If so I can reach out now for both approval and images.

**Comment by hannahkane** [comment]
Headshots would be great. Thankds, @ldecoursy!

**Comment by ldecoursy** [comment]
OK emailed them both will keep you posted!

**Comment by ldecoursy** [comment]
Maurya approved, here's her photo:

![550474_10151289899842329_2028778841_n](https://cloud.githubusercontent.com/assets/4885898/6420808/93e53f06-be97-11e4-90b6-b81600edaf32.jpg)

**Comment by chrislarry33** [comment]
OK with truncated quotes

**Comment by hannahkane** [comment]
Any word on Mikko's OK + headshot, @ldecoursy ?

**Comment by ldecoursy** [comment]
I reached out again via email - haven't heard back yet, will try via Twitter!

**Comment by ldecoursy** [comment]
Heard back from Mikko, got his OK, expecting headshot today.

**Comment by ldecoursy** [comment]
I've asked for an option with more of his face, but here's what he sent as placeholder ![image1](https://cloud.githubusercontent.com/assets/4885898/6493917/1f7b5436-c28c-11e4-8ec7-50756314d9af.jpeg)

**Comment by ldecoursy** [comment]
Here's another shot - his preference is not to have full-on image with his full name. Are we planning to do first name, last initial? 
![image1](https://cloud.githubusercontent.com/assets/4885898/6528666/9d420f98-c3f1-11e4-94e9-c2d23f6b0cd7.jpeg)

**Comment by ldecoursy** [comment]
Marking this closed as we have approval on quotes and images.

**Comment by chrislarry33** [comment]
#lovedclosed

**Comment by ldecoursy** [comment]
Sorry, just received link to what might be a better image for Mikko https://secure.gravatar.com/avatar/809aa24eb51b76e4f561c66180a96478?d=https%3A%2F%2Fstuff.webmaker.org%2Favatars%2Fwebmaker-avatar-200x200.png&s=400
