### ISSUE TITLE
Design next iteration of Activities page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#830]
The next iteration of the /activities page will accomplish the following:
 * display all of the various types of activities we have, including the "a la carte" activities and teaching kits as well as the more prescriptive Clubs Curriculum
 * aim for scale (imagine a future when we have many more activities, teaching kits, and curriculum)
 * offer solutions for users looking to search and for those looking to browse

### Content ###

* Intro copy: “Teach others how to read, write and participate on the web with these free activities created by and for teachers and technologists.”
* “Find the perfect activity” [faceted search, based on keyword, age group, and level]
* Prominently feature Clubs modules - e.g. Web Lit Basics, Privacy (but more to come)
* “Teaching Kits” “Teaching Kits are sequences of activities that work well together. These make ideal curriculum for Mozilla Clubs”

**Comment by hannahkane** [comment]
Grooming notes:
Implementation effort:
 * Seems fairly straightforward
 * Medium

**Comment by ldecoursy** [comment]
Here's the curriculum queue if helpful: http://mozilla.github.io/webmaker-curriculum/

**Comment by hannahkane** [comment]
Let's use "Read, Write, Participate" as a framework

**Comment by ldecoursy** [comment]
This is about refining the page, making the scaffolded Clubs curriculum more prominent, and making it more searchable in general. 

I think for now if we're going to use "Teaching Kits" to signify the best content for Clubs Curriculum, that we should change the titles for the following existing content on the page:
* Lo-Fi/No-Fi Activities
* Remove (Teaching Kit) from Become a Password Pro, Hack Your Notebook, and Minecraft a Flavor of Java

**Comment by anmechung** [comment]
+1
I was just looking for the clubs curriculum, and it was not so easy to find.

**Comment by ldecoursy** [comment]
Moving to June 5th since not covered last heartbeat

**Comment by hannahkane** [comment]
This is the least urgent design ticket in this heartbeat.

**Comment by hannahkane** [comment]
@sabrinang - I'm going to roll this into the next heartbeat, where it will probably continue to be a p2.

**Comment by hannahkane** [comment]
Closing pending conversations about curriculum dbase
