### ISSUE TITLE
revise site map 

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#832]
Revise the site map to reflect the current thinking.

Reference: https://docs.google.com/document/d/1Nw9iaocU7E41E6jKCWPh_InA0dMg-8AqBSVO3W6ycXA/edit#

**Comment by iamjessklein** [comment]
Okay, here's a first stab at the revision - you can see it on [Redpen here](https://redpen.io/vqc9ff283542648aa6)

![revised sitemap](https://cloud.githubusercontent.com/assets/535012/7380008/f3591094-edc6-11e4-8411-39048800842d.png)

**Comment by hannahkane** [comment]
Nice! Added some comments.

**Comment by iamjessklein** [comment]
Thanks @hannahkane - i'll make some edits based on your feedback. Is there any one else whose :eyes: should be on this sitemap?

**Comment by hannahkane** [comment]
@chrislarry33 @ldecoursy @thornet @amirad @LauraHilliger @adamlofting @HPaulJohnson - this site map should look familiar, since it's based on the doc we've all been working on. Let us know if something's not right!

**Comment by iamjessklein** [comment]
Great. [I updated it to incorporate edits.](https://redpen.io/vqc9ff283542648aa6) 

![revised sitemapv3](https://cloud.githubusercontent.com/assets/535012/7381831/e0def154-edd5-11e4-8b4d-84d4f1cd219b.png)

**Comment by chrislarry33** [comment]
wfm

**Comment by amirad** [comment]
Looks fine. Is each MP case study getting it's own page?

**Comment by hannahkane** [comment]
I think the MP case study solution is still TBD. It depends on the nature of the content we want to show and what we think the purpose is. I would argue that the goal is to help people feel empowered to host their own MP. Personally, I think three or five short, scannable blurbs with photos and bullet points about the event (e.g. "20 fifth graders, elementary school, did Hack Your School activity, 2 hours") would both give people a sense of what a Maker Party looks like and help to illustrate what  that there's no "right way" to do it.

Perhaps others would argue that there's a different purpose to showing the case studies, or that more in-depth case studies are required to achieve the empowerment goal? (Note: I definitely think longer, fully fleshed out case studies would be appropriate to include in the supplementary MP materials - i.e. the /events/resources page

**Comment by hannahkane** [comment]
@iamjessklein - can we close this ticket?

**Comment by ldecoursy** [comment]
Where did we land on where Hive fits here? Currently looks like it's only a link in the footer. Should it not be in the secondary nav under a headline like "connect your city?" 

Also noticed no link to Webmaker in the footer - assuming that will be covered by a link on the Tools page (and in Tabzilla) but just checking.

**Comment by iamjessklein** [comment]
+1 to Webmaker.
The reason that I have the Hive in the footer is that it directs to a page off the Teach site. Unless there's some sort of deeper integration, I am still voting for it to remain in the footer.

**Comment by ldecoursy** [comment]
My feeling is that having it in the footer makes Hive seem disconnected. Could an option be to have a landing page (under "connect your city" secondary nav) with basic information and a link to the Hive Global site for more?

**Comment by toolness** [comment]
@iamjessklein is the link to the new sitemap still going to be at http://invis.io/9G2DK7SR2 ? If not, can you file a PR that changes the link at https://github.com/mozilla/teach.webmaker.org/blob/develop/components/dev-ribbon.jsx#L27 so our dev ribbon modal is updated?

**Comment by hannahkane** [comment]
I think the "Connect Your City" secondary nav idea has merit, but I wonder about the purpose of it. Would we expect that this would be an entry point for someone starting a Hive in their city? That seems a little unrealistic to me. 

I wonder if a better strategy might be focusing on connecting people to existing Hives, in which case we might only show Hive content to people we've identified based on IP address as being near a Hive.

**Comment by chrislarry33** [comment]
I like this approach:

I wonder if a better strategy might be focusing on connecting people to existing Hives, in which case we might only show Hive content to people we've identified based on IP address as being near a Hive.

**Comment by hannahkane** [comment]
@ldecoursy, what do you think of that? I can file tickets for that work separately, and we can keep Hive in the footer in the meantime? (Thought: we could also add info about Hive to the /about page.)

**Comment by hannahkane** [comment]
I'm going to close this ticket. I think we can continue to address the Hive issue in upcoming tickets about IA.
