### ISSUE TITLE
Interim solution: add links to /clubs/curriculum from /activities

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#833]
We've agreed that the distinction between Clubs Curriculum and Teaching Activities is not important to users. A more permanent solution is being designed in #830.

In the meantime, let's make the following changes:

* Remove the link to /clubs/curriculum from the sub-menu in the Mozilla Web Clubs nav item
![screen shot 2015-04-28 at 9 07 43 am](https://cloud.githubusercontent.com/assets/8389648/7374267/1229110e-ed86-11e4-8f7d-b0621f85e9df.png)

* Instead, let's link to that curriculum by adding a new first item to the list of activities on /activities
  * Image: [the same one used on /clubs/curriculum]
  * Title: Web Literacy Basics (Teaching Kit) 
  * Level: Beginner
  * Developed by: Our seasoned educator community
  * Description: This six-part series helps learners become familiar with reading, writing and participating on the web. They'll discover the foundations of the web through production and collaboration. This is an ideal kit for Mozilla Clubs.

* Edit the content at the top of the /clubs/curriculum page to match this image:
![screen shot 2015-04-28 at 9 13 04 am](https://cloud.githubusercontent.com/assets/8389648/7374397/f4366b6e-ed86-11e4-92bd-fe16e86557a0.png)

* Remove the "What is Web Literacy" section from the bottom of the /clubs/curriculum page

* Change the path of the /clubs/curriculum page to /activities/web-lit-basics

**Comment by hannahkane** [comment]
@LauraHilliger and @thornet - does this match what we agreed upon? Please advise on specific copy choices I suggested above.

**Comment by LauraHilliger** [comment]
I would just change "This is an ideal series for Mozilla Web Clubs." to "This is an ideal kit for Mozilla Web Clubs." Otherwise sounds great! Thanks @hannahkane :+1:

**Comment by thornet** [comment]
Sounds good. Also, all instances of clubs should be called "Mozilla Clubs", i.e. without "web". :-)

**Comment by mmmavis** [comment]
@hannahkane 

> Image: [the same one used on /clubs/curriculum]

Is it this one? https://teach.mozilla.org/img/pages/clubs-curriculum/photo-clubs-curriculum.jpg

**Comment by hannahkane** [comment]
Yes, that image. Good call on changing the color theme. Thanks, @mmmavis. 

Also updated the description to say that we should change the url from /clubs/curriculum to /activities/web-lit-basics

**Comment by mmmavis** [comment]
@sabrinang do you have the original file of https://teach.mozilla.org/img/pages/clubs-curriculum/photo-clubs-curriculum.jpg (<--- this has been cropped).  We want to use it on /activities page and the size of the thumbnail should be 225(W) * 165(H).  (would also need the @2x file as well :smile: thanks)

**Comment by sabrinang** [comment]
The original file on flickr is here: https://www.flickr.com/photos/newyouthcity/14153664077/in/album-72157644495371568/

I helped crop it to that dimensions and retina you can find here: https://drive.google.com/drive/u/1/#folders/0B4Q8pzCpDS_eR2dpNnJXRTR1UVU/0B4Q8pzCpDS_eTExVZ25OLUNjTU0

![clubs-photo](https://cloud.githubusercontent.com/assets/2492510/7661787/a0de5594-fb0a-11e4-8408-da934dbae088.png)
