### ISSUE TITLE
Update Hive India to Hive Banglore on hivelearningnetworks.org

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#835]
This one's for @mmmavis!

Need to make the following update on hivelearningnetworks.org
* Change references from India to Bangalore on landing page and locations page under "Hive Learning Communities"
* Social media links should go to Twitter: @HiveBangalore and Facebook: https://www.facebook.com/HiveBangalore?fref=ts
* Mission: To transform the learning landscape by empowering youth and educators to enact Connected Learning through a diverse network of civic and cultural institutions. 
* Logo:  https://drive.google.com/file/d/0B2lvtScE69lRQW1RYTRjQk85cWxnRlB6eFdaX1MtM0JpZHhV/view?usp=sharing 
* Contacts: Vineel R. Pindi: Co-founder: pindivineelreddy@gmail.com, Galaxy Kadiyala: Co-founder: igalaxyk@gmail.com, Aarati Rao: Co-founder: aaratirao90@gmail.com
* Headshots: below

![aarati rao](https://cloud.githubusercontent.com/assets/4885898/7379918/4a595f9e-edc6-11e4-9624-e5cf62210079.jpg)
![galaxy](https://cloud.githubusercontent.com/assets/4885898/7379920/5133b1fc-edc6-11e4-8e55-a0fae4d71d7f.jpg)
![vineel photo mozfest](https://cloud.githubusercontent.com/assets/4885898/7379926/55e3dc54-edc6-11e4-9658-8d1350140c10.jpg)

cc @simonaramkisson

**Comment by hannahkane** [comment]
@mmmavis - let's prioritize this over some of the other tickets in your queue.

**Comment by mmmavis** [comment]
Hi @ldecoursy ,

> * Mission: To transform the learning landscape by empowering youth and educators to enact Connected Learning through a diverse network of civic and cultural institutions. 

Did you mean replacing
```
Hive India promotes experiential learning through the interests of young people and the creative use of digital media. Hive India, founded in September 2013, is an attempt to map and empower a community of educators and creative people who share a passion to innovate, evolve and change the learning landscape. 
```
with the text you mentioned about?

* Logo:  https://drive.google.com/file/d/0B2lvtScE69lRQW1RYTRjQk85cWxnRlB6eFdaX1MtM0JpZHhV/view?usp=sharing 
* Contacts: Vineel R. Pindi: Co-founder: pindivineelreddy@gmail.com, Galaxy Kadiyala: Co-founder: igalaxyk@gmail.com, Aarati Rao: Co-founder: aaratirao90@gmail.com

For websites, are we keeping `http://hive.mozillaindia.org/` and hiveindia.tumblr.com/` still?

**Comment by ldecoursy** [comment]
Hi @mmmavis,

Yes, please replace that statement, and you can remove those old Hive India links.  Thanks!

**Comment by mmmavis** [comment]
@ldecoursy could you verify that the name is matching to the corresponding headshot? 

![screen shot 2015-04-29 at 1 49 01 pm](https://cloud.githubusercontent.com/assets/2896608/7401131/8828342a-ee76-11e4-88cc-894b93682324.png)

Also, do you want me to include Galaxy's Twitter https://twitter.com/galaxyk (found via Google) as well? (I can't find Aarati's)

**Comment by ldecoursy** [comment]
You got it, and yes. Thanks @mmmavis!

**Comment by mmmavis** [comment]
done.

**Comment by ldecoursy** [comment]
Thanks @mmmavis!
