### ISSUE TITLE
[MIGRATED] Template a "Letter from the Future" for RC Guide

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#837]
We need to write an example letter to ourselves from 2018 on what Mozilla Clubs look like in our region. 

Describe what it looks like if Mozilla Clubs grew in your region. What inspires you about it? How would you have gotten there? What are the challenges?

**Comment by thornet** [comment]
cc @soapdog who's taking a first stab.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/160"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/160.
Please don't comment on it here.
