### ISSUE TITLE
[MIGRATED] Put the "Protecting Your Data" module on teachDOT

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#838]
We'll be testing in parallel, but as this module was already tested by @smithisgeneric and Hive Toronto and I've iterated since, the new "Protecting Your Data" module is ready for teachDOT. Needed modifications won't affect teachDOT.

cc/ @hannahkane @thornet @chrislarry33 @ldecoursy

# Protecting Your Data

Learners begin to take a critical look at their online privacy as they read, write and participate on the web while learning about Cookies, Trackers and Passwords. Through collaboration and production-centered activities, learners will know how to make secure passwords, track the trackers and understand how their data is being collected. 

The learning objectives underpinning each activity are informed by Mozilla's [Web Literacy Map](https://teach.mozilla.org/teach-like-mozilla/web-literacy/). Complete the activities in sequence, or mix and match for your learners. Need help? Visit our [discussion forum](http://discourse.webmaker.org/category/clubs) to get help and share your experience.

# Section 1: Reading the Web
## [IP Tracer](http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session01-ip.html)
**Understanding privacy**
Learners will explore internet protocol (IP) addresses and learn how it may be associated with themselves, a device, or a website. They will trace IP addresses and make a map.
image: http://mozilla.github.io/webmaker-curriculum/images/ip-tracer-badge.jpg

## [Bad Password Collage](http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session01-password-collage.html)
**Understanding security**
Test the strength of passwords using tools called password meters. Learners will look at annual lists of the top 25 worst passwords, compiled from more than 3.3 million leaked passwords during each year and make a collage of what to avoid when creating a password. 
image: http://www.technobuffalo.com/wp-content/uploads/2013/08/password-630x420.jpg

# Section 2: Writing the Web
## [Cookies and Third-Party Tracking](http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session02-lightbeam.html)
**Understanding privacy and open practices**
Using a free and open source tool called Mozilla Lightbeam, you can help visually show learners how cookies and third-party trackers are monitoring them as they perform their own everyday tasks on the web. Help learners manage and protect their data trail by having them race to see who can gather the most trackers on their team's Lightbeam graph.
image: https://www.mozilla.org/media/img/lightbeam/Lightbeam_Illustration7.png

## [Draw Secure Passwords](http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session02-secure-passwords.html)
**Understanding privacy and security**
Learn about pass-phrases, pronounceable and random passwords using generators. You will find out what you can do to create better passwords, and explore different types of passwords to learn about their pros and cons.

# Section 3: Participating on the Web
## [Data Trail Timeline](http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session03-datatrail.html)
**Understanding remixing, privacy**
Learners will create a timeline, video or slideshow remix to demonstrate how information gets collected by companies and other organizations throughout the course of a typical day. 
image: http://mozilla.github.io/webmaker-curriculum/images/datatrail-badge.jpg

## [Privacy Coach](http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session03-privacycoach.html)
**Understanding privacy and open practices**
Learners mentor their peers to enhance their privacy through their online or digital activities. Knowledge and expertise is shared through discussion or by remixing a response template to report on experiences.
image: http://mozilla.github.io/webmaker-curriculum/images/privacycoach-badge.jpg

Index page link (for easy access, not for public): http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/index.html

**Comment by ldecoursy** [comment]
@LauraHilliger Do you know if we have permission from the content authors/partners to feature this info on teach.mozilla.org and with the CC BY-SA license? Also think we need permissions from folks whose photos are featured. I'll forward you the language we used for the first round of content - let me know if/how I can be of help.

**Comment by LauraHilliger** [comment]
@ldecoursy content was produced by Hive Toronto and Mozilla. I will follow up with @smithisgeneric to make sure the OPC (funder) agrees. And I'll remix your text for the Mozilla Privacy team as well.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/161"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/161.
Please don't comment on it here.
