### ISSUE TITLE
Determine content for Events/Maker Party page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#84]
Goals:
* Identify content that we want to port over
* Re-frame in light of new year-round MP schedule
* Re-frame as a component of Mozilla Learning, as opposed to its own stand-alone site

Started draft here: https://docs.google.com/a/mozillafoundation.org/document/d/1hqK0lbCri_oRb0NKI7Y_3RE-kCxasLFDICyh_5OPkRU/edit#heading=h.wdu9u570h9

**Comment by hannahkane** [comment]
This one's on hold until after March 9. Meeting scheduled.

**Comment by hannahkane** [comment]
@amirad and I met today. She's working on a draft this week.

**Comment by amirad** [comment]
Draft is here https://docs.google.com/document/d/1yORrrsU4lN7itEC7BLTLHSR8JqRevppVPABxlmJqxXg/edit?usp=sharing 

Feedback coming in from @hannahkane @ldecoursy @LucyeoH by EOD

**Comment by hannahkane** [comment]
Great start! Added my comments to the doc. Would love some design-thinking from @iamjessklein and @vazquez if they have time, as well.

**Comment by hannahkane** [comment]
@amirad and I are good with where the copy is now. Will wait for a +1 from @ldecoursy before officially closing this ticket and opening the design phase.

**Comment by ldecoursy** [comment]
Just added a few small changes on the site copy, and tried to tighten up the resources stuff too. Lookin good!

**Comment by chrislarry33** [comment]
Can someone accept/clear out the edits and i will give final read

**Comment by amirad** [comment]
Thanks @ldecoursy 

@chrislarry33 cleaned it up. Have a look now.

**Comment by iamjessklein** [comment]
@amirad @ldecoursy - going to take a look at this today.

**Comment by hannahkane** [comment]
I'm going to close this ticket since it is @chrislarry33 approved. Will link to the doc from the corresponding Design ticket (#35) so we can start that work now.

**Comment by iamjessklein** [comment]
:+1:
