### ISSUE TITLE
Change instances of "Mozilla Web Clubs" to "Mozilla Clubs"

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#842]
Looks like I missed a few the last time around.
 * Main navigation - please change to "Mozilla Clubs"
 * /clubs/toolkit "Name and Brand Your Club" section - please replace the Naming paragraph with the following:  "We love seeing Mozilla Clubs pop up, yet we also welcome adaptations of the name to better represent your community or language. Example club names include: Toronto Mozilla Club Toronto, Xavier School Web All-Stars, St. Patricks Church Tech Squad or London Library Web Brigade. You can also embed your club in an existing program or brand."

**Comment by hannahkane** [comment]
Crap. This is my fault.

The Naming paragraph should read:

"We love seeing Mozilla Clubs pop up, yet we also welcome adaptations of the name to better represent your community or language. Example club names include: Toronto Mozilla Club, Xavier School Web All-Stars, St. Patrick's Church Tech Squad or London Library Web Brigade. You can also embed your club in an existing program or brand."  

(As it currently reads, there is an extra "Toronto" in the list of example names.)

**Comment by toolness** [comment]
Should we re-open this ticket then?

**Comment by hannahkane** [comment]
You know what, let's just push what we have and I'll file the world's tiniest bug as a follow-up. It it not even remotely close to a blocker.

**Comment by toolness** [comment]
Ah good idea!
