### ISSUE TITLE
No analytics for "safe mode" browsers

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#846]
I just realized that, as far as I know, there actually isn't any analytics being done for browsers that either have no JS or are running in [safe mode](https://github.com/mozilla/teach.webmaker.org/pull/579).

Things we can do to resolve this:

* For browsers running in safe mode, we actually *can* run JS, we just don't. So we can still load `react-ga` and initialize it and send some sort of event indicating that the user is viewing the site in safe mode.
* For browsers that have JS disabled entirely, we could either do some kind of S3-based logging, or if GA supports image-based tracking, we could use that.

Any thoughts on this @adamlofting?

**Comment by adamlofting** [comment]
If we can enable for safe mode that would be great.

For non-js browsers, that's fine. The analytics industry just accepts a missing % of traffic as the important thing we're looking for is trends and averages. Logs and image based tracking get so full of noise from bots that the effort to clean them up is rarely worth it (which was one of the reasons GA became so popular in the early days).

**Comment by toolness** [comment]
Ahh I didn't know that about logs/image based tracking! Thanks.
