### ISSUE TITLE
Build step doesn't clean up old files

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#848]
Our build step doesn't **delete** old files that were previously copied to `/dist`.   Maybe we can have a gulp task to handle that?

cc @toolness

**Comment by mmmavis** [comment]
This could be useful: https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md

**Comment by toolness** [comment]
yeah, i've been wanting a cleanup command for a while! want to submit a PR?

**Comment by mmmavis** [comment]
yup yup :neckbeard:

**Comment by toolness** [comment]
Hey mavis, I'm removing this ticket from the current milestone and adding it to grooming, since we should probably triage it first?
