### ISSUE TITLE
Create questionnaires for 3. Participating on the Web: Community Participation

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/teach.webmaker.org#85]
We've got the [Story of Us](https://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session03-storyofus.html) activity, so we now just need to build out:

* [x] [Pre-session questionnaire for Learners](http://goo.gl/forms/KeeMwn7pMJ)
* [x] [Post-session questionnaire for Learners](http://goo.gl/forms/8UWO57WswT)
* [x] [Pre-session questionnaire for Mentors](http://goo.gl/forms/kAPPY2NDET)
* [x] [Post-session questionnaire for Mentors](http://goo.gl/forms/gUaeABnBuh)

**Comment by dajbelshaw** [comment]
# Pre-session questionnaire for Learners

## Question 1
**Do you currently participate in online communities?**

* Yes
* No
* Unsure

## Question 2
**If you have participated in an online community, what kind of community was it?**

* Learning
* Gaming
* Social
* Other *(please specify)*

## Question 3
**If you have participated in an online community, which tools/apps have you used?**

* Chat *(e.g. WhatsApp, IRC)*
* Social networks *(e.g. Twitter, Facebook, LinkedIn)*
* Forums
* Other *(please specify)*

**Comment by dajbelshaw** [comment]
# Post-session questionnaire for Learners

## Question 1
**What kind tool did you use to reflect on your community participation?**

* Video
* Audio
* Text
* Unsure
* Other *(please specify)*

## Question 2
**Why did you decide to use that tool?**

* It was suggested to me
* I already knew about it
* I discovered it by searching
* Unsure

## Question 3
**Was the session fun? Was it interesting? What did you learn?**
*[paragraph text]*

**Comment by dajbelshaw** [comment]
# Pre-session questionnaire for Mentors

## Question 1
**Which of these skills do you think the activity will help teach?**

* Encouraging participation in web communities
* Using constructive criticism in a group or community setting
* Configuring settings within tools used by online communities
* Participating in both synchronous and asynchronous discussions
* Expressing opinions appropriately in web discussions
* Defining different terminology used within online communities

## Question 2
**How many of your learners do you feel have created a video and put it on the web before today?**

* Most
* Some
* A few
* None
* Unsure

## Question 3
**What kind of difficulties do you think your learners may encounter with this activity?**
*[paragraph text]*

**Comment by dajbelshaw** [comment]
# Post-session questionnaire for Mentors

## Question 1
**Which of the following skills did at least 70% of your learners demonstrate?**

* Use and share files in open, web-friendly formats when appropriate
* Participate in both synchronous and asynchronous discussions
* Choose a Web tool to use for a particular contribution

## Question 2
**Which part of the session do you think your learners enjoyed most? Why?**
*[paragraph text]*

## Question 3
**Were the activities effective ways to engage learners to understand Open Practices?**

* Highly agree
* Agree
* Neutral
* Disagree
* Highly disagree
* Unsure
* Not applicable/did not attempt 

## Contact details
Thanks! To complete the survey press 'Submit' below. You are welcome to remain anonymous, but sharing your name/email/location allows us to follow-up if needed.

* Name
* Email
* Location

**Comment by dajbelshaw** [comment]
Just need to transfer questions to respective Google Forms now. Doing it this way so we have a backup copy of the content...

**Comment by dajbelshaw** [comment]
OK, questions transferred and ready for review:

* [Pre-session questionnaire for Learners](http://goo.gl/forms/KeeMwn7pMJ)
* [Post-session questionnaire for Learners](http://goo.gl/forms/8UWO57WswT)
* [Pre-session questionnaire for Mentors](http://goo.gl/forms/kAPPY2NDET)
* [Post-session questionnaire for Mentors](http://goo.gl/forms/gUaeABnBuh)

**Comment by ldecoursy** [comment]
Thanks for these! Closing this since they're already done and in the field.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/36"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/36.
Please don't comment on it here.
