### ISSUE TITLE
Typo on /clubs/toolkit

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#853]
The Naming paragraph should read:

"We love seeing Mozilla Clubs pop up, yet we also welcome adaptations of the name to better represent your community or language. Example club names include: Toronto Mozilla Club, Xavier School Web All-Stars, St. Patrick's Church Tech Squad or London Library Web Brigade. You can also embed your club in an existing program or brand."

(As it currently reads, there is an extra "Toronto" in the list of example names.)

**Comment by mmmavis** [comment]
one more question @hannahkane :grimacing: 
is it
St. **Patricks** Church Tech Squad
or
St. **Patrick's** Church Tech Squad

**Comment by hannahkane** [comment]
St. Patrick's
