### ISSUE TITLE
Implement user profile and editor

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#857]
Pending #711

**Comment by hannahkane** [comment]
Also blocked on #585

**Comment by hannahkane** [comment]
Grooming notes:
 * Seems straightforward
 * consider gravatars for image upload if passes UX requirements
 * some of this is related to id.webmaker.org

Estimating: medium

**Comment by chrislarry33** [comment]
@hannahkane is this same work/thought as directory?

**Comment by hannahkane** [comment]
yes, this is part 1 of expanding the directory to all of the LN communities.

**Comment by hannahkane** [comment]
closing; out of date
