### ISSUE TITLE
Redesign Clubs page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#858]
The purposes of the re-design are to:
 * Better scaffold the starting of a Club by:
  * clarifying the value of starting a Club
  * building the confidence of the user to start their own Club
  * provide useful resources for getting started
 * Provide a pathway for users who are unsure whether starting a club is right for them
 * Provide a pathway for users who already have Clubs and want to access resources

Final copy here: https://etherpad.mozilla.org/clubssitemeeting

**Comment by hannahkane** [comment]
Grooming notes:
Effort: small

**Comment by chrislarry33** [comment]
Is this copy reviewed/editable somewhere?

**Comment by hannahkane** [comment]
Was discussed here: https://docs.google.com/document/d/1Nw9iaocU7E41E6jKCWPh_InA0dMg-8AqBSVO3W6ycXA/edit

**Comment by ldecoursy** [comment]
Note that @thornet @amirad working on new Clubs one-pager to help inform copy here.

**Comment by hannahkane** [comment]
Do we have an expected ETA on the one-pager?

**Comment by ldecoursy** [comment]
Maybe Tues? Still editing draft, then prob need eyes from Paul and @chrislarry33 signoff

**Comment by thornet** [comment]
Goal to have it signed off by @chrislarry33 this Wed. 

We can already do some re-structuring based on what's in the one-pager. @hannahkane: I could make a section in that doc to better draft out the update page for the site: https://docs.google.com/document/d/19yk3ZW1Mtjf3oUwspCiXPeNJ_zD63UYGpfEn3BdNxS0/edit#

**Comment by chrislarry33** [comment]
@amirad @thornet Can you both get together and get final clean draft together and ship to Paul and Kevin. More comments will be diminishing returns. Once they make edits lets revisit ASAP

**Comment by ldecoursy** [comment]
@hannahkane Thinking we should add this to the June 19th milestone? Updated fact sheet is here: http://mozilla.github.io/learning-networks/clubs/

**Comment by thornet** [comment]
Revised via Paul and Kevin (pulled from https://docs.google.com/document/d/19yk3ZW1Mtjf3oUwspCiXPeNJ_zD63UYGpfEn3BdNxS0/edit#)

[Headline]: Mozilla Clubs
[Definitional statement]: “Meet regularly as a group to learn the mechanics, culture and citizenship of the web together.”
[Value to user]: “Empower your community through purposeful making, reflective learning, and connection to peers around the world."
[Inspire confidence in user]: “What you get when you start a Mozilla Club in your community:
We’ll provide you with the Mozilla Club Manual, which guides you through every part of the process from getting your Club up and running, to keeping it going over time
You'll have early access to new activities to do with your learners
We’ll connect you with a Regional Coordinator who will be your go-to person for advice and guidance at any point
You’ll also be connected to our network of educators and activists, who are as passionate as you are about teaching web literacy and digital skills“
“See Mozilla Clubs in action” [images/links to three different Club case studies, showing diversity of settings, locations, ages, meeting schedules]
[Primary CTA]: “GET STARTED” - button workflow that triggers automatic email with manual + follow up email from regional coordinator [needs to be clear to the user what is going to happen - they’re going to give us their email address and we’ll send them the manual and a RC will be in touch.]
[Secondary CTA]: “Still not sure if Mozilla Clubs are right for you? Request a one-on-one chat with one of our Regional Coordinators.”
[Tertiary CTA]: Already have a Club? Map with button “ADD YOUR CLUB” “Find Teaching Kits for your Club”

**Comment by hannahkane** [comment]
As per conversation with @sabrinang and @thornet - let's try to narrow this down to one CTA that's focused on requesting a 1:1 conversation

**Comment by sabrinang** [comment]
**Note:** http://mozilla.github.io/learning-networks/clubs/ has most up to date info to refer to

**Comment by thornet** [comment]
Sharing a few examples of other "get in touch with us" sites: 
* https://www.youravon.com/REPSuite/become_a_rep.page#

**Comment by amirad** [comment]
The "know a representative" and FAQ at the bottom are what really call out to me in the Avon page. Things we can easily model and can make a big difference.

**Comment by sabrinang** [comment]
I have done some sketching and synthesized some notes on redpen: https://redpen.io/p/zo723c090907201b0d

WIP
![clubs information planning](https://cloud.githubusercontent.com/assets/2492510/8140997/211748da-1116-11e5-96a6-a360593400ed.png)

It is a rough (information dense) structure on how we can communicate our information and after chatting with @hannahkane I can incorporate the map and think about dividing the general club information from the information that focuses on getting people to start a club.

**Comment by hannahkane** [comment]
@thornet @ldecoursy @chrislarry33 - take a look at the above, but note that another iteration is coming soon, as @sabrinang mentioned. we should think about tightening up copy.

**Comment by ldecoursy** [comment]
Coming together, thanks @sabrinang! 

There is A LOT of info, wondering if we should think about what might go on a child page? Maybe the "who" section, where we could also list or profile the RCs? 

I think in this draft there are probably too many placeholders for icons, images, thumbnails.

**Comment by amirad** [comment]
Who we are and the Why seem misplaced and far down on that page. That's the type of info that lives on an "about page" or at the top of the page.

**Comment by hannahkane** [comment]
@sabrinang - hope you don't mind. Wanted to share your latest iteration: https://redpen.io/sw8e4f6ac8a6e32422 and your list of questions: https://teach.etherpad.mozilla.org/teachsite-clubspage

So that @ldecoursy @thornet @amirad can weigh in.

**Comment by hannahkane** [comment]
Added a bunch of copy and re-org suggestions to the etherpad. I was aiming for simplicity, so you'll see I'm suggesting we cut entire sections.

**Comment by sabrinang** [comment]
WIP redpen: https://redpen.io/yd22d96ae21ed1077f
WIP copy: https://teach.etherpad.mozilla.org/teachsite-clubspage

Please drop your feedback in the etherpad and use redpen as a rough visual reference.

**Comment by hannahkane** [comment]
Thanks, @sabrinang. I responded to one of the comments in the pad with suggested copy for a new section about the responsibilities of being a Club Captain. It starts on line 15 on the pad. Would love to see a new iteration with that worked in.

**Comment by hannahkane** [comment]
Blocked on #1086

**Comment by hannahkane** [comment]
No longer blocked. w00t!

Final copy here: https://etherpad.mozilla.org/clubssitemeeting

**Comment by hannahkane** [comment]
@thornet @ldecoursy - question that came up during stand-up today with @sabrinang and @mmmavis - do you expect the content in the google docs for the different use cases (e.g. "Your Afterschool Program," "Your Neighborhood Meetup", etc) will stay in google docs for long? Is there an intention to move them to github or somewhere else at some point?

Not a blocker or anything, just curious about the longer-term plan.

**Comment by thornet** [comment]
Hurray! @hannahkane yes, think we should move it to something more stable soon. I'll file a ticket for that. But we can move ahead with the copy as is!

**Comment by hannahkane** [comment]
Just saw Sabrina's wireframes, and want to suggest the following shortened copy for the "Why start" section, because it's not very scannable currently:
 * Your learners will make things that interest them. We learn best by making projects we care about, with peers who support and encourage us. 
 * You can use Mozilla's free and educator-tested curriculum. Our curriculum [link to /activities] is free to use and remix. 
 * Your learners will benefit from regular engagement. Literacy doesn’t happen overnight. Mozilla Clubs honors the fact that learning takes time. 
 * You can embed it in your existing program. You may already be serving a group of learners or running an educational offering. Mozilla Clubs can be a way to embed Web Literacy into your existing program. 
 * You'll develop your leadership skills. Improve your own leadership and organizing experience by becoming a Mozilla Club Captain. 

Would that work for you, @thornet?

**Comment by thornet** [comment]
Beautiful! Works for me.

**Comment by sabrinang** [comment]
![clubs mockup update](https://cloud.githubusercontent.com/assets/2492510/9285952/45cb99f4-42a0-11e5-9027-218f830982d7.png)
I updated the clubs page: https://redpen.io/egd04381c2b4f26f22

**Comment by sabrinang** [comment]
![clubs-page-intro-photo](https://cloud.githubusercontent.com/assets/2492510/9286281/f9523b32-42a4-11e5-893b-cceeb1da3dd8.png)

original: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eMmZ6QV8zQmZyaVk/view?usp=sharing
retina: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eVWEzWEJZNUlPM0E/view?usp=sharing

**Comment by thornet** [comment]
<3! Thanks, Sabrina. Looking amazing. Added a few small comments in the redpen.

**Comment by sabrinang** [comment]
Thanks for your feedback @thornet and I revised the redpen as well: https://redpen.io/egd04381c2b4f26f22

**Comment by hannahkane** [comment]
Looks great, @sabrinang. Added some questions to the redpen; might be more for @thornet to answer.

**Comment by thornet** [comment]
Thanks! Responded in the redpen. Also cc @amirad for her review.

**Comment by hannahkane** [comment]
@thornet - two other comments on the redpen for you. Thanks!

**Comment by hannahkane** [comment]
Also see #1174

**Comment by thornet** [comment]
@hannahkane sorry, redpen ate the comments I left yesterday! Added them again. 

cc @amirad for her review.

**Comment by hannahkane** [comment]
Thanks, @thornet. I'm worried we're not spelling out the difference between the two choices on that page well enough. e.g. the user needs to understand the benefits/drawbacks of clicking "MATCH ME" as well as the benefits/drawbacks of clicking "GET STARTED ON MY OWN."

Added a few comments to the redpen to highlight where we might want to make things more clear.

**Comment by sabrinang** [comment]
We can have the buttons side by side on larger devices and on mobile they will be 1 column:
![clubs-page-revised-desktop-081915](https://cloud.githubusercontent.com/assets/2492510/9367122/5c336220-4670-11e5-8673-a09c44863599.png)
![clubs-page-revised-mobile-081915](https://cloud.githubusercontent.com/assets/2492510/9367124/5e31cf3a-4670-11e5-938c-10b707ef73a9.png)

I updated the redpen (https://redpen.io/egd04381c2b4f26f22) but I think there is still some copy comment to be resolved (https://redpen.io/egd04381c2b4f26f22/2?showing_comment=1206232)

**Comment by amirad** [comment]
With these updates is the clubs toolkit tab being kept or removed? I think we've talked about both. In which case, if it is removed we will need messaging on people who click "I'm okay starting on my own" that mentions they will get access to resources, guides and material that can help their club hit the ground running. Maybe we can include info and a process to do that anyways when they click that button?

**Comment by hannahkane** [comment]
Can we find a time to talk about this? This feels pretty confusing to me now, so I'm not sure how to convey it well to users. I'll put something on the calendar.

**Comment by hannahkane** [comment]
Blocked on (me) not having a full understanding of the "Start on my own" flow.

**Comment by hannahkane** [comment]
Unblocked! Design is here: https://redpen.io/egd04381c2b4f26f22

Will file some follow-up tickets to account for new content coming soon (i.e. "Your First Month as a Club Captain")

**Comment by thornet** [comment]
Beautiful! Thanks, @hannahkane.

On Tue, Aug 25, 2015 at 12:24 AM, hannahkane <notifications@github.com>
wrote:

> Closed #858 <https://github.com/mozilla/teach.webmaker.org/issues/858>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/teach.webmaker.org/issues/858#event-391107622>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by soapdog** [comment]
:+1: beautiful work!
