### ISSUE TITLE
[MIGRATED] Determine which badges (if any) to issue in Q2

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#86]
See: https://github.com/mozilla/webmaker-curriculum/issues/140 for context

Reply here since other repo no longer active.

**Comment by ldecoursy** [comment]
My vote is to have a Club Leader badge  - question is could it cover a range of involvement from helping to develop the program, create curriculum, and actually run clubs, or do we need more nuance here.

**Comment by chrislarry33** [comment]
I think we keep
Hive Community Members
Webmaker Menor/Super Mentor
Web Lit Skill Sharer-er
Event Organizer

Add: Club Leader Badge

**Comment by hannahkane** [comment]
Add'l questions to consider:
 * Do we "retire" other badges, or just not offer them on the landing page? (that is, should someone who previously earned the Curriculum remixer badge still be able to access it? assuming yes.)
 * Do any of these badges come with add'l privileges? e.g. Should Super Mentors be able to approve certain other badge applications? 
 * Should the Event Organizer badge be system-issued based on adding an event to the database, or does it need to be human-verified?

**Comment by thornet** [comment]
Notes from chat with @chrislarry33: 

* For Webmaker Mentor & Super Mentor: consider an "almuni" badge. Then prompt to apply for / earn new badges.

* New badges: 
- "Frontline Educator" -- aka aligned practioner. Someone pledging or joining. 
- Club Leader
- Regional Coordinator
- Organizer

* Web Lit Badges: 
- Privacy ones great to start with.

**Comment by jgmac1106** [comment]
Do we have to look at the badging criteria again or just the current badges align with v 1.1 of the map? 

I don't think it's a major change at all, maybe a couple of words. We will need to split the design and accessibility badges plus combine web mechanics.

**Comment by hannahkane** [comment]
Excited for this!

A few questions:
 * How are you envisioning the alumni badges? Is it almost like a "currently inactive Mentor"? And then it can get re-activated?
 * Is the Web Lit Basics curriculum not associated with any badges?
 * Do we still want to have Event Host, Skill Sharer, and Curriculum Remixer badges?

**Comment by Saallen** [comment]
I would like to add a MozFest Volunteer badge to this list please -

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/37"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/37.
Please don't comment on it here.
