### ISSUE TITLE
Add Privacy module to site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#862]
The Privacy module should be the second item on the /activities page, just after the Web Literacy Basics module, and just above the Lo-fi/No-fi teaching kit.

Copy/images here: https://github.com/mozilla/learning-networks/issues/161

---

**Updates (by Mavis)**
This ticket includes 2 tasks:
- [ ] create a "Protecting Your Data" page on Teach site
- [ ] on the /activities page, add that module as the 2nd item on the list (in between Web Literacy Basics and Lo-fi/No-fi teaching Kit)

**Comment by mmmavis** [comment]
This ticket includes 2 tasks:
- [ ] create a "Protecting Your Data" page on Teach site
- [ ] on the /activities page, add that module as the 2nd item on the list (in between Web Literacy Basics and Lo-fi/No-fi teaching Kit)

**Comment by ldecoursy** [comment]
Dependent on #938

**Comment by mmmavis** [comment]
@hannahkane what's the URL we want to have to this page?

**Comment by hannahkane** [comment]
How about /activities/protecting-your-data?

**Comment by mmmavis** [comment]
yea that works for me

**Comment by mmmavis** [comment]
actual, I can't decide between `/activities/protecting-your-data` and `/activities/protect-your-data`

**Comment by hannahkane** [comment]
Shorter one is fine, I think. Good call.

**Comment by mmmavis** [comment]
![screen shot 2015-06-01 at 6 41 23 pm](https://cloud.githubusercontent.com/assets/2896608/7926931/d99c6a34-088d-11e5-8418-5f40c5f56739.png)

@hannahkane could please you help get copy for those ??? fields in the screencap?

**Comment by ldecoursy** [comment]
How's this?

Level = Beginner
Developed By = Hive Toronto in partnership with the Office of the Privacy Commissioner of Canada, Mozilla Privacy 
These six, production-centered activities engage learners in thinking critically about online privacy by creating secure passwords, understanding how and where their data is being collected, and more. This is an ideal kit for Mozilla Clubs,

**Comment by hannahkane** [comment]
+1

**Comment by anmechung** [comment]
+1 and also wonder if all will know what production-centered means? same as project-based activity?

**Comment by ldecoursy** [comment]
Can change to "six hands-on activities"

**Comment by mmmavis** [comment]
(sorry I'm having some ESL problem here :stuck_out_tongue_closed_eyes: )

@ldecoursy 

> Developed By = Hive Toronto in partnership with the Office of the Privacy Commissioner of Canada, Mozilla Privacy 

The above are 2 groups of people or just 1?  Also, would you like the text to be hyperlinked?

**Comment by ldecoursy** [comment]
Hive Toronto hivetoronto.org
Office of Privacy Commissioner of Canada https://www.priv.gc.ca/index_e.asp
Mozilla Privacy https://www.mozilla.org/en-US/privacy/

Hive Toronto in partnership with the Office of the Privacy Commissioner of Canada, and Mozilla Privacy
