### ISSUE TITLE
Redirect Webmaker legacy tool links to teach.mozilla.org

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#864]
In an effort to avoid 404 links from third-party sites that currently link to the following Webmaker tool pages, it would be great to redirect them to their new homes on teach.mozilla.org when we know exactly where those will be :)

* https://webmaker.org/en-US/tools
* https://webmaker.org/en-US/goggles
* https://thimble.webmaker.org/

cc @HPaulJohnson

**Comment by hannahkane** [comment]
no longer applicable
