### ISSUE TITLE
make it obvious when an email is coming from staging

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#865]
e.g. "new club" email notification

**Comment by toolness** [comment]
Ok, I've changed the "from" email to start with the word "STAGING" so it's more obvious:

![screen shot 2015-05-06 at 7 05 19 am](https://cloud.githubusercontent.com/assets/124687/7492099/554054c8-f3be-11e4-9c74-fbec367f1cf2.png)

Closing this now, but feel free to re-open if you don't think it's obvious enough.

**Comment by hannahkane** [comment]
Perfect. Thanks!
