### ISSUE TITLE
Update links for Teaching Activity: Image Seeking for Fantastic Visual Metaphors Image Seeking for Fantastic Visual Metaphors

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#867]
Can we please update the following:

* The activity should link to : https://cogdog.makes.org/thimble/LTEyMjQ4NjUyOA==/imageseeking-for-fantastic-visual-metaphors (it's currently linking to an outdated version of that activity)
* Link to author, Alan Levine, should go to :  http://cogdog.info  (instead of his Twitter handle)

Thanks!

**Comment by hannahkane** [comment]
@toolness - can I assign this one to you to do this week?

**Comment by hannahkane** [comment]
@mmmavis - any chance you could do this one today since @toolness is out?

**Comment by mmmavis** [comment]
@hannahkane yup yup. done!

**Comment by ldecoursy** [comment]
Thanks!
