### ISSUE TITLE
Update MP collateral (MAY 15 DEADLINE)

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#869]
See https://github.com/mozilla/learning-networks/issues/163

Each of the below needs new photographs, and the Save the Date needs new dates. July 15-31, 2015.

![join maker party](https://cloud.githubusercontent.com/assets/10170768/7519984/92a2b15a-f4b1-11e4-8a39-560d159299c6.jpg)

![maker party](https://cloud.githubusercontent.com/assets/10170768/7519987/99060c54-f4b1-11e4-9cdc-0ebab9f375da.png)

![save the date](https://cloud.githubusercontent.com/assets/10170768/7519997/a4c527dc-f4b1-11e4-983a-16d6b6705dce.png)

**Comment by hannahkane** [comment]
@ldecoursy - is there a more specific deadline for this other than the end of the May 22nd heartbeat?

**Comment by ldecoursy** [comment]
Yes, if we can shoot for May 15th that would be ideal. Blog post is slated to go up on May 18th, as well as well as @amirad announcing on the project call. 

Official Save the Date external email and social is slated to begin later that week (May 21).

**Comment by hannahkane** [comment]
let's skew a little older on the photos, and a more active photo

**Comment by sabrinang** [comment]
I've swapped some colours in the blocks and been digging through https://www.flickr.com/photos/mozilladrumbeat/ to look for photos:

![makerparty_savethedatesocial2015](https://cloud.githubusercontent.com/assets/2492510/7576790/7fb05bfe-f7f6-11e4-8f00-b1d0b2c7bf24.png)
https://www.flickr.com/photos/mozilladrumbeat/15031214510/in/dateposted/

![makerparty_social2015](https://cloud.githubusercontent.com/assets/2492510/7576789/7fae8068-f7f6-11e4-81e9-a54a3d14eaa4.png)
https://www.flickr.com/photos/mozilladrumbeat/15063360388/in/album-72157647305286970/

I haven't found many great photos so far but if you found some you want included please comment photo links!

**Comment by amirad** [comment]
These look good. I like the 'older' pictures. Hive NYC flickr has a bunch of great photo albums too
https://www.flickr.com/photos/newyouthcity/sets/72157644495371568
https://www.flickr.com/photos/newyouthcity/sets/72157645434988967
https://www.flickr.com/photos/newyouthcity/sets/72157646643449214

**Comment by ldecoursy** [comment]
These look good to me too. Can we get input from @KevZawacki and @HPaulJohnson on the copy? I actually think since it's a two-week campaign we should put the date on the 2nd graphic too, and maybe URL for teach.mozilla.org?

Suggestion for Save the Date: Maker Party is our annual campaign about teaching others how to read, write and participate on the web! 

Sign up to receive your XXXX (free event kit and certificate)?

**Comment by KevZawacki** [comment]
@ldecoursy, agreed — we should add the end date (31), too. And can we add the month (July) above the calendar graphics?

For copy, minor tweak: Maker Party is our annual campaign that teaches how to read, write and participate on the web!

**Comment by sabrinang** [comment]
updated to include: teach.mozilla.org & July 15-31, 2015 date
![makerparty_socialmediaimages](https://cloud.githubusercontent.com/assets/2492510/7643995/9cc3afac-fa53-11e4-92ae-9e62bdb9e152.png)
![makerparty_socialmediaimages1](https://cloud.githubusercontent.com/assets/2492510/7643998/9cc84f9e-fa53-11e4-9210-24ddd85dcbdf.png)
![makerparty_socialmediaimages2](https://cloud.githubusercontent.com/assets/2492510/7643996/9cc6d132-fa53-11e4-8f27-cda5596ebb2f.png)
![makerparty_socialmediaimages4](https://cloud.githubusercontent.com/assets/2492510/7643997/9cc78afa-fa53-11e4-93b8-c0a1bf62a0c2.png)

**Comment by amirad** [comment]
Thanks @sabrinang 
@KevZawacki we can update images for blog post and social!

**Comment by KevZawacki** [comment]
On it!
Awesome designs, @sabrinang

**Comment by ldecoursy** [comment]
Closing this ticket - thanks again @sabrinang!

**Comment by amirad** [comment]
@sabrinang - Firefox team just told us they need specific sizes to share these. Any way we can accommodate? cc: @KevZawacki 

Facebook (FB) 1200x627 px. Some graphics need to have <20% text to be boosted. 
Twitter (TW) graphics 1760x800 px.

**Comment by sabrinang** [comment]
@amirad Can you explain more what <20% text is? I am not quite sure what % are the current MP social share graphics are at to compare. If there is copy you suggest that would be really helpful.

**Comment by amirad** [comment]
I'm not sure @KevZawacki think you can bug MJ while you're with her right now to see what that means

**Comment by KevZawacki** [comment]
Sure, on it.

**Comment by hannahkane** [comment]
@amirad - should we change the deadline on this ticket, since May 15th has passed and we're waiting on an answer?

**Comment by amirad** [comment]
Sure, we can close it and make a new one for MoCo specific collateral.

**Comment by KevZawacki** [comment]
@hannahkane @amirad @sabrinang 

MJ says to disregard the "<20% text" ask. So, we just need graphics at:

Facebook 1200x627 px. 
Twitter graphics 1760x800 px.

**Comment by sabrinang** [comment]
I made 3 versions (exported at 1200x627px & 1760x800px each)
![maker-party_facebook-socialshare2015_1200x627](https://cloud.githubusercontent.com/assets/2492510/7997432/04043c38-0ae2-11e5-996c-6153f1047e08.png)
![maker-party_twitter-socialshare2015_1760x800](https://cloud.githubusercontent.com/assets/2492510/7997436/16a540b2-0ae2-11e5-8e4a-4913b06d9a72.png)
![maker-party_facebook-socialshare2015-alt2_1200x627](https://cloud.githubusercontent.com/assets/2492510/7997438/19acba06-0ae2-11e5-8401-9019ded6cbe3.png)
![maker-party_twitter-socialshare2015-alt2_1760x800](https://cloud.githubusercontent.com/assets/2492510/7997441/1cb6fe6e-0ae2-11e5-9f49-f186bf4b3a30.png)
![maker-party_facebook-socialshare2015-alt3_1200x627](https://cloud.githubusercontent.com/assets/2492510/7997443/207622e6-0ae2-11e5-9493-11aa873b357f.png)
![maker-party_twitter-socialshare2015-alt3_1760x800](https://cloud.githubusercontent.com/assets/2492510/7997445/23b70c90-0ae2-11e5-9a27-2f28e700ee15.png)

**Comment by KevZawacki** [comment]
Thank you, @sabrinang. @amirad, I'll share with MJ.

**Comment by amirad** [comment]
Beauty. Thanks @sabrinang @KevZawacki
