### ISSUE TITLE
Strange workflow to add a password to an existing account 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/teach.webmaker.org#870]
1. Have an old account - not remember the password
2. Request to set one (the system is telling you have a user without pass) 
3. I have receive a mail "Webmaker Login Request" with: Sihn in, Sing in & remeber, or copy this in webmaker
4. Open link from sign in - put the pass give in the mail - nothing works
5. Go back to teach.m.o - retake the process to request a password
6. I have receive a mail "Set up your new Webmaker account password" and I was able to set a new password

I think people will get frustrated or quit at step 4.

**Comment by ioana-chiorean** [comment]
Also stating "Or, copy this key into Webmaker: " is a bit confusing.. as u might not know where to go.

**Comment by hannahkane** [comment]
Opening in different repo: https://github.com/mozilla/id.webmaker.org/issues/290

**Comment by ioana-chiorean** [comment]
Sorry for the wrong submission - I did not realize is in other one!

**Comment by hannahkane** [comment]
No worries! Thanks for reporting these issues.
