### ISSUE TITLE
Improve messages at wrong/invalid password

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/teach.webmaker.org#871]
Trying to set a new password I got messages like:
* invalid password
* Something went wrong. Try again

I think we should add some more context specially at Invalid one like: the pass is to long, to short, etc

![screenshot from 2015-05-07 20 28 33](https://cloud.githubusercontent.com/assets/1391451/7521894/0c11d8a2-f4fa-11e4-9dd8-94568f928d99.png)
![screenshot from 2015-05-07 20 28 17](https://cloud.githubusercontent.com/assets/1391451/7521895/0c11f5e4-f4fa-11e4-931c-aef18b14a371.png)

**Comment by hannahkane** [comment]
Opened this in a new repo: https://github.com/mozilla/id.webmaker.org/issues/288
