### ISSUE TITLE
Set the Continue button disabled when problem with paawords 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/teach.webmaker.org#872]
![screenshot from 2015-05-07 20 28 33](https://cloud.githubusercontent.com/assets/1391451/7521902/246ae164-f4fa-11e4-8a8e-60b6c458bf7f.png)
![screenshot from 2015-05-07 20 28 17](https://cloud.githubusercontent.com/assets/1391451/7521903/248d2eae-f4fa-11e4-8edb-9f2cbd996748.png)

Here - I was not sure if entering a new pass will delete the pink message , so it might be helpful to have a disable state for he button so u know you need to enter a new pass

**Comment by hannahkane** [comment]
Opening this issue in a different repo, and closing here. Thanks, Ioana!
