### ISSUE TITLE
No actionable thing to do after you reset the password/request one

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/teach.webmaker.org#873]
![screen shot 2015-05-07 at 20 48 27](https://cloud.githubusercontent.com/assets/1391451/7521943/7fd966d8-f4fa-11e4-89f9-ceed06058d06.png)

After you request a new password - there is no link to tap to continue with:
* browsing the website
* go to sign in page

In the above screenshot there are three places that might have links attached 
* logo -> go back to the teach.m.o
* letter icon -> maybe same as above?
* Need an account - sign up -> should have also sign-in

**Comment by hannahkane** [comment]
Opened in different repo: https://github.com/mozilla/id.webmaker.org/issues/289
