### ISSUE TITLE
Webmaker blog - add subscription form

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#876]
Add subscription form(a feature of [Jetpack plugin](https://wordpress.org/plugins/jetpack/)).  See reference [here](https://github.com/mozilla/teach.webmaker.org/issues/604#issuecomment-100041527).

**Comment by mmmavis** [comment]
blocked by https://github.com/MozillaFoundation/mofo-devops/issues/56

**Comment by mmmavis** [comment]
Sigh, encountered another problem with WordPress  :confounded: :confounded: :confounded: :confounded: :confounded: 

As I mentioned to you today @jbuck , this is the error message I got

![screen shot 2015-05-19 at 10 25 28 am](https://cloud.githubusercontent.com/assets/2896608/7716411/ac863c56-fe46-11e4-9d2b-4058906b07bf.png)

I googled and this seems to be a solution: http://usefulmix.com/wordpress-nginx-varnish-jetpack-xml_rpc-32700-glitch-fix/.  Could you take a look at this when you get a chance?  Or maybe point me to where `nginx` dir is and I will try to fix this myself :mask:

**Comment by jbuck** [comment]
@mmmavis /etc/nginx

**Comment by mmmavis** [comment]
Oh dear, this is finally done.  :sob:

**Comment by toolness** [comment]
Hoooray!! Thanks jbuck and mavis!
