### ISSUE TITLE
Update clubs toolkit to include legalese on financial contributions 

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#881]
On this page: https://teach.mozilla.org/clubs/toolkit/ in the Fundraise section, could we add this as a final bullet? The text is from the legal team:

"Many jurisdictions require you to register if you solicit contributions from people or organizations in their borders for charitable or educational activities and raise more than a threshold amount; some jurisdictions require registration of clubs and associations in other circumstances as well.  Check the rules applicable to you before proceeding."

**Comment by hannahkane** [comment]
Putting this in the current heartbeat. @mmmavis or @toolness - can either of you do this one?

**Comment by mmmavis** [comment]
Just checking to see if we want to start with a short italics highlighted sentence.  Seems like all the bullet points are following that convention.

**Comment by hannahkane** [comment]
How about just the word "Registration" in italics? Also, I think this should be the fourth bullet point, so that "More ideas!" is still the last one.

**Comment by mmmavis** [comment]
![screen shot 2015-05-12 at 10 42 13 pm](https://cloud.githubusercontent.com/assets/2896608/7604510/93cb5db6-f8f8-11e4-8fe5-322db685f9db.png)

Sounds good, thanks @hannahkane
