### ISSUE TITLE
Have to click section headers twice to open 

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#883]
On /clubs/toolkit the sections only open if you click them twice. Weird!

**Comment by jgmac1106** [comment]
The same thing kind of happens on the web literacy map page. If you have
one header expanded and click on another header/menu the first click closes
the open menu and then you have to click again to open the new menu/header

**Comment by toolness** [comment]
Hmm, I think that the regression occurred because of https://github.com/mozilla/teach.webmaker.org/pull/877#discussion_r29916167, where we switched from using a mousedown handler to a click handler.

**Comment by toolness** [comment]
@jgmac1106 - yep, that makes sense that it also happens on the weblit map page, as both pages use the same Expander component that's causing the bug. Thanks for reporting it!
