### ISSUE TITLE
Embedded Flickr thumbnail images on event resources page are large

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#886]
On my Windows PC, the tests were timing out because PhantomJS was taking a really long time to load everything on the events page. I discovered that it was at least partly because the Flickr images on that page are reasonably large. For that immediate problem I committed 8ce6d153694319e751ca3bd45debf4c946f55c5c as a workaround, but I think that we should consider using smaller images there: two of those three Flickr images are almost 200k, while the third is 80k. The images are also much higher-resolution than we need, as they're only displayed as thumbnails. We might want to use `srcset` to load higher-resolution images for retina displays.

I'm also wondering if we should be using `staticflickr.com` to host those images, or if we should be hosting them ourselves.

**Comment by toolness** [comment]
According to [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fteach.mozilla.org%2Fevents%2F&tab=mobile):

* Compressing and resizing https://c3.staticflickr.com/3/2915/14592256638_55ec5cf36b_b.jpg could save 202.2KiB (99% reduction).
* Compressing and resizing https://c4.staticflickr.com/4/3905/14715964794_a9fa75002c_c.jpg could save 196.8KiB (99% reduction).
* Compressing and resizing https://c2.staticflickr.com/6/5587/15213220651_9055dffbe6.jpg could save 86.1KiB (98% reduction).

**Comment by ldecoursy** [comment]
Per #843, we're going to remove the current Flickr thumbnails from the /events page - they'll be replaced by images for three case studies.

**Comment by mmmavis** [comment]
(closing this ticket)
