### ISSUE TITLE
Design "Tools" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#887]
Copy is here: https://teach.etherpad.mozilla.org/toolscopy

**Comment by sabrinang** [comment]
Initial mockup idea of Tools page under /teach-like-mozilla (green layout)
![teach like mozilla tools idea](https://cloud.githubusercontent.com/assets/2492510/7803450/ecade690-0304-11e5-9653-217491bb3a08.png)

**Comment by ldecoursy** [comment]
This looks great to me! 

Maybe we can use one of @LauraReynal's photos from a recent research trip at the top (instead of an icon)?

@hannahkane @chrislarry33 @HPaulJohnson Want to review (copy and layout)?

**Comment by sabrinang** [comment]
**Photo Option**
![toolstoteach-photo](https://cloud.githubusercontent.com/assets/2492510/7830902/3c23ab5e-0406-11e5-81be-9496ab1497f5.png)
(original) https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eSHRJYnJaYnhYVjQ/view?usp=sharing
(retina) https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ecm1zYWFEaFc0RzA/view?usp=sharing

![tools to teach mockup](https://cloud.githubusercontent.com/assets/2492510/7830839/caaa07d4-0405-11e5-995f-694568da1a6c.png)

**Comment by ldecoursy** [comment]
In general we should be adding more photos that are less North American-focused. How about the group shot from page 46 here: https://webmaker-dist.s3.amazonaws.com/reports/kenya.pdf or page 35 here: https://webmaker-dist.s3.amazonaws.com/reports/india.pdf

**Comment by sabrinang** [comment]
**More photo options**

![toolsgroup-photo](https://cloud.githubusercontent.com/assets/2492510/7844632/b42c25d0-0466-11e5-8f7b-36a449063561.png)
![screen shot 2015-05-27 at 11 37 25 am](https://cloud.githubusercontent.com/assets/2492510/7844635/ba121b4e-0466-11e5-8408-4d112f3f318d.png)
(original) https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eUmNON24tX2ZTQlU/view?usp=sharing
(retina) https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ebmJmN05SYjB6OWM/view?usp=sharing

![toolsboy-photo](https://cloud.githubusercontent.com/assets/2492510/7844633/b468c83c-0466-11e5-97cd-aefbecda1ad2.png)
![screen shot 2015-05-27 at 11 40 50 am](https://cloud.githubusercontent.com/assets/2492510/7844639/beeb7f3e-0466-11e5-9bc0-c49aa56587a2.png)
(original) https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ea3IwRXFrc0dhY0E/view?usp=sharing
(retina) https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eVEpIdTVFODBIYXM/view?usp=sharing

**Comment by flukeout** [comment]
I think the photo should be ditched or treated differently on this page. It feels too similar to the tool icons below, which I'm guessing are clickable links to the respective tool.

**Comment by cassiemc** [comment]
Tending to agree with @flukeout maybe a color behind the banner could help separate the functionality, though. Would love some thoughts from @lovegushwa on the actual photo treatment, we were just geeking out about Lightroom. These seem a bit yellow and grainy to me but maybe just the export?

**Comment by hannahkane** [comment]
+1 to no photo.

The webmaker description seems to be missing a word or two at the end.

Also, I realize I helped draft this copy, but looking at it now, I don't think we're doing enough to distinguish between the three tools. If I wasn't familiar with them, I don't think I'd understand what the difference is between them. Not sure how to solve for that—maybe offer specific audiences ("great for beginners"), or situations where each tool is particularly appropriate, or perhaps even just a plain-language description to supplement the not-totally-intuitive product names (e.g. X-Ray Goggles—a code inspector, Thimble—a code editor, Webmaker—an app builder).

**Comment by lovegushwa** [comment]
@cassiemc what about something like this? I think playing up green color creates a bit more association with the overarching "teach like Mozilla" category.  
![tools-image-9](https://cloud.githubusercontent.com/assets/12228435/7848380/1d172fea-0480-11e5-9ae6-77b72403418a.jpg)

You could also change the intro copy to green (I'm not sure if this would be a problematic or inconsistent style.)

![tools-image-10](https://cloud.githubusercontent.com/assets/12228435/7848435/9c7a2fa8-0480-11e5-8608-b67ade64fbe7.jpg)

**Comment by ldecoursy** [comment]
"literacies" is the final word that's missing in the Webmaker description. 

I think the Thimble description is clear. 

Could change Goggles to:  This code inspector lets you view and remix the code of your favorite web pages. Swap images, change text, delete ads, and more — then publish your remix on the Web.

@HPaulJohnson is there a description for Webmaker that specifies it currently as a mobile web content, or app, developer? Agree we could get more specific in this description - we can always update it when desktop launches.

**Comment by hannahkane** [comment]
+1 to Goggles copy change.

@HPaulJohnson - ping re: Webmaker description question above.

**Comment by HPaulJohnson** [comment]
Thanks for the ping. Here's some suggested text, though I'd like @KevZawacki to review and make any final edits he thinks are necessary: 

Webmaker is a free, open source tool that is practical, fun-to-use and a key building block for understanding the Web. It allows users to create, discover and share content in their local language, on their mobile device, giving people at any skills level the opportunity to elevate their skills for Web user to Web maker.

**Comment by KevZawacki** [comment]
+1 to Paul's copy. Just some small tweaks to the final sentence. So:

Webmaker is a free, open source tool that is practical, fun-to-use and a key building block for understanding the Web. It allows users to create, discover and share content in their local language and on their mobile device, giving people at any skill level the opportunity to evolve from Web user to Web maker.

**Comment by sabrinang** [comment]
Trying line art for header image to match our other subpages on the teach site (like [clubs toolkit](https://teach.mozilla.org/clubs/toolkit/) & [web literacy](https://teach.mozilla.org/teach-like-mozilla/web-literacy/) )
3-column layout
![teach like mozilla - tools layout 1](https://cloud.githubusercontent.com/assets/2492510/7946018/2855bf72-0929-11e5-9777-1990230fdab0.png)
highlight tool & 2 column layout
![teach like mozilla - tools layout 2](https://cloud.githubusercontent.com/assets/2492510/7946019/29664198-0929-11e5-9fbf-06660da14d73.png)

Redpen: https://redpen.io/p/wxe69cd1b2a3116a5c

**Comment by hannahkane** [comment]
@HPaulJohnson @KevZawacki - What do you think of this revision to make it match the length and second person voice of the other two descriptions?:

Webmaker is a free, open source tool that lets you create, discover and share content in your local language on your mobile device. It gives you opportunity to elevate your skills from Web user to Web maker.

**Comment by HPaulJohnson** [comment]
Works for me.

**Comment by KevZawacki** [comment]
+1

**Comment by sabrinang** [comment]
![teach like mozilla - tools layout 1 updated](https://cloud.githubusercontent.com/assets/2492510/7950239/98150854-094c-11e5-9d87-03f411e1b9d2.png)
updated [redpen](https://redpen.io/hn88c5775817cf7d60) 
- fixed title alignment
- adjusted icon composition and stroke width
- updated webmaker copy

**Comment by hannahkane** [comment]
+1. Looks great!

**Comment by sabrinang** [comment]
updated [redpen](https://redpen.io/hn88c5775817cf7d60)
![teach like mozilla tools updated 060415](https://cloud.githubusercontent.com/assets/2492510/7989681/1336b1fa-0aa0-11e5-97c3-ec67b9accec1.png)
updated:
- new shorter copy for tools
- grid alignment
- logo scale
- sample activity text treatment
- added icon for teaching activity section
- included footer cta icon links

**Comment by sabrinang** [comment]
Updated [redpen](https://redpen.io/hn88c5775817cf7d60)
![teach like mozilla tools - updated 3 col](https://cloud.githubusercontent.com/assets/2492510/7994542/017f35ea-0ac3-11e5-8fbb-59696e7284f3.png)
Updated: 
- spacing
- sample activity text treatment
- remove teaching activity icon

@ldecoursy - can you clarify your redpen comment: 
> "Prefer the above for web literacy"

Are you referring to changing the teaching activities copy? and not having web literacy as a icon cta?

Alternative iteration on [redpen](https://redpen.io/gyd72e008f741b4a02)
![teach like mozilla tools updated 2 col](https://cloud.githubusercontent.com/assets/2492510/7994603/860135e8-0ac3-11e5-8c01-64966854a506.png)
Changes: 
- 2-column design (if webmaker is not ready to be on the page)
- h1 aligned with intro copy

**Comment by hannahkane** [comment]
@ldecoursy - can you give the OK on this? Want to close this ticket, and implement this heartbeat.

**Comment by ldecoursy** [comment]
OK with me - sorry, above I was saying I liked the science-y icon (that was with the original design by the teaching activities link) instead of the brain, but now realizing the brain is consistent with what's already on the site ;)

**Comment by hannahkane** [comment]
Yay!

**Comment by mmmavis** [comment]
@sabrinang mind attaching files here? :hamster: :hamster: :hamster:

**Comment by sabrinang** [comment]
.svg icon: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eZVNQZUpnREFNaU0/view?usp=sharing
tool logos: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_edjhMQWxUSFlYVE0&usp=sharing

also - I iterated on the sample activity treatment ([redpens](https://redpen.io/p/wxe69cd1b2a3116a5c)):
![tools-page---sample-activitiy-iteration](https://cloud.githubusercontent.com/assets/2492510/8047974/e77590fe-0e00-11e5-8258-bf0dbd1f3e96.png)

**Comment by sabrinang** [comment]
![icon-horizontal-divider](https://cloud.githubusercontent.com/assets/2492510/8071618/d55ffff6-0ec0-11e5-99b3-ba6486b47788.png)
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eVlBVSmlSbDNvTWs/view?usp=sharing

**Comment by mmmavis** [comment]
@hannahkane @sabrinang 

I'm a little confused - which is the final mockup we are going with?

**Comment by sabrinang** [comment]
I got some design review feedback today on https://redpen.io/bu9ded39ad3b05ea46 - I just need to tweak some text styles in the sample activity section and should get the R+; I will update this for tmrw

**Comment by mmmavis** [comment]
k, I'll reopen this ticket. Please close it when the design has been finalized.  Thannnnksssss

**Comment by sabrinang** [comment]
![teach like mozilla - tools larger text](https://cloud.githubusercontent.com/assets/2492510/8089737/a208405c-0f5e-11e5-884a-dd4f2a02a1b9.png)
updated redpen: https://redpen.io/bu9ded39ad3b05ea46
- adjusted text alignment
- adjust text size

@cassiemc R?

**Comment by cassiemc** [comment]
R+

**Comment by hannahkane** [comment]
Closing this ticket and unblocking the implementation ticket.

**Comment by mmmavis** [comment]
@sabrinang could you also attach the .ai file so I can inspect the font sizes?

**Comment by sabrinang** [comment]
This was a .sketch file you can find here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eRnRyamZPemIyVTQ/view?usp=sharing
