### ISSUE TITLE
Map UK GCSE Curriculum to Webmaker Club curriculum (and Web Literacy Map v1.1)

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/teach.webmaker.org#89]
_From @mickfuzz on January 21, 2015 18:0_

There's a page on the wiki. 

https://github.com/mozilla/webmaker-curriculum/wiki/Mapping-Webmaker-to-GCSE-Computing

I'll make a start and invite people to help. 

_Copied from original issue: mozilla/webmaker-curriculum#123_

**Comment by dajbelshaw** [comment]
Hey @mickfuzz thanks for this! Looking forward to seeing how it grows. :+1: 

Be aware that v1.5 of the Web Literacy Map will be landing at the end of March - but it won't be *radically* different from v1.1 :)

**Comment by dajbelshaw** [comment]
_From @mickfuzz on January 25, 2015 15:13_

@dajbelshaw Great, I'll have a play around with the formatting of it, get some feedback and then start to invite people.

**Comment by dajbelshaw** [comment]
Saw via Miles Berry this morning that the government has released a 'spec of specs': https://www.gov.uk/government/publications/gcse-computer-science

**Comment by dajbelshaw** [comment]
_From @mickfuzz on January 27, 2015 19:24_

Well spotted, this seems a good base to work from rather than casting the net wider. 

The school I've just started at aren't doing Computing and are still on ICT for GCSE. That seems to map a bit more directly to the Web Literacies.

**Comment by LauraHilliger** [comment]
closing as this exists here: https://github.com/mozilla/webmaker-curriculum/wiki/Map-UK-GCSE-Curriculum-to-Webmaker-Club-curriculum-%28and-Web-Literacy-Map-v1.1%29

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/40"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/40.
Please don't comment on it here.
