### ISSUE TITLE
Create a BSD mailinglist signup form for STAGING site to use

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#892]
... so that we don't always have to test on PROD :cold_sweat:

**Comment by toolness** [comment]
So to do this you'll probably want to add an environment variable setting that tells the site which BSD configuration to use, which means you'll want to:

- [ ] Update the `README.md` to document the new environment variable.
- [ ] Mention the environment variable as an added feature in `CHANGELOG.md`.
- [ ] Add the environment variable to the list of vars exported to the client-side browser code in `webpack.config.js`.
- [ ] Set the environment variable to its appropriate value in `TRAVIS_BRANCH_CONFIGS` in [`lib/travis.js`](https://github.com/mozilla/teach.webmaker.org/blob/develop/lib/travis.js).

Phew! I think that's it...
