### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#893]
Our current release process should be documented!

For v0.0.4, it consisted of these steps:

* Verify that the ["Unreleased" section of `CHANGELOG.md`](https://github.com/mozilla/teach.webmaker.org/blob/develop/CHANGELOG.md#unreleased) is up-to-date by comparing it against GitHub's commit list (you can see that by clicking on the "Unreleased" section heading).
* Create a branch off develop called `v0.0.4-rc` and issue a PR to merge it into `master` titled [Tag and release v0.0.4](https://github.com/mozilla/teach.webmaker.org/pull/888). Paste in the latest changes from the topmost "Unreleased" section of `CHANGELOG.md` into the description of the PR so stakeholders know what's changed.
* Make sure that Travis thinks the PR looks good (i.e., all tests pass).
* Wait for the stakeholders to sign-off on the release (as [comments](https://github.com/mozilla/teach.webmaker.org/pull/880#issuecomment-101015657) in the PR). 
* Update the version number in `package.json` and then run `node lib/changelog.js bump`, which will create a new entry for the new version in `CHANGELOG.md`. Commit the changes with the commit message [Release v0.0.4.](https://github.com/mozilla/teach.webmaker.org/commit/3ff9e784e5548fb602924679ada9b0bb5c4599b2).
* Push the new commit to the PR.
* Merge the PR into `master`. Once Travis CI is finished, the site will be deployed to production.
* Run `git tag -a v0.0.4 -m "Release v0.0.4."` to create a tag for the release.
* Run `git push origin v0.0.4` to push the tag to GitHub (assuming `origin` is your remote pointing to GitHub).
* Merge `v0.0.4-rc` into `develop`.

**Note:** Creating the "Tag and release v0.0.4" PR is actually a bit tricky because it involves manually choosing the appropriate branches to merge. Having a script that automatically generates the URL to visit to make this easier could be nice. The URL has a pattern that looks like `https://github.com/mozilla/teach.webmaker.org/compare/master...toolness:v0.0.4-rc`.

**Comment by toolness** [comment]
Hey @jbuck, @ScottDowne, @simonwex, do you have any thoughts on this? Is it way too heavyweight? I don't want to bother documenting this more than I already have here unless there's some agreement that it's a reasonable process--otherwise I want to iterate on the process itself rather than further documenting a suboptimal one.

**Comment by jbuck** [comment]
The only additional weight above and beyond what we do elsewhere is writing up the changelog, so this seems fine.

**Comment by toolness** [comment]
Cool, thanks jbuck.

I've added some code to make updating the changelog and verifying that it's in-sync with `package.json` easier in 4bba7fdf91261cf6f8cbcfe657480bb6c1b32b57.

**Comment by toolness** [comment]
Also added some tooling in b1c3f17c040279421752f03a7431326635db225c to make it easier to version-bump the changelog.

**Comment by toolness** [comment]
Woo! In 054477e77fe044cd9bd160c3ac5e53565b8629b0 I also made it so the release notes show up in the tag message, which means that they show up on the [Releases](https://github.com/mozilla/teach.webmaker.org/releases) page. The first release to feature this is [v0.0.6](https://github.com/mozilla/teach.webmaker.org/releases/tag/v0.0.6).

**Comment by toolness** [comment]
Ok, the release process is now documented in [`RELEASE.md`](https://github.com/mozilla/teach.webmaker.org/blob/develop/RELEASE.md).

**Comment by hannahkane** [comment]
Sweet. :)
