### ISSUE TITLE
Design gallery implementation

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#895]
Before we can move Thimble to Teach, we'll need to have a solution for gallery views of Thimble makes. This ticket is to design a solution that meets these minimum requirements:
 * A view of all public Makes, sorted by publication date (most recent first)
 * A view of an individual user's Makes, visible to them

Future iterations will address searching/filtering, browsing, sorting, marking as "featured," etc.

**Comment by hannahkane** [comment]
cc @simonwex to help with this one, and add detail

**Comment by simonwex** [comment]
Worth noting, we're intentionally abandoning the MakeAPI here. We'll be loosing some functionality, but this will be a healthy departure from some legacy. The open question is how to share the publishing infrastructure(?), modules(?) and/or services with the new webmaker publishing API.

@cadecairos, @jbuck and myself will be discussing this tomorrow morning at 11:00am PDT

**Comment by hannahkane** [comment]
@simonwex - any update on this since your meeting?

**Comment by ldecoursy** [comment]
@toolness @simonwex @cadecairos meeting later today, then will update!

**Comment by toolness** [comment]
Ok, I talked to simon and cade and this is the current state of things:

* When we decommission the MakeAPI, people's Thimble and Goggles makes will be archived on the Web, **but they won't necessarily be visible in the gallery on Teach**. Doing this would require a data migration that we likely won't have time to do. That said, we might be able to create some kind of importer that users can opt-in to in the future, or something like that. And we might be able to have a link to "view your legacy makes", which would take users off-site to view a static, read-only page linking to all their legacy makes.
* We were originally hoping we could share some code between Teach and the publishing service provided by [api.webmaker.org](https://github.com/mozilla/api.webmaker.org) to publish Webmaker app makes, but after talking with cade it looks like there actually might not be much code we can share.
* The new version of Thimble (aka "Bramble") will actually support Makes that consist of multiple files in them, which is quite different from the current version in which each Make is just one HTML page. Furthermore, as implied by the "selfie" demo in today's demo call, some of those files may be images that the user captures from their webcam. So we'll have to talk to @humphd about how we're actually going to store this data.

**Comment by ldecoursy** [comment]
Thanks for the update. Any next steps on figuring out a publish solution for Goggles?

**Comment by humphd** [comment]
We talked to @jbuck today, who encouraged us to do something simple for storage, basically node+postgres and essentially create a simple static web server for your content, see https://github.com/mozilla/thimble.webmaker.org/issues/486#issuecomment-104749587.

We're designing and starting to implement this in our next heartbeat, so if you want to be involved and help us make sure we address bits you need, please let me know.  Also, I hope that we can migrate old Thimble makes, see https://github.com/mozilla/thimble.webmaker.org/issues/509.

**Comment by humphd** [comment]
A thing published with Goggles is basically a single page project, which is a subset of what Thimble will need.  So if we want to combine the needs of both systems and build a single web page/site publishing app, that might solve a bunch of things all in one go.

**Comment by toolness** [comment]
Ah, that's awesome humphd!!

I guess this is blocking on actual design, then, which will inform our technical solution?

**Comment by hannahkane** [comment]
A little confused about the next step for this. During Teach stand-up, we discussed UX as the next step. During the Thimble kick-off, though, I think I heard @humphd say that we might not be ready for that yet.

Anyone clear on what the next step ought to be? Seems to me we need to prioritize this in order to deliver in advance of the June 19th switcheroo.

cc @humphd @simonwex @toolness

**Comment by toolness** [comment]
Hmm, I meant that some low-fidelity wireframing could be very useful here for obtaining more detailed end-user requirements. In a similar way that sabrina's mock-ups for the Activities Page redesign (can't find the actual mockups, we looked at them in our stand though) are helping us figure out exactly what kind of API we'll need for the back-end in order to power search, and in a similar way that the [clubs mock-ups](https://redpen.io/p/jza7e4f541a24313ff) helped us define exactly what the current [`/clubs` Teach API endpoint](https://teach-api.herokuapp.com/api/clubs/) looks like, I think that mock-ups (or at least low-fidelity wireframes) would help us figure out what we'll need from a back-end in order to implement the new gallery.

**Comment by jgmac1106** [comment]
One of the problems with currently with Goggles, is the inability to edit
previously published makes. I often use Goggles in my class and students do
not finish. They have to publish and then remix the remix. This makes the
URL really long. Thimble and Popcorn (cue taps) had the edit pencil.

Sounds like this is a really complicated issue but if you could edit
something previously published that would be an awesome feature.

**Comment by hannahkane** [comment]
@humphd - do you agree that getting some lo-fi wireframes would be a good next step, or did you have a different approach in mind?

@jgmac1106 - thanks for the input! Would you be up for filing an issue in https://github.com/mozilla/thimble.webmaker.org? That's where we're tracking Thimble-specific work (tracking the gallery here, because it's on the Teach site).
