### ISSUE TITLE
Remove references to "add your event"

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#897]
There are two places on /events where we tell people to add their event via events.webmaker.org. We've decided we don't actually need to collect data about individual MP events this year, so let's remove those references.

1. In the main "Join us" text, let's just remove the second clause ("and add your events to our global list any time of year")

2. Remove the "Add Your Event" CTA from the bottom. Can we just center the two remaining CTAs for now? Soon enough we'll be adding new CTAs to this page (see #843), but for now, let's just get the "Add Your Event" CTA off the page.

There's also a reference on /events/resources. Let's remove the entire "Add Your Events to the Map" section of the "Before Your Event" tab

**Comment by hannahkane** [comment]
@mmmavis - wondering if you'd have time to do this this week, so we can push it before next week. We're sending out Save the Date emails early next week, and I don't want ppl to think they have to add their events to the database. Thanks!

**Comment by ldecoursy** [comment]
@mmmavis Re-opening this - doesn't look like either of these changes have been made - can you provide an update or ETA? Thanks!

**Comment by mmmavis** [comment]
Changes are live on https://teach.mofostaging.net already.

@toolness are we ready for another release for PROD`?

**Comment by toolness** [comment]
sure--since hannah is out on PTO, i guess lainie can give the thumbs up this time? i will fire up another production release PR.

**Comment by ldecoursy** [comment]
Yes - those changes look good to me - thanks @mmmavis and @toolness!

**Comment by ldecoursy** [comment]
Closing this ticket - I re-opened it by accident although it was already taken care of in staging and is now live.
