### ISSUE TITLE
Remove unlinked CTA at bottom of /clubs and /clubs/toolkit

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#898]
There's an unlinked CTA at the bottom of /events/resources that reads, "Do you meet regularly with a group of learners to increase web literacy skills?" Let's remove that and the orange line above it.

**Comment by mmmavis** [comment]
hey @hannahkane did you mean on https://teach.mozilla.org/clubs/ and https://teach.mozilla.org/clubs/toolkit/ instead?

**Comment by hannahkane** [comment]
Weird. Yes, thanks.
