### ISSUE TITLE
Change copy on Events in navigation

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#899]
We're lying to people!

Right now reads, "EVENTS Find gatherings near you, or host your own"
Let's replace with: "MAKER PARTY Host a one-time event or workshop"

**Comment by mmmavis** [comment]
![screen shot 2015-05-13 at 5 39 43 pm](https://cloud.githubusercontent.com/assets/2896608/7624023/526eaaa4-f997-11e4-81d1-af2b8de43185.png)
