### ISSUE TITLE
Determine URL for new teach site

### ISSUE THREAD

**Issue by cassiemc** [mozilla/teach.webmaker.org#9]
From @Hannahkane:

Don't know if this ticket also encompasses the issue of the name and the url, but wanted to leave these ideas from @hpauljohnson here:

    A possible solution is to have Mozilla Learning be the name, and "Teach the Web" be a tagline
    Another option for the url is potentially learning.mozilla.org

@davidascher @hpauljohnson @hannahkane  – Discuss :)

Deadline: in time for an April 1st launch of the site.

**Comment by hannahkane** [comment]
duped by #175
