### ISSUE TITLE
Implement "pre/during MP" state for /events 

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#900]
Pending #843

**Comment by toolness** [comment]
This will be interesting to implement from a technical standpoint... At first I was thinking that we could control it entirely through an environment variable, which would involve steps similar to what mavis did for #894.

But at the same time I think it'd be great for QA folks to be able to switch between the different states on the staging site, perhaps via a rudimentary UI on the dev ribbon modal. So we could have the "default" state be set via environment variable, but allow the state to be changed through developer-only UI hooks in the site, so that the different configurations can easily be verified during development.

**Comment by hannahkane** [comment]
This is no longer blocked by design.

**Comment by sabrinang** [comment]
maker-party_logo.png & maker-party_illustration_globe.png found here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efkJQcEJseDlNOUlMUGNhdWwzMVFkcWp1anh6NEVZX0hMT1hiWTk5TExVWnM&usp=sharing
![maker-party_logo](https://cloud.githubusercontent.com/assets/2492510/8242341/868105b0-15c3-11e5-9342-fc400976834b.png)
![maker-party_illustration_globe](https://cloud.githubusercontent.com/assets/2492510/8242345/8f23ba14-15c3-11e5-9178-f730863975c5.png)

repeating blue MP border pattern: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eUENsWU5VekM2SlE/view?usp=sharing
![maker-party_border-pattern](https://cloud.githubusercontent.com/assets/2492510/8242352/99cc1222-15c3-11e5-91d0-7386d6143175.png)

Maker Party photo thumbnails found here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efnhlekE4NElUSEtWWU9qUzF3UGRNa3VaYUJrUHVDaUZ4QnV0YlkxTDVUU2c&usp=sharing
![lofi-maker-party](https://cloud.githubusercontent.com/assets/2492510/8242353/9e2d1eb0-15c3-11e5-89a5-7369afb9943c.png)
![make-remake-hackathon](https://cloud.githubusercontent.com/assets/2492510/8242354/9f8516a0-15c3-11e5-83b0-e734769d4739.png)
![nn-maker-party](https://cloud.githubusercontent.com/assets/2492510/8242355/a0ee6f50-15c3-11e5-908c-5f1b42f24788.png)
![thumbnail-more-event-photos](https://cloud.githubusercontent.com/assets/2492510/8242357/a2268e02-15c3-11e5-9fec-a4d590c29e9a.png)


Teach like mozilla icon .svg - https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eUWNtd3ktZHB2OHM/view?usp=sharing
![icon-gears-preview](https://cloud.githubusercontent.com/assets/2492510/8242380/c2b3f86c-15c3-11e5-939a-994c426b9a8b.png)

**Comment by mmmavis** [comment]
![finalized mockup](https://cloud.githubusercontent.com/assets/2492510/8172494/ed49f02c-1375-11e5-844d-4f8f9c3fabbd.png)

@sabrinang could you let me know what color code we want to apply to the "HOSTED BY" etc labels?

**Comment by sabrinang** [comment]
I used #6B7FB0 which I took from the rectangle behind mozilla on events page
![screen shot 2015-06-18 at 3 16 39 pm](https://cloud.githubusercontent.com/assets/2492510/8243575/1714236a-15cd-11e5-81d1-b9c83590a953.png)

**Comment by mmmavis** [comment]
@hannahkane @sabrinang 
:question: just wanna confirm this ticket is for building the **pre-MP** version, *not* both pre and during verions.

**Comment by hannahkane** [comment]
The pre- and during- states will be the same. We won't make any changes until after MP.

**Comment by mmmavis** [comment]
@hannahkane the Teach Like Mozilla CTA(near footer) is missing subhead, I can leave it blank for now.

@sabrinang are the host names(e.g., David in the screencap below) hyperlinks or it's just the text colour is blue?
![screen shot 2015-06-20 at 7 44 26 pm](https://cloud.githubusercontent.com/assets/2896608/8270137/c8da88f6-1784-11e5-84b4-159963b89b5d.png)

**Comment by hannahkane** [comment]
Teach Like Mozilla CTA can be: "Learn about our approach to teaching"

If the host names are hyperlinks, I would not link "David" at all, would link Digital Harbor to http://www.digitalharbor.org/, and Mozilla Indonesia to https://www.mozilla.org/en-US/contact/communities/indonesia/

**Comment by mmmavis** [comment]
@sabrinang ^^ are the host names hyperlinks?

**Comment by sabrinang** [comment]
Yeah, I intended to mirror the "Developed by" labels on https://teach.mozilla.org/activities/ so people can click the hyperlink to see who made it so I thought it would be great to link back organization or host so they can be found. For individuals, just like on our activities page, we link to their twitter but I have no idea who "David" is on that mockup so I have no idea how to link to him.

**Comment by hannahkane** [comment]
@ldecoursy @amirad - does the David who did the Net Neutrality MP in his home have a twitter account we could link to?

**Comment by amirad** [comment]
Yup, it's @DGuarch @hannahkane

**Comment by amirad** [comment]
WOOP! Thanks all, the page looks great.
