### ISSUE TITLE
Design low bar CTA for "Pledge to teach"

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#908]
Context: right now, the only incentive for someone to sign-up is to add their Club, which is a high bar ask.. In the future, we'll have many more reasons to sign up (including low-bar options).

In the meantime, we'd like to capture site visitors who need something low bar to entice them. We're thinking a "Pledge to Teach" that requires them to provide their email address would be a good option.

Deliverable:
UX/UI for a pledge, that integrates into the new homepage.

@ldecoursy to provide copy for pledge and @amirad to provide copy for transactional email that follows

**Comment by amirad** [comment]
Timeline for email to be completed?
I think we need their name too for communication or data purposes?
@ldecoursy thoughts on "pledge to teach" versus "become a web champion" - we talked about this in our working group yesterday.

**Comment by hannahkane** [comment]
Would be good to have all copy finalized by the start of the next heartbeat (Monday, May 25).

re: getting their name—is it absolutely necessary? not sure the value of being able to use their name in an email outweighs the value of having a dead simple form. having said that, it could be kind of cute in the context of a pledge. "I, [fill in your name], pledge to..."

**Comment by hannahkane** [comment]
Brainstorm just now: perhaps the three main CTAs should actually be Pledge, Teach, and Start a Club, since soon (after #736), we'll be promoting Maker Party in a special way anyway.

**Comment by chrislarry33** [comment]
I LOVE this

**Comment by hannahkane** [comment]
Note: will need an icon in the style of the other CTAs

**Comment by ldecoursy** [comment]
@sabrinang to mock up form for when someone clicks Pledge

**Comment by ldecoursy** [comment]
Data to go into BSD list - @amirad do we want to add to existing list or create new one?

**Comment by sabrinang** [comment]
An idea for the Pledge to Teach icon for low bar CTA in a similar style with the other icons:
![screen shot 2015-05-25 at 3 30 56 pm](https://cloud.githubusercontent.com/assets/2492510/7802815/19f17dd6-02f3-11e5-97db-e80414fc9c95.png)
and when we promote Maker Party an idea is that we can have some banner below:
![teach_homepage_makerparty_edition-03](https://cloud.githubusercontent.com/assets/2492510/7802813/fe4d3d90-02f2-11e5-85f8-4207aace5274.png)

**Comment by sabrinang** [comment]
@ldecoursy - let me know when you have copy for the pledge form and I can mockup the page

**Comment by amirad** [comment]
Can we add to Mentor BSD list. They are same category and group.

**Comment by ldecoursy** [comment]
@amirad We'll want a separate autoresponder, or maybe just need to update the existing one? The transactional email here will ask people to complete the survey.

**Comment by amirad** [comment]
We can update the existing text! Don't see why not.

**Comment by ldecoursy** [comment]
@amirad Will you have time to share a draft of the transactional email? Here's a link to the draft survey that we'll want to be sure is part of it: http://bit.ly/1F4jomG

Draft copy is here for that form that pops-up when someone clicks "Pledge to teach" on the homepage: https://etherpad.mozilla.org/pledgecopy

Thoughts? @chrislarry33 @thornet @amirad @HPaulJohnson

**Comment by chrislarry33** [comment]
Not sure what exactly I am commenting on here. Lets get program review feedback and then review. I do really like the progress we have made here.

**Comment by sabrinang** [comment]
Pledge to Teach CTA is clicked form appears (similar style to Add your Club)
![pledgetoteach-example](https://cloud.githubusercontent.com/assets/2492510/7830596/bd41fe0a-0403-11e5-8558-b6c587def87a.png)

Redpen: https://redpen.io/wtedad357e37cf2190

**Comment by hannahkane** [comment]
I like using the same modal as on the Clubs page, but seeing it in context it's clear the copy is too long. I also think it should be more pledge-like. As in, "I pledge to do X, Y, and Z."

My suggestion:
Because the web is a global public resource that's integral to modern life, I pledge to: 
 * teach others digital literacy skills through hands-on making
 * help people move beyond simply consuming the web to creating it
 * be a passionate advocate of an open and accessible web
 
Pledge now, and we'll follow up with with details about how you can teach the web!

@ldecoursy @chrislarry33  - thoughts?

**Comment by chrislarry33** [comment]
Pro streamlined copy for sure

**Comment by chrislarry33** [comment]
Will it be possible to add in a function that lets people share their pledge via social media? Generate a tweet at least? I think that would/should be a key feature

**Comment by hannahkane** [comment]
I like that idea. We haven't yet seen what happens after the user clicks the "Pledge Now" button. User should probably receive immediate feedback—e.g. 'Thanks for pledging to teach the web!" That seems like a good place to offer a tweet option as well. Tweet might read, "I just pledged to #TeachTheWeb! [link to teach.mozilla.org]"

**Comment by ldecoursy** [comment]
Love the streamlined copy, and the tweet. 

Options for immediate feedback (so not too redundant with the tweet copy right below it) 
* "Thanks for your commitment to keeping the web open, accessible and ours." 
* "Thanks for your commitment to helping more people see themselves as citizens of the web."

**Comment by hannahkane** [comment]
I like the first one.

**Comment by sabrinang** [comment]
![pledgetoteach-modal-updated](https://cloud.githubusercontent.com/assets/2492510/7893187/19b2974a-0610-11e5-9c8e-324876196145.png)
![pledgetoteach-modal-updated-post](https://cloud.githubusercontent.com/assets/2492510/7893188/1ad021b0-0610-11e5-8d13-3a62503b93e4.png)
Copy suggestions for the title of the post pledge modal and copy that goes above the social buttons?

**Comment by hannahkane** [comment]
Looking good! Can the bullets be indented a bit, so they're not outside the paragraph text?

Copy suggestion for title of post pledge modal: "Pledge to Teach the Web"
I like the copy you provided for above the social buttons

**Comment by ldecoursy** [comment]
+1 I think instead of saying "thanks" twice the copy in the body could say "We appreciate your commitment to keeping the web open, accessible and ours."

**Comment by hannahkane** [comment]
Ah, just realized I misunderstood. My copy suggestion was for the *pledge model* not the post pledge modal. I think the post-pledge modal title could just be, "Thanks for your pledge!"

Agree with Lainie's suggestion above.

**Comment by sabrinang** [comment]
Updated pledge  ([redpen](https://redpen.io/mbe87484921e8819fc))
![teach_homepage_pledge-20](https://cloud.githubusercontent.com/assets/2492510/7923227/4a3a41da-0866-11e5-8a9d-85932fd6a601.png)
Updated copy
![pledgetoteach-modal-updated-post2](https://cloud.githubusercontent.com/assets/2492510/7923225/47f9eeac-0866-11e5-8dcd-2661f991c65d.png)

Another alternative iteration on redpen here: https://redpen.io/yv0bc876f4e89dca0d

**Comment by hannahkane** [comment]
I dig the one you posted on the ticket. Liking this a lot.

**Comment by chrislarry33** [comment]
I agree, really love the progress here. I am in awe daily how awesome everyone is doing iterating on the site. It's come a long long way

**Comment by sabrinang** [comment]
https://redpen.io/mbe87484921e8819fc
@cassiemc R?

**Comment by cassiemc** [comment]
Hey @sabrinang, left some comments on redpend, just a bit of cleanup to do. Looking nice!

**Comment by sabrinang** [comment]
![teach_homepage_pledge-updated](https://cloud.githubusercontent.com/assets/2492510/7969955/7894ddbc-09ef-11e5-97a1-8998bff9c7a2.png)
Updated redpen: https://redpen.io/mbe87484921e8819fc

**Comment by hannahkane** [comment]
<3

**Comment by sabrinang** [comment]
updated icon
![teach_homepage_pledge-updatedicon](https://cloud.githubusercontent.com/assets/2492510/7995176/a4910196-0ac8-11e5-8221-e8333af399f8.png)

**Comment by hannahkane** [comment]
This is good to implement in this heartbeat. @cassiemc, feel free to file any follow-up issues.

**Comment by sabrinang** [comment]
![teach_homepage_pledge-updatedicon2](https://cloud.githubusercontent.com/assets/2492510/8044040/cd3ce344-0dde-11e5-98c5-09f6cc4f6af3.png)
small tweaks to button (smaller width and all caps) and icon (smaller chalkboard)

**Comment by cassiemc** [comment]
This looks great @sabrinang :)

**Comment by mmmavis** [comment]
@sabrinang can you attach files here? thanks!

**Comment by sabrinang** [comment]
![icon-teach-man-chalkboard-pledge](https://cloud.githubusercontent.com/assets/2492510/8121191/0412f77a-105d-11e5-8ddf-d9c9dc985b66.png)

.svg icon: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eYnU4VXE2UWFDN3M/view?usp=sharing

**Font Awesome**
fa-hand-o-right #1A90CD
fa-facebook #FFFFFF (on #507BBE square)
fa-twitter #FFFFFF (on #64CCEF square)

18px Titles
14px Body Copy
