### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#909]
All the cool kids have one.

**Comment by flukeout** [comment]
So sad 
![image](https://cloud.githubusercontent.com/assets/25212/7865597/c20ebe48-051e-11e5-9e15-f3e404a19c5a.png)

**Comment by sabrinang** [comment]
https://www.mozilla.org/favicon.ico

**Comment by hannahkane** [comment]
Do we need a separate ticket to implement this?

**Comment by mmmavis** [comment]
I just created one

**Comment by hannahkane** [comment]
Thanks!
