### ISSUE TITLE
Roadmap new curricular structure

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/teach.webmaker.org#91]
_From @LauraHilliger on April 9, 2015 12:46_

Web Lit stream in progress here: https://teach.etherpad.mozilla.org/weblitbasics
TLM stream: https://docs.google.com/a/mozillafoundation.org/document/d/1quD8jfETB3_vuRc6IqWlbKAcn9bMcLGQOnpBiuH66Mw/edit and [blogged](http://www.zythepsary.com/techie/open-fluency/)

**Update:** latest commenting is [here](https://github.com/mozilla/webmaker-curriculum/issues/97#issuecomment-73267007)

NOTE: Laura deleted outdated meta-arcs in this issue _find those arcs in the original issue: mozilla/webmaker-curriculum#97_

**Comment by dajbelshaw** [comment]
I guess it depends what our theory is around progression. To what extent is Web Literacy Basics I-III a progression - as opposed to a smörgåsbord - of activities?

Suggest we make enhancements / build out the wiki until @thornet returns from PTO.

**Comment by dajbelshaw** [comment]
OK, so here's my $0.02, riffing off @LauraHilliger's braindump above. This is dependent on a couple of (potential) changes coming in Web Literacy Map v1.5:
* **Infrastructure** merging with **Web Mechanics** (see [this issue](https://github.com/mozilla/webliteracymap/issues/10))
* **Design/Accessibility** separating out into two distinct competencies (see [this issue](https://github.com/mozilla/webliteracymap/issues/13))

With these tweaks, I think we can cover all 15 competencies with five per module. **Once we're agreed on the running order, perhaps we could choose skills to cover and formulate some learning objectives?** Then we can find some awesome activities. 

# Web Literacy Basics I
* Credibility
* Web Mechanics
* Composing for the Web
* Remixing
* Open Practices

# Web Literacy Basics II
* Navigation
* Search
* Designing for the Web
* Collaborating
* Privacy

# Web Literacy Basics III
* Security
* Accessibility
* Coding/scripting
* Sharing
* Community Participation

-----
I think this would give us a nice mix of competencies that are somewhat related to one another. We can also choose scaffold this or leave each as being on the same 'level'.

Would love to know your thoughts @thornet @LauraHilliger @ldecoursy et al. :)

**Comment by dajbelshaw** [comment]
_From @ldecoursy on January 26, 2015 13:56_

Seems like a good flow to me (knowing that many activities will cross over competencies and hopefully draw on/reinforce skills learned earlier in the process). Would be good to get the curriculum working group's weigh-in once we have that group identified after tomorrow's call.

**Comment by dajbelshaw** [comment]
Just flagging that in Issue #113 I've [flagged a potential need](https://github.com/mozilla/webmaker-curriculum/issues/113#issuecomment-71480839) to switch **Designing for the Web** and **Remixing**.

**Comment by dajbelshaw** [comment]
OK, taking another stab knowing that we'll need *two* activities for the **Participating on the Web** part of **Web Literacy Basics I**. Let's just focus on the first couple of modules to begin with:

# Web Literacy Basics I

## Reading
* Credibility 
* Web Mechanics

## Writing
* Composing for the Web
* Remixing

## Participating
* Open Practices
* Privacy

# Web Literacy Basics II

## Reading
* Navigation
* Search

## Writing
* Designing for the Web
* Coding/scripting

## Participating
* Collaborating
* Privacy

-----

Would love feedback from @thornet & @ldecoursy!

**Comment by LauraHilliger** [comment]
related: #92

**Comment by dajbelshaw** [comment]
Let's take this to etherpad: https://teach.etherpad.mozilla.org/weblitbasics

**Comment by LauraHilliger** [comment]
took it to etherpad, did some planning and have a outlined roadmap. Everything is here: https://teach.etherpad.mozilla.org/weblitbasics, and I've already completed #549 

This outline needs discussion, will file new issue.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/42"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/42.
Please don't comment on it here.
