### ISSUE TITLE
Changes to Clubs form

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#910]
Placeholder ticket, pending @thornet and @amirad's research into what information is necessary to know whether a Club meets our criteria.

**Comment by hannahkane** [comment]
Putting in June 5 milestone for now, though it could be delayed if needed

**Comment by ldecoursy** [comment]
Goal: Better prompts so approvers have relevant information to make decisions, and also so content featured publicly feels more in fidelity with clubs.

Draft for new form fields/prompts:

* Who is your Mozilla Club affiliated with? (Name your organization, school, community group, etc.)
* Where are you located? (Type in a city or country) KEEP AS IS
* How do you teach the web? (Provide a brief description of your club activities)
* What is your club's website? (www.myclubwebsite.com) KEEP AS IS

Note that we'll have their email (it's included in the transactional email we receive when new clubs have been added). 

Also need to keep this to five or fewer questions to retain the current design. 

@amirad @thornet Anything to add based on your 1:1's with folks who have added clubs already?

**Comment by chrislarry33** [comment]
@ldecoursy So we could ask one last question? @thornet Would it be worth asking about what their first task(s) will be based on your user flow plans?

**Comment by ldecoursy** [comment]
@thornet @amirad Any other q we should ask for updated form based on any of your 1:1's with folks that have already submitted clubs?

**Comment by ldecoursy** [comment]
@thornet Instead of a fifth question, per your earlier email, do you want to add a button for someone to click "I've read the Mozilla Clubs Fact sheet" with a link to http://mozilla.github.io/learning-networks/clubs/?

**Comment by thornet** [comment]
+1 to the edits above and to @ldecoursey's suggestion about the button and fact sheet.

**Comment by ldecoursy** [comment]
Removed the block - ready for @mmmavis to make the changes. Let me know if you need anything else for this.

**Comment by toolness** [comment]
Ok, I'm working on this in #960. I should note, though, that the placeholder text provided for the "name" field is quite long and will likely get cut off on mobile devices:

![2015-05-29_10-04-27](https://cloud.githubusercontent.com/assets/124687/7884203/263ba662-05ea-11e5-94f1-31cac2c62b95.jpg)

As such, I recommend removing the words "community group", but it's up to you.

Also, I capitalized the word "Web", because I think that's Mozilla's policy? I can lowercase it if you want.

**Comment by toolness** [comment]
Note also that the screenshot in my [previous comment](https://github.com/mozilla/teach.webmaker.org/issues/910#issuecomment-106817244) doesn't yet have the checkbox linking to the fact sheet because I haven't added it yet. Two questions about that, though:

* I assume you want it to be a standard checkbox that defaults to being unchecked, right?
* And it's required that the user check it in order to submit the form?

**Comment by ldecoursy** [comment]
Can we change to "Name of organization, school, group"?

Yes on capitalizing Web :)

I vote yes on both bullets above - that they need to check the box (in hopes they read the fact sheet and understand what Clubs are--that they're not necessarily equivalent to Mozilla Communities) and that they need to check that before submitting the form.

**Comment by toolness** [comment]
Ok, done! This is what it looks like now:

![2015-05-29_10-50-30](https://cloud.githubusercontent.com/assets/124687/7885210/90d60b42-05f0-11e5-840d-a36f1b1f2db0.jpg)

I should also note that the checkbox *only* appears on the "Add Club" form, and *not* on the "Change Club" form.

As suggested above and +1'd by lainie, the checkbox defaults to unchecked, and requires the user to check it before they can submit the form.

**Comment by ldecoursey** [comment]
I don't know what this is....I am Louann DeCoursey not Lainee .....please
delete my email.

**Comment by toolness** [comment]
Sorry about that Louann! I think we mispelled Lainie's username in an [earlier comment](https://github.com/mozilla/teach.webmaker.org/issues/910#issuecomment-104785684), which accidentally brought you into our conversation.

Unfortunately I don't think there's any way for me to stop you from receiving notifications in this thread, but you can unsubscribe yourself by visiting https://github.com/mozilla/teach.webmaker.org/issues/910 and unsubscribing from further notifications. Instructions on how to do that are here:

https://help.github.com/articles/unsubscribing-from-conversations/

**Comment by hannahkane** [comment]
Looks great!
