### ISSUE TITLE
Make a graphic overview of the activities

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#92]
We will need a graphic to help people understand the club activities and how we intend them to be used. A non-outdated version of:

![club-proposal-assets](https://cloud.githubusercontent.com/assets/539017/6369629/7925e5cc-bce8-11e4-90f9-3d39b556b056.png)

**Comment by hannahkane** [comment]
Hey, @LauraHilliger — is this meant for marketing materials, or the website, or somewhere else? Thanks!

**Comment by LauraHilliger** [comment]
For somewhere "next to" the curriculum on the site. We've found that people need a quick overview to understand how different bits relate to one another. Illustrate the "preferred" pathway, if you will.

**Comment by dajbelshaw** [comment]
Wondering if, to "yes, and..." @LauraHilliger's comment, there's any value in showing a preferred path amongst other options?

![hexagons](http://digitalliteraci.es/wiki/images/thumb/7/77/Non-linear-pathways.png/120px-Non-linear-pathways.png)

![branching](http://digitalliteraci.es/wiki/images/thumb/9/98/Branching-logic.png/120px-Branching-logic.png)

**Comment by LauraHilliger** [comment]
"yes, and...and" multiple preferred paths also a possibility at the moment, since we're developing multiple activities in the Clubs curriculum. In any case, we can't solve this until we solve #91 :dart:

**Comment by hannahkane** [comment]
Given that we're about to launch a new presentation of the curriculum, I'd like to wait and see if a graphic is needed. Ideally, we'll solve this problem by presenting the curriculum and pathways in a coherent way right on the site. 

Is it okay if I close this for now?

**Comment by LauraHilliger** [comment]
this should be considered for #457 - when we have loads of clubs activities, people will likely want some sort of an overview. Closing for now, will address with #457

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/43"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/43.
Please don't comment on it here.
