### ISSUE TITLE
Change subject line of email notification to staff about new Clubs

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#922]
Should be: "Please review: new club has been submitted"

**Comment by toolness** [comment]
Cool. We should probably also add a link directly edit the new club in the admin UI, so that one can easily approve/deny/etc directly from the email. Won't be hard.

**Comment by toolness** [comment]
Ok, I've actually changed the email a bit to look like this:

```http
Subject: Please review: new club has been submitted

toolness would like to add their Club to the map.

Name: my club
Location: Madison, WI
Website: http://myclub.com/
Description: This is my new club.

This club is currently in a pending state and you can approve or deny it
for inclusion in the public map at:

https://teach-api.herokuapp.com/admin/clubs/club/1/

You may also want to email them at toolness@example.org to say hello!
```

Does that look ok?

**Comment by hannahkane** [comment]
This looks good. One tiny thing that might help the manual process we'll be using temporarily—could you actually include the email as a fifth field in the list? That would make copy/paste to the spreadsheet easier.

**Comment by toolness** [comment]
Ah sure, just added that in https://github.com/toolness/teach-api/commit/8ed32b2477b24ef918f68eb8374ae5f6416a0d4d.

**Comment by toolness** [comment]
This has actually been merged into teach-api, so I'm closing this issue.
