### ISSUE TITLE
Create concept of an RC (Regional Coordinator) user type

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#923]
The RC type should ONLY have the privilege to view pending Clubs and change their status (staff users should also have this privilege by default)

**Comment by toolness** [comment]
Does this imply that there should also be a concept of "region"? If so, is there a list of regions that the system should start out with? (e.g., India, South America, etc)

**Comment by ldecoursy** [comment]
I don't think we need "region" yet.

**Comment by ldecoursy** [comment]
@toolness to compile list of assumptions for review.

**Comment by hannahkane** [comment]
Didn't mean to suggest the need for regions just yet. 

Also, to clarify, right now there may not be any significant difference between a staff user type and a regional coordinator user type—they'll both have Clubs status editing privileges. I'm not sure if staff users have any additional privileges/functionality that we need to block RCs from having. I'm mostly just predicting that in the future we may add more privileges and will want to be able to distinguish between staff and RCs.

**Comment by toolness** [comment]
It's largely an issue of [principle of least privilege](http://en.wikipedia.org/wiki/Principle_of_least_privilege). Right now staff are actually treated as admin users in Django terms, which actually gives them a ridiculous amount of power--enough to cause all sorts of havoc if that power fell into the wrong hands, or if some button were accidentally clicked. Which, um, reminds me that we need to be making backups of the site's database. :sweat_smile: On that note, I just filed #948!

Anyways, what I really need to do is the same thing I did with the Hive Directory, whereby "staff" actually isn't the same thing as a Django admin user. There should actually be only a tiny handful of Django admin users--possibly just me and anyone else I've trained. These would, for instance, be the only people capable of actually irrevocably *deleting* a Club, rather than simply marking it as inactive.

**Comment by toolness** [comment]
Also, in keeping with POLA, I recommend having RC's have minimal access to user records. If they have the same privileges as staff, they'll be able to see every email address of every webmaker user who's ever logged into the teach site. Which I guess might be OK if we really trust them, and also trust them to follow good security practices (e.g. strong passwords) to ensure that their accounts don't get compromised.

**Comment by hannahkane** [comment]
Didn't realize staff was same as Django admin. Def good to file #949. I would define RC privs as limited to managing Clubs, only, not users.

**Comment by toolness** [comment]
Is it OK if RCs can view and change every single club in the system, or do we want them to only view/change clubs that teach staff have assigned them to?

The latter also brings up the concept of "assigning" a club to a RC, which will involve changing the data model. The former will be ridiculously easy to implement. Both are totally doable though, just need to know which one to implement for our MVP.

**Comment by hannahkane** [comment]
I vote for the former. It's possible we'll want to add more granular permissions in the future, but it seems smarter to wait and see if that need emerges.

**Comment by toolness** [comment]
Ah cool, in that case this is now done as of https://github.com/mozilla/teach-api/commit/f64ae67451af8f11c10e6edb9b663fb829710e85.

Currently only a bona fide Admin user can promote someone from being a mere user to a RC, which is currently the easiest way to do this... I say we just give a very limited number of teach staff admin privs, and train them to not shoot themselves in the foot.

**Comment by toolness** [comment]
I guess I feel like the only thing left is to either document or teach people the process used to "bless" a user with RC privileges. This basically comes down to marking them as **Staff status** in the Django User admin UI and putting them in the **Regional Coordinators** group:

![2015-06-09_17-04-53](https://cloud.githubusercontent.com/assets/124687/8069623/beb9bd7e-0ec9-11e5-9a73-bb3db86bf209.jpg)

Hmm, I'm also realizing for the first time that there's now multiple meanings for the word "staff": "Staff status" just means someone has access to the Django admin UI, but offers no specific editing permissions by itself. While "Teach Staff" specifically grants editing permissions for users and clubs.

**Comment by toolness** [comment]
I guess I am gonna close this issue and we can file any other tasks that need to be addressed as separate issues.
