### ISSUE TITLE
Create UX for RC to approve/deny Clubs

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#924]
Needs an entry point, and UX for changing the state of the Club

**Comment by toolness** [comment]
This will definitely be easiest to do through the Django admin UI, most likely a drop-down that allows the RC to set the status to pending (the default), approved, or denied.

**Comment by toolness** [comment]
Er, to clarify, a designer should probably *not* make a mock-up for this, as we'd just configure it through the Django admin UI.

Does the back-end need to send a transactional email if the user's club is denied, or will the RC and/or teach staff be responsible for all communication with the user after the initial "thanks for submitting a club" transactional email has been sent out?

**Comment by toolness** [comment]
At this point this is basically done in https://github.com/mozilla/teach-api/pull/16, with the addition of the following UI in the admin view for clubs:

![2015-05-29_7-53-25](https://cloud.githubusercontent.com/assets/124687/7882070/ddec9ea0-05d7-11e5-9b03-511d6f6feca1.jpg)

As mentioned in https://github.com/mozilla/teach.webmaker.org/issues/921#issuecomment-106767432, though, there is currently no transactional email sent out when this status has been changed in the admin UI, so the teach staff/RC is responsible for manually emailing the club owner to let them know about the status change.

**Comment by hannahkane** [comment]
I think this is fine for this period where we're piloting the process. We'll add more automation as the process firms up!

**Comment by hannahkane** [comment]
This is done!
