### ISSUE TITLE
[MIGRATED] Update "Club Audit" with a curriculum audit

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#93]
Moving from the curriculum repo:

We have this audit of orgs with club-like activities. It notes that certain orgs have curricula, we should be auditing to see how we might be able to use what already exists. Need to check for licensing, remixability and alignment to Web Lit Map, especially for competencies that don't have a lot of materials to pull from.

https://docs.google.com/a/zythepsary.com/spreadsheets/d/1JvIm1nAVBqtbOTwEpwzc_WyGL11Sx3QG5zSGUy1SQk8/edit#gid=0

(note: back in Textbook phase, Kat and I had worked on listing curriculum from both inside and outside webmaker that covered competencies. Might be worth cross referencing both in the audit as well as for future curriculum production. https://teach.etherpad.mozilla.org/best-in-show )

**Comment by LauraHilliger** [comment]
Related: https://github.com/mozilla/webmaker-curriculum/issues/85

**Comment by LauraHilliger** [comment]
based on web lit map http://myfuture.net/essentials

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/44"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/44.
Please don't comment on it here.
