### ISSUE TITLE
Hive Directory is down.

### ISSUE THREAD

**Issue by omnignorant** [mozilla/teach.webmaker.org#931]
https://directory.hivelearningnetworks.org/ returns a Bad Request (400) error.

@ldecoursy @toolness @simonaramkisson

**Comment by ldecoursy** [comment]
Closing this since this repo is just for teach site. Dev Ops issues should be filed here: https://github.com/MozillaFoundation/mofo-devops/issues/new

**Comment by omnignorant** [comment]
@ldecoursy Are you moving it then? Or should I?

**Comment by toolness** [comment]
Unfortunately, this is related to a misconfiguration with https://github.com/MozillaFoundation/mofo-devops/issues/34. JP's working on it right now!

**Comment by jdotpz** [comment]
This has been resolved.  We added host headers and cloudfront-forwarded-proto cookies to the whitelist, and @toolness fixed up some code to work with that.

**Comment by toolness** [comment]
actually i didn't even have to change any code, just had to reconfigure the ol' `SECURE_PROXY_SSL_HEADER` to `CloudFront-Forwarded-Proto: https`! Hooray!!
