### ISSUE TITLE
Need interim brand identity for Mozilla Clubs

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#933]
We've heard from several Regional Coordinators that there's a need for a Mozilla Clubs logo to lend credibility (make it feel official), to create signs for doors/events where Clubs programs are happening, etc. 

I know this is connected to larger branding concerns, but hoping we can create something basic for now, even knowing that it may change down the road. 

cc @HPaulJohnson @chrislarry33 @thornet

**Comment by HPaulJohnson** [comment]
We've talked awhile about creating a basic visual identity for Clubs to help with the more generic naming. I think we can/should proceed with that. Is there are dedicated designer for Teach that we can leverage or should we get this prioritized via TPS?

On the overall branding front, I've had a few good conversations with the new CMO and am doing more of a product line review with him on Friday. From those conversations, I'm optimistic we'll finally see some movement on the the larger branding conversation.

**Comment by ldecoursy** [comment]
Likely to be tackled in the June 19th heartbeat given design resources.

**Comment by cassiemc** [comment]
Yes would love if @lovegushwa could lend us his expertise here! cc @edrushka

**Comment by edrushka** [comment]
Chatting with Cassie on Monday about upcoming design projects. Stay tuned!

**Comment by hannahkane** [comment]
Can we do just a wordmark, rather than a logo with an icon/illustration?

**Comment by hannahkane** [comment]
@HPaulJohnson @cassiemc ^

**Comment by HPaulJohnson** [comment]
+1 to just doing a wordmark for now.

**Comment by sabrinang** [comment]
vertical and horizontal wordmark mockup
![mozilla-clubs-wordmark](https://cloud.githubusercontent.com/assets/2492510/8046603/35bc9f7e-0df1-11e5-8fac-cbb42980294b.png)

**Comment by ldecoursy** [comment]
Nice! I like the vertical lockup, and prefer metapro medium with uppercase "C" 

I wonder if we need a singular Mozilla Club lockup for folks to add their org or city name to? 

cc @thornet @amirad

**Comment by hannahkane** [comment]
+1 to @ldecoursy's comments. What makes the most sense? "Toronto Mozilla Club" or "Mozilla Club Toronto" or "Mozilla Clubs Toronto"?

**Comment by amirad** [comment]
+1 to vertical, though don't feel strongly either way about the capital C

I like "Mozilla Club Toronto" - it's the same one many other clubs use (coder dojo, code club etc.) though there are other club like model like Toastmasters that go the other way.

**Comment by cassiemc** [comment]
It'll be useful to have a horizontal version as well as vertical, to use in different contexts. You can prioritize the vertical, though. There's something weird about that capital C, can't put my finger on it. I like that it feels more prestigious, just something weird about the letterform. Seems like there should be a tad less space between 'mozilla' and 'clubs' in the horizontal version. cc @lovegushwa

**Comment by sabrinang** [comment]
Examining existing wordmark structures and continuing to iterate on wordmarks with city name incorporated 
![mozilla-clubs-wordmark-exploration](https://cloud.githubusercontent.com/assets/2492510/8069490/abd5be84-0eaf-11e5-88a4-0625057e4ae5.png)

**Comment by ldecoursy** [comment]
I like the Open Badges equivalent. Think it would need to be singular "Club" though.

**Comment by sabrinang** [comment]
singular version update
![mozilla-clubs-wordmark-exploration-singular](https://cloud.githubusercontent.com/assets/2492510/8069929/a9c3d9ca-0eb2-11e5-9893-c5e756e0ca63.png)

**Comment by hannahkane** [comment]
I also like the OpenBadges-inspired one for horizontal, and I think I prefer the Gigabit-inspired one for vertical.

@ldecoursy and @cassiemc - would you both be okay with those options?

**Comment by sabrinang** [comment]
More explorations on wordmarks and iterate on "mozilla club" as a unit followed by city name
![mozilla-clubs-wordmark-exploration2](https://cloud.githubusercontent.com/assets/2492510/8169897/72cf1f2a-1361-11e5-963a-7bb25f9d3110.png)

**Comment by hannahkane** [comment]
I like the 4th row the best, with the smaller "mozilla club" and larger city name, but the lighterweight font overall.

Also, would love to not spend too much more time on this particular ticket, if possible. :)

**Comment by hannahkane** [comment]
@ldecoursy @cassiemc - do you have final choices?

**Comment by ldecoursy** [comment]
Just looked over with @amirad and @thornet and we're liking the third option. Feeling like the ones on the bottom de-emphasize Mozilla Clubs too much.

**Comment by cassiemc** [comment]
I also like the ones where mozilla and the city name are a more equal size. Feels like it uses the brand equity in mozilla to our benefit.

**Comment by hannahkane** [comment]
Cool. Let's go with option 3, and call it good! @ldecoursy @thornet @amirad - where do you think is the best place to store this for Club Captains to access? The github page we were talking about creating?

**Comment by ldecoursy** [comment]
Think probably here for now: http://mozilla.github.io/learning-networks/clubs/ but perhaps it also has a place on the new Clubs page

**Comment by hannahkane** [comment]
@sabrinang - can you please provide final assets, and @thornet, can you add them to the github page for now?
Thanks, all!

**Comment by sabrinang** [comment]
You can find the .ai wordmark template here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eRl95YVFBTW9BWEE/view?usp=sharing

Included guides and notes (similarly to hive wordmarks)
![screen shot 2015-06-17 at 4 55 00 pm](https://cloud.githubusercontent.com/assets/2492510/8221348/22da7d72-1512-11e5-9827-e23ffddbb9b2.png)

**Comment by cassiemc** [comment]
This is great Sabrina. Love that you included documentation.

**Comment by hannahkane** [comment]
Awesome. Nice work, @sabrinang. Closing this!

**Comment by chrislarry33** [comment]
AWSM, work agree with @cassiemc that the documentation is awsm. This will help the clubs work grow thank you @sabrinang

**Comment by soapdog** [comment]
Thanks a lot for this! We have immediate usage for this type of resource right now here in Rio. :+1:

**Comment by soapdog** [comment]
Club Captains are having trouble getting FF Meta Pro font. Can we have a vector of "Mozilla Club" to share with them?

**Comment by sabrinang** [comment]
![screen shot 2015-06-30 at 9 07 51 am](https://cloud.githubusercontent.com/assets/2492510/8435720/bf1c4964-1f07-11e5-8d60-6f48bef027e1.png)
The first layer in the template has "Mozilla Club" outlined so it doesn't require the font - however "City Name" would need it so you just delete it.

Also, I exported just a Mozilla Club .eps here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_edk1iZHZpdXgtMVk/view?usp=sharing

**Comment by jgmac1106** [comment]
Can we also have a Thimble make that could use CSS to get close as possible
to the mock up? I worry that the technical skills and software may not be
available to every club captain.

It would be nice if they could just change the text of City Name and take a
screenshot.

Is there another way we can make this easier for captains with little to no
design experience?

**Comment by hannahkane** [comment]
Nice idea. @sabrinang - want to open a separate ticket for a web-based version?

**Comment by sabrinang** [comment]
Yes
