### ISSUE TITLE
Add timestamp to Mozilla Learning Admin 

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#937]
Would be great to add a timestamp column when logged into Mozilla Learning Admin. 

This will be helpful for us in tracking against our KPIs, so we can go in regularly to review and update the MoFo dashboard with new cities.

**Comment by toolness** [comment]
Done in https://github.com/mozilla/teach-api/commit/d472b555510fef96a40856464ac26f58a8c8c448. You can now see the created and modified date in the clubs list view in the admin UI, and can sort by either by clicking on the column heading:

![2015-05-21_14-07-00](https://cloud.githubusercontent.com/assets/124687/7755551/eda84148-ffc2-11e4-9b0c-a08a617e9c63.png)

**Comment by ldecoursy** [comment]
So fast - you rule! Thanks @toolness
