### ISSUE TITLE
Create a "Protecting Your Data" page on teach.mozilla.org

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#938]
Related to #862 

This is for @sabrinang to create a page for the privacy module that looks like the page for the Web Lit Basics module: https://teach.mozilla.org/activities/web-lit-basics/

Main image: (can we use one of the options for the new homepage design that we didn't select?)
Copy: https://etherpad.mozilla.org/privacymodulecopy
Thumbnails: pull from http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/index.html

Let me know if you need anything else!

**Comment by sabrinang** [comment]
I mocked up this in the format like the Web Lit basics module. Everything looks like it is working well but the introduction copy may be a bit long - @ldecoursy if we can cut down some words it will help make it less text heavy up at the top 


![clubs curriculum protect your data](https://cloud.githubusercontent.com/assets/2492510/7779727/bb36005a-008b-11e5-8159-bd9f404cbd6a.png)

**Comment by ldecoursy** [comment]
Thanks @sabrinang! Just shortened intro copy in the etherpad.

**Comment by ldecoursy** [comment]
And it looks great to me :smile:

**Comment by sabrinang** [comment]
![clubs curriculum protect your data update](https://cloud.githubusercontent.com/assets/2492510/7780625/1ec5b8ae-0096-11e5-8b1f-fbef4cea61b5.png)
updated with reduced text

**Comment by ldecoursy** [comment]
looks good to me!

**Comment by ldecoursy** [comment]
Think just waiting for @sabrinang to upload files here, then can add to #862 and #830

**Comment by sabrinang** [comment]
**Design (.sketch) File**
https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eQlFwY0VmMUsycDQ/view?usp=sharing

**Photo**
![protectyourdata-photo](https://cloud.githubusercontent.com/assets/2492510/7829924/1e78e8b2-03fc-11e5-9c83-5bd933942049.png)
(original) https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eOUlCbkZxR3hTQU0/view?usp=sharing
(retina) https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eTWU5OUt4bWVQNmM/view?usp=sharing

**Thumbnails**
![img-cookies](https://cloud.githubusercontent.com/assets/2492510/7830140/7ae8cd9a-03fe-11e5-939e-1adc324fc6b1.png)
![img-datatrail](https://cloud.githubusercontent.com/assets/2492510/7830141/7afb9682-03fe-11e5-9500-4ad15b368393.png)
![img-iptracer](https://cloud.githubusercontent.com/assets/2492510/7830143/7b1ee268-03fe-11e5-9882-129256338ab6.png)
![img-password](https://cloud.githubusercontent.com/assets/2492510/7830142/7b121858-03fe-11e5-95b7-7f92dadb0028.png)
![img-privacycoach](https://cloud.githubusercontent.com/assets/2492510/7830144/7b2fab0c-03fe-11e5-8cfc-ec2972677bdf.png)

(original and retina exports) https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efnIwVklLc3hYSlFaT2FqZE5kNXM0UmdZb2I5VW9xVzAxUVZjM3ZUMWdscVU&usp=sharing
