### ISSUE TITLE
Create stylesheet to print activities and resources

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#94]
Conversation was started here: https://github.com/mozilla/webmaker-curriculum/issues/99

**Comment by LauraHilliger** [comment]
Before I spend time making this basic stylesheet for club curricula prettier so our stuff prints nicely, do we have a webmaker print stylesheet somewhere?

cc/ @k88hudson @toolness @flukeout @cassiemc 

Tips on print styles are appreciated :pray: 

https://github.com/mozilla/webmaker-curriculum/pull/167

**Comment by toolness** [comment]
Cool!

I recently found this [PDFKit](http://pdfkit.org/docs/vector.html) thing, which makes it possible to render a PDF in JavaScript. It's not HTML-based, though, so I get the impression that it *could* be used to create some slick PDFs, but there would be some sort of conversion process involved in taking your original HTML/markdown and turning it into a PDF. It's probably way too much effort but I thought I'd mention it here in case it inspires any other funky ideas.

**Comment by k88hudson** [comment]
This might be a good starting point

https://github.com/twbs/bootstrap/blob/master/less/print.less

**Comment by LauraHilliger** [comment]
well it looks ok. Not brilliant, but ok: https://github.com/mozilla/webmaker-curriculum/pull/170

If we ever decide to move back to markdown, should remember: https://gitprint.com/

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/45"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/45.
Please don't comment on it here.
