### ISSUE TITLE
Timestamp for latest blog post says "invalid date" until posts are loaded

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#955]
I was visiting the homepage and it was taking a little while to load. The timestamp for the latest blog post is supposed to look like this:

![2015-05-28_19-47-40](https://cloud.githubusercontent.com/assets/124687/7873635/cb9e5820-0572-11e5-9b1e-31ede7625e60.jpg)

However, because the posts weren't yet retrieved, it looked like this:

![2015-05-28_19-47-00](https://cloud.githubusercontent.com/assets/124687/7873637/e23c1c7a-0572-11e5-8e32-4af8f0977bdb.jpg)

Note that this is also what it'll look like to users without JS enabled and search engines. For the time being, you can see it at https://teach.mofostaging.net/?safemode=on.

**Comment by toolness** [comment]
Hmm, I'm also noticing in #973 that when we actually replace the stub blog feed loader with the google one, this bug is actually fairly noticeable.

**Comment by mmmavis** [comment]
I think this has been fixed via https://github.com/mozilla/teach.webmaker.org/commit/0e04db2f4665e3e62ff4eae01375e94545ca5762#diff-d06502677d45fab6ff321d04b9d0f54fR66 -- we render nothing unless the feature post data has been loaded.

Gonna close this ticket. :smile:
