### ISSUE TITLE
Copy change on homepage and /about

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#956]
We need to be consistent with our usage of "The Mozilla Learning Network" as opposed to "Mozilla Learning Networks".

On homepage:
 * Second sentence of lead paragraph should read "The Mozilla Learning Network offers programs..."

On About page:
 * Header: "About the Mozilla Learning Network"
 * Intro paragraph: "We want more people to see themselves as citizens of the web. The Mozilla Learning Network offers programs..."

**Comment by toolness** [comment]
> * Header: "About the Mozilla Learning Network"

Should the "the" be capitalized? It looks weird to me not capitalized...

**Comment by hannahkane** [comment]
Grammatically, I believe it depends on whether we consider the "the" to be an official part of the name of the program. @KevZawacki, do you want to create a rule about this that we can use moving forward?

**Comment by KevZawacki** [comment]
Sure. I suggest we *don't* incorporate "the" as part of the title. Often, we use the phrase without it. (eg, "Mozilla Learning Network helps students...")

That's my decree. But am open to debate :-)

**Comment by toolness** [comment]
Ok, sounds good--we won't capitalize "the" in the header then!
