### ISSUE TITLE
Draft email copy for after user signs the pledge

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#957]
* Thank them for taking the pledge
* Provide a next step (survey for now)

**Comment by hannahkane** [comment]
Sorry, @ldecoursy, I totally missed this. We don't have this email copy yet, do we? Can you take a crack at it?

**Comment by hannahkane** [comment]
also cc @amirad

**Comment by ldecoursy** [comment]
Draft here at the top: https://teach.etherpad.mozilla.org/clubtransactionalemails Edit away!

**Comment by amirad** [comment]
Edited!

**Comment by hannahkane** [comment]
Are we good to go with this? Does anyone else need to approve it?

**Comment by ldecoursy** [comment]
Maybe good to have @HPaulJohnson or @KevZawacki eyes on this!

**Comment by HPaulJohnson** [comment]
Added some quick comments in the pad. 

Another suggestion is to have a second email queued up for 7-14 days out that goes to everyone who pledged but did not take the next step to fill out the next survey. Best case scenario, you are going to have a lot of people fall out of the funnel at this step so best to chase them down via a series of communications.

**Comment by KevZawacki** [comment]
Just took a read through — no edits from me. +1!

**Comment by hannahkane** [comment]
I'mma close this ticket, and potentially open a new one to implement @HPaulJohnson's idea of a follow-up email (will discuss at a relevant meeting tomorrow).

Thanks, all!
