### ISSUE TITLE
[MIGRATED] Rio: localize the web literacy map into pt_BR

### ISSUE THREAD

**Issue by soapdog** [mozilla/teach.webmaker.org#96]
Most of our audience in the Rio LAN houses project does not speak English. All resources made available to them needs to be in Brazilian Portuguese.

One special resource that will aid self-assessment is the Web Literacy Map. Right now the map is in that hybrid state where some strings are in Portuguese but most of it is still in English.

![recursos 2015-02-26 10-05-34](https://cloud.githubusercontent.com/assets/23247/6392413/19024cbe-bd9f-11e4-9465-3cbfa4cae49f.png)

**Comment by dajbelshaw** [comment]
Hi @soapdog! Just flagging that this is v1.1 of the Web Literacy Map and v1.5 will be ready by the end of March. The idea is to include localisation as part of that push. :)

https://github.com/mozilla/webliteracymap/

/ cc @hannahkane

**Comment by soapdog** [comment]
Perfect @dajbelshaw! I will help on that repo. Thanks a lot.

**Comment by dajbelshaw** [comment]
I think the translation/localisation itself will happen on Transifex, but the English v1.5 will appear on the above repo first.

We'd love your input on the community calls if you ever get time: https://wiki.mozilla.org/Webmaker/WebLiteracyMap/v1.5

(there's actually a call at 4pm UTC [today](https://teach.etherpad.mozilla.org/weblitmap-26feb15)!)

**Comment by soapdog** [comment]
@dajbelshaw is it on Transifex already? If it is not, then, is it ok to translate and do a pull request?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/47"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/47.
Please don't comment on it here.
