### ISSUE TITLE
Maker party certificate (on makes.org) has a broken image

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#962]
This isn't a bug on the teach site, it's a bug on the [Maker Party Certificate](https://makerparty2014.makes.org/thimble/LTEzNDM3NTAxNDQ=/maker-party-love-bomb) Thimble make on makerparty2014.makes.org. The Mozilla Webmaker Logo in the bottom-right of the page appears to be broken.

![2015-06-01_6-55-48](https://cloud.githubusercontent.com/assets/124687/7911394/44f03dbe-082b-11e5-9040-f82e68c0c675.jpg)

**Comment by hannahkane** [comment]
Is that the right logo to include, @amirad?

**Comment by amirad** [comment]
We can probably replace the Webmaker logo with just a generic Mozilla logo now

**Comment by hannahkane** [comment]
Word.

**Comment by hannahkane** [comment]
@amirad - do you have access to that make? If not, who would?

**Comment by amirad** [comment]
Yes.

Username: makerparty2014
Email: makerparty.webmaker@gmail.com
Password: teachtheweb

**Comment by mmmavis** [comment]
@hannahkane I got the credentials from Amira now.

@sabrinang could you attach the mockup of this certificate (if you still have it)?  Just wanna do a quick comparision :smile_cat:

**Comment by sabrinang** [comment]
![maker-party_certificate-thimble-mockup](https://cloud.githubusercontent.com/assets/2492510/8047323/a176a172-0df8-11e5-95db-2e991355f3e9.png)

**Comment by mmmavis** [comment]
fixed by hosting those 404 images on http://stuff.webmaker.org.s3.amazonaws.com/teach.mozilla.org/makes/ instead
