### ISSUE TITLE
Map popup disappears if it's too tall

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#968]
I've noticed that if a city has lots of clubs in it--or even just one club with a really long description--the map popup can become so tall that the marker cluster plugin causes the pin to collapse into a cluster when the user is viewing the top of the popup, which then causes the popup to disappear. Because mapbox immediately scrolls to the top of the popup when it's opened, this results in the popup seeming to show for a split-second and then immediately disappear.

We may want to specify a maximum height for the popup, and have its contents scroll if they overflow.

**Comment by mmmavis** [comment]
I haven't been able to reproduce this, @toolness .  But yea specifying a max. height could also help with solving https://github.com/mozilla/teach.webmaker.org/issues/976 (enable vertical scrollbar for tall popup)

**Comment by toolness** [comment]
Er yeah, I believe this bug will be addressed by the vertical scrollbar that will be added #976, so we might want to just mark this one as a dupe?

**Comment by toolness** [comment]
Woot this just got fixed by #1001, so I'm closing it.
