### ISSUE TITLE
Update "Name and Brand Your Club" section of Club Toolkit

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.webmaker.org#969]
Updated text for "Name and Brand Your Club" section (links stay the same):

Your club is yours to design but to help you, here are some tips on how to brand your club or hack the materials.

    Naming. Customize your Mozilla Club name by adding your location, school, library, community or anything else in the name that identifies your group. 

    Mozilla branding. The Mozilla brand helps identify your clubs as part of our global network and mission. Have a look at the Mozilla branding guidelines. 

    Github. Our curriculum is available via Github. You can fork any of those pages and make them your own by editing activities or changing the language. Share your new pages with the community, you never know who might find them helpful.

**Comment by amirad** [comment]
@ldecoursy @thornet does that sound more aligned with the UR text?

**Comment by mmmavis** [comment]
@ldecoursy @thornet are we good with the updated text?

**Comment by ldecoursy** [comment]
Sorry for delay, WFM!

**Comment by thornet** [comment]
Looks good! Are we going to add the files and example uses of the simple Mozilla Clubs wordmark?

**Comment by hannahkane** [comment]
Good idea, @thornet. How about if we link to a section on the Clubs Fact Sheet with that information, once you've had a chance to add it (see #933)?

**Comment by thornet** [comment]
@hannahkane works for me!
