### ISSUE TITLE
Popup info panel for Clubs Map needs better spacing and vertical scrollbar

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#976]
![screen shot 2015-06-01 at 3 26 31 pm](https://cloud.githubusercontent.com/assets/2896608/7924748/c1a715c0-0872-11e5-8bc6-5254cf32249a.png)
(screencap taken from https://github.com/mozilla/teach.webmaker.org/pull/965's branch)

- [ ] We should probably introduce divider of some sort to visually separate one club from another.
- [ ] a vertical scrollbar should be presented when the popup gets too long

**Comment by mmmavis** [comment]
updated this bug again - a vertical scrollbar is also needed when Club list is long

**Comment by mmmavis** [comment]
this popup really bothers me and I know @sabrinang has been super busy getting A LOT of design work done... :wink: 

... so I decided to tweak this a bit - listified the Clubs (following Teach site's list item border convention), adjusted font sizes and some spacing.  Can we maybe use this as a temporary solution or iterate from here?  Sorry but it's just the current one is not really readable to me :bowtie: 


(here's the "before" and "after")
![map-popup](https://cloud.githubusercontent.com/assets/2896608/8017230/1b859bb8-0ba5-11e5-81f7-5402610196e3.jpg)

**Comment by hannahkane** [comment]
So much better!

**Comment by sabrinang** [comment]
@mmmavis the hierarchy with text is looking way better!
The only feedback I have is to give a little space beneath the location line (i.e - _Vancouver, British Columbia, Canada_ ) so there is a bit of separation between the Title & Location lines from the body description.

**Comment by toolness** [comment]
Ultra cool! I mentioned at https://github.com/mozilla/teach.webmaker.org/pull/1001#discussion_r31910486 that it might also be good to style things so that the orange lines only appear *between* clubs rather than also at the top and bottom of the list, but it's up to you.
