### ISSUE TITLE
Determine where Contact details live on Teach site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#98]
### Content

Each of these things needs a home:

* Chat with other mentors on Discourse
* Email us: help@webmaker.org
* Follow us on Twitter: @Webmaker
* Join the conversation using the #TeachTheWeb hashtag

**Comment by hannahkane** [comment]
@cassiemc - who should be assigned to this one?

**Comment by cassiemc** [comment]
@iamjessklein can you help us tackle this one?

**Comment by iamjessklein** [comment]
Yep. This should probably live on the "About" Page and possibly incorporated into the footer. 

cc/ @vazquez

**Comment by iamjessklein** [comment]
Incorporated into About Page - [invision doc here](http://invis.io/E52EM9WXT)
Closing this thread - add your comments on issue #99
