### ISSUE TITLE
Design "About" page of site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#99]
Copy coming in #38

**Comment by hannahkane** [comment]
Copy is ready in #38.

**Comment by iamjessklein** [comment]
Leave comments on [Invision mockup](http://invis.io/E52EM9WXT)

![about](https://cloud.githubusercontent.com/assets/535012/6578343/fa92e8e0-c719-11e4-802f-e9fb7b4c93e6.png)

**Comment by hannahkane** [comment]
Just wanted to acknowledge that I've seen this and have no comments because it looks great.

@ldecoursy @chrislarry33 - can you please leave any comments for @iamjessklein on the wireframe by EOD?

**Comment by chrislarry33** [comment]
WFM

**Comment by ldecoursy** [comment]
Me three

**Comment by iamjessklein** [comment]
:+1:  @vazquez  let's move on the mockups :tada:

**Comment by vazquez** [comment]
Design started, some assets still missing: http://invis.io/3T2FDPIUV

**Comment by hannahkane** [comment]
Looks great from my perspective. Thanks, @vazquez.

**Comment by iamjessklein** [comment]
I dropped my comments in the invision doc. Great work so far @vazquez

**Comment by hannahkane** [comment]
Are we good to close this ticket, so that we can move on to the build?

**Comment by vazquez** [comment]
I still need to design some assets. However, we can start with the build and I can update the assets later.

**Comment by vazquez** [comment]
All assets have been created. Closing issue.

**Comment by gesa** [comment]
@vazquez can you point me in the direction of this asset?
![](http://snaps.akibraun.com/kyvbt.png)

**Comment by ldecoursy** [comment]
It's here: https://www.flickr.com/photos/newyouthcity/14532113128/in/set-72157645434988967

**Comment by gesa** [comment]
Thank you!
