### ISSUE TITLE
Build Tools page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#990]
Design is in #887

**Comment by mmmavis** [comment]
is `https://teach.mozilla.org/tools` the url we wanna go with?

**Comment by hannahkane** [comment]
yes. top level!

**Comment by mmmavis** [comment]
@sabrinang @hannahkane 
I just [commented on the design ticket](https://github.com/mozilla/teach.webmaker.org/issues/887#issuecomment-110534601) since it's not clear which mockup is the one we want to go with.

**Comment by hannahkane** [comment]
No longer blocked, @mmmavis.

**Comment by mmmavis** [comment]
Some notes:

Link X-Ray Goggles to https://goggles.webmaker.org and Thimble to https://thimble.webmaker.org for now
