### ISSUE TITLE
Changes to nav items

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#991]
Let's not yet change the placement of the navigation on the page just yet, but we do need to add two items:
 * Tools (will eventually go to the new /tools page, designed in #887)
 * Community (will link to Discourse)

We'll also need to remove the "Maker Party" item.

The order of items should be:
 * Teaching Activities
 * Mozilla Clubs
 * Tools
 * Community
 * Teach Like Mozilla

**Comment by hannahkane** [comment]
Blocked on #990

**Comment by hannahkane** [comment]
OK, thinking on this more, I don't think we can afford to lose the "Maker Party" nav item until after MP has passed. That means we'll have six top-level nav items until early August, but I think it's necessary for people to be able to easily navigate to the MP page.

That means the order should be:
    Teaching Activities
    Mozilla Clubs
    Maker Party
    Tools
    Community
    Teach Like Mozilla

**Comment by mmmavis** [comment]
I'm adding the "blocked" label back since this is currently blocked on [Build Tools page](https://github.com/mozilla/teach.webmaker.org/issues/990)

**Comment by mmmavis** [comment]
We will also need illustrations for "Tools" and "Community" nav items before we can start making changes to the sidebar.

cc @sabrinang

**Comment by hannahkane** [comment]
Moving this to the next heartbeat

**Comment by mmmavis** [comment]
@hannahkane http://discourse.webmaker.org/ is the link to Discourse, correct? Just wanted to double check.

**Comment by hannahkane** [comment]
Yup. Thanks for checking.

**Comment by mmmavis** [comment]
![screen shot 2015-07-02 at 2 43 50 pm](https://cloud.githubusercontent.com/assets/2896608/8488623/cbd3cc50-20c8-11e5-990b-9274d0c346d4.png)

@hannahkane should we include subheads? (see "fix me" in screencap)

**Comment by hannahkane** [comment]
Let's go with this:

Tools: Open source software to teach and learn the Web
Community: Connect with others on topics you care about

(Can make edits later if others would like to)
